### PR TITLE
Add more shield icons to README

### PR DESCRIPTION
**Pull request by msteiger**
The shield are based on [shields.io](http://shields.io) and Jenkins. More shields can be found on their website. I updated the Jenkins plugin to achieve a common style (thanks @skaldarnar).

image

Other suggestions are welcome.

### CODE REVIEW

**Comment by Cervator** [comment]
Excellent :)

More suggestions:

* Unit test coverage (definitely)
* Code coverage (we're not doing this yet but we should)
* Other code analytics (Checkstyle, etc, maybe there's one for javadoc / documentation / comments?)
* The Waffle.io badge (weirdly when I tried it I couldn't get it to update from 0 in "Ready")
* Maybe one of the version/tag badges (looks like several available, tied to either download, a Git tag, etc)
* Ooohh we can make custom ones .... hmm! That could probably do more of the code analytics or stats on number of (stable?) modules

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/84/
Hooray Jenkins reported success with all tests good!

**Comment by msteiger** [comment]
I added the current release tag. For the other we need to compute the metrics first. e.g. using  [SonarQube](http://www.sonarqube.org/).

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/85/
Hooray Jenkins reported success with all tests good!

**Comment by msteiger** [comment]
Merging this as agreed upon with @Cervator

**Pull request merged**
