### PR TITLE
[WIP] Add FullRotationFamily - placed blocks always "facing" the player

### PR DESCRIPTION
**Pull request by skaldarnar**

### CODE REVIEW

**Comment by skaldarnar** [comment]
Giving the `fullRotation` family to `CoreBlocks:Furnace` yields some funny results. Placing the block in the ground will always result in the front facing upwards... Horizontal orientation is not working as expected in that case.
Upside-down placement is fine. 

Terasology-191020192638-1492x871
Terasology-191020192608-1492x871

A stair block with the rotation family is always facing away from the player when placed on the ground. Upside-down placement works better.

Terasology-191020192334-1492x871
Terasology-191020192345-1492x871

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by skaldarnar** [comment]
Superseded by #3978

**Pull request closed without merging**
