### PR TITLE
Added links to contributors.

### LINKED ISSUE #2319: Update credits to link to individual contributors
... because I'm too lazy to do it :-)

Or it could be from there being like 100+ people on there and I'm having a hard enough time finding time to do important stuff! :blush: 

In short: Update the credits list under /docs to use `[username](url)` style link to the contributor's GitHub user page.

Alternatively for contributors without a GitHub user page can link to their forum user page instead

Bonus: Vary the username in the link if the contributor's primary nick differs from GitHub user (IRC nick, forum username, or other preference by the contributor)

Example: @begla would list as [Benjamin 'begla' Glatzel](https://github.com/begla) 

`[Benjamin 'begla' Glatzel](https://github.com/begla)`

I realize not all the contributors will easily map and I have notes that might help connect a few, but so long as the bulk gets done I'll consider this issue complete :-)

Probably useful: https://github.com/orgs/MovingBlocks/teams/contributors - the main contributors team, most are included there. Forum member list: http://forum.terasology.org/members/

Extra bonus: Find a way to multi-line the longer teams in a clean fashion, mainly the `General` category. Alphabetic sub-groups? Max 175 chars per line printed? I dunno.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/34222233-update-credits-to-link-to-individual-contributors?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by xrtariq2594**
### Contains

Fixes #2319.

### How to test

No testing required.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by msteiger** [comment]
How did you generate this file?

**Comment by Cervator** [comment]
Pretty sure manually :D

I've been wondering if there might be some clever way to generate a letter-heading based credits or something more manageable. Haven't had time to look though.

**Comment by Cervator** [comment]
Added a few more contributors to the list from the last few days. Linked normally - I figure we can add nicknames / preferred format for anybody who become active under a variant name, otherwise standard GitHub username probably is sufficient.

Thanks @xrtariq2594 ! Also got you properly badged in the forum and such :-)

Probably we should improve the format further in the future to where we can auto-alpha-sort and group somehow. Maybe there are little tools for that out there, or something else spiffy.

**Pull request merged**
