### PR TITLE
Fixed issues #2527 and #2364, now main menu music looping infinitely

### LINKED ISSUE #2527: Main menu background track not looping
### How to reproduce
- Open game
- Turn up the audio and find some work to do :stuck_out_tongue: 
- Wait

The background track should play once and not loop back. That is the game goes silent after a while, once the song finishes.

Probably an easy fix.
##

### PR DESCRIPTION
**Pull request by omomthings**
### Contains

Fixes #2527, now music looping infinitely, simple and efficient.

### How to test

Go to main menu, enjoy the music till it ends and  restarts again.. the music is about 3 minutes..

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by ThompsonTyler** [comment]
The music does loop infinitely, but not only in the main menu, when you start playing it just re-loops as well....

**Comment by nihal111** [comment]
You would want to kill the thread in instances when the game is started etc.

**Comment by omomthings** [comment]
Ah ok I thought that it would be nice to have a background music all along hahaha, I'll make the modifs!

**Comment by omomthings** [comment]
@nihal111  the problem is solved for all the possible navigations from the menu and stops when we start the game, however, I found another bug that stops the music if the main menu is kept open for too long in the background, looks like if the game goes on a hibernation mode or something. I'll push when I find out if it's normal. I'll keep you informed.

**Comment by nihal111** [comment]
Are you sure that you can reproduce it reliably?
There is also the case when the music stops abruptly (mostly at start), and I believe that is IntelliJ doing some optimizations, followed by a "Delta too great.." message. Have a look at the discussion in the issue and a related issue- https://github.com/MovingBlocks/Terasology/issues/2364.
The above issue doesn't seem to happen when running the game from the binary though.

Not sure whether what you discovered is the same, just fyi.

**Comment by omomthings** [comment]
Yes I think the two are related, got the same log trace, will probably solve both at the same time.

**Comment by omomthings** [comment]
Hello Nihal, tried to reproduce the problem in various ways, I think that it should be fine now, what happens is that for some reason the music was stopped, now the Listener ensures that the music is looping till we explicitly quit the menu.

**Comment by Cervator** [comment]
Closing as finished by #2945 - added you to the credits for your efforts @omomthings thanks again :-)

**Pull request closed without merging**
