### PR TITLE
Collection serialization improvements

### PR DESCRIPTION
**Pull request by eviltak**
# Goal
This PR mainly aims to improve the way collections are serialized. Currently, each `TypeHandler` contains code for serialization of both individual type instances and collections of type instances. This leads to a lot of hidden code duplication, with different `(de)serializeCollection` implementations doing almost the same thing. This PR introduces `CollectionTypeHandler`, a type handler that (in conjunction with `CollectionTypeHandlerFactory`) works for any `Collection<E>`. A unified `CollectionTypeHandler` has the following implications:
- No need for separate `TypeHandler`s for `Set`, `Queue`, `List`, etc.
- `TypeHandler.serializeCollection` and `deserializeCollection` are eliminated, simplifying existing `TypeHandler`s
- Many collection-related methods in `SerializationContext` and `DeserializationContext` are made redundant, greatly simplifying their implementations
- Collections are serialized in one format without variation. Should users wish to serialize a specific collection in a different (and possibly more efficient) way, they can add a custom `TypeHandler`/`TypeHandlerFactory`

# Changes
- Added `InstanceCreator` -> Functional interface for specifying how types with no-args constructors are instantiated
- Added `ConstructorLibrary` -> A library of `ObjectConstructor`/`InstanceCreator` instances for creating objects of various types.
- Added `CollectionTypeHandler` -> The `TypeHandler` that performs the brunt of collection serialization
- Removed `TypeHandler.serializeCollection` and `deserializeCollection`
- Removed `SimpleTypeHandler`, which was made redundant by the above removal
- Removed `SerializationContext.create(Collection<T>, Class<T>)`
- Removed `DeserializationContext.deserializeCollection`

# Prerequisites
This PR includes commits from #3446 and requires that it be merged.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by eviltak** [comment]
Rebased onto #3446, please re-fetch.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Okay tested around a fair bit: host/client + client multi, headless multi, GooKeeper, MasterOfOreon, LightAndShadow, MedievalCities, GooeysQuests ... hardly exhaustive but after a while I couldn't find anything serious, at least not related to this PR. Seems like we have a growing small pile of unrelated issues starting to add up. Not enough detail to really write up issues on yet though.

Going to be merging in some module fixes after the build is done. Will try to hit other PRs another day 👍

**Comment by Cervator** [comment]
Note: Reverted as part of #3489 and parked for re-merging at some point via #3490

**Pull request merged**
