### PR TITLE
Added Javadocs to a number of Renderer-related packages, classes and methods.

### PR DESCRIPTION
**Pull request by emanuele3d**
With the work in #3276 done, rendering functionality is now open to external modules via the API. 

A good number of packages, classes and methods now available through the API had no javadocs however, making it harder to use. This PR adds the missing javadocs and improves some pre-existing ones. 

Besides comments on the changes proposed in this PR, please also let me know of any other rendering-related package, class/interface or method that is still missing javadocs. 

Tagging @vampcat and @readv for review.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by readv** [comment]
As far as I can see, most important classes are documented. I've noticed a few classes missing javadocs: ConditionDependendNode, DisableStateParameter, SetFacesToCull. I think GLSLShader and GLSLMaterial (and potentially other important OpenGL wrappers) could use some documentation as well. The OpenGL classes are a lot of work however, do you plan to work on them now or leave them for later?

**Comment by emanuele3d** [comment]
@readv: Thank you for the review and spotting those typos, they will be taken care of.

Regarding other files missing documentation, at this stage the focus is on the DAG-related files as that's where most of the work has taken place and that's what is now accessible via the API. 

So, I'll look into  ConditionDependendNode, DisableStateParameter and SetFacesToCull as those should certainly be documented. 

GLSLShader, GLSLMaterial might be refactored during GSOC and I'd leave them for the time being. 
Same for the OpenGL classes: they currently aren't the focus of our efforts.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Pull request merged**
