### PR TITLE
Update menu_it.lang

### PR DESCRIPTION
**Pull request by Halamix2**
Adding default English translation, this may help with Weblate errors.

Maybe we should delete menu.lang and game.lang files and create new languages from *_en.lang files? It seems that it would be better for Weblate .

### CODE REVIEW

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/341/
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
I think that @Trekmarvel already translated it into Italian - we just need to find the commit.

**Comment by msteiger** [comment]
I managed to restore most content in #2056. Thanks nonetheless, @Halamix2

**Comment by Cervator** [comment]
I appreciate you all sorting this out :-)

**Pull request closed without merging**
