### PR TITLE
Add basic Controller support

### PR DESCRIPTION
**Pull request by msteiger**
This PR is complete and functional, but it needs some more brushing up. It currently lacks:

- [ ] Custom bindings for controller axes
- [ ] Multiple controllers
- [ ] UI menu for controller selection
- [ ] Controller events (without binding)
- [ ] Button constants - currently `ZERO` - `ELEVEN`
- [ ] Robustness (don't spam the log when polling fails)
- [ ] Recognize disconnect/reconnect
- [ ] Invert axis
- [ ] Support rotation
- [ ] Support Z axis

This will be dealt with in a follow-up: this PR is already quite large.
Sending a ping to @immortius who might be interested.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/366/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Can confirm that it tests out! Definitely needs some work on bindings to be truly usable :D

I have a generic Gamestop controller and with it hooked up the left stick controlled movement although inverted (push back to go forward). The controller is kinda crappy so it needs a nice dead zone configured in Elite Dangerous to not leave me drifting constantly. I think we might have just coded in a basic dead zone in Destination Sol as I don't have trouble there, but am unsure.

I may have a fancier joystick to test with in a couple days too. Right now spending most my time on being sick and/or working Jenkins/Artifactory/Gradle/JaCoCo...

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Haha, speak of the devil / Gooey. The new test Jenkins has automated management of GitHub hooks enabled and jumped on this PR unintentionally simply because I commented, which sends a payload, and I guess since the test Jenkins PR job hadn't built this at all it decided to do so. Looks like the automated hooks work! I removed it in this case, dunno if it'll come back.

For bonus points the updated Jenkins is supplying the unit test results in the status commit thing! Compare with #2074 which was updated last by the existing Jenkins and just lists "default — Merged build finished." - this one listed " default — Build finished. 473 tests run, 0 skipped, 0 failed. " !

**Comment by msteiger** [comment]
The follow-up PR is here: https://github.com/msteiger/Terasology/pull/24

Most of the remaining issues cannot be solved with LWJGL 2, since the wrapper hides too much information :cry:

**Comment by msteiger** [comment]
I decided to re-implement the controller support based on JInput, because the LWJGL2 integration is insufficient. It doesn't even support the second stick, so you can't look around.

One alternative is [GLFW](glfw.org), which is what LWJGL3 is using, but it doesn't support callbacks (requires continuous polling) and I don't see any real advantages over using plain Java.

**Pull request merged**
