### PR TITLE
Fix duplicate entwork ids at items get splitted that caused invisible items.

### PR DESCRIPTION
**Pull request by flo**

### CODE REVIEW

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/13/
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/14/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Weird, this triggered two builds? Did you submit it first then later rebase a commit or something?

In any case: Cool fix. Does it relate to #1659 or some existing thing like the inventory quirk in multiplayer?

**Comment by Cervator** [comment]
Tested around some and looks like it mostly fixes #1048 - one minor bit remains: When I place the last item in a stack I get a ? icon in the vacated slot until the next inventory interaction. But now it works fine if the last item in a stack is *thrown* rather than placed.

Thanks :-)

**Pull request merged**
