### PR TITLE
feat: improve debug overlay with compass and additional heaps (MovingBlocks/Terasology#1942)

### PR DESCRIPTION
**Pull request by pollend**
I moved in Orientation from CommonWorld so will have to address the duplication.

image

Reference PR: https://github.com/MovingBlocks/Terasology/pull/3655
Reference Issue: https://github.com/MovingBlocks/Terasology/issues/1942

Co-authored-by: Hassan Ali <33906649+Haxsen@users.noreply.github.com>

### CODE REVIEW

**Comment by 4Denthusiast** [comment]
The heap space information seems like something that would be more appropriate as one of the things that you can toggle through (F4 I think) rather than being in the main debug information area.

**Comment by pollend** [comment]
> The heap space information seems like something that would be more appropriate as one of the things that you can toggle through (F4 I think) rather than being in the main debug information area.

you have a pretty good point. umm what should we call the view?

**Review by jdrueckert — COMMENTED** [review]
What do these "Eden Space", "Old Gen", "Survivor Space" hep allocation variants mean?
And is our x-axis the wrong way round? :thinking: seems like if I walk east, x decreases, while if I walk west it increases... that somehow seems the wrong way round...

**Comment by pollend** [comment]
@jdrueckert https://stackoverflow.com/questions/2129044/java-heap-terminology-young-old-and-permanent-generations

umm, what do you think is wrong with the x axis?

**Comment by pollend** [comment]
> What do these "Eden Space", "Old Gen", "Survivor Space" hep allocation variants mean?
> And is our x-axis the wrong way round? thinking seems like if I walk east, x decreases, while if I walk west it increases... that somehow seems the wrong way round...

just realized we are using a right handed coordinate system so. 

+x is left +y is up and z+ is forward. 

image

**Comment by jdrueckert** [comment]
> just realized we are using a right handed coordinate system so.
> 
> +x is left +y is up and z+ is forward.

yes this is exactly what caught my eye. but I guess that's something quite deeply rooted then?
and thanks for the link about the heap terminology, that helped 👍

**Review by jdrueckert — APPROVED** [review]

**Pull request merged**
