### PR TITLE
outputdir --> destinationDirectory, prepare gradle upgrade

### PR DESCRIPTION
**Pull request by soloturn**
### Contains

outputdir --> destinationDirectory, prepare gradle upgrade

### How to test
cleaning the folder and unit test gives no errors.
```
git clean -xfd
./gradlew clean unitTest
```

### CODE REVIEW

**Comment by soloturn** [comment]
when doing gradlew test instead of gradlew unitTest it gives errors i did not see otherwise. what can this be?

```
./gradlew test
...
> Task :engine-tests:test
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.terasology.engine.utilities.ReflectionUtil (file:/run/media/rt/4tb-home/1tb-no-space/src/Terasology/engine/build/libs/engine-5.4.0-SNAPSHOT.jar) to field java.util.concurrent.ExecutorCompletionService$QueueingFuture.task
WARNING: Please consider reporting this to the maintainers of org.terasology.engine.utilities.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

ModuleManagerTest > [1] class org.terasology.engine.world.block.structure.AttachSupportRequiredComponent FAILED
    java.lang.NullPointerException at ModuleManagerTest.java:47

ModuleManagerTest > [2] class org.terasology.engine.logic.permission.PermissionSetComponent FAILED
    java.lang.NullPointerException at ModuleManagerTest.java:47

ModuleManagerTest > [1] class org.terasology.engine.core.PathManager FAILED
    java.lang.NullPointerException at ModuleManagerTest.java:47

ModuleManagerTest > [2] class org.terasology.engine.logic.permission.PermissionSetComponent FAILED
    java.lang.NullPointerException at ModuleManagerTest.java:47

ModuleManagerTest > engineModuleContainsSubsystems() FAILED
    java.lang.NullPointerException at ModuleManagerTest.java:47

TestModuleEnvironmentSandbox > findSubtypeOfEngineClass() FAILED
    java.lang.NullPointerException at TestModuleEnvironmentSandbox.java:38

TestModuleEnvironmentSandbox > findSubtypeOfModuleClass() FAILED
    java.lang.NullPointerException at TestModuleEnvironmentSandbox.java:38

TestModuleEnvironmentSandbox > findSubtypeOfGlobalClass() FAILED
    java.lang.NullPointerException at TestModuleEnvironmentSandbox.java:38

846 tests completed, 8 failed, 20 skipped
There were failing tests. See the report at: file:///run/media/rt/4tb-home/1tb-no-space/src/Terasology/engine-tests/build/reports/tests/test/index.html

```
the error is for all similar:
```
java.lang.NullPointerException
	at org.terasology.engine.utilities.Jvm.logClasspath(Jvm.java:23)
	at org.terasology.engine.core.module.ModuleManager.newModuleFactory(ModuleManager.java:114)
	at org.terasology.engine.core.module.ModuleManager.<init>(ModuleManager.java:73)
	at org.terasology.engine.testUtil.ModuleManagerFactory.create(ModuleManagerFactory.java:17)
	at org.terasology.engine.persistence.typeHandling.reflection.TestModuleEnvironmentSandbox.provideSandbox(TestModuleEnvironmentSandbox.java:38)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by DarkWeird** [comment]
> when doing gradlew test instead of gradlew unitTest it gives errors i did not see otherwise. what can this be?
> 
> ```
> ./gradlew test
> ...
> > Task :engine-tests:test
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by org.terasology.engine.utilities.ReflectionUtil (file:/run/media/rt/4tb-home/1tb-no-space/src/Terasology/engine/build/libs/engine-5.4.0-SNAPSHOT.jar) to field java.util.concurrent.ExecutorCompletionService$QueueingFuture.task
> WARNING: Please consider reporting this to the maintainers of org.terasology.engine.utilities.ReflectionUtil
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> 
> ModuleManagerTest > [1] class org.terasology.engine.world.block.structure.AttachSupportRequiredComponent FAILED
>     java.lang.NullPointerException at ModuleManagerTest.java:47
> 
> ModuleManagerTest > [2] class org.terasology.engine.logic.permission.PermissionSetComponent FAILED
>     java.lang.NullPointerException at ModuleManagerTest.java:47
> 
> ModuleManagerTest > [1] class org.terasology.engine.core.PathManager FAILED
>     java.lang.NullPointerException at ModuleManagerTest.java:47
> 
> ModuleManagerTest > [2] class org.terasology.engine.logic.permission.PermissionSetComponent FAILED
>     java.lang.NullPointerException at ModuleManagerTest.java:47
> 
> ModuleManagerTest > engineModuleContainsSubsystems() FAILED
>     java.lang.NullPointerException at ModuleManagerTest.java:47
> 
> TestModuleEnvironmentSandbox > findSubtypeOfEngineClass() FAILED
>     java.lang.NullPointerException at TestModuleEnvironmentSandbox.java:38
> 
> TestModuleEnvironmentSandbox > findSubtypeOfModuleClass() FAILED
>     java.lang.NullPointerException at TestModuleEnvironmentSandbox.java:38
> 
> TestModuleEnvironmentSandbox > findSubtypeOfGlobalClass() FAILED
>     java.lang.NullPointerException at TestModuleEnvironmentSandbox.java:38
> 
> 846 tests completed, 8 failed, 20 skipped
> There were failing tests. See the report at: file:///run/media/rt/4tb-home/1tb-no-space/src/Terasology/engine-tests/build/reports/tests/test/index.html
> 
> ```
> the error is for all similar:
> ```
> java.lang.NullPointerException
> 	at org.terasology.engine.utilities.Jvm.logClasspath(Jvm.java:23)
> 	at org.terasology.engine.core.module.ModuleManager.newModuleFactory(ModuleManager.java:114)
> 	at org.terasology.engine.core.module.ModuleManager.<init>(ModuleManager.java:73)
> 	at org.terasology.engine.testUtil.ModuleManagerFactory.create(ModuleManagerFactory.java:17)
> 	at org.terasology.engine.persistence.typeHandling.reflection.TestModuleEnvironmentSandbox.provideSandbox(TestModuleEnvironmentSandbox.java:38)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> ```
> 

Strange. 
Seems, PathManager didn't find installPath.

Can you debug `PathManager#findInstallPath()`?

**Comment by skaldarnar** [comment]
Related to #5109.

**Comment by soloturn** [comment]
#5109 obsoleted this one.

**Pull request closed without merging**
