### PR TITLE
Added the Turkish translation for i8n #2309

### PR DESCRIPTION
**Pull request by aybuke**
### Contains

Brief description of what the PR does like "Fixes #12345"
### How to test

Brief description of how to test / confirm this PR before merging
### Outstanding before merging

If anything. You can use neat checkboxes! Feel free to delete if not needed
- [ ] Need to consider use case x
- [ ] Still have to adjust the wiki doc
- [ ] Will need translation work

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by rzats** [comment]
@aybuke: will you be able to continue work on this? A working Turkish translation would be great 🙂

**Comment by tdgunes** [comment]
@rzats: I think I am qualified to do it. 😄 🇹🇷 (wonders how many lines are needed to be translated. 🤔). It'd be great if you can tell the basics to start translating.

**Comment by skaldarnar** [comment]
@tdgunes you could either check out this commit and apply changes to it manually, then make another PR. The second option is to use our [weblate instance](http://translate.terasology.org/projects/terasology/menu/tr/). The strings show up as already translated, but they are all the English placeholders.

**Comment by tdgunes** [comment]
Thanks @skaldarnar, I'll look into it through weblate.

**Comment by msteiger** [comment]
Any news on this one?

**Comment by Cervator** [comment]
Closing with the hope that we can eventually have @aybuke or @tdgunes translate via code or Weblate. I'm cleaning up language PRs and aiming to update Weblate at last :-)

**Pull request closed without merging**
