### PR TITLE
Fix mouse sensitivity set to 0 when resetting input config.

### PR DESCRIPTION
**Pull request by MaloJaffre**
Get a new config instance in order to have defaults in default.cfg.
Fix a part of #2064.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by msteiger** [comment]
ok to test

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/353/
Hooray Jenkins reported success with all tests good!

**Comment by msteiger** [comment]
Looks good to me. Thanks!

Maybe we should aim for a better way to restore default values. I don't find that very intuitive.

**Pull request merged**
