### PR TITLE
Gltf support

### PR DESCRIPTION
**Pull request by Kanonbell**
_Admin edit: Back to #3785 again, which was updated_ :-)

### Contains

Completes PR #3785 by rebasing the engine to support BiomesAPI.

### How to test

Create a world with the BiomesAPI module activated
To check gltf support run command: spawnPrefab "engine:cubesm"

### Outstanding before merging

- [ ] Convert old models from .md5 to .gltf

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
This one did the trick! Thanks @Kanonbell :-)

Going to edit the GCI task to point to this PR and also leave a note on the old PR

@GooeyHub: add to whitelist

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Kanonbell** [comment]
Any changes to the heightOffset parameter in the skeletalmesh component don't seem to have any effect on the height of the in-game model. The parameter works fine in the main develop branch, but doesn't work on the gltf branch. Can someone else confirm this issue, just in case it may be an error happening with me locally?

**Comment by immortius** [comment]
It is entirely possible I broke it along the way

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by casals** [comment]
Found a possible solution for both floating and rotation that needs confirmation. This PR + Behaviors, PR-23 + WildAnimals, PR-46 + changing prefab `heightOffset` from -0.8 to 0.8

**Comment by Cervator** [comment]
Old PR got rebased with an additional bug fix commit added! And this one got a merge commit added which duplicated the existing commits :-( So closing this one in favor of the old one again - still appreciate your efforts on this @Kanonbell !

Thanks for the bug hunting @casals !

**Pull request closed without merging**
