### PR TITLE
Use Noto font for screen titles

### LINKED ISSUE #2029: Main menu fails to display special characters (Polish example)
Noted by @Halamix2 with #2027 

Example snippet from the Polish menu .lang file:

`"create-game-title": "Utwórz grę",`

From https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/resources/assets/i18n/menu_pl.lang#L41

Yet in display in-game the special character `ę` is missing

polishspecialcharmissing

The character shows fine in the .lang file in IntelliJ (and in a Jenkins workspace too for that sake)

### PR DESCRIPTION
**Pull request by msteiger**
This PR replaces the obsolete `title` font with the (larger) Noto font. The difference in rendered size made a few adjustments necessary.

All subtitles should be at the same vertical position.

I guess we could remove the two obsolete fonts `default` and `title` now.

Fixes #2029

### CODE REVIEW

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/325/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
What about this block?

https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/resources/assets/skins/mainmenu.skin#L44-L47

It is the one other spot I see `"font": "title"` although it looks like a plain `"title"` finds a lot of other hits too. But I'm not sure if those mean something else?

I'd be happy to delete the old fonts as well, am just not sure how to verify them not being in use in modules (possible candidates: InGameHelp, JoshariasSurvival, ManualLabor - pinging @Josharias) - I guess I might notice either logged errors failing to find assets or the text looking weird if even present?

**Comment by msteiger** [comment]
Good catch! I updated the font as well. It is fairly large for those headings though:

image

Maybe we should add functionality to render it smaller than it actually is (or create a medium-size font for those subcaptions).

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/326/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Thanks, submitted #2042 as a follow-up so we don't forget :-)

**Pull request merged**
