### PR TITLE
Bugfix/remove classpath

### PR DESCRIPTION
**Pull request by pollend**
this reverts the changes in: https://github.com/MovingBlocks/Terasology/commit/8befab34221667074a43a897e88939128a34fff3

### CODE REVIEW

**Comment by keturn** [comment]
Here's my current take on this:

This is not a build configuration error.

Some things shifted around and now single-player games (in certain dev environments) are running in to the performance problem we identified in multiplayer games in #4154 back in September.

For next steps, I suggest:
 * optimize this code querying subtypes in ModuleEnvironmentSandbox and/or gestalt's ModuleClassLoader. There are some [preliminary ideas about that](https://github.com/MovingBlocks/Terasology/issues/4154#issuecomment-705382655) written down already.
 * update to current gestalt (#4144), and _then_ optimize that stuff, because some of it probably changes with the new version anyway.

In the meantime, the stopgap workaround is:
* don't have a ton of modules subprojects checked out in your workspace. The performance problem climbs sharply with the number of module directories.

**Comment by pollend** [comment]
I'm just using the branch to see what is different with the configuration. I don't think its a query problems. something is strange where the classloaders take a really long time to load the classes.

**Comment by keturn** [comment]
yeah, the note I had on that issue that I don't think is subtype-specific is

> the other thing in ModuleClassLoader.loadClass I'm suspicious of is that I think a class loader should check to see if the class is already loaded before calling up the chain, as described for https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/ClassLoader.html#loadClass(java.lang.String,boolean)
>
> but I'm not sure ModuleClassLoader checks that first.
>
> I don't yet understand the ModuleClassLoader thing of each classloader having a parent but ModuleClassLoaders also have a baseClassLoader, so I'm really not sure what order things happen in.

**Comment by pollend** [comment]
> yeah, the note I had on that issue that I don't think is subtype-specific is
> 
> > the other thing in ModuleClassLoader.loadClass I'm suspicious of is that I think a class loader should check to see if the class is already loaded before calling up the chain, as described for https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/ClassLoader.html#loadClass(java.lang.String,boolean)
> > but I'm not sure ModuleClassLoader checks that first.
> > I don't yet understand the ModuleClassLoader thing of each classloader having a parent but ModuleClassLoaders also have a baseClassLoader, so I'm really not sure what order things happen in.

`AccessController.doPrivileged(new ObtainClassloader(clazz));` seems to be the main bottleneck in the chain.

**Comment by pollend** [comment]
with this branch the classloader isn't chained to another module class loader.

**Comment by keturn** [comment]
on the security (not performance) impacts of the classpath thing: #4375

**Comment by keturn** [comment]
why does this show up when running from IntelliJ but not gradle? Likely clue:

gradle is putting the _jar_ files on the classpath, but IntelliJ is giving the classes _directory_.

It's not _wrong_ to use the directories here. It might help module and asset hot-reloading speed in development and saves a build step. gradle might well do the same thing if the configuration changes a bit.

**Pull request closed without merging**
