### PR TITLE
Md5 patterns and unit tests

### PR DESCRIPTION
**Pull request by J-Dill**
### Contains

Based off of #3240 

I created a class, MD5Patterns, to hold the patterns that were in both the 
MD5AnimationLoader and MD5SkeletonLoader classes. Also,
I updated the float pattern from @kartikey0303's suggestion. 

In addition, I added unit tests for all of the patterns in the 
new class that was created. 

### How to test

Run the new unit test class, along with all of the unit tests.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Poking @kartikey0303 and @flo for review referencing this as a replacement for #3240 :-)

Beyond the regular models and the newest ones from HumanoidCharacters we should probably also test it with the MawGooey, but I'm realizing we don't have it in a module yet, we just have the meta module: https://github.com/MetaTerasology/MawGooey

@kartikey0303 or @Quaternius would either of you mind doing an export and adding the files to https://github.com/Terasology/MawGooey please ? I just created it along with a team so you should both have access

**Comment by Cervator** [comment]
I've spent some time testing this, #3240, the deer, skeleton, and new MawGooey (https://github.com/Terasology/MawGooey) - I think there is something slightly off with the Regex here, I'm getting some parsing errors from WildAnimals and the MawGooey when running this one.

#3240 does seem to work even if it doesn't cover all the cases quite as well, so I've merged that in and figure we can add this on top with another regex tweak. @J-Dill could you take a look at starting the game with this PR with the WildAnimals and MawGooey modules enabled? Look for the parsing errors on startup, and spawn some stuff to see what happens - with this PR i didn't get any animations, although the models did load into the world

* `spawnPrefab deer`
* `spawnPrefab mawGooey`

Play test in about 10 hours to try the new model and other stuff out, will be around most the day fixing bugs and coordinating GSOC stuff :-)

**Comment by J-Dill** [comment]
Hey @Cervator, I am getting the parsing errors also, along with the absence of animations. I will try out the float pattern that is in #3240 to see if that fixes things.
If I do replace the float pattern, do you think that it would be acceptable to remove the cases from the unit tests that we know the pattern will not be able to handle?

**Comment by Cervator** [comment]
Hey @J-Dill thanks :-)

> If I do replace the float pattern, do you think that it would be acceptable to remove the cases from the unit tests that we know the pattern will not be able to handle?

Sure - or mark those as ignored as well with a TODO to improve the pattern further? Depends a bit on whether it is just too much hassle to figure out at the moment but still desirable to get to later, or entirely "Yeah don't worry about it". If the latter then just remove outright :-)

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by J-Dill** [comment]
@Cervator  Was able to figure out the parsing error, and I decided to just take the test cases in the unit tests out. I believe it should be good to go, but then again I did before also :p

**Comment by Cervator** [comment]
Does indeed look good this time :-)

No errors noted in the log and the models I could test turned out fine. Unit tests run. 👍 

Merged and added you to the credits. Also tweaked at some trivial quality issues since the files were being touched anyway (feel free to update license years, empty javadoc, etc)

**Pull request merged**
