### PR TITLE
Update external versions

### PR DESCRIPTION
**Pull request by msteiger**
This updates:

* Gradle to 2.10
* VersionEye-integration to 1.10
* PMD and CheckStyle
* slf4j
* treelayout (used for the behavior editor)

Guava and GSON were removed as they are already specified in gestalt.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/368/
Hooray Jenkins reported success with all tests good!

**Comment by msteiger** [comment]
Requires https://github.com/MovingBlocks/gestalt/pull/48

**Comment by Cervator** [comment]
I'll roll this in with my first round of Gradle + infrastructure upgrades as both include a swap to Gradle 2.10. Which causes an Artifactory issue first introduced in Gradle 2.4 (we are/were at 2.3) that I'm not sure how to fix properly but there's an easy workaround.

Got JaCoCo 0.7.5 working too and reports updating on codecov using XML instead of the exec files. Jenkins still wants exec though, but at least it works with the latest versions of everything.

On Guava and GSON - if we require them shouldn't we to be proper keep them as direct dependencies rather than rely on the transitive dependencies from Gestalt? I know that makes it easier to stay in sync and we'll always have the dependency on Gestalt - it just seems iffy from a dependency management perspective :-)

**Comment by Cervator** [comment]
Got this merged in and checked on. There was a weird error seemingly only in the new setup (upgraded Jenkins/Artifactory/plugins) but not in the old Jenkins or locally related to the slight upgrade of reflections at the build script level. Probably (and likely coincidentally) a conflict between transitive dependencies of Guava from different things or something. Maybe with the Artifactory Gradle plugin which I finally got hooked up more properly.

**Comment by msteiger** [comment]
I amended the commit and added Guava and GSON back in.

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/372/
Hooray Jenkins reported success with all tests good!

**Pull request merged**
