### PR TITLE
Prepare Javadoc for Java8

### PR DESCRIPTION
**Pull request by msteiger**
This PR fixes most of the Javadoc errors. A few more tricky ones remain and will be dealt with separately.

I left the `@author` tags in, but removed the email address hoping that this approach suits all or at least most developers.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/7/
Jenkins Success Message

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/11/
Hooray Jenkins reported success with all tests good!

**Comment by msteiger** [comment]
I fixed all javadoc errors. Let's see how it goes with those super-strict settings. We might want to consider setting the `failOnError` to `false` if that becomes too much hassle.

**Comment by Cervator** [comment]
I put out an announcement asking if anybody objects to just removing the author tags entirely: http://forum.terasology.org/threads/removal-of-all-javadoc-author-tags-any-objections.1273/

Pinging @MovingBlocks/contributors on here to get the word out. If anybody objects please post here or in the forum thread :-)

We have a nice recently updated JavaDoc page in the wiki too: https://github.com/MovingBlocks/Terasology/wiki/JavaDoc

I figure we can add the javadoc task to the PR builder job so any failures will break the build and report back to a PR that something is wrong with javadoc. Then we can get it fixed before merging.

Really we should probably enable the checkstyle nagging for javadoc and such while we're at it (not necessarily in this PR), and tweak some rules to see if we can adhere to a convention.

Doing some build testing with http://jenkins.terasology.org/job/TerasologyTemp/

**Comment by Cervator** [comment]
Merged this since we'll needs these fixes regardless. Then we can do the author tags next - no objections so far.

**Pull request merged**
