### PR TITLE
Add import statement order config file for Eclipse

### LINKED ISSUE #2117: Consistent order of import statements for IDEs
This is based on the discussion in the forum: http://forum.terasology.org/threads/order-of-import-statements.1323/#post-12064

I believe we should stick with the IntelliJ default, since this is what the majority uses and how 90% of the code is currently formatted. So what is needed is a config file for eclipse that changes the order so that it matches that of IntelliJ.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29728376-consistent-order-of-import-statements-for-ides?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by rzats**
Fixes #2117.

_Note: since .importorder is a semantic extension, I've chosen not to name this file at all - looks clean and .gitignore-like. This may cause some awkward issues on Windows, though, so it's subject to change._

### Usage:

- In Eclipse, go to Window → Preferences → Java → Code Style → Organize Imports.

- Import the import order file, click Apply.

screenshot of Organize Imports menu in Eclipse

- **[Recommended]** Switch to Editor → Save Actions, check Perform the selected actions on save and Organize imports.

screenshot of Save Actions menu in Eclipse

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
ok to test

Hi @rzats and thanks for the PR! :-)

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/444/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Merged! And I copied the instructions to https://github.com/MovingBlocks/Terasology/wiki/Eclipse

I know we have a few other config files like that, feel free to enhance that page with how to use the others. I know @msteiger and a few use Eclipse, but I'm on IntelliJ so not as familiar :-)

We had a few related instructions before but I've been on a bit of a "Heal it with fire!" rampage in there and haven't quite built everything back up yet!

Also added you to the credits, let me know if you're in the forum for a contributor badge :-)

**Pull request merged**
