### PR TITLE
Editor context menu

### PR DESCRIPTION
**Pull request by rzats**
### Contains

An implementation for https://github.com/rzats/gsoc-nui-editor/issues/5.

- `ContextMenuScreen`: a typical pop-up menu screen: wraps a `UIList` with a fullscreen listener that closes the list when clicked on and provides functions to set the menu's position (ideally to the mouse pointer's position), change the options within the `UIList`, the listeners for selecting an option & closing the menu respectively.

context menu screenshot

- A context menu for the NUI editor's tree items. Includes the options to copy or paste a specific node (as an alternative to Ctrl+C/Ctrl+V) and, if appropriate, add a widget scaffolding with a type chosen from a list of selected widgets.

widget selection popup screenshot

### How to test

Launch the NUI editor (now activated by F10), select a screen to edit and right-click on any tree item.

### Outstanding before merging

- [x] The widget scaffolding should be added to the tree and refresh the widget view.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by flo** [comment]
Good work with the "outside click closes context menu" functionality. It is even still possible to click another element without having to click twice.

I think design wise the context menu could be improved in regards of how events are handled. Instead of having a selection listener that gets called for any kind of selection I think it would be better if one could register context menu items with action. e.g.
```
/** Class for constructing and showing context menus. 
 * Abstracts the context menu creation anddisplay away 
 * so that the implementation can change without breaking anything
 */
class ContextMenuBuilder{
  public <E> void addActionItem(String itemText, Consumer<E> activationHandler, E item) {
     /// ....
  }
}

class MyScreen {
public void showContextMenuFor(MyItem item, Vector2i postion) {
// maybe further arguments are needed for ContextMenuBuilder:
ContextMenuBuilder menuBuilder = new ContextMenuBuilder();
contextMenuBuilder.addActionItem("Copy", MyScreen::onCopy, item);
contextMenuBuilder.addActionItem("Paste", MyScreen::onPaste, item);
contextMenuBuilder.buildAndShow(position)
}

public void onCopy(MyItem myItem) {
  // does not need to close the screen, as that happens automatically. It doesn't even know the screen.
}
```
This avoids the need to compare string constants which is a bad design in my opinion and it abstracts away the logic that shows the context menu (Which is good because it allows us to change it without breaking any users of it).

Some issues I noted:
* I get a lot of console spam from `JsonTreeNode.toString` that has some random debug string printing.
* It is not possible to add a widget to the root element.

**Comment by flo** [comment]
The field contents of CoreScreenLayer is not a list but a single widget. So maybe a "Replace widget"  option could be offered so that the user is not confused why "Add Widget" is missing. Although seeing now ihat is just a single widget you don't need to add any functionality for it at this stage.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by flo** [comment]
Merged. The dragging and dropping of items is really fun to play around with already.

**Pull request merged**
