### PR TITLE
Fix inactive controller inputs being consumed

### LINKED ISSUE #2554: Game controller input still being consumed with the game window inactive
## Description

If you de-focus the game window (switch to some other window) while having a game controller of some sort hooked up, input from the controller still affects the game (unlike mouse or keyboard). This is _probably_ not a hard bug to solve.
## Definition of 'Done'
- [ ] de-focusing the game window will ignore all input (especially from attached controllers)
## Requirements
- you will work with the game's input system which requires intermediate knowledge of Java
- access to a game controller of some sort to test it out :-)
## Where to start?
- #2108 added controller support, the PR gives a good overview of involved classes
##

### PR DESCRIPTION
**Pull request by ThompsonTyler**
### Contains

Fixes #2554 and prevents controller input from being accepted when the game window isn't active.
Not actually sure how to run Checkstyle on the code, so unable to verify that currently...

### How to test

Run game with out change using a controller, test that controller works for the game, make the window inactive and then try to input on the controller(it will still put in inputs).

With change these inputs on the inactive window are not accepted and function as a mouse or keyboard input would.

With the window active the game still functions normally and consumes all inputs.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
I've got a controller - somewhere - to help test this. Wonder if another person or two could try it too. @indianajohn could you check to see if it bumps into any of your motion controller stuff?

@GooeyHub: ok to test

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Tested it out and it confirms well :-)

Minor whitespace fix (whitespace after if and before the opening `{`) but that's a tiny thing so I did it during the merge.

Added to our credits. Thanks!

**Comment by Cervator** [comment]
Oh, and I keep forgetting to ask people: got a forum account yet? Your name differs between here and IRC so I wonder if I'm just not spotting your forum account under yet another name ... :D

Need an account and a contributor intro sometime so we can get you a badge :-)

**Pull request merged**
