### PR TITLE
UIScrollbar zero division hardening

### PR DESCRIPTION
**Pull request by rzats**
### Contains

Short and simple fix for #2283. I originally wanted to couple this with more zero division fixes, but after some investigation (i.e. searching for '/' in widget code) it seems that these are actually the only lines of code in the UI* widget family that don't handle zero division properly.

### How to test

Launch the game, type in `showScreen migTestScreen`, click on the `min`-sized UIScrollbar, check that it didn't throw a silent stacktrace.

### Outstanding before merging

No outstanding issues.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/582/
Hooray Jenkins reported success with all tests good!

**Comment by msteiger** [comment]
Thanks, @rzats. Does a `sliderSize` value `0` make sense?
If so (and this is the only spot where slider size is a divisor), then I would split the modified line in two to make it easier to read and understand. 
If not, then I'd clamp the minimum slider size to 1 (or maybe more?).

**Comment by rzats** [comment]
@msteiger: `sliderSize` is checked for zero in the same file [(blob link)](https://github.com/rzats/Terasology/blob/d78b51bb619b9a9d9bb87334f2abf0ea3d530f93/engine/src/main/java/org/terasology/rendering/nui/widgets/UIScrollbar.java#L229), so I assume it's an acceptable value. 

Not quite sure what you mean regarding splitting the line in two. Should the control flow look like this?
```java
if (sliderSize > 0) {
    if (vertical) {
        updatePosition(pos.y - mouseOffset);
        setValue(TeraMath.clamp(pos.y - mouseOffset, 0, sliderSize) * getRange() / sliderSize);
    } else {
        updatePosition(pos.x - mouseOffset);
        setValue(TeraMath.clamp(pos.x - mouseOffset, 0, sliderSize) * getRange() / sliderSize);
    }
} else {
    setValue(0);
}
```

**Comment by msteiger** [comment]
Thanks for the info. I find this easier to read and understand. You might need to add `updatePosition(..)` for the case where `sliderSize` is zero. How about this?
```java
int delta;

if (vertical) {
    delta = pos.y - mouseOffset;
} else {
    delta = pos.x - mouseOffset;
}
updatePosition(delta);
if (sliderSize > 0) {
    int clamped = TeraMath.clamp(delta, 0, sliderSize);
    setValue(clamped * getRange() / sliderSize);
} else {
    setValue( .. what is a reasonable value in that case and why? );
}
```

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/584/
Hooray Jenkins reported success with all tests good!

**Comment by rzats** [comment]
@msteiger: thanks for the feedback! Updated accordingly.
Fallback value should definitely be set to 0, IMO (since the slider is 0-sized, any higher values may potentially cause unexpected issues).

**Comment by msteiger** [comment]
Great - thanks for the update.

**Pull request merged**
