### PR TITLE
Removed Title and Default fonts from engine

### PR DESCRIPTION
**Pull request by n4n0byte**
### Contains
Fixes one part of issue #2472 

### How to test
run the application

Brief description of how to test / confirm this PR before mergin
Removes title and default fonts from engine folder

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by flo** [comment]
What is the status of the modules mentioned in the issue? Have they been switched to different fonts?

**Comment by Cervator** [comment]
I don't think so - the one Equipment PR doing the switch for instance stalled: https://github.com/Terasology/Equipment/pull/2

@n4n0byte mentioned in #2472 having worked on modules but I'm not sure we saw any PRs come out of it. Hi @n4n0byte still around? Sorry about the slow reply. 

Triggering bot for test build

@GooeyHub: ok to test

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by jellysnake** [comment]
Hey @n4n0byte how's the status on this? Is anything happening with switching the other modules' font?

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by jellysnake** [comment]
I'm going to close this on lack of response/moment.

@n4n0byte feel free to re-open this whenever you're able :)

**Pull request closed without merging**
