### PR TITLE
Added JavaDocs to 5 classes

### PR DESCRIPTION
**Pull request by Metatricity**
### Contains

Multiple classes that have new JavaDocs. For GCI.

Classes changed:
AudioConfig
ClientIdentity
PermissionConfig
WorldGenerationConfig
ServerInfo

### How to test

Untestable, however, they can be reviewed by going GitHub and viewing the classes one by one.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
Uh, not quite sure what happened there, but you added *new files* rather than update the existing files with JavaDoc ... :-)

That's not quite going to work. Ideally you need to be working out of IntelliJ. At that point you can actually use `CTRL-Q` on a usage of a particular variable or method you updated and IntelliJ will pop up the JavaDoc :-)

**Comment by Metatricity** [comment]
Wow. Never realized that. Sorry I'm just slipping in and out of sleep here, let me fix that. :shipit:

**Comment by Metatricity** [comment]
There we are. :+1: Sorry 'bout that, I was not working in IntelliJ so I must've messed up when I was uploading...

**Comment by Metatricity** [comment]
Closing pull request and making a new one.

**Pull request closed without merging**
