### PR TITLE
Add dropdown scrollbar menu

### PR DESCRIPTION
**Pull request by AlexanderGrooff**
Fix for issue #844 and #2134.

UIDropdownScrollable is extended from the UIDropdown class, having the same features except for the extra scrollbar on the right.

Implementation is similar to the UIDropdown, but with an extra option `menu.setVisibleOptions(x)` to set the number of visible option in the dropdown menu.
This is an optional command, since the default setting is set to 5 visible options.

This new class has been implemented in the playerSettingScreen for the language menu to fix issue #2134.

## Remaining issue

One issue remains however, which is that the menu doesn't close when you click outside of the menu and the scrollbar is focussed last. 
Normally, when you click somewhere outside of the menu area, the menu closes.

To better explain this, try to follow these steps:
1. Open the language menu in the player setting screen
2. Click somewhere on the scrollbar to make it scroll down/up
3. Try clicking somewhere next to the menu, attempting to close it. You should see that it doesn't close like that.

A possible solution to this would be to swap the position of the scrollbar and the menu background around, so that the scrollbar is 'under' the menu. 
This does have its own complications however, and it seemed to be out of the boundaries of the mentioned issues.
We would appreciate any feedback you have on this PR.

Kind regards from @janzegers, @BdeBock, @arkka and @alexandergrooff.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
ok to test

Hi all! Great to see you and get new code! Will review as soon as able :-)

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/435/
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/436/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Tested and merged! Thanks all :-)

I see the quirk you mention but am not worried about it since you can simply select an entry to make it go away. I don't think it is worth worrying about yet, after all we're a fair distance from beta and trying to add final polish still (with other similar UI quirks pending like tabbing between elements). I'd much rather focus on more important fixes and additions :D

Added you all 4 to our Contributors group here on GitHub and the credits! New issue submitted to have this applied to another couple dropdowns and plenty of other UI and contributor friendly issues your efforts would be hugely appreciated for! :-)

Let me know if you have forum accounts for contributor badges there.

**Pull request merged**
