### PR TITLE
Added Library Utility Commands

### PR DESCRIPTION
**Pull request by digitalripperynr**
This PR adds Library Utility Commands to the Groovy Wrapper by creating a new Groovy script.

`groovyw lib get Name` ---> retrieves 'Name' from MovingBlocks into the 'libs' folder.
`groovyw lib create Name` ---> adds a blank library 'Name' to the 'libs' folder.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by jellysnake** [comment]
Same as the other groovyw command, I'm going to approve it but hold off on merging it til Cervator confirms. In case there is a slight issue with it.

**Comment by digitalripperynr** [comment]
Thanks! @jellysnake

**Comment by digitalripperynr** [comment]
#3206 aims to merge the functionality of this script and others into a single unified script.

**Comment by Cervator** [comment]
Superseded / merged via #3263 - thanks! :-)

**Pull request closed without merging**
