### PR TITLE
Added the Japanese translation for i8n

### PR DESCRIPTION
**Pull request by roshikouhai**
### Contains

Partial fix to #2309  by adding in the Japanese Translation

### Outstanding before merging
- [ ] Will need translation work

Translated and entered japanese version of english language.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
Neat, thanks @roshikouhai !

@GooeyHub: ok to test

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by msteiger** [comment]
Thanks, @roshikouhai - this is definitely better than the current state. I think we need font bitmaps for Japanese glyphs.

Some glyphs seem to be Katagana while some are Kanji. Can you confirm this?
Is it enough to cover the [CJK Unified Ideographs (Part 1)](https://en.wikipedia.org/wiki/CJK_Unified_Ideographs_(Unicode_block))?

**Comment by msteiger** [comment]
Even part 1 alone contains 5375 glyphs (4E00–62FF), so this is hardly an option. Does is make sense to include Katagana only (30A0-30FF)?

**Comment by Cervator** [comment]
@roshikouhai - ping! Still out there? :-)

**Comment by roshikouhai** [comment]
Sorry, had school tests for a while. So do you want me to convert all of the translation into katakana?

**Comment by msteiger** [comment]
That would make it easier for us, yes. Does that make sense? Is that readable/understandable for everyone?

**Comment by roshikouhai** [comment]
It would still get the point across at the downside of being unconventional. I will get working on a katakana verison then.

**Comment by msteiger** [comment]
What would be the "usual" approach then? Kanji? It seems to comprise roughly 5400 glyphs without extensions.

**Comment by roshikouhai** [comment]
How about a mixture of hiragana and katakana? That would be easier to read.

**Comment by msteiger** [comment]
Sounds great! I will prepare the fonts for that while you adjust the translation.

**Comment by roshikouhai** [comment]
I'm fairly new to the Github workflow. Should I submit a new pull request or commit this branch?

**Comment by msteiger** [comment]
Both works in general. I would add the commit to this branch so it will be part of the Pull Request and discussion.
You can merge the commits later into one if you want or even re-edit the existing commit, but there's no need to do that.

**Comment by msteiger** [comment]
What do you think of that rendering?

image

This is Hiragana and Katagana characters only, but complete.

**Comment by roshikouhai** [comment]
really nice! Almost down with hiragana and katakana translation.

**Comment by roshikouhai** [comment]
Changed so that the japanese translation is only hiragana and katakana.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by msteiger** [comment]
Thank you, @roshikouhai!

**Comment by Cervator** [comment]
Much appreciated @roshikouhai ! Looks great

Will add you to the credits shortly, waiting for a related PR that overhauls the credits list itself :-)

If you have a forum account or make one let me know and we'll get you a Contributor badge there. Feel free to introduce yourself at http://forum.terasology.org/forum/contributor-introductions.7 if you're interested in contributing more stuff, anything is appreciated!

**Pull request merged**
