### PR TITLE
Player is shown the respawn screen, if he joins a game where his character is dead.

### PR DESCRIPTION
**Pull request by l0ftyWhizZ**
Until now, when the player joins a game, and the `restorePlayer` function is called, it checks whether it has the AliveComponent, and if not, then it attaches one. 
So, this allowed the dead players to join the game with 0 health, which doesnt seem logical. So, instead with this change, the players who are dead are shown the respawn screen, and only upon clicking the `respawn` button does the player get back in the game.

### Contains

A small logical fix to the dead-players rejoining the game.

### How to test

- Generate a new game.
- Type in `hjump` command, and jump. Upon landing, you will be shown the DeathScreen.
<b> Make sure you dont have `softLanding` cheat enabled. </b>
- Now, don't respawn, instead directly 'Exit Terasology'.
- Run the build again, and join the same game.
- You'll be shown the respawn screen before spawning into the world.

### Outstanding before merging
- Nothing as of now.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by mjuvekar7** [comment]
@GooeyHub ok to test

**Comment by mjuvekar7** [comment]
The respawn screen is showing, but I'm not respawning properly. However I am pretty sure it's an issue with my workspace (been having some issues lately). Can someone else please verify just in case?

**Comment by oniatus** [comment]
Poking at some opinions if we should respawn the player before entering the menu @skaldarnar @flo @Josharias @iojw :) I would be fine to merge as-is.

**Comment by Cervator** [comment]
@gooeyhub ok to test

Thanks for the tweak! Sorry for taking so long but should be catching up soon :-)

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by iojw** [comment]
I think we should try to have consistency between the actions of the Exit Main Menu button and Exit Terasology button on the death screen since they both involve leaving the current world. As mentioned Exit to Main Menu sends a RespawnRequestEvent before leaving but Exit Terasology does not so that's why this issue occurs. We could either remove the respawn event from both buttons (so players would be shown the death screen after joining) or add it to both buttons, I'm ok with either 🙂

**Comment by l0ftyWhizZ** [comment]
So what should I work on further in this PR? :D

**Comment by Cervator** [comment]
IMHO: Don't force the player to respawn on an exit event on any sort. Respawning could have follow-up actions the player then would miss, like an auto-respawn in a persistent world with aggressive creatures might just leave the player's avatar to get eaten again.

So better leave the player dead, and trigger the respawn event on joining again. Then the player gets the choice each time - could even ignore the screen once more and exit, then get served the choice again later.

But maybe that should be a separate PR after this one :-)

**Comment by iojw** [comment]
I've tested this a bit and if I Exit Terasology from the death screen twice without respawning, rejoining the game again will lead to me entering the game with 0 hearts again. 

@l0ftyWhizZ Could you look into this? You can also remove the respawn event from the Exit Main Menu button in DeathScreen.java so both buttons will have the same interaction.

**Comment by l0ftyWhizZ** [comment]
Oh so exitting twice doesn't make the respawn screen to appear? I'll look into it. Thanks! 😄

**Comment by l0ftyWhizZ** [comment]
So earlier, the AliveComponent got added to the player even when he/she chooses to exit the game, hence causing the player to spawn with 0 health the next time. So, now unless the player chooses to respawn, AliveComponent won't get added.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by mjuvekar7** [comment]
Tested it out, and it works just fine.

**Comment by l0ftyWhizZ** [comment]
Are there any other changes recommended for this PR? 😄

**Comment by iojw** [comment]
LGTM!

**Comment by l0ftyWhizZ** [comment]
Closing this PR since I forgot to rebase and simply "pulled". Will make a new one

**Pull request closed without merging**
