### PR TITLE
Allow rigid bodies to settle and sleep - time for more explosions!

### PR DESCRIPTION
**Pull request by Josharias**
When rigid bodies are removed,  an area around them is woken up so that bodies resting on top can fall.  This allows large amounts of rigid bodies in the world without actively calculating physics on them (like say from the railgun).  The falling bodies problem was solved before by always setting the bodies to an active state, now it only activates a region around the removed body.

You will see framerates improve a couple seconds after a number of railgun hits.  Previous to this change it would drop the framerate down really low until the entities were removed entirely by the LifespanComponent.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/429/
Hooray Jenkins reported success with all tests good!

**Comment by Josharias** [comment]
Also,  I have done a quick pass on improving lots of dropped blocks in a multi-player situation.  This reduces a bunch of changed components being sent over the wire.  There is more to be done in regards to the jittery/wobbly items in general,  but this makes it more playable.

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/430/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Awesome! Can't wait to check it out when I get a chance :-)

**Comment by Josharias** [comment]
I found some other excellent optimizations for this.  Hold off on official testing for a few days.

**Comment by Cervator** [comment]
Roger that!

Linking to #1680 for reference, more notes and ideas there :-)

**Comment by Josharias** [comment]
Major improvements on the multi-player side by reducing the network traffic.  There is still something odd about how headless and remote client seem to not settle the dropped blocks.  Also,  there is still an issue of blocks slipping through the cracks which cause the physics engine to work harder.

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/431/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Initial review confirms a *massive* performance improvement from going mad with the railgun, including in multiplayer!

I still see a bit of a heavy hit right as you fire the railgun but then yeah as the blocks come to rest the engine calms down quite a bit.

Even in multiplayer the client survives pretty well with just a bit more of a delay seeing the carnage result in blocks removed and physics cubes dropping vs. the same action on the hosting client.

Observations:

* TiDi in debug text seems stuck at 1.0? I don't see it change on either server or client even with massive railgunning. So hard to say if I'm seeing actual TiDi improvements or just cubes at rest :-)
* Blocks seem to be all falling straight down now rather than flying in all sorts of directions. Is that intentional so they'll settle faster vs. a rain of blocks falling off a mountain?
* Is your comment about blocks slipping through the cracks perhaps related to #2139?
* Railgun is awesome again :D

terasology-160220004630-1152x720

terasology-160220005039-1152x720

@immortius if you're around and available this might be relevant to your interests, with physics and multiplayer involved. And fun railgunning!

**Comment by Josharias** [comment]
Right.  I suppose I should say that you automatic time dilation is a opt in feature.  Use the command ```toggleAutoTimeDilation``` to enable it and see if it makes a significant FPS improvement when everything is working hard.

**Comment by Josharias** [comment]
The heavy hit when you pull the railgun trigger I think is just creating all the new block entities.  I dont have proof,  but it definitely seemed like that especially on a remote client as the network traffic would spike up.

Blocks falling straight down is possibly because I refactored that out somehow by accident?  Ill check.  We should bring back the bigger dropped blocks.  They are so satisfying.

Blocks slipping through cracks is indeed probably related to #2139 

"thoroughness of the railgun"... come on man!  I just made it better in its current state... now you want more blocks dropped!?   Haha  ;)

Indeed,  explosions and railguns in general will satisfy my 4 year old boy now. :)

**Comment by Cervator** [comment]
Ahh I thought I saw an opt-in somewhere, but I guess I figured it was systems that would have to opt into it rather than a command. Alright, able to see the number change now :-)

In single player I *think* it makes a small difference? Hard to tell without setting up some actual repeatable metrics of some sort. In multiplayer I can see it but probably the pressure of running two players on one system is overshadowing any gains you'd see with a real headless server on a different system.

Bigger dropped blocks ftw! Bonus for being able to easily tweak at what size/quantity to get with different circumstances. I'd love to see the ability to quarry large single blocks with one tool (to build with again) and break apart into several smaller blocks with a different tool (say for smelting minerals - with the tool quality impacting how many/which smaller dropped blocks you get)

And yeah! Thoroughness of railgun :D We toned it down when the physics got too crazy after all. Old school railgun would drill pretty clean tunnels till the end of loaded world. Speaking of: Huh, neat, can't recall having seen as deep tunnels as when I was trying to hit player 2 in the distance with player 1

**Comment by Josharias** [comment]
Ill fix up and make the railgun fancier, but I need to do it after the Health move to Core.  Also on the explosion todo list is to make the TNT have a fuse and to chain react. Because that is all my son does when playing MC,

I agree that it is hard to know if the time dilation is actually helping.  It did cause my FPS to go from 2 to 5.  So in terms of percentage increase in FPS it is effective...  but the game is still not playable at 5.  So...  I dunno what to do with it.

**Comment by Cervator** [comment]
Keep it around in any case, especially since it is an opt-in system :-)

We should set up a better test server approach via Jenkins so we can test out and benchmark server changes like these (without it being a full test server running latest release)

Fancy railgun later is fine. And yeah TNT with a fuse has been on my wish list, or rather TNT with a remote detonator has! Easy little tool with a mark to arm and trigger to go boom :-)

**Comment by Cervator** [comment]
Tested out on top of the inventory/health changes. Seems good still!

We can worry about benchmarking more exactly later :-)

**Pull request merged**
