### PR TITLE
NUI editor icons

### PR DESCRIPTION
**Pull request by rzats**
### Contains

An implementation for rzats/gsoc-nui-editor#7.

- The NUI editor is modified to use the `StringIconTextRenderer` conveniently created in #2270, which is slightly tweaked to support `null` icon textures.
- 16x16 icons for all core widgets (`UI*`), layouts and JSON node types are added.
- An option is added to disable icons, wrapped within a new `NUIEditorConfig` class. 
- `TreeViewTestScreen` is removed as obsolete.

editor-icons

### How to test

Open the NUI editor (F10), check out icons for widget nodes, then try enabling/disabling icons within the Settings menu.

### Outstanding before merging

- [x] Provide attribution for the icon set used ([Fugue Icons](http://p.yusukekamiyamane.com/)), as well as any other sets. @Cervator: should the attribution notices be located in `CREDITS.md`?
- [x] Add icons for common properties (`type`, `layoutInfo`, `contents`, `@LayoutConfig`-annotated properties of core widgets).
- [x] If possible, add icons for core layouts.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by flo** [comment]
merged

good job

**Pull request merged**
