### PR TITLE
i18n-ed toolbar slots' descs and added polish trans

### PR DESCRIPTION
**Pull request by anuar2k**
### Contains

Minor i18n fix. :)

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Merged this at long last, after resolving conflicts. Thanks @anuar2k ! :-)

Also took the opportunity to grab latest translation work from Weblate (resolving lots of conflicts from there) to merge in as well, plus re-updating Weblate itself.

**Pull request merged**
