### PR TITLE
Overhauled serialization system

### LINKED ISSUE #3490: Recover and finish parked serialization / type handling overhaul
See #3489 for background information. @eviltak is behind the parked code related to this and may be interested in continuing with it, but is low on time as of this writing. If anybody else is hugely interested in serialization and type handling feel free to look at this but be warned that it is a large piece of work and a complex topic :-)

Goal for this issue is to work with branch https://github.com/MovingBlocks/Terasology/tree/newSerialization to finish stabilizing it so it can be re-merged

As part of that work several modules need syntax changes to compile again, as was the case when originally merging #3449. The same modules and likely more beyond that will need changes after #3456 is considered as well, both for compile fixes (maybe just the same set of modules as the first PR) and runtime issues encountered in testing with the second PR (unsure if all those would go away purely with additional engine changes)

Affected modules by round one and their initial syntax fix commits (reverted as part of preparing this issue):

* https://github.com/Terasology/MasterOfOreon/commit/17a008952995a354e93f3cc2c71ed14ae8b7adec
* https://github.com/Terasology/DynamicCities/commit/bce035463cf156fc7208257f7e4adcb8bbabbf5e
* https://github.com/Terasology/Dialogs/commit/3b5804ebf557060c24a53a79760a3d3e80cf1064
* https://github.com/Terasology/Tasks/commit/b1576fb1011f8fd7886ff7a96007ce85d2895e52
* https://github.com/Terasology/TutorialDynamicCities/commit/e5766b8374f53e0d0b9a600f53aa7176f94876d1
* https://github.com/Terasology/LightAndShadow/commit/fa33f332569990f1c6cab306fe52635b402b06a5

To be clear those commits just let those modules compile after the *first* round of serialization changes. It may be pointless to re-apply those changes exactly, as the underlying changes from round two may require entirely different fixes.

See the PRs linked in #3489 for more research and discovered issues.

As a potential follow-up to this the new Record & Replay system is awaiting some of these changes to better improve its own usage of serialized events and such. @iaronaraujo would be the primary contributor involved in that effort.

### PR DESCRIPTION
**Pull request by eviltak**
# Contents
- Clean serialization API for use in the engine and in modules
- Add serialization support for various types previously unsupported
- Modularize serialization to make it easier to add custom type serialization
- Rework serialization to serialize objects via Gson or Protobuf by changing a single line of code (see `AbstractSerializer`, `GsonSerializer` and `ProtobufSerializer`)

Closes #3490.

# Review guide
This PR is finally ready to review and merge! Since there are a lot of changes to review, I'd recommend taking a look at the user-facing API introductions/changes first:

- [`AbstractSerializer`](https://github.com/MovingBlocks/Terasology/pull/3535/files#diff-2941c45404523e22f6e2065994f11747)
- [`GsonSerializer`](https://github.com/MovingBlocks/Terasology/pull/3535/files#diff-816e327c5e9a4f8b10204a0e0cde698e)
- [`ProtobufSerializer`](https://github.com/MovingBlocks/Terasology/pull/3535/files#diff-277310030793629bd23b8b3e84e07a4c)
- [`TypeHandlerLibrary`](https://github.com/MovingBlocks/Terasology/pull/3535/files#diff-76befd1046e3bd671dffb4e3994e53fb) (renamed from `TypeSerializationLibrary`)
- [`TypeHandler`](https://github.com/MovingBlocks/Terasology/pull/3535/files#diff-ed98a03252f3f4c7750bbe08c2f14ace)
- [`TypeHandlerContext`](https://github.com/MovingBlocks/Terasology/pull/3535/files#diff-497284d4c2d9a118ea2c83bddfbf0506)
- [`TypeHandlerFactory`](https://github.com/MovingBlocks/Terasology/pull/3535/files#diff-9e490a02ea1ddf5cfab8db828bcfdb04)
- [`SerializedName`](https://github.com/MovingBlocks/Terasology/pull/3535/files#diff-3a94a5171ecc346de026ea8247d2c617)
- [`TypeInfo`](https://github.com/MovingBlocks/Terasology/pull/3535/files#diff-fdccd99cf7bf0a08d54808a83a9dd717)
- [`ReflectionUtil`](https://github.com/MovingBlocks/Terasology/pull/3535/files#diff-35714e56a06ddc78003aaa818ea3d9b1) -- will probably not be used outside the engine at all, but it's still worth a look to see if I missed documenting any public methods
- [`SerializationSandbox`](engine/src/main/java/org/terasology/persistence/typeHandling/reflection/SerializationSandbox.java) -- again, not intended for use outside the engine, but still worth a look

Since there are a _lot_ of files changed by this PR (still no conflicts, surprisingly!), I'd suggest you initially skip the ones with few (< 20) changed lines and a similar number of additions and deletions -- almost all of these files were changed by the IDE during a refactor and have no real reviewable changes.

After you finish reviewing the API changes in the files listed above, you can take a look at the logic introduced by the code in this PR: almost all of it resides in the `persistence.typeHandling` package under a `TypeHandler` or a `TypeHandlerFactory`, or the `ReflectionUtil` class. However, I am pretty confident that all these classes/methods have been tested thoroughly to ensure they work as intended, so this step can be skipped if needed.

I'd then recommend looking at the tests to see how the new serialization system would be used; the main ones to look at here are [`TypeSerializerTest`](https://github.com/MovingBlocks/Terasology/pull/3535/files#diff-d5b410b5495c61bcb2cf6a66a3e3e187) and [`TypeHandlerLibraryTest`](https://github.com/MovingBlocks/Terasology/pull/3535/files#diff-d6207d378dd049d2cbe42e0530b7a6f2), since these test most of the user-facing APIs.

# Testing
Check out branch `MovingBlocks/newSerialization` and run `./gradlew tests`

# TODO
- [x] Prevent modules for adding handlers for types they do not declare (compare module declaring `TypeHandler<T>` and module declaring `T`).
- [x] Add `TypeHandlerLibrary.getRuntimeTypeHandler` that returns the retrieved type handler wrapped in a `RuntimeDelegatingTypeHandler` to support subtype serialization
- [x] Create a reflection abstraction over `ModuleEnvironment`/`Reflections` with more `AbstractClassLibrary`-esque resolution features (if made with a `ModuleEnvironment`).
- [x] Flatten the `RuntimeDelegatingTypeHandler` serialization format by adding the `class` entry to the serialized object itself, if the serialized representation is a map

## Module Fixes
- [x] Terasology/Tasks#7
- [x] Terasology/DynamicCities#33
- [x] Terasology/Dialogs#8
- [x] Terasology/MasterOfOreon#29
- [x] Terasology/LightAndShadow#74
- [ ] Terasology/GooeyDefence#30
- [ ] Terasology/GooeysQuests#31

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by jellysnake** [comment]
@Eviltak, is this ready to be reviewed and then subsequently merged? Or is there still outstanding work blocking this?
Would _love_ to get this in as part of the merge-ocalypse

**Comment by eviltak** [comment]
@jellysnake unfortunately there is still some work to be done, potentially involving related changes in gestalt. I would say that this should be merged only after all modules have PRs fixing code that has been broken by these changes. I shall update the PR description with clear todo items so that progress can be easily gauged!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
This pull request **introduces 2 alerts** when merging 0ae28ce430c3523dd7ec98c395221030a4243939 into b6590b75c30c6dcadc3023da314d3b8eccc0ac35 - [view on LGTM.com](https://lgtm.com/projects/g/MovingBlocks/Terasology/rev/pr-c2ad18717c0694927518ea12b98ddb771b21f0ab)

**new alerts:**

* 1 for Potential output resource leak
* 1 for Dereferenced variable may be null

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
This pull request **introduces 2 alerts** when merging a9fe6e896e02ec34440900f50a0b6e6739998c59 into e831d1515d0ecc4fddd5eecab0940dcf1d57aa8d - [view on LGTM.com](https://lgtm.com/projects/g/MovingBlocks/Terasology/rev/pr-1574900ba383e6be3c64c740a12bcced1cc80d32)

**new alerts:**

* 1 for Potential output resource leak
* 1 for Dereferenced variable may be null

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by Cervator** [comment]
This pull request **introduces 2 alerts** when merging ac877f5cbbfe05fa4c95c43bcac3d2cdad98fe30 into e831d1515d0ecc4fddd5eecab0940dcf1d57aa8d - [view on LGTM.com](https://lgtm.com/projects/g/MovingBlocks/Terasology/rev/pr-7212e7ba2ef2047fa00e0224b094acea661059f8)

**new alerts:**

* 1 for Potential output resource leak
* 1 for Dereferenced variable may be null

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
This pull request **introduces 2 alerts** when merging a54b2e46b8c8512fc729e12442bc3d6cd7472ef6 into b02e53d71ea3f5ef2000405f631481fb74f6ede2 - [view on LGTM.com](https://lgtm.com/projects/g/MovingBlocks/Terasology/rev/pr-3358e2e1e1448dc0da4aae68aed029b3e1aeed41)

**new alerts:**

* 1 for Potential output resource leak
* 1 for Dereferenced variable may be null

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by eviltak** [comment]
Rebased onto `develop`, please re-clone the branch.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
This pull request **introduces 1 alert** when merging 95a786f7bf0bdf6b110b5c85017821e6e9f598c0 into dbc32f0da97e46c447ae2293a00e5babaf92c85b - [view on LGTM.com](https://lgtm.com/projects/g/MovingBlocks/Terasology/rev/pr-832a16706724ecb870b5e4073c921da411c5318a)

**new alerts:**

* 1 for Potential output resource leak

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Cervator** [comment]
This pull request **introduces 1 alert** when merging c207cd1b9e298521c171d934a44c2a29c17d37e2 into 8acfcfa776d88c82682a664d3d291185096d559b - [view on LGTM.com](https://lgtm.com/projects/g/MovingBlocks/Terasology/rev/pr-e472cae847de5759a7a2c30213bfaf7f8a15e61a)

**new alerts:**

* 1 for Potential output resource leak

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
This pull request **introduces 1 alert** when merging 821c8f7528de1d412f861179176d44dbf66f870b into 07cda61532a656c9fec148e1eee565640f0bcb9a - [view on LGTM.com](https://lgtm.com/projects/g/MovingBlocks/Terasology/rev/pr-1f1a7bb9f4f21cb3e4544d8a498eb2bf65f229c7)

**new alerts:**

* 1 for Potential output resource leak

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
This pull request **introduces 1 alert** when merging b14ebcac801b04a464e0ab59f5e11eefdfbe361d into 07cda61532a656c9fec148e1eee565640f0bcb9a - [view on LGTM.com](https://lgtm.com/projects/g/MovingBlocks/Terasology/rev/pr-5046b15a61197e21976377b7cd6f81634cd091c4)

**new alerts:**

* 1 for Potential output resource leak

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by eviltak** [comment]
This PR is finally ready to review and merge! Since there are a lot of changes to review, I'd recommend taking a look at the user-facing API introductions/changes first:

- [`AbstractSerializer`](https://github.com/MovingBlocks/Terasology/pull/3535/files#diff-2941c45404523e22f6e2065994f11747)
- [`GsonSerializer`](https://github.com/MovingBlocks/Terasology/pull/3535/files#diff-816e327c5e9a4f8b10204a0e0cde698e)
- [`ProtobufSerializer`](https://github.com/MovingBlocks/Terasology/pull/3535/files#diff-277310030793629bd23b8b3e84e07a4c)
- [`TypeHandler`](https://github.com/MovingBlocks/Terasology/pull/3535/files#diff-ed98a03252f3f4c7750bbe08c2f14ace)
- [`TypeHandlerContext`](https://github.com/MovingBlocks/Terasology/pull/3535/files#diff-497284d4c2d9a118ea2c83bddfbf0506)
- [`TypeHandlerFactory`](https://github.com/MovingBlocks/Terasology/pull/3535/files#diff-9e490a02ea1ddf5cfab8db828bcfdb04)
- [`TypeHandlerLibrary`](https://github.com/MovingBlocks/Terasology/pull/3535/files#diff-76befd1046e3bd671dffb4e3994e53fb) (renamed from `TypeSerializationLibrary`)
- [`SerializedName`](https://github.com/MovingBlocks/Terasology/pull/3535/files#diff-3a94a5171ecc346de026ea8247d2c617)
- [`TypeInfo`](https://github.com/MovingBlocks/Terasology/pull/3535/files#diff-fdccd99cf7bf0a08d54808a83a9dd717)
- [`ReflectionUtil`](https://github.com/MovingBlocks/Terasology/pull/3535/files#diff-35714e56a06ddc78003aaa818ea3d9b1) -- will probably not be used outside the engine at all, but it's still worth a look to see if I missed documenting any public methods

Since there are a _lot_ of files changed by this PR (still no conflicts, surprisingly!), I'd suggest you initially skip the ones with few (< 20) changes lines and with a similar number of additions and deletions -- almost all of these files were changed by the IDE during a refactor and have no real reviewable changes.

After you finish reviewing the API changes in the files listed above, you can take a look at the logic introduced by the code in this PR: almost all of it resides in the `persistence.typeHandling` package under a `TypeHandler` or a `TypeHandlerFactory`, or the `ReflectionUtil` class. However, I am pretty confident that all these classes/methods have been tested thoroughly to ensure they work as intended, so this step can be skipped if needed.

I'd then recommend looking at the tests to see how the new serialization system would be used; the main ones to look at here are [`TypeSerializerTest`](https://github.com/MovingBlocks/Terasology/pull/3535/files#diff-d5b410b5495c61bcb2cf6a66a3e3e187) and [`TypeHandlerLibraryTest`](https://github.com/MovingBlocks/Terasology/pull/3535/files#diff-d6207d378dd049d2cbe42e0530b7a6f2), since these test most of the user-facing APIs.

**Comment by eviltak** [comment]
Besides the requested reviewers, I also request @iaronaraujo and @llvieira to take a look at how this new serialization system impacts the Record and Replay system (specifically [`RecordedEventSerializer`](https://github.com/MovingBlocks/Terasology/pull/3535/files#diff-3d63c06d13cf043d18ce00b6d4100b34) and [`RecordAndReplaySerializer`](https://github.com/MovingBlocks/Terasology/pull/3535/files#diff-5e0fec1fbe59ce29d7f45df369cd0696)), and test it out to ensure everything still works as intended. Please also create issues for future fixes and improvements as you see fit.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by eviltak** [comment]
This PR should be ready to merge with no more outstanding changes; the review guide is in https://github.com/MovingBlocks/Terasology/pull/3535#issuecomment-507014391.

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by eviltak** [comment]
Rebased, please refetch the branch!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
### Testing & merge report

Tried out the following modules to some degree, including their dependencies & fix PRs if ready:

* Tasks & QuestExamples - found a minor bug in the tasks type handler, actually managed to fix it woo
* MedievalCities - mostly to exercise a smaller set of modules at first, fixed the Perlin->Simplex thing
* LightAndShadow (GSOC) - still had a soft dependency on Tasks, restored it for now
* MetalRenegades (GSOC)  - no module fix PR yet, managed to put one together with a bunch of tweaks
* MasterOfOreon (TSOC)
* WildAnimalsMadness (GSOC)
* Apiculture (GSOC)

I think that's the critical stuff for now. JoshariasSurvival and others need some attention in the near future as well, but there's no GSOC or TSOC impact on there, so less time sensitive. Phiew. This might be happening!

/itshappeninggif

**Pull request merged**
