### PR TITLE
Rework logging system

### PR DESCRIPTION
**Pull request by msteiger**
This PR 

* effectively removes groovy from the set of dependencies by configuring the logging in XML and Java. This is should improve startup time, remove unnecessary library code and reduce jar file size.

* delegates log events to different log files depending on the game phase (using a *sifting log appender*). Currently only in-game and not in-game are supported.

* The logging folder is cleared on startup from `*.log` files

* A *daily* rolling file appender (10 days history) ensures that logs don't get infinitely long.

* Shader dumps are no longer created by default, but can be activated in the `RenderingConfig`

* Module setup is logged for both server(+single player) and client

* Use CrashReporter 2.1.0, which now supports uploading multiple logs

A log folder could look like this now:

    shaders/
    Terasology-init.log
    Terasology-init-2015-02-22.log
    Terasology-Game 6.log
    Terasology-Game 6-2015-02-22.log

### CODE REVIEW

**Comment by emanuele3d** [comment]
Very nice!

Given previous discussions on the matter this PR is already quite a step
forward and from a feature-only perspective I'd be happy for it to be
merged as it is.

If I had to be really picky, I'd suggest to be more flexible with the
sifting so that the user/admin can group arbitrary lists of GameStates into
one log file. Initially I thought this could be done right in logback.xml,
but perhaps it should happen a GameState level, each implementation either
hardcoded or set at runtime to log to a specific file or simply generating
an output containing a sifting key string.

But splitting between ingame and not-ingame of course already covers a lot
of ground.

**Comment by Cervator** [comment]
This looks great :-)

Lots of prepwork here this evening after first day at new job. I want to give this and the applet PR some good focus for testing properly. Should have more time for that tomorrow :-)

One note: Should we support moving the old log files to an "old" dir under logs instead of just outright deleting them? Deleting the old dir first if it exists. Then we have a buffer between game starts.

I'm not sure how useful that would be, but am curious what you think

**Comment by msteiger** [comment]
Good point @emanuele3d - it now uses GameStates to differentiate between different .. well .. game states. Some of them direct to the same log to keep the number of different files low.

The folder is cleared when the game starts. Thus, they are still around when the game exits. But yeah, we could add some kind of small archive if the need comes up.

**Comment by Cervator** [comment]
Tested it out some (and merged the applet PR). The new log files pop up as expected, cool :-)

Do we advise users any differently now? Any potential for confusion with the multiple files we can prepare for?

Testing the CrashReporter's new multi-file thing failed for me though :-(

```
01:17:32.561 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.RuntimeException: Test crash triggered!
	at org.terasology.crash.CrashGameBlockSystem.onActivate(CrashGameBlockSystem.java:32) ~[na:na]
	at org.terasology.crash.CrashGameBlockSystemMethodAccess.invoke(Unknown Source) ~[na:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:497) ~[classes/:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:278) ~[classes/:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:257) ~[classes/:na]
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:157) ~[classes/:na]
	at org.terasology.logic.characters.CharacterSystem.onActivationRequest(CharacterSystem.java:141) ~[classes/:na]
	at org.terasology.logic.characters.CharacterSystemMethodAccess.invoke(Unknown Source) ~[reflectasm-1.09.jar:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:497) ~[classes/:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:268) ~[classes/:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:259) ~[classes/:na]
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:157) ~[classes/:na]
	at org.terasology.logic.players.LocalPlayer.activateTargetOrOwnedEntity(LocalPlayer.java:184) ~[classes/:na]
	at org.terasology.logic.players.LocalPlayer.activateTargetAsClient(LocalPlayer.java:160) ~[classes/:na]
	at org.terasology.logic.players.LocalPlayerSystem.onFrobButton(LocalPlayerSystem.java:308) ~[classes/:na]
	at org.terasology.logic.players.LocalPlayerSystemMethodAccess.invoke(Unknown Source) ~[reflectasm-1.09.jar:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:497) ~[classes/:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:278) ~[classes/:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:257) ~[classes/:na]
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:157) ~[classes/:na]
	at org.terasology.input.internal.BindableButtonImpl.updateBindState(BindableButtonImpl.java:177) ~[classes/:na]
	at org.terasology.input.InputSystem.processKeyboardInput(InputSystem.java:319) ~[classes/:na]
	at org.terasology.input.InputSystem.update(InputSystem.java:205) ~[classes/:na]
	at org.terasology.engine.modes.StateIngame.handleInput(StateIngame.java:191) ~[classes/:na]
	at org.terasology.engine.subsystem.lwjgl.LwjglInput.postUpdate(LwjglInput.java:65) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:461) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:372) ~[classes/:na]
	at org.terasology.engine.Terasology.main(Terasology.java:142) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_55]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_55]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_55]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_55]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134) [idea_rt.jar:na]
01:17:32.562 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
01:17:32.575 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Creating game snapshot
01:17:32.596 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Snapshot created: Writing phase starts
01:17:32.599 [main] INFO  o.t.n.internal.NetworkSystemImpl - Client disconnected: Cervator
01:17:32.632 [main] INFO  o.t.logic.console.ConsoleImpl - [NOTIFICATION] Player "Cervator" has left the game
01:17:32.632 [main] INFO  o.t.n.internal.NetworkSystemImpl - Network shutdown
01:17:34.073 [Saving-0] INFO  o.t.p.internal.SaveTransaction - Save game finished
01:17:34.073 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
java.nio.file.NoSuchFileException: logs\Terasology.log
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
	at sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:193)
	at java.nio.file.Files.readAttributes(Files.java:1684)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:105)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:69)
	at java.nio.file.Files.walkFileTree(Files.java:2600)
	at org.terasology.crashreporter.pages.ErrorMessagePanel.findLogs(ErrorMessagePanel.java:160)
	at org.terasology.crashreporter.pages.ErrorMessagePanel.<init>(ErrorMessagePanel.java:85)
	at org.terasology.crashreporter.RootPanel.<init>(RootPanel.java:70)
	at org.terasology.crashreporter.CrashReporter.showModalDialog(CrashReporter.java:80)
	at org.terasology.crashreporter.CrashReporter$1.run(CrashReporter.java:59)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:302)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

I was launching from IntelliJ and verified I got the 2.1 CR jar, yet the CR says it failed to find the old school log location. Any ideas? I provoke the crash with the CrashGameBlock from the Sample module.

Also, in LoggingContext.java line 89 there's another one of those "inner class variable must be final" issues that I think only happens in Java 7, but works on 8? I just added `final` to the `Path rootPath` and it worked fine on Java 7

**Comment by msteiger** [comment]
Thanks - that should fix it!

**Comment by Cervator** [comment]
Tested and merging :-)

Some CR suggestions for the future: 

* Maybe make the default window size a little bigger? Feels cramped, especially with extra world creations in one launch (more log tabs)
* Maybe find a way to sort the tabs so the one the crash happened in is first? I made one world, went back to the main menu, made another world, crashed, and the first tab was the first world with no problems
* Maybe make it more obvious that the active tab will be what gets uploaded when you click "Next" - maybe put the filename on the next button? Big enough if the window is bigger. I expect we'll get some reports with the wrong log file attached, doh
* Maybe add support for posting a multi-file Gist containing all the log files? Maybe with some checkboxes added in for customizing. Other multi-file approaches would also be helpful IMHO

**Pull request merged**
