### PR TITLE
Merge latest translations

### PR DESCRIPTION
**Pull request by Cervator**
Grabbed everything from our live Weblate server, pushed to the `weblate` branch.

Merged on top of latest `develop`, pushed to a temporary `weblateTest` I'm also going to configure a secondary test Weblate to use (at least for engine). @qwc is looking at maybe doing an upgrade and enabling machine translation.

http://weblate-testing.terasology.net

In this batch Arabic was enabled, as requested a while ago - but I don't think we actually have any translations for it yet.

Turkish was added, we got a somewhat problematic PR submitted for it with #2583 that wasn't written quite right. @tdgunes did a bit of translation from within Weblate resulting in https://github.com/MovingBlocks/Terasology/commit/8a4c86a6daf582b2d59949ba7e4b75de5c873d24 - do you think any other strings from #2583 could be included? It looks like some there have translations that are still untranslated.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by tdgunes** [comment]
@Cervator Sorry but yes, there are. Would it be possible to eliminate other _placeholder_ translations to see what's remaining?

**Comment by skaldarnar** [comment]
re untranslated languages: #2621

**Comment by Cervator** [comment]
@tdgunes I would just copy paste + adjust the translations from the older PR directly into `menu_tr.lang` and do a PR this time, then we'll figure out via #2621 how to make that clearer within Weblate in the future :-)

You could grab this branch then add the additional translations on top, make a new PR, and that one will cover both when merged. Or I'll grab this one later tonight my time, then can just use develop like normal.

**Pull request merged**
