### PR TITLE
Fix LGTM Alerts

### PR DESCRIPTION
**Pull request by bpas247**
### Contains

Fixes some of the LGTM alerts mentioned in #3510

### How to test

Run the unit tests that are covering the affected files.

### Outstanding before merging

- [x] Fix LGTM Implicit Casting Alerts 
- [x] Fix LGTM Javadoc Alerts

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
This pull request **fixes 13 alerts** when merging 35bf46cced69f5e8499326c0537189430e5bd4a5 into 948676050a7827dac5e04927087832ffc462da41 - [view on LGTM.com](https://lgtm.com/projects/g/MovingBlocks/Terasology/rev/pr-b792e6f3bf94c49274331097865f8d869f36ab6f)

**fixed alerts:**

* 13 for Implicit narrowing conversion in compound assignment

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Cervator** [comment]
This pull request **fixes 27 alerts** when merging f75e61ec1f0d79e22fb6eb7c37acfcb2f9bbe596 into 948676050a7827dac5e04927087832ffc462da41 - [view on LGTM.com](https://lgtm.com/projects/g/MovingBlocks/Terasology/rev/pr-a0d817b0742d3013361d634905616dfbfecfa4d2)

**fixed alerts:**

* 27 for Implicit narrowing conversion in compound assignment

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Adrijaned** [comment]
@GooeyHub ok to test

**Comment by jellysnake** [comment]
@gooeyhub: add to whitelist

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Tested and merged, thanks! Also added you to the credits :-)

**Pull request merged**
