### PR TITLE
Block and Health commands

### LINKED ISSUE #2524: `giveBlock air` crashes the game
### How to reproduce
- Start a game
- Type `giveBlock air` in console

Game should crash and loading the saved game should crash the game again.

Perhaps an easy fix. There is a need to filter out the "engine:air" block in console command `giveBlock` as suggested by @Cervator.
## 

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/38250904-giveblock-air-crashes-the-game?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by portokaliu**
Contains:
Fixes for some health and block command issues. Fixes #2524, #2430 and #1619

Required parameter count is now considered the minimum number of parameters the command needs. If it doesn't get enough, the client gets no message telling him what the issue is. If the command is processed, then he gets the proper messages. (#1619 & #2430) and would close #2217

Invisible blocks will now not override their mesh generator. As a consequence, air blocks can now be given to players but won't have much purpose (except replacing liquid blocks and other replaceable stuff) (#2524)

How to test:
Spawn 32 air blocks on a client whose max health is set to 500.

Last but not least, an idea:
- [ ] Server will tell the client to return a console error once the command has been cancelled for having insufficient params.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Thanks for this! I love being able to close multiple issues with one PR :-)

Tested out the assorted fixes and all looks well. Perhaps except for the peculiar commit message :D

Want to submit a separate issue to cover improving client-side notifications over problematic command output?

**Comment by portokaliu** [comment]
I didn't really know how to change the commit message, and I was fearing losing the changes to my code, so I just left it like this but with a proper explanation :)

Sorry for the quality bits, I realized now what I forgot and will try not to do the same with the next PRs (+ looking over all the javadoc/test stuff )

About the last issue, I would like to fix that one as well yeah. Though I'd get comments to know what to improve about the PR to complete the code part and clean the code, but I can just put it in another PR :P

**Comment by emanuele3d** [comment]
@portokaliu: via command line you can change the message of a commit with --amend. This also allows you to make more significant changes to a commit, i.e. include additional changes to the code. Similar functionality is also available via IntelliJ's VCS/Commit Changes interface.

--amend can be very useful and I'd recommend you to use it. _However_ you need to be conscious of what it does, i.e. the fact it changes the commit's ID. 

More info here: https://help.github.com/articles/changing-a-commit-message/

Hope it helps.

**Comment by portokaliu** [comment]
Hmm, I did look through the VCS menu but haven't found the proper command for this. I will use the command with the git console though :) . Looking at the descriptions in the link and might try it on one of my other repos.

Thanks for the help @emanuele3d :D

**Comment by emanuele3d** [comment]
Have you looked into VCS/Commit change? In the top-right of the commit interface there's an amend checkbox, at least in my intelliJ version. By the way, I also used to like command line better and I still do lots of things through it. But the interface does help in writing multi-line commit messages AND helps to visually compare files.

**Comment by Cervator** [comment]
The code quality stuff is minor, I've been meaning to go looking myself when I merge something just because I have an excuse to (the files are being changed anyway) :-)

Rebase in IntelliJ can do the updated commit message nicely too, since you can squash a second commit (like a few follow-up tweaks) into the first one and update the commit message right in the IDE. I haven't gone looking much for alternatives tho, so the VCS/Commit route may actually be easier!

**Pull request merged**
