### PR TITLE
Refetch controllers by clicking on menu button

### PR DESCRIPTION
**Pull request by georgewbar**
### Contains
This pull request begin with PR #3705 as a base for changes.

* A "Refresh Controllers" button was added to main menu that partially
solves "recognize disconnect and reconnect" feature in issue/#2125. When
this button is pressed, the list of controllers are re-fetched to be
recognized by the system. This partially solves the problem of having
to close and re-open the game every time a controller is created.

* Also, when this button is pressed, the "Controller Settings" screen is
disposed from the assets. This is done to solve to force the system to re-create
the "Controller Settings" screen in case it had already loaded in the assets
before the "Refresh Controllers" was pressed. This makes the system show the controllers
in the "Controller Settings" screen after re-fetching the controllers. That is why it is related to issue/#3648.

Note that: the re-fetching of controllers was implemented and tested only for windows 10 and Xbox 360 controller. Implementing and testing needs to be done for other operating systems and controllers.

### How to test
Run the game as usual without connecting a controller. You can begin a new game if you want. Then go back to the main menu. Connect a controller. Click on "Refresh Controllers". Then, go to "Settings" -> "Controller Settings" if you want. You should see that the controller options are shown. Then you can go back to the main menu and continue playing using the controller.

**Note that**: when resuming the game in the manner described above, sometimes you need to move the mouse a little bit on the screen and see that player is rotating. Then, begin playing with the controller. I think that it has to do with focus on screen or something like that.

It was a little bit hard to write unit tests (two unit tests only were written) to test this feature because it was hard to hard to simulate plugging and unplugging a controller.

### Outstanding before merging

- [ ] Need to implement and test for other operating systems (e.g. linux and macOS) and other types of controllers.
- [ ] Need more unit tests.
- [ ] Need to have a way to not need the "Refresh Controllers" totally. Maybe JNI is a good option. Or move "Refresh Controllers" button to be in "Controller Settings" menu instead.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
Hi @georgewbar and possibly others, little hard to tell from the commit history what's going on - when possibly try to avoid merge commits and PRs within other forks, unless you end up rebasing or using a clean branch at the end :-)

Thank you very much for submitting this PR! And apologies for taking a little while to get to it. Will try to review & test sometime soon. One quick thing I noticed is that you have a series of code style issues in your PR, Would you mind setting up and running [Checkstyle](https://github.com/MovingBlocks/Terasology/wiki/Checkstyle) on just the files you modified? Feel free to also fix any issues that existed before your edits. The important stuff is things like missing brackets on single-line `if` statements and such. Checkstyle & your IDE will mark stuff that needs attention for you 👍

**Comment by jellysnake** [comment]
Just quickly tested this out, I can't seem to get it to work.
Booted the game without any controllers plugged in  
Plugged in my XBOX360 controller
Hit Refresh
Nothing changed. The game still didn't think it could find the controller.

Aside from that I would also like to see the button moved to the Settings menu or even the top of the Controllers Settings menu. Having it on the main menu is quite a bit out of place

**Comment by pollend** [comment]
kind of confused why we need a button to do this. I'm pretty sure you can detect this automatically.

**Comment by Cervator** [comment]
Going to close this as out of date, based on #3705 which itself was replaced by #3839 yet that was also closed for going out of date without active maintenance toward making it merge-worthy. Will add references to this one elsewhere to make it visible to anybody in the future wanting to work on the area. Thank you again for the effort @georgewbar - if you're interested in picking this back up and salvage this and other related pieces please feel free, that would be lovely :-) See #4544 and #3648 as well

**Pull request closed without merging**
