### PR TITLE
made the TriggerComponent to be compatible on a network

### PR DESCRIPTION
**Pull request by 0shine0**
### Contains

Makes the variables of the TriggerComponent to be synched between server and client.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by 0shine0** [comment]
pinging @Cervator for reveiw

**Comment by Cervator** [comment]
Based on Slack I'm not sure if there's an update coming for this one? Or ready to merge?

I released v1.3.1 of TeraBullet with your fix from https://github.com/MovingBlocks/TeraBullet/pull/3 - we could increase the engine's dependency version on TB as part of merging this PR by editing `/engine/build.gradle` - could also be done for local testing. Speaking of, can we test this in any particular way? What part of the CombatSystem exercises this?

**Comment by 0shine0** [comment]
It is just a precaution i guess. Because the variables in the TriggerComponent were not marked to replicate over server. I added @Replicate annotation to them as is also the case in RigidBodyComponent.
You can test it by doing the usual as well multiplayer testing.

**Comment by Cervator** [comment]
I took care of the TeraBullet dependency bump. Tested locally and merged :-)

I was able to get at least one perfect bounce with an arrow, including having it stick in the ground at the end. Still mostly quirky, but cool! And that was with a multiplayer client.

**Pull request merged**
