### PR TITLE
Remove duplicate image converter util

### PR DESCRIPTION
**Pull request by msteiger**
Moved `imageToByteBuffer` from `LwjglGraphics` to `TextureUtil`.

Also added a tiny fix in `TextureDataFactory` about creating single-color textures.

### CODE REVIEW

**Comment by Cervator** [comment]
I tested this and it initially looked good, although 4 Omega modules use the method and needed renames: Fluid, ItemRendering, PlantPack, and WoodAndStone.

I fixed ItemRendering and switched to the YinYang branch for LASR to see how that would look - I know IR is being used for that. Looked perfectly normal, yay!

But then I tried out TTA and did `giveitem woodenbucket` to go scoop some water ... which made the bucket blue and the water red :D

The bucket behaved normally in binary Omega 95 so it might be this PR making it act funny. Able to take a look? I can fix the modules if you want as long as you can check on the engine code :-)

**Comment by msteiger** [comment]
Good catch! Should be fixed now.

**Comment by Cervator** [comment]
I'm still getting blue blood-buckets :(

**Comment by Cervator** [comment]
Ah, maybe never mind - I wonder if the old version is stuck on my system vs your rebased version. Trying again.

**Comment by Cervator** [comment]
Yep that did it, my mistake :-)

We still have some weird issues about the grass, but that's pre-existing:

terasology-150301125054-1152x720

**Pull request merged**
