### PR TITLE
Make teleport command work in multiplayer.

### PR DESCRIPTION
**Pull request by flo**
### Contains

Make teleport command work in multiplayer.

API wise, character teleports can now be simply triggered on the server side by sending a CharacterTeleportEvent to the entity. So implementing a portal should be much simpler now.

### How to test

Use the teleport command as remote client.

### Outstanding before merging

Can be merged after #1619 so that @HashCode55  does not have to do the merging.

@HashCode55: I started trying it out (because I was curious) before I read your reply and when I read it I was almost done. I hope you don't mind that I created this pull request.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/490/
Hooray Jenkins reported success with all tests good!

**Comment by Josharias** [comment]
I tested this in a headless server/remote client scenario.  Works great.  Also,  I like the new event,  I must admit I have avoided anything teleport-y bceause of the complexity of doing this.

Ill wait till after #1619 to merge this.

Also... flo, your github branches are taking over my branch list!  :D

**Comment by Cervator** [comment]
> Also... flo, your github branches are taking over my branch list! :D

Haha yes, so much this :D

Thanks for the quick fix!

**Comment by Cervator** [comment]
With #2217 now potentially being problematic due to the server/client stuff should we go ahead and merge this first?

With a release scheduled Sunday I'd rather stay safe on stability, can merge the other one after.

**Comment by flo** [comment]
yes, since it is clear that the other issue will take longer, please merge this.

**Comment by Cervator** [comment]
Tests out great with headless server + 2 clients, merged :-)

Thanks!

**Pull request merged**
