### PR TITLE
add Hungarian flag

### PR DESCRIPTION
**Pull request by Avalancs**
Add hungarian flag for the settings screen. Also corrected some translations in weblate, how does it appear in git?

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
@GooeyHub: add to whitelist

@Avalancs: thanks again! Huh, we have a Hungarian translation file, but it isn't showing in the player settings list (so easy to miss it also didn't have the flag). That's weird. 

Translations from Weblate we pull over from its branch to develop here occasionally, sometimes right around when we're preparing a release. 

I see pending changes there, will try to merge over tomorrow then figure out why the entry doesn't show up. When it does we should be able to validate the flag from here and merge :-)

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Avalancs** [comment]
I could see the language in the develop build, that's where I noticed it's missing the flag.

**Comment by msteiger** [comment]
Thanks @Avalancs - where does the icon come from? If I remember correctly, we're using [famfam flags](http://www.famfamfam.com/lab/icons/flags/). It would be nice, if the flag icons were consistent (licensing issues aside).

**Comment by Avalancs** [comment]
Ohh sorry, I didn't know. I took the image from the hungarian wikipedia https://hu.wikipedia.org/wiki/Magyarország_zászlaja and edited it with paint so it would look decent in this size.

**Comment by Cervator** [comment]
> Should I replace it with the one from famfam?

Yes please, so we can be consistent with the icons and licensing :-)

**Comment by Avalancs** [comment]
Okay, let me start another pull request, so the one I uploaded won't appear in the history.

**Pull request closed without merging**
