### PR TITLE
Add BEACH and OCEAN biomes

### LINKED ISSUE #1512: Add beach and water biomes to CoreBiome
Currently, there is no biome definition for neither water bodies nor beaches. The legacy world generator performed simple checks for sand blocks and sealevel height to prevent trees from growing there.

In the current setup this doesn't exist anymore. Thus, a beach could actually be in the forest biome and be overgrown with trees.

I am currently refactoring the tree generation process to enhance flexibility, but also to bring back the functionality of the legacy generator. If there was a biome for sand beach, it could have growing probabilities assigned like the others.

Same goes for water bodies. This would even allow for underwater plants.

I therefore suggest to add the following two biome types:

* `BEACH` or maybe shore/beach front/coast
* `WATER-BODY` or water/underwater/sea

Maybe a native-speaker can pick the best expression?

### PR DESCRIPTION
**Pull request by msteiger**
This PR adds two more biomes to the Core module:

image

This allows for specifying plant growth probabilities and few more niceties.
A few more minor things:

* Removed WorldGenerationConfig (obsolete, unused)
* Removed CoreBiome.vegetationFriendly (obsolete, unused)

Fixes #1512

### CODE REVIEW

**Comment by emanuele3d** [comment]
I don't know much about World Generation, so please forgive me if I'm asking something obvious.

If one day somebody wants to add a number of underwater biomes or a module that adds underwater biomes, would having an Ocean biome already somehow limit the possibility?

**Comment by msteiger** [comment]
This is only for the world generators in the Core module (Perlin, Flat and HeightMap). Modules can define arbitrary Biomes, so this should not affect them.

**Comment by Cervator** [comment]
Looks good, definitely an improvement on what we have so beaches can get back in line on being more unique :-)

I am guessing it isn't quite perfect yet but that's okay - for instance the solid underground below an ocean gets labelled as ocean, and I think beach goes all the way down too.

Should the beach edge definition be more in line with the terrain generator? Currently it can place sand one block higher (or more?) than the beach biome so you can find a stump of sand to jump on you're suddenly in plains :-)

One problem before anybody can go ahead and merge this as reviewed: WorldGenerationConfig is totally in use, in Cities no less :D I figure you might just not have updated it yet? Feel free to merge this at the same time as tweaking that (or undelete it if we do actually need it)

**Comment by msteiger** [comment]
I moved the WorldGenerationConfig class to Cities, which seems to be the only module that is using it.
I also updated the commit and removed the beach-style areas for non-beach biomes.

Afaik, biome definitions are independent of y coordinate. Therefore also the blocks below the seafloor and those up in the sky are in the OCEAN biome.

**Comment by MarcinSc** [comment]
That is incorrect. If you take a look at WorldProviderCore and CoreChunk interfaces, they both define biome as being defined by (x,y,z) coordinates.

**Comment by Cervator** [comment]
That's the biome-per-block I take it :-)

I don't recall how 2D biomes (old school) and per-block biomes (new school but not in place everywhere and empty/default if not set) compare or work together currently

Should we go ahead and merge this then or are there any outstanding concerns?

**Comment by msteiger** [comment]
Ah, that's interesting. The `SolidRasterizer` reads the biome from the 2D facets and writes it for the entire column. Thanks for the hint.

**Pull request merged**
