### PR TITLE
New create game flow, final touches

### PR DESCRIPTION
**Pull request by TheFlash98**
### Contains
Disabled the time progression slider and world shape drop down. Changed the UI of the `WorldSetupScreen` and removed the Message Popup which appeared by clicking "Re-Roll".

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by nihal111** [comment]
LGTM, merging!

**Comment by TheFlash98** [comment]
[theflash98 & multi-world](https://trello.com/c/dYU1iOul/38-theflash98-multi-world)

**Pull request merged**
