### PR TITLE
Testing upgrade

### LINKED ISSUE #3538: Mockito support issues on Java 10 & 11
### What you were trying to do

Run all unit tests in the `engine-tests` project with Java 10 on a Mac

### What actually happened

About 200 tests failed, seemingly with well-known Mockito compatibility issues on newer Javas. See for instance https://github.com/mockito/mockito/issues/1419

I suspect we might just have to keep an eye on this but in the meantime could probably try to update to the very latest Mockito anyway so long as it doesn't break anything (at least on Java 8)

### How to reproduce

* Run the engine unit test with Java 10 or 11
* Try varying the version of Mockito in the `build.gradle file in `engine-tests` to `2.23.0` - for me that cuts it down to about 6 broken tests, still at least some are Mockito related  

### Computer details

* MacOS Mojave update 10.14
* Java 10.0.1+10

### PR DESCRIPTION
**Pull request by DarkWeird**
### Contains

Upgrade Junit 4 -> 5
Upgrade Mockito -> Mockito 3 (Fixes  #3538)
Upgrade Jacoco, PMD

* Testing takes 2-3x less time (even less on java 11+(checked))
* Tests can run on Java 9+ 

### How to test

* Run "gradlew test" 

### Outstanding before merging

- [x] Migrate Junit4's asserts to Junit5's asserts

### CODE REVIEW

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by DarkWeird** [comment]
Update of PMD breake PMD Config :(

**Comment by DarkWeird** [comment]
Update PMD config file in:
https://github.com/MovingBlocks/TeraConfig/pull/6

Has incorrect encoding: UTF-8 BOM - fixed

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by Cervator** [comment]
Alright this took a bit of poking and prodding, but I got a viable new zip for TeraConfig shoved manually into Artifactory and validated locally - yay! Tested around a bit and everything looks good so going ahead and merging. Thanks! :-)

**Pull request merged**
