### PR TITLE
Update world gen. configuration with Component clones

### PR DESCRIPTION
**Pull request by msteiger**
This PR changes the current property binding scheme for world gen. configuration. Previously, fields were modified directly through PropertyProvider's reflection system. This has the drawback that world gens are not notified (or only afterwards) that a parameter has changed.

This PR uses copies of configuration components and calls worldConfig.setProperty() as usual. This allows the world gen. to update accordingly (reload a height map, clear caches) or even decline the new parameter set.

I had to change `handleSwitchToPreviewEnvironment.handleSwitchToPreviewEnvironment` so it would update the `ComponentLibrary` with the new module environment. It also uses the sub-context now. Unfortunately, this update cannot be undone atm. Since this is using the sub-context only, it should be ok though.

To test this try the HeightMap world gen. or PolyWorld. Both should work nicely now even when the height map / graph density is modified.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/228/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Tested around some, making config changes with heightmap and previewing a bunch. Looks fine. Does that cover the changes?

Pinging @flo if interested in commenting on the fun with contexts

**Comment by flo** [comment]
This will propably collide with the changes @immortius  made about the engine life cycle.

See his last comment on https://github.com/MovingBlocks/Terasology/issues/1770

**Comment by immortius** [comment]
Probably not worth worrying about my branch though, who knows when it will be ready.

**Comment by Cervator** [comment]
Went ahead and merged it then, at least it isn't a huge number of changes to deal with :-)

**Pull request merged**
