### PR TITLE
Fix bug #2154

### LINKED ISSUE #2154: Selection grid appears in wrong spot for a multi-block workstation
Noted while testing #2141 (but likely unrelated):

terasology-160206155224-1152x720

Probably just need to find the spot in code that picks where to put the selection grid and react better to multi-block objects (I suspect it isn't just this TTA workstation). With a little know-how or detective skills that may be contributor friendly.

Reproduce: In Throughout The Ages break apart enough branches and dirt to make a crude axe hammer (craft with `g`) then chop some tree trunk blocks, place two adjacent, right click either top with the axe, tadaa you get a two block work station. Or just cheat and requests the wood trunk blocks via console :-)

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/30611485-selection-grid-appears-in-wrong-spot-for-a-multi-block-workstation?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by TobyShaw**
### Contains

Fixes #2154 

The target returned came from the entity associated with the block, which for all elements of a multi-block object would give a location in the same place. This modifies the target to set the LocationComponent to targetBlockPos

### How to test

Reproduce: In Throughout The Ages break apart enough branches and dirt to make a crude axe hammer (craft with g) then chop some tree trunk blocks, place two adjacent, right click either top with the axe, tadaa you get a two block work station. 

Hover over the station, see that the selection grid appears in correct place for all blocks at all times.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
ok to test

Thanks for the PR @TobyShaw ! :-)

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/491/
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/492/
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/494/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Tested! Looking good. Adding to credits & stuff :-)

If you are already playing with TTA stuff want to look at #2213 next? It is pretty annoying (can't see crafting output) and probably easy to fix. Would be great to have done before the v1.0.0 release tomorrow.

**Pull request merged**
