### PR TITLE
Bug Character can jump once under water fixed

### PR DESCRIPTION
**Pull request by Maximetinu**
### Contains
Fixes [#3267](https://github.com/MovingBlocks/Terasology/issues/3267)

### How to test
Jump into the water and check that you're not able to jump, neither diving underwater nor swimming above the surface

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
Hi @Maximetinu and thanks so much for the fix! Just to clarify though, are there are special conditions at all needed to reproduce it? I can't actually replicate #3267 reliably when I'm *in* water, only when I'm at the very top and get the little "help hop" meant to make you have an easier time to get out from water onto solid land. Which admittedly doesn't make sense when you're not up against a block you can jump on to.

I do recall occasional weird jumping-like behavior, I just can't reproduce it to really test this well before applying the fix. After the fix can you still easily get out of water on to dry land with the "help hop" or does that get disabled too?

By chance are you one of the GSOC student candidates and/or do you have a forum account/intro yet?

@GooeyHub: ok to test

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Maximetinu** [comment]
Hi @Cervator, glad to be of help! 

I've been testing and yes, there are a special condition that I have not mentioned. To reproduce it, you must get in the water without jumping, because if you jump just before it starts the swimming/diving mode, then the number of jumps left is set to 0 and it's not possible to jump. But, if you hit the water without jumping, whether by falling or by walking forward, the variable "numbersOfJumpsLeft"is still 1 and you're able to make a jump.

About the "help hop", I am aware that it's not a bug and after the fix it isn't disabled, of course.

And yes, I'm one of the GSoC students interested in working with MovingBlocks. I still don't have a forum account, thus far I've been diving into the code and thinking about the projects, but soon you'll see me over there.

**Pull request merged**
