### PR TITLE
docs: update module lineup list

### PR DESCRIPTION
**Pull request by devindoherty**
### Contains

Reorganization and updating of docs/modules.md

Cross referenced list in the omega properties with module lineup in docs/modules.md.
Updated module list.
Added Other Module subsection.
Added Tutorials section.

I don't have much experience with git or documentation so criticism / thoughts welcome.

Refs #4040

### CODE REVIEW

**Comment by pollend** [comment]
I really like this organization to the the README I'm sure @Cervator would have some comments on this.

**Comment by devindoherty** [comment]
> I really like this organization to the the README I'm sure @Cervator would have some comments on this.

I mostly just moved things around and copied descriptions from the individual modules.

Few questions I had:

Should archived modules be left in the secondary list?

Should all Tutorial repos be listed here?

**Comment by jdrueckert** [comment]
IMO we don't need the archived modules in the secondary list.
And I'm in favor of listing all tutorial repos there, yes. Didn't check, which are missing?

**Comment by devindoherty** [comment]
> And I'm in favor of listing all tutorial repos there, yes. Didn't check, which are missing?

I think all these:

TutorialTelemetry
TutorialPathfinding
TutorialProfiling
TutorialGroups
TutorialEventsInteractions
TutorialEntitySystem
TutorialMultiplayerExtras
TutorialI18n
TutorialBlockFamily
TutorialSnakeTournament
TutorialParticleSystem

**Comment by jdrueckert** [comment]
Okay, then I would say the following should definitely be listed:
TutorialPathfinding
TutorialParticleSystem
TutorialEntitySystem
TutorialEventsInteractions
TutorialMultiplayerExtras
TutorialBlockFamily
TutorialI18n
TutorialTelemetry (needs updating now that we moved it to k8s @agent-q1 )
TutorialProfiling


I'm not so sure about the following... opinion @Cervator ?
TutorialGroups
TutorialSnakeTournament

**Comment by skaldarnar** [comment]
@devindoherty From the conversation it looks like this PR would be ready to merge when the following tutorial modules are listed as well:

> TutorialPathfinding
> TutorialParticleSystem
> TutorialEntitySystem
> TutorialEventsInteractions
> TutorialMultiplayerExtras
> TutorialBlockFamily
> TutorialI18n
> TutorialTelemetry (needs updating now that we moved it to k8s @agent-q1 )
> TutorialProfiling

We'd highly appreciate if you could add those, will gladly merge then 🙃

**Comment by devindoherty** [comment]
> We'd highly appreciate if you could add those, will gladly merge then 🙃

Should all be added.

**Review by skaldarnar — APPROVED** [review]

**Pull request merged**
