### PR TITLE
Add proper Controller support

### PR DESCRIPTION
**Pull request by msteiger**
This PR is complete and functional, but still not perfect due to shortcomings in JInput. 

- [ ] Custom bindings for controller axes/buttons
- [x] Multiple controllers
- [x] UI menu for controller selection
- [ ] Controller events (without binding)
- [ ] Button constants - currently `ZERO` - `ELEVEN`
- [x] Robustness (don't spam the log when polling fails)
- [ ] Recognize disconnect/reconnect
- [x] Invert axis
- [x] Support rotation
- [x] Support Z axis

This is enough to play the game properly with a XBOX 360 (original or emulated) controller.
Controllers can be configured through the Input menu (at the bottom).

### CODE REVIEW

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/381/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Hoping to take a look at this in the weekend. I've got a nice new X-55 Rhino crazy HOTAS thing to set up and play with, figured I'd test that as well just to see :-)

**Comment by Cervator** [comment]
Testing this now (the conflict is tiny and benign) - before I forget my goofy old generic PS3 controller was still able to provoke the log spam if removed :(

```
14:29:07.607 [main] INFO  o.t.i.lwjgl.JInputControllerDevice - Removed controller: Afterglow controller for PS3
Jan 10, 2016 2:29:07 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to poll device: Failed to poll device (8007000c)
```

Next up testing dual controller just... I dunno, because? :8ball:

**Comment by msteiger** [comment]
Ah that's great! Thanks for testing! Both controllers should be equally able to move the player around.
Will look into the log spam issues - might take a few days though.

**Comment by Cervator** [comment]
Two controllers test out fine! Heck technically three controllers got tested! This HOTAS thing counts as two separate things (throttle stick and joystick). Could move with all three at once, although not very well haha.

I'm going to have to post a "And now for something completely different" video that's just me pushing a flight throttle forward to move a character in Terasology. You know, just for overkill. With default settings this X-55 thing has a "split throttle" (the throttle can be unlocked into two independent throttle sticks) where the left side is strafe left/right and right side is move forward/back, quite amusing to move with it locked since then you get both at once.

Very nifty input detection where it gives the full name too!

terasology _ alpha_2016-01-10_23-46-19

That monster has so many buttons I did manage to find several that would crash the game. There are probably multiple more exotic input types there than simply buttons and axes. Watch out for castle hat sticks!

The "Home" key on my boring old PS3 generic controller does also cause a crash. I wouldn't worry about that (or the log spamming) too much, we still have a ways to go before the input mappings look like something out of Elite Dangerous. Although now I look forward to piloting something in Terasology that can fly! :D

**Pull request merged**
