### PR TITLE
Game Name + Spawning World Issue + UniverseConfig [WIP]

### PR DESCRIPTION
**Pull request by TheFlash98**
### Contains
Fixes the issue the GameName being null and the one with spawning world. 
### Outstanding before merging
I'll push the config stuff to this PR itself, no need to merge this one yet.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Doesn't work for me :-(

Tried both without deleting an existing `config.cfg` then deleted it to start fresh. First attempt had loaded the prior setup fine so Master Of Oreon was queued up. After deleting `config.cfg` game as expected queued up JoshariasSurvival. Both resulted in an NPE on attempting to start a game from the first screen in the create workflow (the quickstart so to say)

```
19:20:03.721 [main] WARN  o.t.engine.internal.TimeBase - Delta too great (1333), capping to 1000
19:20:11.926 [main] WARN  o.t.engine.internal.TimeBase - Delta too great (2056), capping to 1000
19:20:21.210 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.NullPointerException: null
	at org.terasology.rendering.nui.layers.mainMenu.GameManifestProvider.createGameManifest(GameManifestProvider.java:67)
	at org.terasology.rendering.nui.layers.mainMenu.NewGameScreen.lambda$initialise$1(NewGameScreen.java:157)
	at org.terasology.rendering.nui.widgets.UIButton.activate(UIButton.java:208)
	at org.terasology.rendering.nui.widgets.UIButton.access$100(UIButton.java:41)
	at org.terasology.rendering.nui.widgets.UIButton$1.onMouseRelease(UIButton.java:99)
	at org.terasology.rendering.nui.internal.CanvasImpl.processMouseRelease(CanvasImpl.java:247)
	at org.terasology.rendering.nui.internal.NUIManagerInternal.mouseButtonEvent(NUIManagerInternal.java:576)
	at org.terasology.rendering.nui.internal.NUIManagerInternalMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:531)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:301)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:280)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:204)
	at org.terasology.input.InputSystem.send(InputSystem.java:367)
	at org.terasology.input.InputSystem.sendMouseEvent(InputSystem.java:354)
	at org.terasology.input.InputSystem.processMouseButtonInput(InputSystem.java:184)
	at org.terasology.input.InputSystem.processMouseInput(InputSystem.java:169)
	at org.terasology.input.InputSystem.update(InputSystem.java:129)
	at org.terasology.engine.modes.StateMainMenu.handleInput(StateMainMenu.java:196)
	at org.terasology.engine.subsystem.lwjgl.LwjglInput.postUpdate(LwjglInput.java:55)
	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:467)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:421)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:397)
	at org.terasology.engine.Terasology.main(Terasology.java:154)
19:20:21.210 [main] WARN  o.t.engine.internal.TimeBase - Delta too great (1983), capping to 1000
```

Same happened from the advanced game setup screen. If I went all the way through and started from the final screen I think it might have made it past that point (just some config not prepared early enough?) but then I crashed on what I expect is an unrelated error. Might poke around a bit more and see if I can still test using that flow.

**Comment by Cervator** [comment]
Bypassing the unrelated error does get me in-world 👍 

However, I added a perlin then a flat, then picked perlin to start, and still ended up in flat. Looking at the config after I see the new block:

```
  "universeConfig": {
    "worlds": [
      {
        "title": "main",
        "seed": "Perlin-00",
        "time": 43200000,
        "worldGenerator": "Core:flat"
      },
      {
        "title": "main1",
        "seed": "Flat-11",
        "time": 43200000,
        "worldGenerator": "Core:flat"
      }
    ],
    "spawnWorldTitle": "main",
    "universeSeed": "7oqOStiXmmf2GD0ddoNPrtk9GvnOo7yE"
  }
```

That's odd. Also, the old block is still there as well:

```
  "worldGeneration": {
    "worldTitle": "New World",
    "defaultSeed": "blockmania",
    "defaultGenerator": "Core:flat"
  },
```

Tried a second time after deleting `config.cfg` again, but same results.

Oddly, the `manifest.json` for the world itself does have references to perlin in its `"seed": "Perlin-00",` - but the actual world entries again are just two flats.

Can't check on the world name null thing since I crash on trying to quickstart. On the plus side looking at Game Details does manage to list both worlds! :-) Including their differing seed values.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Crash is fixed 👍 

Can still reproduce wrong world selection 👎 

It is peculiar and quirky, there are ways where everything works. Exact steps to replicate:

1) Delete `config.cfg` just to eliminate that as a factor
2) Start game and pick Core, go to Universe Setup
3) Add a Perlin (shows first by default - this could be changing and confusing things in successive tests without clearing config?), then add a Flat
4) Continue but change the target world during preview back to Perlin (defaults to flat since latest added)
5) Spawn and find yourself in Flat and on exiting now somehow `config.cfg`'s new `universeConfig` block has *two* `"worldGenerator": "Core:flat"` entries - one with seed "Perlin-00" so it seems like it started as Perlin but then got overwritten with Flat - maybe when the second world was added?

In the end the old `worldGeneration` block also has `"defaultGenerator": "Core:flat"` which might also be a clue. This'll be something simple but easy to overlook - the world selection / target world / spawn world config stuff might be overly fragile :-)

**Comment by Cervator** [comment]
Tried again but while I can still replicate I could also do something similar but not quite the same even before this PR. So there's either some general shakiness in the area or my workspace is really messed up. I suspect a combination :-)

Since even the case I can replicate here doesn't really affect gameplay (only happens with multi-world testing) I'm going to go ahead and merge this for the other bug fixes and general improvements so we can move along.

Going to add the other case to #3400 for future reference

**Pull request merged**
