### PR TITLE
The game details screen now shows the world name instead of "main"

### LINKED ISSUE #3583: Use the new explicit world name on the Game Details page, allow custom name?
_Edit: partially completed, just the custom name textbox is left - see #3591 for what's been implemented so far_

With the partially completed multi-world functionality individual worlds can now have names (defaulted to "WorldGenName-#", in addition to the overall _game_ name (defaulted to "Game #")

2018-12-23 18_13_10-terasology _ alpha

With the game details overhaul you can see a "main" world entry on a saved game 

2018-12-23 18_13_33-terasology _ alpha

It would be nice if that "main" could be changed to load the actual name out of the game manifest somehow. 

Bonus: It would be even _better_ if the user could give a given world a custom name, maybe with a bit of flavor (creative planet or dimension names instead of "Perlin-1"). I think this would go well as a new text box at the top of the individual world config page:

2018-12-23 18_13_21-terasology _ alpha

See the `GameManifest` class and its usages for some clues on how to achieve all this, look at the involved UI screens, and if needed consult the NUI tutorial: https://github.com/Terasology/TutorialNui/wiki

### PR DESCRIPTION
**Pull request by Snooober**
### Contains

Fixes #3583 by showing the world name ("Perlin-0"/"Flat-1"/etc.) instead of "main".

gamedetailsscreen

### How to test

- Create a multi-world game (via "Advanced" set-up) and add multiple worlds.
- Start playing the game and exit to main menu for the game to be saved.
- Select your saved game and go to "Details".
- See the "Worlds & Biomes" tab and note the names on the list under the "Worlds" heading.

### Outstanding before merging

- [ ] Still could allow for custom names (where the player can name the world what they would like instead of "Perlin-1").

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Snooober** [comment]
Hmm I amended my email but I was unable to merge it into a single commit :/

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Finally had a chance to test this out, sorry about the delay @Snooober ! :-)

Can confirm it works fine! I applied one small tweak on top which might be a good example to learn more about large open source projects: see how you changed the constructor in `WorldInfo` ? You caught the places where you had to adjust the usages _in the engine_ but there was a module and another facade that still used the old version of that constructor. Thus they failed to compile after I merged this.

A simple solution is to add a _new_ constructor and just chain it to the old one. Here's the commit that does it, super easy: https://github.com/MovingBlocks/Terasology/commit/ef6fbea9d1a461502a217c318c913c8aeb93a77b

With that added suddenly our API remains unchanged and everything automatically works without having to fix anything else :-) I didn't even have to thoroughly search for any more old style usages I might have needed to fix as well since now we're not risking any breakage at all.

With that in place I've merged this and added you to the credits! Congratulations you're now on the dev team 😁

**Comment by Cervator** [comment]
Oh and don't worry about the old commits. Your Git setup is fixed now so it will be cleaner going forward 👍

**Comment by Cervator** [comment]
I spoke too soon - I found one spot missed in testing: if you "quick start" a game without first going through world customization there's no target world yet and thus no name of the target world.

I added a quick `if` block that fixed it up real quick. Although that ends up with unnamed worlds. Hmm. Will update #3583 with a note to look at improving that :-)

**Comment by Snooober** [comment]
Thanks! :+1:

**Pull request merged**
