### PR TITLE
update mockito-all to latest mockito-core, fixes #2934

### LINKED ISSUE #2934: Incompatible test libraries, mockito-all and Junit 4.11+
Execute the following test somewhere in the `engine-tests` project to reproduce:
```
    @Test
    public void test() {
        org.junit.Assert.assertThat(42, org.hamcrest.CoreMatchers.is(43));
    }
```

Instead of 
```
java.lang.AssertionError: 
Expected: is <43>
     but: was <42>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
```
I am getting 
```
java.lang.NoSuchMethodError: org/hamcrest/Matcher.describeMismatch(Ljava/lang/Object;Lorg/hamcrest/Description;)V
```

The issue seems to be in the dependencies of the test project:
```
    compile group: 'junit', name: 'junit', version: '4.12'
    compile group: 'org.mockito', name: 'mockito-all', version: '1.10.19'
    compile group: 'org.jboss.shrinkwrap', name: 'shrinkwrap-depchain-java7', version: '1.1.3'
```

The problem here is, that `mockito-all` bundles hamcrest `1.1` but junit has a transitive dependency to hamcrest `1.3`. The IDE picks up the hamcrest version from junit but the tests get executed with the one from mockito which is not compatible to junit 4.11+ See also [1] and [2].
It would be interesting to know if this is an Eclipse-only problem and maybe can be fixed with a workspace change or if it also affects our IntelliJ developers.

A possible solution would be to import hamcrest at first, e.g. like
```
    compile group: 'org.hamcrest', name: 'hamcrest-core', version: '1.3'
    compile group: 'junit', name: 'junit', version: '4.12'
    compile group: 'org.mockito', name: 'mockito-all', version: '1.10.19'
    compile group: 'org.jboss.shrinkwrap', name: 'shrinkwrap-depchain-java7', version: '1.1.3'
```

but we may also consider to move away from mockito-all and use mockito-core instead, maybe even in the latest version 2.2 which has some improvements like better java 8 support, e.g. mocking default method. [3]

[1] https://tedvinke.wordpress.com/2013/12/17/mixing-junit-hamcrest-and-mockito-explaining-nosuchmethoderror/
[2] http://stackoverflow.com/questions/15833015/nosuchmethoderror-with-hamcrest-1-3-junit-4-11
[3] https://github.com/mockito/mockito/wiki/What%27s-new-in-Mockito-2

### PR DESCRIPTION
**Pull request by oniatus**
Updates the mockito dependency to the latest version which does not include hamcrest 1.1
See #2934 for details.

Also updated some tests, as mockito 2.x is more restrictive on type checks as 1.x, see https://github.com/mockito/mockito/wiki/What%27s-new-in-Mockito-2#incompatible-changes-with-110 for details.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
So oddly while trying this out I got 11 failed tests locally in IntelliJ - but Jenkins is all green so it must be something odd with my workspace maybe?

Would be interested to hear if anybody else get the same issues in IntelliJ.

Sample error (this is after `gradlew idea` to make sure my libs are current):

```
org.mockito.exceptions.misusing.UnfinishedVerificationException: 
Missing method call for verify(mock) here:
-> at org.terasology.logic.behavior.InterpreterTest.testNoTerminate(InterpreterTest.java:136)

Example of correct verification:
    verify(mock).doSomething()

Also, this error might show up because you verify either of: final/private/equals()/hashCode() methods.
Those methods *cannot* be stubbed/verified.
Mocking methods declared on non-public parent classes is not supported.


	at org.terasology.logic.behavior.InterpreterTest$1.createTask(InterpreterTest.java:154)
	at org.terasology.logic.behavior.tree.Interpreter.start(Interpreter.java:95)
	at org.terasology.logic.behavior.InterpreterTest.testInit(InterpreterTest.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by vampcat** [comment]
Strangely enough, I'm also using IntelliJ and all the unit tests run fine for me.

@Cervator Try running `gradlew idea` again? xD

**Comment by Cervator** [comment]
@vampcat wait did you replicate it (as noted in #2934) or not, as noted here? :D

I submitted a follow-up issue in any case, just so we don't forget: #2951

**Comment by vampcat** [comment]
Running all the unit tests after this PR gives me success on every single one, unlike your workspace.

The earlier comment was directed to that particular sample test posted there (which is not a Terasology unit test).

**Pull request merged**
