### PR TITLE
Added dimensions to the view distance setting

### PR DESCRIPTION
**Pull request by cribsb**
This was a task for the Google Code In. The changes in RenderingConfig.java were neccesary because viewDistance would be null on a first time startup.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by rzats** [comment]
@GooeyHub: ok to test

@cribsb: hi and thanks for the submission! I'll test this out in a few minutes then merge & approve task if everything works fine.

**Comment by cribsb** [comment]
Thanks! Didn't think of that... I'll make the changes tommorow.

**Comment by cribsb** [comment]
I added the changes you suggested. I hope it is OK now

**Comment by rzats** [comment]
@GooeyHub: ok to test

**Comment by rzats** [comment]
@GooeyHub: ok to test

Didn't work the first time for some reason.

**Comment by Cervator** [comment]
@GooeyHub: ok to test

Checking if Gooey is being biased

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by rzats** [comment]
No (other) unit tests appear to have failed, so merging this! Also added you to our credits (https://github.com/MovingBlocks/Terasology/blob/develop/docs/Credits.md) - thanks again for the contribution 🙂

**Comment by cribsb** [comment]
Thank you as well!

**Comment by emanuele3d** [comment]
Congrats!

**Pull request merged**
