### PR TITLE
Added onEnterBiome event

### PR DESCRIPTION
**Pull request by nihal111**
### Contains

Adds a `onEnterBiomeEvent` that gets sent whenever the player enters a new biome.
Note: The `updateMode` method has moved because of an auto code clean up.

### How to test

Add this line
`logger.info("newBiome: " + newBiome);`
inside the  [if block](https://github.com/MovingBlocks/Terasology/pull/2954/files#diff-e81079f2b9fefe8630619776b065c2aaR175) where the event is sent. 
Run the game. 
Walk around a little.
You'd see logs whenever an onEnterBiomeEvent is sent as and when the player enters a new biome.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Tested out good - merged! :-)

Thanks for the extra tweaks and docs!

**Pull request merged**
