### PR TITLE
Fix for NPE at loading save games

### PR DESCRIPTION
**Pull request by nihal111**
### Contains

Fix for NPE at loading save games

### How to test

Manage to kill the game when saving is in progress.
Open the game. There should be a NPE [here](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/savedGames/GameProvider.java#L69)

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
@rzats you managed to validate this right? Can you confirm or even merge this if so please? :-)

**Comment by rzats** [comment]
@Cervator: merging! Though as discussed on IRC I'd look into making the error visible to the user as a followup.

**Comment by nihal111** [comment]
@rzats Will you? I was thinking of looking into it..

**Comment by rzats** [comment]
@nihal111, what I meant is I'd _[...suggest that you...]_ look into making the error visible to the user 😛

**Comment by Cervator** [comment]
Thanks :-)

**Comment by nihal111** [comment]
I found this again and realized I hadn't looked into making the error visible to the user earlier.
Should we probably create save games such that a temp save game file is created which later replaces the original save game file? Since termination of the game midway during creating the save file causes this error, using this approach at least the second most recent save would be available to the user in such an event. @Cervator  @rzats

**Comment by Cervator** [comment]
I added a comment over to #2614 which is still open and very similar so a better place for discussion :-)

**Pull request merged**
