### PR TITLE
Support facade classpaths

### PR DESCRIPTION
**Pull request by mkienenb**
Adds a hook so that facades can add classpaths to the engine module.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by mkienenb** [comment]
Also merge

https://github.com/MovingBlocks/FacadeAWT/pull/10

**Comment by Cervator** [comment]
@GooeyHub: add to whitelist

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by mkienenb** [comment]
Changed SpriteParticleRenderer.java so that opengl code won't run unless we are using LWJGLDisplaydDriver.  A better fix would be to resolve the "BIG" todo in the code and move the LWJGL-specific code into a shader.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Looks reasonable and tests out, merged with thanks :-)

Reference ping for @vampcat over the tiny rendering tweak, will re-note on Slack as well

**Pull request merged**
