### PR TITLE
Adds the Create Game screen subtitle

### PR DESCRIPTION
**Pull request by BdeBock**
Fixes issue #2233
Adds a subtitle to the create game screen in singleplayer and multiplayer game.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
Thanks!

You might look into playing with Git Rebase next, to avoid merge commits like that :-)

It is done clean enough to where I can merge this OK as-is, but if you try it out and get it working feel free to apply it for this PR, it'll be a bit before I can grab it.

@GooeyHub add to whitelist

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/500/
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/501/
Uh oh, something went wrong with the build. Need to check on that

**Pull request merged**
