### PR TITLE
fix(networking-timeout): graceful shutdown after failed connection

### PR DESCRIPTION
**Pull request by DarkWeird**
### Contains

Make graceful game close after Connection failed when try to connect to server.
was non-daemon thread for timeout, which stucks on WAITING state when game closing.

Bonus - timeout thread named now. new license header for file

### How to test

1. open Terasology
2. Go to `Join Game`
3. try to connect to some stopped servers.
4. close game. (ideally faster then 10 seconds)
5. check that game closes (game process exited)

### CODE REVIEW

**Comment by syntaxi** [comment]
Just tried to test this out locally. Followed the instructions and had the game never close.

I've put the log here:  
https://gist.github.com/134094c0db4a9c9fc0517f48fe722ee0

**Comment by DarkWeird** [comment]
> Just tried to test this out locally. Followed the instructions using the "Official Stable" server and had the game never close.
> 
> I've put the log here:
> https://gist.github.com/134094c0db4a9c9fc0517f48fe722ee0
> 
> Doing a thread dump shows the thread "Netty-Timeout-Timer" still on WAITING

Odd, You have another Waiting threads?

**Comment by syntaxi** [comment]
> > Just tried to test this out locally. Followed the instructions using the "Official Stable" server and had the game never close.
> > I've put the log here:
> > https://gist.github.com/134094c0db4a9c9fc0517f48fe722ee0
> > Doing a thread dump shows the thread "Netty-Timeout-Timer" still on WAITING
> 
> Odd, You have another Waiting threads?

image
This was the result of a thread dump

**Comment by DarkWeird** [comment]
> > > Just tried to test this out locally. Followed the instructions using the "Official Stable" server and had the game never close.
> > > I've put the log here:
> > > https://gist.github.com/134094c0db4a9c9fc0517f48fe722ee0
> > > Doing a thread dump shows the thread "Netty-Timeout-Timer" still on WAITING
> > 
> > Odd, You have another Waiting threads?
> 
> image
> This was the result of a thread dump

There waiting nioEventGroupLoop (or request info or trying to join)

**Comment by jdrueckert** [comment]
Didn't work for me unfortunately :slightly_frowning_face: 
```
[...]
20:25:09.698 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
20:25:11.085 [Thread-1] DEBUG c.j.d.entities.pipe.UnixPipe - Received packet: Pkt:FRAME{"evt":null,"data":{"assets":{"large_image":"515746954660151306"},"timestamps":{"start":1606591450000},"name":"Terasology","details":"Name: Nira","state":"In Lobby","type":0,"secrets":{},"application_id":"515274721080639504"},"cmd":"SET_ACTIVITY","nonce":"41a6871a-a271-49fe-ac0e-321ef07be692"}
20:25:13.515 [main] WARN  o.t.r.nui.layers.mainMenu.WaitPopup - An error occurred during execution
java.util.concurrent.ExecutionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: testserver.terasology.net/165.227.137.205:25777
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at org.terasology.rendering.nui.layers.mainMenu.WaitPopup.update(WaitPopup.java:100)
        at org.terasology.rendering.nui.internal.NUIManagerInternal.update(NUIManagerInternal.java:547)
        at org.terasology.engine.modes.StateMainMenu.updateUserInterface(StateMainMenu.java:228)
        at org.terasology.engine.modes.StateMainMenu.update(StateMainMenu.java:200)
        at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:469)
        at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:432)
        at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:408)
        at org.terasology.engine.Terasology.main(Terasology.java:174)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: testserver.terasology.net/165.227.137.205:25777
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
20:25:15.464 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
20:25:16.046 [Thread-1] DEBUG c.j.d.entities.pipe.UnixPipe - Received packet: Pkt:FRAME{"evt":null,"data":{"assets":{"large_image":"515746954660151306"},"timestamps":{"start":1606591450000},"name":"Terasology","details":"Name: Nira","state":"In Lobby","type":0,"secrets":{},"application_id":"515274721080639504"},"cmd":"SET_ACTIVITY","nonce":"8bbb3b7b-bc31-429e-9a93-ae614cc25dd8"}
20:25:17.496 [main] DEBUG c.j.d.entities.pipe.UnixPipe - Closing IPC pipe...
<============-> 99% EXECUTING [6m 2s]
> :facades:PC:game
```

What I did:
1. Start Game
1. Go to "Join Game"
1. Select "Official Event Server" and click "Join"
1. See an error message and directly (definitely faster than 10 seconds) close the game via Alt+F4

**Comment by DarkWeird** [comment]
> Didn't work for me unfortunately :slightly_frowning_face: 
> ```
> [...]
> 20:25:09.698 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
> 20:25:11.085 [Thread-1] DEBUG c.j.d.entities.pipe.UnixPipe - Received packet: Pkt:FRAME{"evt":null,"data":{"assets":{"large_image":"515746954660151306"},"timestamps":{"start":1606591450000},"name":"Terasology","details":"Name: Nira","state":"In Lobby","type":0,"secrets":{},"application_id":"515274721080639504"},"cmd":"SET_ACTIVITY","nonce":"41a6871a-a271-49fe-ac0e-321ef07be692"}
> 20:25:13.515 [main] WARN  o.t.r.nui.layers.mainMenu.WaitPopup - An error occurred during execution
> java.util.concurrent.ExecutionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: testserver.terasology.net/165.227.137.205:25777
>         at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
>         at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
>         at org.terasology.rendering.nui.layers.mainMenu.WaitPopup.update(WaitPopup.java:100)
>         at org.terasology.rendering.nui.internal.NUIManagerInternal.update(NUIManagerInternal.java:547)
>         at org.terasology.engine.modes.StateMainMenu.updateUserInterface(StateMainMenu.java:228)
>         at org.terasology.engine.modes.StateMainMenu.update(StateMainMenu.java:200)
>         at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:469)
>         at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:432)
>         at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:408)
>         at org.terasology.engine.Terasology.main(Terasology.java:174)
> Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: testserver.terasology.net/165.227.137.205:25777
> Caused by: java.net.ConnectException: Connection refused
>         at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
>         at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779)
>         at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
>         at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
>         at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
>         at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
>         at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
>         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
>         at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
>         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
>         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
>         at java.base/java.lang.Thread.run(Thread.java:834)
> 20:25:15.464 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
> 20:25:16.046 [Thread-1] DEBUG c.j.d.entities.pipe.UnixPipe - Received packet: Pkt:FRAME{"evt":null,"data":{"assets":{"large_image":"515746954660151306"},"timestamps":{"start":1606591450000},"name":"Terasology","details":"Name: Nira","state":"In Lobby","type":0,"secrets":{},"application_id":"515274721080639504"},"cmd":"SET_ACTIVITY","nonce":"8bbb3b7b-bc31-429e-9a93-ae614cc25dd8"}
> 20:25:17.496 [main] DEBUG c.j.d.entities.pipe.UnixPipe - Closing IPC pipe...
> <============-> 99% EXECUTING [6m 2s]
> > :facades:PC:game
> ```
> 
> What I did:
> 1. Start Game
> 1. Go to "Join Game"
> 1. Select "Official Event Server" and click "Join"
> 1. See an error message and directly (definitely faster than 10 seconds) close the game via Alt+F4

Which threads still alive??

**Comment by jdrueckert** [comment]
"Get Thread Dump" in Intellij shows:
image

and

```
"nioEventLoopGroup-3-1@6424" prio=10 tid=0x35 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at sun.nio.ch.EPoll.wait(EPoll.java:-1)
	  at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:120)
	  at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:124)
	  - locked <0x19aa> (a sun.nio.ch.EPollSelectorImpl)
	  - locked <0x19ab> (a io.netty.channel.nio.SelectedSelectionKeySet)
	  at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:141)
	  at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:68)
	  at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:805)
	  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:457)
	  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	  at java.lang.Thread.run(Thread.java:834)
```

**Comment by DarkWeird** [comment]
Hmm netty's thread. I will dig it

**Review by jdrueckert — APPROVED** [review]

**Pull request merged**
