### PR TITLE
Work on four more render nodes

### PR DESCRIPTION
**Pull request by emanuele3d**
### Contains
Refactoring, cleanup and documentation of four render nodes:
- PrePostCompositeNode
- SimpleBlendMaterialsNode
- LightShaftsNode
- InitialPostProcessingNodes

Longer term PrePostComposite and InitialPostProcessing  will see more refactoring work, mostly to split them into smaller, more specialized nodes. 

### How to test
- Run Terasology
- Create a new game or Load an existing one
- verify nothing is wrong with the rendered image

### Notes
I can't see bloom producing any effect, but this seems to be the case also in develop. As I proceed with the refactoring it will become possible and necessary to revamp the debug mode to show the exact contribution of each effect to the final picture - if any. In this case it will allow to verify if the bloom effect is too subtle to notice given the in-game circumstances or if it is completely absent.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by emanuele3d** [comment]
Hey everybody! I could use a review here! I already have another three refactored nodes waiting in the wings!

**Comment by Cervator** [comment]
Aiiee! So much to review, in the midst of GCI, and Xmas on top :D

Things are quieting down some in NYC now I think, so I might be able to at least do some testing soon. Returning home on Wednesday the 28th.

**Comment by Cervator** [comment]
I can vouch for this testing out on my Win8 tablet. World looks fine, lightshafts still work, etc. Changed graphic settings while in-game no problem.

@emanuele3d if you don't hear from any of @tdgunes @indianajohn or @Avalancs in the near future feel free to just hit the merge button yourself and move on to the next PR :-)

**Comment by Avalancs** [comment]
Hi @emanuele3d

Sorry, I don't have access to a PC that is able to run until tomorrow, but I'll be sure to test when I get the chance!

**Comment by indianajohn** [comment]
I looked over the code here and was able to understand why all of the changes were being made. I also tested this on both of my machines (and VR mode) and everything seems to work as before.

Thumbs up on this end.

**Comment by emanuele3d** [comment]
Thank you for the thumbs up @indianajohn. I feel much more confident about a set of changes if at least two pair of eyes have reviewed it. Given @Avalancs seemed to be on the verge of reviewing this I will wait another 24 to give him the chance. If not, I'll merge as you suggest @Cervator.

**Comment by Avalancs** [comment]
Hi @emanuele3d !

I have a weird bug, not sure if it is related. No matter if the outlines are on or off, I get thick black lines between blocks in a single direction:

visual bug

I'll try if I get the same with the develop branch, or if some other settings matter

**Comment by Avalancs** [comment]
Tweaking the settings, it disappeared after I disabled "Parallax Mapping"

**Comment by emanuele3d** [comment]
@Josharias was working on Parallax Mapping but the latest I knew on the matter (from some months ago) was that it wasn't working. So, I don't think this has changed much. Have you checked if the problem also occurs in develop?

**Comment by Cervator** [comment]
Thanks for the review all! (heya @tdgunes I see you there! Thanks and let us know sometime if you got that OSVR headset to work!)

Merged and did one final test, all seems well. That line issue along block edges is oooolld yeah :-)

**Comment by emanuele3d** [comment]
Yay!

**Pull request merged**
