### PR TITLE
Added @API to NotificationMessageEvent

### PR DESCRIPTION
**Pull request by nihal111**
This adds @API to NotificationMessageEvent, making it usable to external modules.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
As a general practice you might want to package this sort of change with a PR or module change needing it, rather than insta-merging a PR here - just link the two together and say they need to be tested & merged together :-)

This is for https://github.com/Terasology/FunnyBlocks/pull/9 just for documentation purposes.

**Comment by nihal111** [comment]
Alright, I thought this was trivial and should have existed earlier, so went ahead and did it. Will keep this in mind next time :)

**Pull request merged**
