### PR TITLE
Refactor of selection screens

### PR DESCRIPTION
**Pull request by ar0ne**
### Contains

I've refactored new selection screens. Separate common logic, and fix an issue with wrong preview image after creating new game.

### How to test

Generally, you need to check that SelectGame, Replay and Record screens work as expected.

### Outstanding before merging

Ping @iaronaraujo for awareness.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by ar0ne** [comment]
Additional items that should be covered from [Issue#3400](https://github.com/MovingBlocks/Terasology/issues/3400) and nor.
1. Removed old CreateGameScreen class.
2. The multiplayer popup about changing your name applied only for Multiplayer.
3. Stop taking screenshot twice.
4. Removed excess Details buttons from Replay&Record.

**Comment by Cervator** [comment]
Can confirm the additional fixes :-)

Two issues I'd like to see fixes for if possible:

* The module environment switch still isn't quite right. If I pick a gameplay template then I can get those modules activated. If I just go with Core then try to manually activate more modules then they don't get activated at all. Switching back to develop fixes that
* The reset filter button would be really great to get working, and may relate to the module weirdness?

Keep it up! :-)

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by ar0ne** [comment]
Heyo @Cervator, 
Can you check it when you have time, should be fine now:)

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Retested and solid! Nice job :-)

Updating #3400 with some more notes and checking off fixed stuff, let me know if I missed anything

**Pull request merged**
