### PR TITLE
Fix errors in the Spanish translation

### PR DESCRIPTION
**Pull request by RaymonMolas**
{
    "activate-module": "Activar",
    "add-server": "Agregar Nuevo",
	"add-server-tip": "Puede pulsar INTRO para copiar el nombre en el campo de dirección.",
    "advanced-usage": "Uso Avanzado!",
    "animate-grass": "Animacion de Hierba",
    "animate-water": "Animacion del Agua",
	"audio-settings": "Sonido",
    "audio-settings-title": "Configuración de Audio",
    "back": "Atras",
	"behavior-editor-assign": "asignar",
    "behavior-editor-copy": "copiar",
    "behavior-editor-layout": "diseñar",
    "behavior-editor-new": "nuevo",
    "behavior-editor-paste": "pegar",
    "behavior-editor-remove": "Elimiar",
    "binding-attack": "Atacar",
	"binding-autoMove-mode": "Modo Movimiento Automatico",
    "binding-backwards": "Hacia Atrás",
    "binding-behavior-editor": "Alternar Editor de Comportamiento",
    "binding-chat": "Activar Chat",
    "binding-console": "Activar Consola",
    "binding-crouch": "Agacharse / Bajar",
	"binding-crouch-mode": "Modo Agachado",
    "binding-decrease-view-distance": "Disminuar Distancia de Vista",
    "binding-forwards": "Hacia Adelante",
    "binding-frob": "Utilizar Objectivo",
    "binding-hide-hud": "Esconder/Mostrar HUD",
    "binding-increase-view-distance": "Aumentar Distancia de Vista",
    "binding-jump": "Saltar / Ascender",
    "binding-left": "Strafe Left",
    "binding-nui-editor": "Editor NUI",
    "binding-nui-skin-editor": "Editor de Skin NUI",
    "binding-pause": "Pausa",
    "binding-right": "Strafe Right",
	"binding-screenshot": "Captura de Pantalla",
    "binding-show-online-players": "Mostrar Jugadores en Línea",
    "binding-toggle-speed-permanently": "Activar velocidad permanentemente",
    "binding-toggle-speed-temporarily": "Activar velocidad temporalmente",
    "binding-use-item": "Usar Objeto",
    "bloom-effect": "Bloom",
    "bobbing": "Balanceo",
    "camera-blur": "Aspecto Borroso",
    "camera-blur-max": "Máximo",
    "camera-blur-normal": "Normal",
    "camera-blur-off": "Apagado",
    "camera-blur-some": "Algunos",
    "camera-details-settings": "Camara / Configuración de Detalles Gráficos",
    "camera-film-grain": "Granulado de Pelicula",
    "camera-setting": "Configuración de Camara",
    "camera-setting-cinematic": "Cinemático",
    "camera-setting-normal": "Normal",
    "camera-setting-smooth": "Suave",
    "category-behavior": "Comportamiento",
    "category-general": "General",
    "category-interaction": "Interacción",
    "category-inventory": "Inventario",
    "category-mouse": "Ratón",
    "category-movement": "Movimiento",
    "category-nui": "NUI",
	"change-keybind-popup-message": "Ya está ligado a una acción. ¿Rebindear de todos modos?",
    "change-keybind-popup-title": "Tecla en uso",
    "clamp-lighting": "Iluminación de Abrazadera",
    "cloud-shadows": "Sombras de Nubes",
	"connecting-to": "Conectando a",
    "connection-failed": "Conexión Fallida",
    "could-not-connect-to-server": "No se puede conectar al servidor",
    "crash-reporter": "Error de edición",
    "non-native-jvm-warn": "ADVERTENCIA: Está utilizando un JVM de 32 bits en un sistema de 64 bits! / Utilice una instalación Java de 64 bits para obtener el mejor rendimiento.",
    "credits": "Creditos",
    "create-game": "Crear",
    "create-game-title": "Crear Partida",
    "create-preview": "Previsualizar",
    "custom-servers": "Personalizado",
	"desactivate-module": "Desactivar",
    "death-screen-title": "Estás Muerto",
	"default-binding": "Controles predeterminados",
    "delete-game": "Borrar",
    "dev-tools-bt-editor": "Editor de Árbol de Comportamiento",
    "dev-tools-nui-editor": "Editor de Pantalla NUI",
    "dev-tools-skin-editor": "Editor de Skin NUI",
    "dev-tools-title": "Herramientas de Desarrollo",
    "dialog-cancel": "Cancelar",
	"dialog-no": "No",
    "dialog-ok": "Ok",
	"dialog-option": "Opción2",
	"dialog-yes": "Sí",
    "disable-all-modules": "Desactivar Todo",
	"disable-launch-popup": "Recordar y no volver a mostrarlo",
    "download-module": "Descargar",
	"downloading-server-list": "Descargando lista de servidor ..",
	"drop-item": "Tirar objeto",
    "edit-server": "Editar",
    "edit-server-title": "Agregar/Editar Servidor",
    "enable-error-reporting": "Enviar error de registro al servidor",
	"enable-telemetry": "Enviar metricas al servidor",
	enter-username-message":  "Hola y Bienvenido al multijugador de Terasology! / ¿Quieres actualizar tu nombre de usuario?,
	"enum-editor-prompt": "Seleccione un valor para el nodo:",
    "enum-editor-title": "Editor de Nodos de Enumeración",
	"error": "Error",
	"error-downloading-server-list": "Fallo al descargar lista de servidor!",
	"existing-file-warning": "Archivo %s ya existe. ¿Quieres sobrescribir el archivo?",
    "exit-game": "Cerrar Terasology",
    "extra-lighting": "Iluminación Adicional",
	"experimental": "Experimental",
    "eye-adaption": "Adaptación de Ojo",
	"failed-to-join": "Fallo al conectar",
    "file-picker-access-denied-to": "Acceso denegado a ",
    "file-picker-cant-change-dir": "Fallo al cambiar la dirección",
    "file-picker-file-name": "Nombre del Archivo: ",
    "file-picker-full-path": "Ruta completa del archivo: ",
    "file-picker-home": "Home",
    "file-picker-invalid-file-name": "Nombre del archivo invalido",
    "file-picker-invalid-location": "Ubicación invalida",
    "file-picker-parent": "Parent",
    "file-picker-root": "Raíz",
    "file-picker-roots-title": "Raíz de archivos del sistema",
    "file-picker-title": "Seleccione un archivo",
    "flickering-lights": "Luces Parpadeantes",
	"fog": "Niebla",
    "fov-amount": "Cantidad Fov",
    "framerate-limit": "Límite de Cuadros",
    "game-name": "Nombre del Juego",
    "game-settings": "Configuración",
    "game-worlds": "Mundos",
    "gameplay": "Plantilla de Jugabilidad",
    "gameplay-info": "puedes cliquear 'módulos' para personalizar más",
    "host-multiplayer-game": "Hospedar Partida",
	"identity-export": "Exportar identidades multijugador",
    "identity-export-fail": "Fallo al exportar identidades",
    "identity-export-ok": "Exportación con éxito %d de identidades a %s.",
    "identity-import": "Importar identidades multijugador",
    "identity-import-cancel": "Cancelar importación",
    "identity-import-cancelled": "La opercaion a sido cancelada, no se han importado las identidades",
    "identity-import-conflict": "Para el servidor con ID %s, existe una identidad local con ID de cliente %s, pero el archivo que se está importando contiene una identidad para el mismo servidor con ID de cliente %s. Elija una opción.",
    "identity-import-failed": "Fallo al importar las identidades",
    "identity-import-no-new": "El archivo seleccionado no contiene ninguna identidad",
    "identity-import-ok": "Importacion exitosa %d identidades",
    "identity-import-overwrite": "Importacion (sobrescrtitura local)",
    "identity-import-skip": "Omitir",
    "ingame-menu-title": "Menu en el Juego",
    "input-settings": "Entrada",
    "input-settings-title": "Input Settings",
	"inspection-set": "Fijar",
    "invert-mouse": "Invertir Ratón",
    "invert-x": "Invertir Eje X",
    "invert-y": "Invertir Eje Y",
    "invert-z": "Invertir Eje Z",
    "join-game-online": "Conectar a Partida",
    "join-server-refresh": "Actualizar",
    "join-server-action": "Unirse",
	"join-server-requested": "Solicitado",
    "join-server-title": "Unirse al Servidor",
    "light-shafts": "Ejes de Luz",
    "listed-servers": "Enlistado",
    "load-game": "Cargar",
	"menu-animations": "Animacion del menu",
    "missing-name-message": "Debes introducir un nombre",
    "module-dependencies-empty": "Este modulo no tiene dependencias",
    "module-dependencies-exist": "Dependencias del módulo",
	"module-filter": "Filtro",
	"module-list": "Módulos",
    "module-name": "Nombre",
    "module-status": "Estado",
	"module-status-activated": "Activado",
    "module-status-activegameplay": "Activar jugabilidad",
    "module-status-available": "Disponible",
    "module-status-dependency": "Dependencia",
    "module-status-error": "Dependencias incompatibles o no resueltas",
    "module-status-notpresent": "NO está presente",
    "module-version-available": "En línea",
    "module-version-installed": "Instalado",
	"module-version-installed-none": "Ninguno",
    "motion-blur": "Desenfoque de Movimiento",
    "mouse-sensitivity": "Sensibilidad del Ratón",
    "movement-dead-zone": "Movimiento Eje Zona muerta",
    "music-volume": "Volumen de Música",
	"new-binding": "Nuevo bind",
	"next-toolbar-item": "Siguiente elemento de la barra de herramientas",
    "none": "ninguna",
    "not-bound": "no unido",
    "nui-editor-alternative-locale": "Vista previa de la ubicación del widget",
    "nui-editor-assign": "agignar",
	"nui-editor-close": "Cerrar",
    "nui-editor-copy": "Copiar",
    "nui-editor-disable-autosave": "Deshabilitar autoguardado",
    "nui-editor-disable-icons": "Deshabilitar iconos de vista de árbol",
    "nui-editor-layout": "Diseñar",
    "nui-editor-new": "Nuevo",
	"nui-editor-override": "Guardar",
    "nui-editor-paste": "Pegar",
    "nui-editor-redo": "Rehacer",
    "nui-editor-save": "Guardar Como...",
    "nui-editor-settings-title": "Configuración del Editor",
    "nui-editor-undo": "Deshacer",
    "oculus-rift-support": "Soporte Oculus Rift",
	"online-players": "Jugadores En linea",
    "open-inventory": "Abrir inventario",
    "outline": "Contórno",
	"particle-effect-limit": "Limite de efecto de particulas",
    "parallax-mapping": "Parallax Mapping",
	"parsing-content": Analisis de contenido ..",
    "ping" : "Ping",
    "player-color": "Color del Jugador",
    "player-name": "Nombre del Jugador",
	"player-height": "Altura del jugador",
    "player-eye-height": "Altura del Ojo del Jugador",
    "player-settings": "Jugador",
	"player-settings-identities-export": "Exportar...",
    "player-settings-identities-import": "Importar...",
    "player-settings-title": "Configuración del Jugador",
    "please-wait": "Por favor, espere...",
	"preview-world-title": "Pre visualizar Mundo...",
    "preview-zoom-factor": "Enfocar",
	"previous-toolbar-item": "Elemento anterior de la barra de herramientas",
	"remove-binding": "Eliminar",
    "remove-server": "Eliminar",
	"reset-default": "Reiniciar",
    "reset-fov-amount": "Restablecer fov",
    "resolution-scale": "Escala de Resolución",
    "respawn": "Revivir",
    "restore-defaults": "Restaurar  a predeterminado",
    "return-main-menu": "Salir al Menu Principal",
    "rotation-dead-zone": "Rotacion dee Eje de Zona Muerta",
	"save-game-patch": "Guardar parche del juego",
    "screenshot-format": "Formato de Pantallazo",
    "screenshot-size": "Tamaño de pantallazo",
    "screenshot-size-double": "Doble Tamaño",
    "screenshot-size-half": "Medio Tamaño",
    "screenshot-size-normal": "Tamaño Normal",
    "screenshot-size-quarter": "Un Cuarto de Tamaño",
    "select-game-title": "Selecciona Juego",
    "select-modules": "Módulos...",
    "select-modules-title": "Selecciona Módulos...",
	"select-multiplayer-game-sub-title": "Multijugador",
    "select-singleplayer-game-sub-title": "Un Jugador",
    "select-world-gen": "Elije Generador de Mundo",
    "select-world-gen-info": "activar módulos puede activar otros",
    "server-address": "Dirección",
	"server-list-complete": "Lista de servidor completa",
    "server-name": "Nombre",
    "server-owner": "Dueño",
    "server-port": "Puerto",
    "settings-language": "Idioma",
    "settings-title": "Configuración",
    "shadows": "Sombras",
    "shadows-off": "Apagado",
    "shadows-on": "Encendido",
    "shadows-pcr": "Encendido (PCR)",
    "sound-volume": "Volumen del Sonido",
    "ssao": "SSAO",
    "start-game": "Jugar",
    "start-singleplayer-game": "Un Jugador",
	"storage-service": "Iservicio de almacenamiento de identidades",
    "storage-service-conflict-message": "Durante la última sincronización de las identidades del cliente almacenadas localmente con el servicio de almacenamiento, se detectó un conflicto. Para el servidor con %s de id, el certificado almacenado localmente tiene %s de id mientras que para el servidor remoto tiene %s de id. ¿Qué es lo que quieres hacer? Tenga en cuenta que mantener una de las versiones borrará la otra; ignorar mantendrá la identidad local local y remota remotamente, y el conflicto será detectado de nuevo durante la próxima sincronización.",
    "storage-service-conflict-keep-local": "Mantener la versión local (sobrescribir en el servicio)",
    "storage-service-conflict-keep-remote": "Mantener la versión remota (sobrescribir local)",
    "storage-service-conflict-ignore": "Ignorar",
    "storage-service-log-in": "Iniciar Sesión",
    "storage-service-log-out": "Cerrar Sesión",
    "storage-service-log-out-popup": "Está a punto de desconectar su cuenta de este cliente. ¿Desea borrar las identidades de cliente almacenadas localmente? Si no los elimina, se cargarán en la cuenta del siguiente usuario que inicie sesión. Elija Sí si desea iniciar sesión con otra cuenta; seleccione No si desea volver a iniciar sesión con esta cuenta después de cerrar la sesión. Elija Cancelar si no desea cerrar la sesión en absoluto.",
    "storage-service-logged-in": "Has iniciado sesión como %s",
    "storage-service-logged-out": "No has iniciado sesión",
    "storage-service-login-fail": "Error de acceso - %s",
    "storage-service-login-ok": "Inició sesión con éxito",
    "storage-service-logout-fail": "Error de cierre de sesión - %s",
    "storage-service-logout-ok": "Sesión cerrada exitosamente",
    "storage-service-popup-bad-url": "La URL introducida no es válida.",
    "storage-service-popup-login": "Iniciar sesión",
    "storage-service-popup-password": "Constraseña",
    "storage-service-popup-title": "Inicie sesión en el servicio de almacenamiento de identidades",
    "storage-service-popup-url": "URL del servicio",
    "storage-service-popup-warning": "Advertencia: hay certificados de identidad del cliente almacenados localmente. Si te conectas, se cargarán en el servicio.",
    "storage-service-sync-conflicts": "Advertencia: había identidades en conflicto. Haga clic en Unirse al Juego desde el menú principal para resolver los conflictos..",
    "storage-service-sync-fail": "Falló al sincronizar las identidades - %s",
    "storage-service-sync-ok": "Sincronización completada - %d descargado, %d cargado, %d en conflicto.",
    "storage-service-sync-previous-conflicts": "Se detectaron conflictos durante la última sincronización. No es posible iniciar una nueva sincronización hasta que se hayan resuelto los conflictos.",
    "storage-service-token-fail": "Autenticación desde el token almacenado y URL fallida - %s.",
    "storage-service-token-not-present": "No hay datos de configuración presentes, por lo que se mantiene desconectado.",
    "storage-service-token-ok": "Iniciar sesión con éxito utilizando las credenciales almacenadas.",
    "storage-service-upload-fail": "Falló al cargar identidades - %s.",
    "storage-service-upload-ok": "Cargó con éxito nuevas identidades.",
    "storage-service-wait": "Trabajando, por favor espere...",
    "storage-service-working": "El cliente de servicio de almacenamiento sigue funcionando (sincronización de identidades o entrada/salida). Unirse a un juego ahora puede causar conflictos de identidad entre el servicio de almacenamiento y la configuración local. ¿Quieres continuar de todos modos?",
    "telemetry-button": "Menú de Métricas",
    "telemetry-launch-popup-text": "El sistema de telemetría enviará métricas y errores al servidor. Hacemos todo lo posible para evitar el envío de cualquier cosa identificable desde su PC, por ejemplo, la telemetría incluye su nombre de sistema operativo, la versión Java pero no incluye la dirección MAC, el camino a casa, etc. Puede revisar en el Menú Métrico y hacernos saber si nos hemos perdido de algo. La telemetría es muy útil para un proyecto tan voluntario como el nuestro y realmente lo apreciaremos!",
    "telemetry-launch-popup-title": "Telemetría en Terasology",
    "telemetry-menu": "Menú de métricas",
    "telemetry-description": "Esta pantalla muestra las métricas y sus valores que se enviarán al servidor. Puede activarlo/desactivarlo aquí. La telemetría es muy útil para un proyecto tan voluntario como el nuestro y realmente lo apreciaremos!",
    "telemetry-block-destroyed": "Bloque destruido",
    "telemetry-block-placed": "Bloque Colocado",
    "telemetry-game-configuration": "Configuración del juego",
    "telemetry-game-play": "Estadísticas del juego",
    "telemetry-creature-killed": "Criatura Matada",
    "telemetry-system-context": "Contexto del sistema",
    "telemetry-modules": "Modulos",
    "this-language-English": "Spanish",
    "this-language-native": "Español",
	"update-module": "Actualizar",
	"validation-username-max-length": "El nombre de usuario no puede ser más largo que 100 caracteres",
    "video-display-mode": "Modo de visualización",
    "video-fullscreen": "Pantalla Completa",
	"video-windowed-fullscreen": "Ventana con Pantalla Completa",
    "video-windowed": "Ventana",
    "video-graphic-settings": "Ventana / Configuración Gráfica",
    "video-high-end-settings": "Alto Rendimiento / Configuración Experimental",
    "video-preset": "Preajuste",
    "video-preset-custom": "Personalizado",
    "video-preset-high": "Alto",
    "video-preset-low": "Bajo",
    "video-preset-medium": "Medio",
    "video-preset-message": "No cambia la distancia o el punto de vista",
    "video-preset-minimal": "Mínimo",
    "video-preset-ultra": "Ultra",
    "video-settings": "Vídeo",
    "video-settings-title": "Configuración de Video",
    "video-vsync": "Sincronización Vertical",
    "view-distance": "Distancia de Visión",
    "view-distance-blind": "Legalmente Ciego",
    "view-distance-extreme": "Extremo",
    "view-distance-far": "Lejos",
    "view-distance-mega": "Mega",
    "view-distance-moderate": "Moderada",
    "view-distance-near": "Cercano",
    "view-distance-ultra": "Ultra",
    "vignette": "Viñeta",
	"volumetric-fog": "Niebla Volumétrica",
    "warn-modules": "ADVERTENCIA: La habilitación de módulos adicionales, especialmente todos o aquellos que no están en la alineación estable, puede causar fallos en el juego o mundos rotos.",
    "warning": "Advertencia",
    "water-reflections": "Reflecciónes del Agua",
    "water-reflections-global": "Global",
    "water-reflections-sky": "Solo el Ciélo",
    "water-reflections-ssr": "SSR (experimental)",
    "widget-selection-prompt": "Seleccione el tipo de widget:",
    "widget-selection-title": "Selección de widgets",
    "world-config-preview": "Detálles...",
    "world-seed": "Semilla"
}

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
Hi @RaymonMolas - this did not exactly get set up the right way. Please check out the documentation again and consider experimenting with Git / GitHub / PRs in a personal repo for testing :-)

You can also try https://try.github.io which has some great tutorials

**Comment by Cervator** [comment]
@RaymonMolas you can also see this PR for an example of the expectations: #3175

**Pull request closed without merging**
