### PR TITLE
Feature: French translation update

### PR DESCRIPTION
**Pull request by Aizen93**
Hello,
### Contains

This PR contains an update for the french translation:

- menu_fr.lang : was updated in Engine ressources assets folder 

### How to test

- Go to the Settings
- Change langage to french in the langages menu list
- Apply choice 
- Play the game to see translation

Thank you for your attention
Aizen93 and fortiseven

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by msteiger** [comment]
test this please

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by msteiger** [comment]
Looks good to me

**Comment by Aizen93** [comment]
Tested again looks good for me too

**Comment by jellysnake** [comment]
LGTM and more languages are always needed, wanted and appreciated.
Merging now

**Pull request merged**
