### PR TITLE
Add Documentation + Internationalized Strings (GCI)

### PR DESCRIPTION
**Pull request by TheJYKoder**
For the PlayerConfig and DefaultCelestialSystem, I've followed the instructions and added JavaDocs to only methods that are not self-explanatory.

For the SpaceTree, I have many questions:
-What is the position exactly?
-Is there anything I misinterpreted?

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by TheJYKoder** [comment]
I've simplified the docs a bit. Thanks for the tip :D

**Comment by TheJYKoder** [comment]
I'm not sure about the migTestScreen.ui

I went through all the UI's, and internationalized them. So if there are others wanting to do this task, please don't accept my migTestScreen.ui.

**Comment by Cervator** [comment]
Retroactively added the Javadoc parts via #2731

**Pull request closed without merging**
