### PR TITLE
GitHub

### PR DESCRIPTION
**Pull request by mperalta92**
metrics implemented...

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by msteiger** [comment]
I guess the PR wasn't meant for this target repository.

**Comment by mperalta92** [comment]
sorry, this pull request is an error..

**Comment by Cervator** [comment]
Still keeping an eye out on all the good work you guys are doing! Happy to see you still at it :-)

**Pull request closed without merging**
