### PR TITLE
Translations and Placeholders for #2285

### PR DESCRIPTION
**Pull request by joseph-healy**
### Contains

Helps fix some issues in #2285. I added spanish translations which I was able to obtain from someone fluent in spanish, and I also put in placeholders where I couldn't access the correct translations.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
@GooeyHub: ok to test

@joseph-healy: thanks! Much appreciated. It does look like some of the "minimal" and "custom" entries are translated and reusable, mind added those back in?

You can just push a new commit to the same branch and it'll update this PR :-)

**Comment by joseph-healy** [comment]
Yeah, I'll add those in

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Thanks! Merged :-)

When dealing with JSON it can be useful to run the game and try to trigger what uses it, one language was missing a comma with this PR, and another even before (whoops!). Helps to enable `*.lang` (and `*.prefab` along with a few others) as extensions for the JSON file type then IntelliJ will handily do syntax highlighting and detect issues.

Added you to the credits, do you have a forum account yet for a contributor badge?

**Comment by Cervator** [comment]
Oh, by the way, feel free to group commits more. One commit per functional change is fine, one per changed file is a bit much, even at a language each :-)

**Comment by joseph-healy** [comment]
Yeah thanks, I'm pretty new to Git in general thats helpful!

**Pull request merged**
