### PR TITLE
Input settings menu i18n; misc. i18n fixes

### PR DESCRIPTION
**Pull request by rzats**
### Contains

An implementation for #2309. Adds internationalization support to static strings, categories and binding names in the Input Settings menu - if a category/binding name is a URN to an internationalisable string, it will be translated, otherwise it will fall back to the default (presumably English) string value

Other miscellaneous additions:

- Sorted the language files by key (via https://www.npmjs.com/package/sort-json). Doesn't break anything but makes the diff look spookier than it actually is.
- Fixed the mess in the Galician file - it used some empty string values, causing awkward UI issues. Not that this particular translation was ever usable :confused:

### How to test

Go to Settings → Player, switch the language to Ukrainian, return to Settings → Input (the fourth button from the top :wink:) and check out the translated menu!

Translated menu screenshot

### Outstanding before merging

- [ ] The Inventory category has some strings specific to the Core module. If these are to be translated, they will require a new set of .lang files and a separate Weblate subproject.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Cool points for "Pyx" - that's a nice looking word! :-)

I see the `API` label there, is there anything changing the modding API potentially breaking modules or is it just a "seemed fitting" for the PR's content?

Also for whatever reason the PR is marked as having conflicts. Maybe missing a rebase on top of the latest develop branch?

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by rzats** [comment]
The `API` label refers to this, which is technically a binding API change:

> if a category/binding name is a URN to an internationalisable string, it will be translated, otherwise it will fall back to the default (presumably English) string value

Fixed the merge conflicts - these were caused by the extra #2301 string.

**Comment by msteiger** [comment]
Modules can inject custom key bindings into the settings dialog. Like you say, the Core bindings should reside in new Weblate subproject.

The JSON keys in the files should be ordered in the same way that Weblate does to avoid confusion. I think that this is alphabetically, so this should be correct. You could add trailing new-line chars, but again, Weblate might override it.

Looks good to me. Thanks you, @rzats.

**Comment by rzats** [comment]
@msteiger: is there any extra setup required to add new .lang files? I've created a Core/Assets/i18n directory and placed some .lang files with valid strings in there, but they aren't picked up by `TranslationSystemImpl`.
A module that has its own translation files might help as an example, although I'm not aware of any that exist.

**Comment by msteiger** [comment]
The translation system iterates over all known translation assets: [TranslationSystemImpl#L69-L84](https://github.com/MovingBlocks/Terasology/blob/8358d38f2847e6faa3884a29eb276a0ab89d0628/engine/src/main/java/org/terasology/i18n/TranslationSystemImpl.java#L69-L84)
I would assume that the asset files are not loaded.

They should be named like this: ` <project-name>_<language-tag>.lang`.

Then, the `TranslationFormat` asset file reader should create a translation project from it: [TranslationFormat:L85-L107](https://github.com/MovingBlocks/Terasology/blob/8358d38f2847e6faa3884a29eb276a0ab89d0628/engine/src/main/java/org/terasology/i18n/assets/TranslationFormat.java#L85-L107). Does that help?

**Comment by rzats** [comment]
@msteiger: well, yes and no - after some debugging it looks like the asset files are never loaded in either `TranslationSystem` or `TranslationFormat.load()`. Their names don't appear to matter: neither of _Core.lang_, _Core_en.lang_, _core.lang_ or _core_en.lang_ work.

This most likely has something to do with the files being in Core instead of engine, requiring some additional hooks. Pinging @immortius.

**Comment by Cervator** [comment]
Weird, looks like another one of my messages never made it through. I must be writing posts then getting distracted by another browser tab and then never make it back :-)

@rzats thanks for the API description! That makes sense.

Should we go ahead and merge this then worry about Core later? That is the start to a very deep rabbit hole, with or without asset scanning quirks :-)

**Comment by msteiger** [comment]
I agree - we should look into module i18n separately.

**Pull request merged**
