### PR TITLE
Fix javaDoc (try #2)

### PR DESCRIPTION
**Pull request by ar0ne**
It's my second try (and I hope is the last one!) to fix javaDocs for the PR #3278 ( Issue #3268 ).

PLEASE DO NOT MERGE IT ! 
before @emanuele3d will have opportunity to take a look and approve it.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by vampcat** [comment]
@emanuele3d can you have a look at the changes, so that it can be fixed/merged?

**Comment by vampcat** [comment]
Yup, looks good to me as well.

Thanks for the javadocs ar0ne, they are always appreciated :)

**Comment by ar0ne** [comment]
Hi @vampcat  and @emanuele3d ! Thank you and could we close this Issue #3268 then.

**Comment by vampcat** [comment]
Sure, done :)

**Pull request merged**
