### PR TITLE
Highlight issues modul details page

### PR DESCRIPTION
**Pull request by godfather2**
### Contains

Colors the bad modules in the module dependencies section in red.
I have been fiddling with the code for a couple of days and it seems likely that you can't color the modules in the 'Modules' list and the text in the 'installed' label without making some serious changes to the code.

### How to test

Mess with versions on any module so that it's installed version is out of bounds.

### Outstanding before merging

- [ ] Colors the modules in the 'Modules' list
- [x] Colors the modules in the 'Module Dependencies' list
- [ ] Colors the text in the 'installed' label

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by DarkWeird** [comment]
1. You violate Variable Naming Conversion, using variable name which starts with uppercase.
2. You can


use getMajor() 



instead

toString ().charAt()



• it will bug with major version greater then 10.

**Comment by godfather2** [comment]
Fixed the naming issue. getMajor() doesn't work for 'installed version'.I used regex instead.

**Comment by e-aakash** [comment]
Thanks for the work.
But the issue has been resolve in https://github.com/MovingBlocks/Terasology/pull/3840, hence closing this PR

**Pull request closed without merging**
