### PR TITLE
replaceBlocks Command is done!

### PR DESCRIPTION
**Pull request by engiValk**
replaceBlock command is finished and tested to work in game. I also fixed some checkStyle issues on other commands.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
@GooeyHub: ok to test

Relates to #1661 :-)

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Pull request merged**
