### PR TITLE
Unit tests for Border class

### PR DESCRIPTION
**Pull request by rajiv-thorat**
Hello,

Please consider this pull request.

Thanks

### Contains

Unit tests for org.terasology.math.Border

P.S.
Could not get the CheckStyle to work with IDEA. Ran gradlew check, that did not produce any warnings. So used the Google rules instead.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Adrijaned** [comment]
@GooeyHub: ok to test

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by rajiv-thorat** [comment]
Done!

**Pull request merged**
