### PR TITLE
remove brackets from console query

### PR DESCRIPTION
**Pull request by Owl-A**
### Contains

fix for #2963

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by nihal111** [comment]
@GooeyHub ok to test

**Comment by nihal111** [comment]
@GooeyHub ok to test

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by Cervator** [comment]
Looks like this broke a unit test that looks for a number of results for a given string - I'm not sure why, but the result is at http://jenkins.terasology.org/job/TerasologyPRs/1586/testReport/junit/org.terasology.utilities/CamelCaseMatcherTest/testTeraCommands/ so the test in question lives in `CamelCaseMatcherTest.testTeraCommands`

The exact problematic hit is `liFSB` which I think should auto-expand to find `listFreeShapeBlocks` - unsure why it doesn't. Try to take a look if you can @Owl-A and if it doesn't make sense just let us know and we'll find somebody who can figure out what's going on :-)

And thanks for the PR!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by nihal111** [comment]
Thanks for the fix @Owl-A 
Tests out well. Can confirm that it fixes that issue. Merging. :smile: 
From next time, try to include the steps to reproduce/test, so that anyone can test out the PR, without redirecting to the issue. :slightly_smiling_face:

**Comment by Cervator** [comment]
Belated comment: Adding you to the game credits @Owl-A - thanks again!

**Pull request merged**
