### PR TITLE
Addressing two issues with one stone - #1659 and #1658

### PR DESCRIPTION
**Pull request by MarcinSc**

### CODE REVIEW

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/59/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Tested around some in multiplayer. Inventory looks solid! Thanks :-)

**Comment by Cervator** [comment]
Incidentally, #1658 is already closed. Did you mean a different issue or that one is just more thoroughly fixed now?

**Comment by MarcinSc** [comment]
Well the problem with "?" was still there, at least when I was fixing it.

**Comment by Cervator** [comment]
True, it came back after another fix.

In any case, all clear, huzzah!

**Pull request merged**
