### PR TITLE
UI Link widget, closes #2715

### LINKED ISSUE #2715: New UI Widget: The UI Link Widget
I am opening this Issue in hope that someone will create a new UI Widget: A Link.

The UILink will be a widget used when people need to input a hyperlink. The widget may have fields similar to [UIText](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/rendering/nui/widgets/UIText.java). The only extra field shall be a "URL" or "link" field which can be used to enter hyperlinks (HTTP, HTTPS) to pages (Web pages to begin with, but later probably even in-game descriptive pages). Another optional field could be "image". One could use this field to set an image which, if clicked, would lead to a web page or an in-game page. 

When seen, the link could be of a different color (preferably blue since that is usually the color of links) and if clicked, would lead to the hyperlink or in-game screen in the "URL" or "link" field.

The need for such a widget arose when I was creating an InformativeLinksScreen interface for the user. If you wish to share links like Terasology's main page, Github page, facebook page, or twitter page, it is recommended that the link you share can be clicked to lead to the actual page. If that is not the case, the amount of people who actually use that link merely out of curiosity drastically reduces due to the inconvenience. 

Other than the example shared above, there are a multitude of places where the UILink widget would come in handy. As I mentioned before, in-game links may be helpful. For example, if people wish to update the "help" command to open a page with "links" to the various in-game descriptive pages, that would improve Terasology's UI interface.

Some APIs that this widget may use are:

1. createLink()
2. getLink()
3. setColor()
4. setLinkText()
5. getLinkText()
6. setLinkImage()
7. getLinkImage()

Images of uses of similar widgets are boundless. Some examples are:
1. [In chat](https://nevergrind.com/blog/wp-content/uploads/2015/07/browser-game-chat-hyperlink.png)
2. [As an image](https://puu.sh/t36wF/673d779063.jpg)

### PR DESCRIPTION
**Pull request by lcalona**
### Contains

A starter class for how a UI Link widget (as described in issue #2715) could be implemented. It is a basic structure for the API with JavaDoc comments describing how everything should work together. It extends the UILabel as I envisioned the widget to have two elements: the actual link along with the text that is displayed for the link (which can be different from the actual link itself). The UILabel seemed perfect for the text element of this widget.

### How to test

As described by the [NUI Quick Start](https://github.com/Terasology/TutorialNui/wiki/Quick-Start) page, create a new module, a *.ui file specifying the text and link fields, and a Java class to handle initialization of the UI screen. Currently only displays the text and has no functionality as a hyperlink yet.

### Outstanding before merging

* Need to actually implement hyperlink functionality
* Possibly use `onMouseButtonEvent(MouseButtonEvent event)` to define what happens on a mouse click?

### Notes

I am not sure if this is a correct way of implementing this widget but it's just an idea of how it could be. I also did not address the image field or methods described in the issue.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by oniatus** [comment]
We should provide an API from the engine to open external links with a prior user confirmation.

I would suggest a simple dialog, e.g. like the one in Minecraft which asks the user
```
Are you sure you want to open the following website?
<website url>
[Yes] [Copy to Clipboard] [No]
```

We can provide a simple API interface from the engine, e.g. like

```
@In
private Browser browser;

//...
browser.open(url);
```
which opens the dialog. This would also allow us to exchange the browser-opening logic as needed.
We may even use it later for other cases, e.g. if we add support for embedded links in the chat widget.

@lcalona, are you interested to continue this implementation?
Also ping @VaibhavBajaj and @smsunarto for possible interest from #2715 and feedback :)

**Comment by jellysnake** [comment]
Pinging @Icalona for status. How's the work going on this?

**Comment by lcalona** [comment]
Hey @oniatus and @jellysnake! Sorry for being inactive, I've been busy with schoolwork lately. However, I am still interested in continuing this implementation. I hope it's fine that I can work on it over the summer after school is over and I have more time. And thank you @oniatus for the feedback!

**Comment by jellysnake** [comment]
All good :)
Just chucking a ping out there to see what the status was. Continuing with this in the summer is fine, look forward to seeing this merged :D

**Comment by jellysnake** [comment]
Hey there @Icalona, just putting our another ping to see how you are going and if you are still interested in continuing with this :)

**Comment by skaldarnar** [comment]
Closing this PR due to inactivity. Please feel free to re-open it when making progress on that topic 😉 

One thing to mention about `Browser` is that it may make some trouble on different operating systems (we observed that in the launcher 😞). Just to keep it in mind…

**Pull request closed without merging**
