### PR TITLE
Remove CoreRegistry usage: Part IV

### PR DESCRIPTION
**Pull request by flo**
Reduces CoreRegistry usage.

It does not conflict with #1797

### CODE REVIEW

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/157/
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/158/
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/159/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
@immortius able to give this a spin with some review now that #1797 is merged?

@emanuele3d - ping, maybe a bit of interest, there's some rendering and TeraEd in there.

**Comment by emanuele3d** [comment]
@immortius was way too efficient for me. Perhaps he wanted to save @flo from a barrage of comments from me? =D

I just had a look and I only found one thing I would have commented about. But it's a very minor, non functional, code style issue and we don't need to worry about. At some point I'll have to put my hands on the WorldRendererImpl class again and I'll do the change then.

**Comment by flo** [comment]
@emanuele3d feel free to still create a comment. It is not the last CoreRegistry removal pull request I am creating. So I am happy that @Immoritus merged it.

**Pull request merged**
