### PR TITLE
GCI tasks (3)

### PR DESCRIPTION
**Pull request by mdj117**

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
Thanks for the PR @mdj117 and thanks for the review @Avalancs ! :-)

Triggering our bot for automatic testing:

@GooeyHub: ok to test

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by mdj117** [comment]
Just confirming I have to remove the class  CardLayoutUnitTest or just remove unit from the name
and change the vars C_H and so on to COLUMN_HEIGHT and so on

**Comment by mdj117** [comment]
The test should run now

**Comment by mdj117** [comment]
I'll change the other ones in max two hours :)

**Comment by mdj117** [comment]
@GooeyHub: ok to test

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by Cervator** [comment]
Closing this as obsolete, too much overlap with another instance of the same GCI task (we probably shouldn't have had that task be multi-instance)

**Pull request closed without merging**
