### PR TITLE
doc: update README

### LINKED ISSUE #5094: Remove outdated references to LGTM and optionally suggest alternatives
### Documentation Topic

Once upon a time we implemented Looks Good To Me (LGTM) which was one of the third party code scanning sites that interacted well with GitHub. There are badges in the Readme and even though I helped set it up at this point I honestly don't remember what pieces are involved or if we have any extra info in the docs somewhere :-)

Since then GitHub _itself_ actually acquired the makers of LGTM and embedded the features into GitHub. See https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning for some related commentary and links.

I am aware of some of the related GitHub features but have not dug into them much yet. So to get back into the swing of making issues now that I'm "back" (see our Discord) I thought I'd simply write this to leave something easy to look at later, be it for myself or somebody else interested in a super easy issue that could simply be removing the badges from our readme.

There's no need to actually _implement_ any alternatives as part of this issue, but if somebody is curious to write up a little extra comment here on some potential new things / replacements we could look into feel free to add that extra!

### PR DESCRIPTION
**Pull request by sfavello**
### Contains

Fixes #5094 
Removes the depreciated lgtm badges from the README doc and includes a replacement of Code climate. Code climate offers 3 different types of badges including a tech debt, maintainability, and issues. I researched replacements for the lgtm and often Code climate was recommended as a good substitute. 

**Update photo**

Screen Shot 2023-04-09 at 11 34 58 AM

### CODE REVIEW

**Comment by Cervator** [comment]
Hi @sfavello and thank you for the PR! Code Climate rings a bell and seems quite reasonable. Also, at this point maintainability of 'C' with "just" 11% technical debt seems both fair and surprisingly low 😁 

For a moment I thought "issues" meant total _GitHub_ issues open, or maybe total ever excluding PRs! That reminds me of when we bump Checkstyle up a degree :-)

I'll see if any other maintainers have an opinion on CC (we've also had SonarSource floating around at times) for a little while then merge, much appreciated!

**Review by Cervator — APPROVED** [review]

**Comment by sfavello** [comment]
@Cervator thank you! And definitely, I think those numbers are awesome. I was checking out CC's website and its got a lot of good feedback and tools to help analyze your repo. It was compared a bit to LGTM so i thought it might be a nice sub. When researching I saw a lot of mentions of SonarSource. It's no worries too if CC is not a good fit. I can always update the PR. I want to make sure it's something yall like in the README. 😄

**Comment by jdrueckert** [comment]
Hello and welcome @sfavello ! Thanks a lot for the PR and not only throwing out the old stuff but even thinking about a useful replacement :green_heart: 

I do not have experience with Code Climate so far but I read that it might even use sonar stuff under the hood? We can definitely use it for the badges and give it a try in push validation. Main evaluation points IMO are how well it finds issues - we could try to provoke some stuff it should find to actually be useful and see if it does - and how much it helps PR authors to fix them - testing usability basically.
We do have Sonarcloud set up for the new website repo and it did help with some valid issues while it admittedly also was annoying in some of the refactoring steps involved in getting the old modulesite to become our new website. Anyway, I'll create a new issue to track a Code Climate pushval test and approve this :slightly_smiling_face: 

Thanks again @sfavello and I hope we see more of you! - here on GitHub and maybe even on our Discord :blush:

**Review by jdrueckert — APPROVED** [review]

**Comment by jdrueckert** [comment]
Oh and congrats to your first merged Terasology PR @sfavello :tada: :clap:

**Comment by sfavello** [comment]
Thank you so much! No worries, I love researching and had a lot of fun looking at possible replacements. Yes! I thought that was awesome, in a couple of Code Climate's repos they use SonarLint.  100%, I will definitely be helping out in any way that I can. 💛 Thank you again. 😃

**Pull request merged**
