### PR TITLE
Add NotoSans-Regular-Title to replace old title font

### LINKED ISSUE #2472: "title"/"default" fonts should be removed from the module lineup
Several modules still use the old `title` and `default` fonts in their skin files. These fonts have issues with non-ASCII characters (see #2029, #2446) and have been replaced by NotoSans fonts for a while now, so they should be removed from the game altogether.
- [ ] Remove the uses of the font in [Terasology/Equipment](https://github.com/Terasology/Equipment) (`CharacterScreen.skin` and `CraftingStation.skin`), replacing `title` with NotoSans-Regular-Large and `default` with NotoSans-Regular-Medium.
- [ ] Verify that the fonts aren't used in other modules. If they are, also replace them.
- [ ] Remove the font files from engine!
##

### PR DESCRIPTION
**Pull request by pamtdoh**
Fixes #2472 

The new font uses the NotoSans font (24 px), mantaining the same size as the old title font so there would not be any overlapping text issues.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
Can confirm this looks to do the trick! Need to pull in all the module PRs all at once, no time for that right this moment but I approved the GCI task for now :-)

Associated module PRs to also merge:

- [ ] https://github.com/Terasology/Alchemy/pull/5
- [ ] https://github.com/Terasology/Cooking/pull/131
- [ ] https://github.com/Terasology/Equipment/pull/115
- [ ] https://github.com/Terasology/InGameHelp/pull/7
- [ ] https://github.com/Terasology/InGameHelpAPI/pull/2
- [ ] https://github.com/Terasology/Journal/pull/7
- [ ] https://github.com/Terasology/Potions/pull/49
- [ ] https://github.com/Terasology/StoneCrafting/pull/2
- [ ] https://github.com/Terasology/WoodCrafting/pull/6
- [ ] https://github.com/Terasology/WorkstationCrafting/pull/6

**Comment by pamtdoh** [comment]
Should I attach more screenshots to confirm this is working on the other modules?

**Comment by jellysnake** [comment]
Clarifying that this is ready to merge and just needs to be merged with all the module PR's? If not what is blocking this @Cervator

**Comment by jellysnake** [comment]
I'm fairly sure I've merged all the relevant instances in modules. There were two hits in the engine, but they can be easily fixed when I merge this
I ran some searches and I didn't find any more hits after merging so I'm going to merge this tomorrow. @Cervator does this sound fine?

**Comment by Cervator** [comment]
Well this one sure got to sit around for a while, but happy we're finally getting it out of the way :-)

With @jellysnake's help I tweaked a final few usages in the engine and a few other modules:

* Books (actually had its own for no real reason - deleted)
* Lost
* ModularComputers
* WoodAndStone
* WoodAndStoneCraftingJournal

I also deleted the old fonts. Gone at last! Looked around some after and couldn't find any obvious missing or messed up text.

Thanks again everybody, on here or on module PRs :-)

**Pull request merged**
