### PR TITLE
bugfix: set core profile to 3.3

### LINKED ISSUE #4698: Black screen on Ubuntu 18.04 with alpha-20
### What you were trying to do
When I run Terasology from the launcher, it shows a loading screen. After that, a full-sized window appears and it is completely black. I just see a mouse cursor. I hear music but I don't see anything.

I tried the version preview alpha-20+195 (20210519). I tried different versions also. The last working version seems to be release alpha-19+2.

When I manage to hit a button (which I don't see), it makes a sound. I tried to run a world by clicking at the positions where I think the buttons might be. So maybe I launched a world, maybe I did something completely different. And then it crashed.

### What actually happened
Whole the game screen is black. When I (maybe) launched a world, it crashed.

### How to reproduce

* Step 1: Start the launcher
* Step 2: Select version preview alpha-20+195 (20210519)
* Step 3: Wait until the progress bar on the loading screen fills.
* Step 4: A window with black screen appears.

### Log details and game version
[2021-05-21_09-05-10_5.0.0-SNAPSHOT_463 (Google Drive)](https://drive.google.com/drive/folders/12iLtAduGf4eVk_iEqw2gxIocujwapb3h?usp=sharing)

### Computer details
OS: Ubuntu 18.04 64-bit
GLFW version: 3.2
CPU: Intel® Core™ i3-6100U CPU @ 2.30GHz × 4 
GPU: Intel® HD Graphics 520 (SKL GT2)

$ glxinfo | grep version
```
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 4.6
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.0.8
OpenGL core profile shading language version string: 4.60
OpenGL version string: 3.0 Mesa 20.0.8
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.0.8
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
    GL_EXT_shader_implicit_conversions, GL_EXT_shader_integer_mix, 
```

### PR DESCRIPTION
**Pull request by Hume2**
REF: https://github.com/MovingBlocks/Terasology/issues/4698

### Contains

Fixes #4698 

### How to test

Run it on my computer and if it shows anything except a black screen after the loading screen, it works ;)

### CODE REVIEW

**Comment by pollend** [comment]
@Hume2 this should get you a bit farther: https://github.com/MovingBlocks/Terasology/pull/4712 It crashes when it hits glLoadIdentity. all references to immediate mode needs to go it seems :(

image

**Comment by Hume2** [comment]
When I tried #4712 alone, I saw just a black screen. So I rebased #4712 onto this branch and then this happened: I created a new world, the world loaded but then I saw just the HUD being displayed over the loading screen. After that, nothing was happening, I tried scrolling the mouse wheel to select a different item, pressing I to open the inventory, moving the mouse down and holding the left button to dig stuff bellow me. None of these actions had any effect. I pressed Alt+F4. After a while, it said that the program isn't responding and asked me to kill the application.

[Terasology-game.log](https://pastebin.com/k17Qpaf4)

[screenshot](https://cdn.discordapp.com/attachments/591982628476026891/846685349401198602/Snimek_z_2021-05-25_11-38-55.png)

**Comment by jdrueckert** [comment]
[OpenGL migrations](https://trello.com/c/0nyhaO6R/124-opengl-migrations)

**Review by jdrueckert — APPROVED** [review]
Tested on Windows with Intel Graphics:
```
13:26:47.498 [main] INFO  o.t.e.rendering.ShaderManagerLwjgl - Loading Terasology shader manager...
13:26:47.508 [main] INFO  o.t.e.rendering.ShaderManagerLwjgl - LWJGL: 3.2.3 build 13 / Windows
13:26:47.508 [main] INFO  o.t.e.rendering.ShaderManagerLwjgl - GL_VENDOR: Intel
13:26:47.509 [main] INFO  o.t.e.rendering.ShaderManagerLwjgl - GL_RENDERER: Intel(R) HD Graphics 520
13:26:47.509 [main] INFO  o.t.e.rendering.ShaderManagerLwjgl - GL_VERSION: 3.3.0 - Build 26.20.100.7812
13:26:47.509 [main] INFO  o.t.e.rendering.ShaderManagerLwjgl - SHADING_LANGUAGE VERSION: 3.30 - Build 26.20.100.7812
```

Seems to work out fine:
image

@pollend Maybe we can get this in to re-enable windows and linux users and try to resolve the mac issues in a follow-up?

**Comment by jdrueckert** [comment]
[Pre-GSoC Release](https://trello.com/c/1oMuhurE/125-pre-gsoc-release)

**Pull request merged**
