### PR TITLE
Font color tests

### PR DESCRIPTION
**Pull request by jmryan64**
### Contains

This pull request adds a new test suite under the engine-tests called FontColorTest. I mainly added tests for the isValid() method and the input it is required to take.

### How to test

Run my unit tests in the FontColorTest suite. (org.terasology.rendering)

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by jellysnake** [comment]
@GooeyHub: ok to test

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Hey @jmryan64 and thanks for the tests here and in #3545 ! I can confirm they work, thanks 👍 

Two requests though:

* You have tabs instead of spaces - could you make sure to reformat as per our project style guide? Easiest is to make sure you have [Checkstyle](https://github.com/MovingBlocks/Terasology/wiki/Checkstyle) set up, it'll warn about everything
* Any reason you're using inner classes to hold the tests? I haven't seen that done before and the inner class also triggers a warning since it doesn't start with a capital letter. I would just have the tests right in the main class instead - any drawback?

Same requests for the other PR but otherwise ready and eager to merge! Appreciate it :-)

**Comment by jmryan64** [comment]
Hey @Cervator, I'll go back in and fix those details shortly! Thanks! I'll move the tests into the main class as well

**Comment by jellysnake** [comment]
To piggy back off of @bpas247's comment, if you feel up to it adding tests to those methods would be great but honestly I'd be happy to merge this and the other matching PR as is and let you add the other tests at your own leisure.
I'd be eager to merge this

**Pull request merged**
