### PR TITLE
chore(settings): disable identity service login ui features

### LINKED ISSUE #4104: Disable Identity Service Login
We've got an increasing amount of questions and reports regarding the **Identity Service Login** from players trying out the game. While the backing service (https://github.com/MovingBlocks/terasology-key-server) is in maintenance mode and not working correctly, we should disable the login option from the UI to not confuse players.

ℹ️   Fixing the Identity Service itself is a different issue!

I believe this is the part of the UI that renders information for the Identity Service:
https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/resources/assets/ui/menu/playerMenuScreen.ui#L64-L104

Related forums post: https://forum.terasology.org/threads/unable-to-login-to-terasology-multiplayer.2314/

### PR DESCRIPTION
**Pull request by Ankhell**
### Contains

Added new prop "overrideChildEnabledProp" to AbstractWidget to avoid overriding of child enabled property during initialization (In this exact case - by UIBox), modified UIFormat to process enabled field after Layout content initialization, disabled Identity Service Login features in UI

Contributes to #4104

### CODE REVIEW

**Comment by Cervator** [comment]
Thanks for the PR @Ankhell ! I hope you don't mind hanging on for just a bit, we're in the middle of extracting our UI system this weekend (and maybe a bit longer) which might mean this change would have to be replicated / moved to its new repo https://github.com/MovingBlocks/TeraNUI and specifically its v1.x branch.

Will get to this as soon as otherwise able :-)

**Comment by Cervator** [comment]
Alright, TeraNUI is officially live! #4017 has been merged.

@Ankhell would you be up for replicating this change in a PR made against https://github.com/MovingBlocks/TeraNUI/tree/release/v1.x ? It should be about the same code.

You can re-embed the TeraNUI source into a game engine workspace with `groovyw lib get TeraNUI` which should place the source under `libs/TeraNUI` (you may then have to check out the `release/v1.x` branch for the library) - you should find the exact same classes in there, you would then just push it to a fork of TeraNUI you'd make and create a new PR there. Testing the game should work the same after you've retrieved the library code :-)

If any questions feel free to hop on Discord for live chat sometime!

**Comment by Ankhell** [comment]
@Cervator Sure thing I would do that as soon as I would have some spare time (:

**Comment by pollend** [comment]
the relevant code for this has been moved to this module: @Ankhell https://github.com/MovingBlocks/TeraNUI

**Comment by jdrueckert** [comment]
Hi @Ankhell, quickly checking in: What do you think when you'll find "some spare time"? :upside_down_face: More like this week / this month / next month / before the end of the year?
And please don't mistake this for putting pressure on you, I'm just interested in the topic ;)

**Comment by Ankhell** [comment]
> Hi @Ankhell, quickly checking in: What do you think when you'll find "some spare time"? 🙃 More like this week / this month / next month / before the end of the year?
> And please don't mistake this for putting pressure on you, I'm just interested in the topic ;)

I'm terribly sorry for being lost, moved AbstactWidget part to TeraNUI https://github.com/MovingBlocks/TeraNUI/pull/28 and left everything else here, hope that's what I was supposed to do

**Comment by jdrueckert** [comment]
@Ankhell Thanks for the update and the PR on TeraNUI!
Ideally, these changes should go against `release/v1.x` as that's the TeraNUI release Terasology works with atm.
Probably it's okay, though, to do it against `master` and cherry-pick the change to `release/v1.x` afterwards, right @Cervator / @skaldarnar ?

**Comment by Ankhell** [comment]
@jdrueckert moved PR to the correct branch https://github.com/MovingBlocks/TeraNUI/pull/29

**Comment by Cervator** [comment]
All good with the new branch, thanks @Ankhell 👍 

@jdrueckert I don't know cherry pick well enough to really have an idea if it'll work well in both directions. I get the feeling Git will probably be able to recognize the _same_ commits, but am less sure how much hassle it would be for us to catch all the commits to cherry pick. No worries on this change for now at least :-)

**Comment by jdrueckert** [comment]
So I finally got to try this out (naturally in combination with https://github.com/MovingBlocks/TeraNUI/pull/29). However, I found that the main menu UI still shows elements related to the identity storage service:
image
image

@Ankhell Did I misunderstand the intended effect of the PR? I thought these UI features were to be removed by your PR? Please correct me if I'm wrong :sweat_smile:

**Comment by Ankhell** [comment]
@jdrueckert According to the name of this issue https://github.com/MovingBlocks/Terasology/issues/4104  it was necessary to disable that part of UI, not to remove it, am I right, @skaldarnar ?

**Comment by jdrueckert** [comment]
@Ankhell As skal is currently sitting behind the wheel (at 200 km/h ^^) let me answer this: The identity Server currently doesn't work. That's why we don't want it to be visible to the users at the moment, that includes removing it the two elements I mentioned above from the UI.
The settings UI elements can stay though as we hope to get it to work again in the short- to midterm future. However, disabling any related buttons (I'm currently on the phone and not sure at the moment how exactly this looks like in the settings) would make sense.

**Comment by jdrueckert** [comment]
Hi @Ankhell any news yet? Did you find some time to take out the UI parts or do you need explicit confirmation by @skaldarnar :sweat_smile:

**Review by skaldarnar — APPROVED** [review]
This does not solve the issue completely, but it's a step in the right direction. Will follow-up on the main menu notification in a separate PR.

**Pull request merged**
