### PR TITLE
Update Ukrainian locale with current strings

### PR DESCRIPTION
**Pull request by rzats**
### Contains

As usual, updates the `menu_uk` localization with a couple of changes:
- Adds one missing string, translates one untranslated one.
- Reworks a bunch of settings-related strings - since we have Ukrainian strings in large AAA games now, I can use them as a reference to see what terms everyone's using! (I referred to Baldur's Gate 3 for this one.)
- Corrects a couple of other things, like ім'я (a name for a human) vs. назва (a name but for a thing).

### How to test

Launch the game, switch the language to Ukrainian, then check out various UI screens to see if things look alright. Maybe look things over with Google Translate :)

### Outstanding before merging

None!

### CODE REVIEW

**Comment by rzats** [comment]
https://github.com/MovingBlocks/Terasology/blob/develop/.github/workflows/project-autoadd.yml `PROJECT_GITHUB_TOKEN` needs to be refreshed I think? The related workflow is failing for a while :)

**Comment by jdrueckert** [comment]
> https://github.com/MovingBlocks/Terasology/blob/develop/.github/workflows/project-autoadd.yml `PROJECT_GITHUB_TOKEN` needs to be refreshed I think? The related workflow is failing for a while :)

I refreshed the token earlier today (before your PR came in) but the action unfortunately doesn't work for PRs from forks...

**Review by jdrueckert — APPROVED** [review]
Did check a few translations at random - looks reasonable to me :slightly_smiling_face: thanks for the contribution :green_heart:

**Comment by rzats** [comment]
@jdrueckert thanks for taking a look :)
Seems like the CI is failing with some stuff that doesn't seem i18n-related:
[Integration Tests / org.terasology.engine.integrationenvironment.delay.DelayManagerTest.delayedActionIsTriggeredTest(ModuleTestingHelper)](https://jenkins.terasology.io/job/Terasology/job/engine/job/PR-5156/2/testReport/org.terasology.engine.integrationenvironment.delay/DelayManagerTest/Integration_Tests___delayedActionIsTriggeredTest_ModuleTestingHelper_/)
[Integration Tests / org.terasology.engine.integrationenvironment.ExampleTest.testClientConnection()](https://jenkins.terasology.io/job/Terasology/job/engine/job/PR-5156/2/testReport/org.terasology.engine.integrationenvironment/ExampleTest/Integration_Tests___testClientConnection__/)
what's typically done about this?

**Comment by jdrueckert** [comment]
> Seems like the CI is failing with some stuff that doesn't seem i18n-related: [Integration Tests / org.terasology.engine.integrationenvironment.delay.DelayManagerTest.delayedActionIsTriggeredTest(ModuleTestingHelper)](https://jenkins.terasology.io/job/Terasology/job/engine/job/PR-5156/2/testReport/org.terasology.engine.integrationenvironment.delay/DelayManagerTest/Integration_Tests___delayedActionIsTriggeredTest_ModuleTestingHelper_/) [Integration Tests / org.terasology.engine.integrationenvironment.ExampleTest.testClientConnection()](https://jenkins.terasology.io/job/Terasology/job/engine/job/PR-5156/2/testReport/org.terasology.engine.integrationenvironment/ExampleTest/Integration_Tests___testClientConnection__/) what's typically done about this?

Yup, that's correct, we have 1-2 sporadically failing integration tests.
Usually, either a retrigger helps or we merge despite the failing integration test if it's unrelated which in your case it is.
Had to update the branch anyways because another PR got merged, so let's see what Jenkins says this time :wink: 
If it fails the unrelated test again, I can merge the PR later anyways.

**Pull request merged**
