### PR TITLE
Behavior system cleanup and refactoring

### PR DESCRIPTION
**Pull request by oniatus**
### Contains

First changes for #2070

- some renamings and refactoring
- fixed a bug where the palette removed to many entries on collapse
- improved string representation of entities

### How to test

Worked with L&S but probably not finished. Any ideas for junit-tests?
Small use-case: spawn some L&S creatures, open the behavior editor and try to create and attach a tree with some simple logic to one of them.
I used a repeat node with a squence: set target to local player - find path - move along path, to make a creature follow the player.

### Outstanding before merging

I suggest to use it as a base for the upcoming gsoc.
Note that the change breaks the API of the Actor class which is used in Pathfinding

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
Awesome :-)

I went ahead and resolved the conflict (location based sfx playing had a change) and pushed the merged branch to https://github.com/MovingBlocks/Terasology/tree/btcleanup

It was hard to test without as we had broken API from other recent changes as well and your branch predated that. The new branch should have everything. I included little btcleanup branches for modules as well to merge along with this

- [ ] Cities
- [ ] LightAndShadow
- [ ] Pathfinding (includes https://github.com/Terasology/Pathfinding/pull/23)
- [ ] WildAnimals

When I had that done I could test! L&S creatures spawned just fine and I saw the workboard commands get logged - but none of the creatures actually moved. Did you try the command objects to issue move/build/dig commands or just edit via BT editor?

With WildAnimals active you get wild deer spawning automatically now. So there I got similar good logging:

```
01:54:27.460 [main] INFO  o.t.minion.move.MoveAlongPathNode - Start moving along path to step 0 (29, 67, 42)
01:54:27.909 [main] INFO  o.t.minion.move.MoveAlongPathNode - Finished moving along path pos = (278.78555, 89.307816, 161.21872) block = (278, 88, 161)
01:54:28.003 [main] INFO  o.t.minion.move.MoveAlongPathNode - Finished moving along path pos = (286.00146, 96.27836, 188.4065) block = (286, 94, 188)
01:54:28.953 [main] INFO  o.t.minion.move.MoveAlongPathNode - Start moving along path to step 0 (209, 75, 31)
01:54:29.080 [main] INFO  o.t.minion.move.MoveAlongPathNode - Start moving along path to step 0 (260, 93, 192)
01:54:29.172 [main] INFO  o.t.minion.move.MoveAlongPathNode - Start moving along path to step 0 (277, 91, 183)
```

And it seemed like it worked, but something eventually caused the deer to stop and walk in place, reversing direction constantly. Same thing if I manually spawned a deer - it would succeed for a few movement commands normally, then lock in place and sort of start *vibrating* in trying to walk in two directions at once.

Can you check out the merged branch and see if it is from changes done in the meantime or if there is something still to fix?

**Comment by msteiger** [comment]
The code looks good to me - I haven't tested it.

**Comment by Cervator** [comment]
@oniatus - have you had a chance to check out the updated branch and the issues I noted? Since this changes API slightly I'd like to get it merged before the release on Sunday :-)

**Comment by flo** [comment]
The code looks also good to me, I also haven't tested it.

**Comment by oniatus** [comment]
Unfortunately I had little time this weekend to get a clean workspace with all the changes.If one can test it, that would be great :)
I am not sure which modules to checkout separate to the L&S and Pathfinding for the change.

**Comment by Cervator** [comment]
Thanks both :-)

I"m going to retry just in case there was something wrong with my workspace causing quirky behavior

**Comment by Cervator** [comment]
Went through it again, The quirks are still there, but the deer situation may be a pre-existing issue just made a bit more visible, and the Light & Shadow creatures not moving isn't a huge deal since they need more effort to actually be any use. Merged to get the API change out of the way :-)

**Pull request merged**
