### PR TITLE
Full and updated/fixed french language

### PR DESCRIPTION
**Pull request by Toinane**
I updated french language to be the same as default file and I updated few text to more accurate translations.
I can confirm almost translation because I'm french developer, but not all.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by msteiger** [comment]
ok to test

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by msteiger** [comment]
Thanks!

**Comment by Toinane** [comment]
no problem! 👍

**Pull request merged**
