### PR TITLE
Support different height maps

### PR DESCRIPTION
**Pull request by msteiger**
This PR adds an alternative height map for HeightMapWorldGenerator and introduces different WrapModes that define the area outside the heightmap. Here's an example based on the new "Opposing Islands" map with WrapMode "CLAMP" (border pixels are repeated, creating an infinite ocean).

image

Note that you will spawn in the ocean on that map. Configuring spawning positions is still an open issue (#1379).

### CODE REVIEW

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/35/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Oooohhh that other noise type image of the opposing islands .... so pretty!

Merged in, reminded self of https://github.com/MovingBlocks/Terasology/pull/1651#issuecomment-85768901 which is still a thing (grass blocks start at a wrong level). We should probably throw that in a quick issue unless fixing soon so we don't forget again :-)

**Comment by msteiger** [comment]
That should be fixed already. I found a piece of grass on the beach just one level above the water surface:

image

Maybe the grass density could be increased for the `BEACH` biome.

**Comment by Cervator** [comment]
Oh that's a grass *billboard* they seem fine - look at the dirt blocks in the background. Those should likely be grass *blocks* which becomes very apparent in some "fields of dirt" you might normally expect to be plains :-)

**Pull request merged**
