### PR TITLE
update eclipse formatter

### PR DESCRIPTION
**Pull request by oniatus**
I updated some values in the formatter to match the latest checkstyle in my changes.
This is the exported version of the formatter (line order got messed up a lot) from eclipse neon.

Not sure if this breaks older eclipse installations though :)

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
@msteiger think you can check this out?

**Comment by msteiger** [comment]
Yeah sure, what changes does it contain? The only issue I'm aware of is the different order of import statements.

**Comment by Cervator** [comment]
@oniatus / @msteiger: bump!

**Comment by oniatus** [comment]
The diff is really unreadable :/ 
I made some smaller changes to the whitespacing, e.g. like [this](https://github.com/MovingBlocks/Terasology/pull/2437/commits/c6a77fa94deb57bac6894d8ce3060cdad9c2590a). I am not sure about the correct import order though.

**Comment by skaldarnar** [comment]
Possibly related: http://checkstyle.sourceforge.net/config_imports.html#ImportOrder

**Comment by Cervator** [comment]
Went ahead and merged this so we can move forward with any additional tweaks on top. Heads up to the Eclipse users :-)

**Pull request merged**
