### PR TITLE
fixed attack event for issue #2887

### PR DESCRIPTION
**Pull request by pollend**
Fixed attack event for CharacterSystem.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Yep tests out - merged! Thanks for the fix :-)

**Pull request merged**
