### PR TITLE
Minor tweeks to video settings menu

### PR DESCRIPTION
**Pull request by MottaTheHutt**
### Contains

This is mainly to make the video preset option more prominent, as a response to Issue #2058.
Video presets are now their own category in the menu.

I've updated the preset names to be more generic/typical, but also more likely to be understood by users who don't understand english. 

One thing to note is I updated the "video-preset-[NAME]" name/values to use the new name scheme, though it doesn't look like these are being referenced anywhere right now. I do see it looks like PR #2226 would cause these values to be used in Preset.java, albeit with the old names

### How to test

I've just been looking at the menu to confirm everything looks right.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by MottaTheHutt** [comment]
untitled

**Comment by Cervator** [comment]
@GooeyHub: ok to test

@MottaTheHutt: thanks! Didn't find the time to test tonight but will as soon as able :-)

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/577/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Tested and merged! Had to tweak a little for the translation stuff to try to avoid conflicts and get Weblate prepared, although there'll be a bit more work there (about to submit a separate issue for later)

If anything maybe a little more margin on the sides of the new dropdown could be added sometime, but that's not priority enough to worry about.

Adding to credits, badging in forum, and all that good stuff! Bring on the next PR :D

**Pull request merged**
