### PR TITLE
changed CollideEvent to be consumable

### PR DESCRIPTION
**Pull request by 0shine0**
Required for CombatSystem module where this event is consumed if the other entity the weapon collided with was the player who fired it, so that no action is taken on the player.
For eg. arrows that player fire are spawned in the bounding box of the player and shouldn't hurt him.

### CODE REVIEW

**Comment by 0shine0** [comment]
pinging @Cervator and @portokaliu for review and merge as soon as possible.

**Comment by 0shine0** [comment]
linking pr in CombatSystem module where it is required 
https://github.com/Terasology/CombatSystem/pull/11

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Seems reasonable to me. Pinging a couple others for review just in case - may be wise to try poking them on Slack occasionally too until somebody else can confirm :-)

**Comment by Cervator** [comment]
Tested it out minimally with GooeysQuests, just to make sure a skeleton could still hurt me and vice versa.

**Pull request merged**
