### PR TITLE
[RFM] Added CharacterImpulseEvent

### PR DESCRIPTION
**Pull request by skaldarnar**
### Contains

This PR adds a new `CharacterImpulseEvent` to change the player's movement. 

It allows to apply a forced movement, e.g., to push the player back or give a thrust forward. This does not require additional movement, in contrast to the boosted stats for running or jumping.

### Outstanding before merging

I'd like to have some feedback on this :) There are some outstanding positions I want to address before merging. 

- [x] add a debug command to "push" the player (required for testing)
- [x] investigate player movement - vertical velocity changes have no influence. 

I tried to give the player a "hard hit", throwing him backwards a bit (i.e., up a little and to the back). However, the only effect I could notice was the force backwards. Vertical velocity seems to be only in affect when jumping. Probably this is related to the `MovementMode`.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by skaldarnar** [comment]
The vertical impulse I tested was simply not strong enough to be noticeable in game. Tried with higher y value, player was thrown in the air :smile: Should be ready for merge from my side, although I'll wait for some feedback.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Can confirm both the console command and the magic dome in L&S! Very impressive!

I was surprised to see it even catches `ghost` *and* `teleport` ! And if you run into the dome with `hspeed` on ... prepare for whiplash :D

**Pull request merged**
