### PR TITLE
fixed loading bar issue

### PR DESCRIPTION
**Pull request by agent-q1**
### Contains

Fixes the loading bar issue where the bar crosses its limits

### How to test

Start the game and the loading bar will not overshoot

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by jellysnake** [comment]
@GooeyHub ok to test

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Thanks for the fix @agent-q1 ! Adding you to the credits shortly

And appreciate the review and merges efforts @jellysnake & @e-aakash :-)

**Pull request merged**
