### PR TITLE
Fixed an issue where the hud throw marker would get stuck if player d…

### PR DESCRIPTION
**Pull request by portokaliu**
Hope this works

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
@GooeyHub ok to test

@portokaliu it looks right, will try it out :-)

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/528/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Tests out great! Thanks :-)

**Comment by portokaliu** [comment]
Yay! :D
More to come soon :tada:

**Pull request merged**
