### PR TITLE
Controller settings

### LINKED ISSUE #3648: Add new "Controller Settings" page
At present the game has a single "Input Settings" sub-menu for things like hot keys. The entries on that specific page are dynamically generated based on an annotation scan for things like `@RegisterBindButton` - each such button and its bindings are put into the Input Settings and the user is able to remap as desired. For an example look at the `FrobButton` class, which by default is the `e` key for interacting with a target object, but also has a secondary default for a `CONTROLLER_BUTTON` with an id of `FOUR`

At present if an actual game controller (for example a USB PS4 or Xbox controller) is connected to the system then the game is launched additional game controller specific options are added to the very bottom of the Input Settings page, such as the ability to configure a deadzone for a given axis. However, the options are fairly limited at present and it is hard to troubleshoot as only those limited options will show up when a working controller is present. See #2125 for some outstanding related issues.

Over time more and more creative controller types have appeared, and in addition to whatever LWJGL 2 allows us in input control (which is becoming quite dated and problematic) there is `OpenVRInput` which attempts to find VR controllers, such as the hand wavy things from the Vive (or, I assume, the Oculus). And, amusingly & apparently, accelerometers on laptops, which can cause weird drift if you happen to move your laptop in funny ways with the game running ...

There are other weird things that may register as a game controller. I've for instance seen my Win8 tablet apparently register its touch screen as a game controller? And who knows what else. There's no obvious way to interface with (or even block) these controllers - unless you're connecting a standard game controller that we can recognize and pop in basic settings for you get nothing.

Lets change that!

This issue requests a new "Controller Settings" sub-menu to go next to the regular input settings, with the current basic settings like deadzone config moved into it. As such this issue may not be easy to work _without_ an actual controller, but it may be workable to a limited degree.

Rather than solely list controllers we know what to do with the page should list _every_ detected controller that could somehow interact with the game and at the very least give the user some sort of option to disable them / ignore input from them inside the game. If no controllers at all are detected then naturally just display a single message on that page going "No controllers found" or so.

If we do believe a specific controller can be used (even creatively, like apparently balancing your laptop to move!) then try to list reasonable configurations for said controller, in its own section. To begin with this may still be nothing but the original deadzone config, maybe an inverse axis or two, etc. Basic stuff.

It would be a nice extra to also list _which_ "buttons" are associated with a given controller on that page. They should still primarily be assigned on the input settings page, but another nice (but likely far more complicated) extra would be to then pick a given controller button and pick a function from a drop-down, which would then replace either the regular or secondary binding for that key. 

Example: A joystick is connected, and supports `CONTROLLER_BUTTON` `JOY1` through `JOY8` - each such entry becomes a button on the page. The user clicks the `JOY5` button and gets a drop-down of all functions that can be mapped to that button. User selects "Frob" and the `FrobButton` secondary binding becomes `JOY5` (I figure it may make more sense for controllers to occupy secondary bindings)

@darshan3 has expressed interest in working some on this issue, but it probably has room for more (particularly users with actual game controllers, especially unusual ones)

We have lots of "controller" related issues, see [this search](https://github.com/MovingBlocks/Terasology/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+controller) - maybe of particular interest is #2933 since we purposefully broke some motion controller stuff that had impacted something else negatively. Maybe some of the stuff linked from there will be good to review for some inspiration (and any fixes would be very appreciated)

### PR DESCRIPTION
**Pull request by EdvinArdo**
#### Contains
Fixes #3648. Builds on #3705, which moved controller settings to its own page.

It is now possible to rebind controller buttons. This is done via
sending a ControllerButtonEvent that is then handled by NuiManagerInternal
and UIInputBind.
    
The controller settings page now contains an axis sensitivity assigned to every axis.
The name labels were previously the raw names from the controller, but are now converted to a display name.

### How to test

Open Settings -> Input and rebind some buttons to controller buttons. Try using the changed buttons in-game.

Start the game with a controller plugged in. Open Settings -> Controllers and adjust the Axis Sensitivity sliders. Look and move around in-game.

Has been tested with an XBOX 360 controller on Linux.

### CODE REVIEW

**Comment by EdvinArdo** [comment]
@Cervator could you take a look at this? Thanks!

**Comment by Cervator** [comment]
Hi @EdvinArdo - nice work! Pings / notifications from GitHub can be very easy to miss due to the amount of repos and such we maintain, better to poke us on Discord or so :-)

It might still take just a bit of time to get to reviewing and testing this, but we very much appreciate the work!

**Comment by skaldarnar** [comment]
Heyo @EdvinArdo, are you still around to address the requested changes? Finishing this up would be highly appreciated!

**Comment by EdvinArdo** [comment]
Heyo! Sorry, I've lost interest and probably won't be finishing up :/

**Comment by Cervator** [comment]
I put an extra note into #3648 to review this if somebody in the future gets back to that topic. Thank you again @EdvinArdo for the work here, even if we weren't able to get it merged :-)

**Pull request closed without merging**
