### PR TITLE
chore: screen merge follow-ups

### PR DESCRIPTION
**Pull request by jdrueckert**
### Contains

* fix screen title
* remove verbose label asking the user to pick a world generator from the drop down
* remove no longer used translation tags
* return user to module selection if no module selected that provides world generator
* differentiate between world generator creation issues and display popup to user if selected world generator cannot be resolved

### How to test

1. Start Terasology
2. Go to advanced game setup
3. Go to universe setup screen
4. Confirm above-mentioned changes

### Outstanding before merging

- [ ] Check and adjust Re-Roll button height to seed text field height

### CODE REVIEW

**Comment by soloturn** [comment]
i do get a build error here, not sure what i am doing wrong:
```
/srv/http/repos/terasology/engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/UniverseSetupScreen.java:360: error: cannot find symbol
        } catch (UnresolvedDependencyException e) {
                 ^
  symbol:   class UnresolvedDependencyException
  location: class UniverseSetupScreen

```

tried to fix it, but i am not sure what one needs to select so that drop back is visible.

**Comment by jdrueckert** [comment]
yeah I must've messed/mixed up the import... GitHub codespaces is not working as well as Intellij when it comes to imports between Terasology and gestalt... also didn't test this yet, so I probably should've opened it as a draft, sorry about that - switching to draft state now.

**Comment by soloturn** [comment]
force pushed my commit with line lenght correct, there was a checkstyle warning. otherwise it builds and works - but i am am a little clueless what should be different from before - so would be cool if you start it once and clcik to the screen you wanted to see a difference? @jdrueckert ?

**Comment by jdrueckert** [comment]
@soloturn I listed the changes I've done in this PR in the description:
> * fix screen title
> * remove verbose label asking the user to pick a world generator from the drop down
> * remove no longer used translation tags
> * return user to module selection if no module selected that provides world generator
> * differentiate between world generator creation issues and display popup to user if selected world generator cannot be resolved

If you navigate to the universe setup screen (Singleplayer -> Create -> Advanced -> Continue to Universe Setup), and compare between develop and this branch, you should be able to notice the frist two aspects. The third one is only visible in-code and the fourth and fifth are indeed hard to test ...

~~I guess one would need to fiddle with the local state of the CoreWorlds module to force these two. I'll play around a bit and if I can reliably force them, I'll provide instructions how to.~~
Scratch that, I don't know how to force them... Removing the world generators from the module before compilation doesn't work because then they're not registered in the first place. And the module cannot be disabled in the advanced game setup because all iota modules are mandatory and, thus, always enabled...

**Review by soloturn — APPROVED** [review]

**Comment by soloturn** [comment]
if its hard to test, then lets merge it, and fix if somebody really notices a regression.

**Pull request merged**
