### PR TITLE
WIP: Feature/joml conversion 1

### PR DESCRIPTION
**Pull request by pollend**
This is a continuation of #3811 and #3837 this PR just ports the rest of the code base over. I added a rounding method to JOMLUtility and we might want to look into adding a PR to JOML adding some kind of rounding constructor between Vector3f <--> Vector3i. I found that trying to port over things by peace meal is more problematic for the long term. There are some odd movement problems that still need to be addressed in the code but it somewhat works for the most part.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by kBlaszczyk** [comment]
Hi guys,
is there a specific reason why this PR is on hold? (other than it being incomplete?)

There are quite a few problems in there.
To name a few:
- the `Vector.sub(a, b)` methods are implemented differently in joml and the usage of these methods needs to be adjusted throughout the engine
- the same is true for some `mul(a, b)` methods
- issues related to column- vs row-majorness of the matrix types.

I have a working fork, based on this PR, with the most recent changes from the develop branch merged into.
I mean working in the sense that the game is running (no odd movement problems) and all tests are green.

If you are serious about migrating to joml (which I hope you are), I'd like to replace this PR with a new one based on my branch:
https://github.com/kBlaszczyk/Terasology/tree/feature/joml_conversion_1
(or update this PR by merging into pollend:feature/joml_conversion_1?)

I'd also be willing to fix more modules depending on TeraMath types in their API usage.
I already fixed Health and Inventory. See:
https://github.com/kBlaszczyk/Health/tree/refactoring/joml-conversion
https://github.com/kBlaszczyk/Inventory/tree/refactoring/joml-conversion

**Comment by pollend** [comment]
we've gone back and forth on this a couple times @kBlaszczyk  and I think we decided it would be less problematic if we did these changes incrementally. I think @PS-Soundwave  and @Cervator could also be a good source if we want to go forward with these changes.

**Comment by kBlaszczyk** [comment]
There are definitely plenty of changes, but most of it is very easy to verify. I'm not sure if putting it in smaller chunks would really help that much.

**Comment by pollend** [comment]
go ahead and open a PR and we can see what we can do.

**Pull request closed without merging**
