### PR TITLE
exposed more to the collision event

### PR DESCRIPTION
**Pull request by pollend**
I exposed a bit more for the collision event. At the moment this is fairly temporary but hopefully something else can be worked out in regards to how physics works in the game. This is just the collision point from each object, how much they penetrate each other and the normal vector in regards to the two collision points.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by pollend** [comment]
I need to actually have accessors for the CollideEvent.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Took it for a quick spin just with a pile of railgunning just to look for anything obvious. Everything seemed fine and you mentioned having gotten feedback from @portokaliu so I'm happy - merged, thanks :-)

**Pull request merged**
