### PR TITLE
Remove use of deprecated methods

### PR DESCRIPTION
**Pull request by MaloJaffre**
I deleted some uses of deprecated methods

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
Gooey: Test this please

ok to test

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/345/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Looking good - thanks! :-)

Got you added to the credits locally, ran out of time with all these nice PRs (again) from doing a release, but will update the credits before that.

Plenty of other neat ways to contribute if you're interested!

**Pull request merged**
