### PR TITLE
Remove the placeBlock command as it does not work in multiplayer.

### PR DESCRIPTION
**Pull request by flo**
Reasoning: The command is not worth fixing for multiplayer as it is
useless. Blocks can be placed via right click. The bad thing about the
command is that it appears to be working but in multiplayer too, but
the blocks exist only on client side only.

Interesting for the future might be a command for placing multiple
blocks at once at a certain location but as it is the command is
useless.

### CODE REVIEW

**Comment by Cervator** [comment]
One advantage does work for placeBlock, last I recalled: You can use it to place a block in nothingness (doesn't have to be placed against something like with right-click). That's a huge advantage for a player just wanting to do creative stuff, even in single player :-)

Wouldn't the same thing that could fix #1441 also fix this? Forcing certain actions to happen on the server (if allowed by permissions) - like spawning a deer as a client attached to a server

**Comment by Cervator** [comment]
Test this please

(Seeing if the PR builder will queue up more than one unique PR at a time)

Also: @flo what do you think about my note above?

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/4/
Jenkins Success Message

**Comment by flo** [comment]
@Cervator I still think we should remove the command as in future we will surely add a command for filling an area at a given location with blocks

**Comment by Cervator** [comment]
Fine by me if you think it is better to just delete it for now :-)

It seems like it has debug potential but I'm not married to it or anything :D

Maybe we should put in a different issue / forum suggestion on how to better handle blocks, with a focus on creative play in multiplayer

**Pull request merged**
