### PR TITLE
Fixed some checkstyle issues

### PR DESCRIPTION
**Pull request by BenjaminAmos**
### Contains

This pull request fixes several checkstyle issues for the engine module.

### How to test

Whilst in general there should be less noticeable issues when testing, a complete list of fixed issues has been attached to compare with the changes in the pull request.

[Checkstyle issues fixed.txt](https://github.com/MovingBlocks/Terasology/files/679707/Checkstyle.issues.fixed.txt)

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
This looks great! Especially with the nice "warnings fixed" attachment, that's a nice extra, thanks for that!

One thing gives me pause, however. Are you sure you're running Checkstyle with the Terasology ruleset? I checked maybe half the fixes but ran across `TeraDeflator` with this old line:

`public abstract TeraArray deflate(final TeraArray in);`

Your warning file lists a redundant "final" but in my IntelliJ running with "Terasology Checkstyle" for the Rules I don't get that warning, nor is it listed in http://jenkins.terasology.org/job/Terasology/1896/checkstyleResult

It could well be a non-issue, but just to be on the safe side I'd like it if you could confirm using the same ruleset, and verify the same warnings are issued (maybe switch to a different branch so you can run it again on the code before your commits then compare to your text file)

Another tiny side issue: try not to merge into a fork's branch - that can cause messy revision history. Better to either leave the branch slightly out of date (if there are no obvious conflicts or related changes in upstream since last) or use rebase instead of merge to move your changes ahead of the newest commit upstream, helps keep the history clean.

Triggering our bot for validation:

@GooeyHub: ok to test

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by BenjaminAmos** [comment]
So, I cloned a fresh copy of the repository and ran the checkstyle plugin for IntelliJ on it. The same warning still occurs. The ruleset it most definitely "Terasology Checkstyle". When I changed it to the default ruleset then it showed this:

checkstyle warning 2
However, if I used the "Terasology Checkstyle", the same warning occured and showed this:

checkstyle warning

The merging into the fork was a mistake. I should have just pulled in the changes (I thought it was a rebase that i did, not a merge). Git is still very new to me.

**Comment by Cervator** [comment]
Ah-hah! That warning appears to have been added very recently to whatever *Checkstyle* version goes with the very latest version of the plugin for IntelliJ. I updated my plugin and now I see it too!

Jenkins likely doesn't see it since the version of Checkstyle it uses is set in the build scripts.

Thank you so much for going the extra mile with the good screenshots and confirmation. All set now :-)

As for Git that's fine! We're all learning something :D

**Pull request merged**
