### PR TITLE
Move environment and utilities classes to src/main in engine-test 

### PR DESCRIPTION
**Pull request by msteiger**
The PR effectively removes all tests and test resources from the `engine-tests.jar`. This change should be mostly transparent as nothing should rely on any of the tests.

This also simplifies the build script somewhat.

Helper classes, utilities and environment classes have been moved to src/main to make them available as before.

As a result, modules will not have the `logback.groovy' from engine-tests in their classpath by default and can define their own. 

Unfortunately, Eclipse still does not distinguish between `compile` and `testCompile` (this was reported in 2008). Therefore the test resources are also available in regular code (`main`) and must still be removed manually :cry:

Jenkins runs the PR just fine: http://jenkins.movingblocks.net/job/TerasologyTemp/10/

I tested this code in every aspect I could think of, but it would be good if someone could test it in IntelliJ (with a mega-workspace maybe?) to verify that it works as expected. Maybe I'm missing some side-effect.

### CODE REVIEW

**Comment by Cervator** [comment]
Thanks, I'll definitely give this a look tonight :-)

Slight tangent: Could you check on #1578 real quick sometime soon? I'd like to get that fixed and do a stable build before merging this and #1575

**Comment by immortius** [comment]
Test classes should not be engine.
Engine should not depend on junit.

**Comment by Cervator** [comment]
Well, sure, but the idea here was more to put the utility classes involved in testing somewhere other than engine-tests, so modules would only need a dependency on engine, not engine-tests. Helps straighten out some of dependency quirks, and might even allow a full collapse back into engine (with main and test source sets) without a separate engine-tests.

Maybe said utility classes still need to be transformed somewhat to fit properly, or maybe too many are being moved. For instance HeadlessEnvironment is one of the prime candidates for the move. Doesn't it make sense for it to be in engine?

**Comment by msteiger** [comment]
w00t! This PR just moves the files *inside* `engine-tests`, namely from `test/java` to `main/java`.

No test classes were moved to engine.
Engine does not depend on JUnit.

In fact, the dependency of modules to JUnit has been removed (it's not required since they depend on `engine-tests`).

**Comment by immortius** [comment]
Ah, I see. I completely misread that.

**Comment by Cervator** [comment]
Finally time to check this, woo! First observation: IntelliJ can blindly build from clean state without running into compilation order issues (usually would get issues with stuff in engine-tests failing to find stuff in engine unless force-compiling it first). Yay! Although I guess Eclipse got less pretty? Boo, but .. as long as you're on top of it! :-)

Weirdly 6 tests do fail in IntelliJ:

* PrefabTest
** prefabHasDefinedComponents
** prefabTransitiveInheritance
** getSimplePrefab
** prefabHasDefinedComponentsWithOrderedMap
** prefabInheritsFromParent
* FactoryTest
** testSaveLoad

Probably related to loading test resources - stuff like:

```
00:53:19.570 [main] DEBUG org.reflections.Reflections - going to scan these urls:
file:/C:/Dev/Terasology/Git/integrate/Terasology/engine/build/classes/
file:/C:/Users/Cervator/.gradle/caches/modules-2/files-2.1/org.terasology/gestalt-module/2.2.3/d7ba668655fc205f3d9da60f299ff4ab6f9fac4f/gestalt-module-2.2.3.jar
00:53:20.841 [main] INFO  org.reflections.Reflections - Reflections took 1269 ms to scan 2 urls, producing 509 keys and 2538 values 
00:53:20.848 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
00:53:20.854 [main] DEBUG org.reflections.Reflections - going to scan these urls:
file:/C:/Dev/Terasology/Git/integrate/Terasology/engine-tests/build/classes/
00:53:20.874 [main] INFO  org.reflections.Reflections - Reflections took 20 ms to scan 1 urls, producing 9 keys and 30 values 
00:53:20.875 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration

java.lang.NullPointerException
	at org.terasology.entitySystem.PrefabTest.prefabHasDefinedComponents(PrefabTest.java:92)
```

Trying from straight Gradle gets me the same results, had thought maybe it related to a way IntelliJ sorts stuff. But it worked in Jenkins ... hmm.

Anyway, merging, then we'll see. Figuring easy fix and we aren't doing the PR test yet so this won't break that. And this is last on my list before I get to work on Jenkins Droplets, yay! Until I go to sleep and wake up with another half dozen new PRs to review ;-)

**Comment by Cervator** [comment]
The 6 tests failed in Jenkins this time too 0_0

http://jenkins.terasology.org/job/Terasology/1352/

Dunno if we made any related changes since this PR went up (or more accurately 9 days ago when the commit was made) that could explain it. Too late for me to think much :-)

**Comment by msteiger** [comment]
I had a look at that and found out that:
* eclipse puts everything in one folder - that's why it works for me
* Jenkins (the TerasologyTmp job) only *git cleans*, but does not *wipe out*, which seems to leave old build files untouched. That's why it still worked there. It runs the "clean" gradle task though - weird..
* Setting the output folder for test and test resources to `build/classes/main` makes the tests compile again, but this is almost as bad as before.

A proper solution would be to:
* Explicitly specify additional (test) resources in `ModuleManagerFactory` to make them available for tests.
* or get the assets into "main" (not very clean, but could be quick workaround). A simple move doesn't work though.

**Comment by Cervator** [comment]
@immortius - thoughts on better support for test stuff in ModuleManagerFactory to keep the source tree more sane?

Maybe we should make a new issue with these notes so we won't forget these comments in a merged PR

**Comment by immortius** [comment]
Yeah, the module stuff is proving a little tricking around testing. The problem is in some environments (gradle) the resource and classes are not combined into one classpath location. The classpath module is set up so you provide a number of classes to indicate classpaths that should be added to the module, but again there is no class in the resource folder to use an indicator. I did add the ability to add all lose folders on the classpath into a classpath module, but this only helps if there is only one such module to deal with.

Otherwise... I've been using a "virtual modules" system in gestalt-assets-core pretty successfully - see: https://github.com/MovingBlocks/gestalt-assets-core/blob/develop/src/test/java/org/terasology/assets/test/VirtualModuleEnvironment.java . This lets you have a bunch of module defined in src/test/resources and load them up. It only works for resource-only modules though.

Perhaps we should just drop test assets from engine-tests.jar and use virtual modules for those? Then engine would be loaded up to include directories on the classpath, other test assets would be in their virtual modules?

**Comment by Cervator** [comment]
@immortius - the tweak over in #1598 made it work for now, do you think that's a suitable fix to keep around for a while? It sounds like you've got a grander design for future improvements :-)

**Pull request merged**
