### PR TITLE
Swimming improvements

### PR DESCRIPTION
**Pull request by coty91**
### Contains

Improvements to swimming and diving for #2492. Damage was not added to diving but is planned for a later PR.
### How to test

Jump while surface swimming, fully submerged, and walking on a solid block with one block of water on top. Also, jump from several different heights into the water to test the new diving improvements.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
@GooeyHub: add to whitelist

Looking good! Feels way better. Well done!

Some quirks /problems noted:

* In one block deep water I could end in up in two states, more rarely I could hear footsteps, typically water squishy noises (expected). I *think* the footstep state comes from swimming up and over to the 1 block deep area, but only sometimes. The footsteps state could get disrupted very easily, like just pushing up against a block could reset it to the expected squishy state, and jumping out then back in definitely "fixed" it
* In either case I could jump from the one block deep water which IMHO is fine, especially since it makes it easier to get out. I wonder if there is a way to limit the strength some of a jump from that sort of starting point?
* I think you mentioned this one, but now I see it better: if you make a column of blocks in deeper water so the top block is even with the water you still can't get out (as you aren't grounded so you can't jump out). We need some sort of fix for that. Ladder blocks use a good solution there you could probably steal *but* - read on!
* It seems to be messing with ladder blocks. Try `giveblock ladder` and place them against a wall. Before this code you can move up and down the ladder easily simply by pointing up or down, even including strafing into/away from the wall to climb up/down. If the ladder is flush with the top block you can simply move up and you'll move gracefully on top of the block the top ladder is against. *With* this code it feels like you are swimming when in a ladder and you can't get up and over the top block.
** Also, hah, the Breathing module triggers when you're on a ladder, as if you're in water :D Before or after this PR, so no change there. But if you spot any obvious issue causing that feel free to fix (note that the icon and placement of the breathing bar is off, that's a known issue)
* It breaks the unit tests in `KinematicCharacterMoverTest` :(
* It has some minor code style violations (usually whitespace) - easy to fix with Checkstyle hooked up
* Fine-tuning: Is there any way the player max "poking out of water" distance could be lowered just a bit? It feels like I'm too high when I am holding down `space` to "tread water" at maximum height
* Fine-tuning: If the resting height when "treading water" is lowered a bit would it make sense to let the player sink when not actively treading water with `space` ?

I love the little bounce when you come out of water, or are swimming right by the surface. Cool when it pulls you back down under water a little so it takes a bit of effort to stabilize above water.

Also neat to see the player dive deep from higher jumps (if that's actually changed, unsure ..)

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by coty91** [comment]
Thanks for the input. I totally forgot to check ladders before doing the PR. oy. Anyway, I'm going to work down your bullet points and fine tune it some more.

**Comment by Cervator** [comment]
Bump - any progress? Lost track of this one since it got closed. You can actually keep PRs open and just apply more commits to the same branch then the PR here will auto-update. Easier to keep track over time and work on review etc :-)

**Comment by coty91** [comment]
I haven't had time to make progress lately. I'll work on it this weekend, though. Didn't realize I could keep them open until recently.

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by Cervator** [comment]
Bump - @coty91 I'm curious about your thoughts on my comment in #2586 (and how you're coming along on this PR). I figure changing around the player's (or creature's?) shape automatically (if appropriate for the active model) on entering/leaving water might relate to your interests :-)

**Comment by flo** [comment]
@coty91  do you still plan to work on this further?

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by jellysnake** [comment]
Pinging @Cervator and @coty91
Any updates on this? Perhaps close it since last ping didn't result in a response?

**Comment by coty91** [comment]
Close it. I haven't had time to work on it.

**Comment by jellysnake** [comment]
Okay. Remember you can re-open pull requests so if you have time in the future then feel free to reopen it

**Pull request closed without merging**
