### PR TITLE
Deprecating methods in Biome API

### PR DESCRIPTION
**Pull request by Adrijaned**
### Contains

`Biome` interface currently contains methods not actually useful for lots of use cases. This PR aims to deprecate them.

### How to test

Just check nothing breaks

### TODO
- [ ] javadoc on new event

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Adrijaned** [comment]
Now also includes biomeChangeListener

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Pull request merged**
