### PR TITLE
Remove MIG layout test menu

### LINKED ISSUE #1012: Remove "Layout Test" menu entry
I think that the upgrade to NUI is mostly complete now. Thus, the "Layout Test" entry in the main menu should no longer be necessary (at least in the develop branch).

Commenting that single line out should fix it, but maybe the code behind can also be removed.

@synopia: what do you think?

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/1612323-remove-layout-test-menu-entry?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by msteiger**
Fixes #1012

### CODE REVIEW

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/348/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Curiously, would it be an idea like in the linked issue to just hide it somewhere out of the way if somebody is tweaking with NUI later and wants to see a before-after impact on all the elements at once?

Maybe we should start thinking about TeraEd in that sense. If you launch with TeraEd, leave the test layout menu active. If not, leave it disabled.

**Comment by msteiger** [comment]
Alright - I left the code in engine, but remove the button from the main menu. You can still open the screen with the new `showScreen` command:

image

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/349/
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/351/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Excellent, thanks! I went ahead and added a little more help text so we won't forget the name of the test screen :-)

**Comment by msteiger** [comment]
Great!

**Pull request merged**
