### PR TITLE
feat: Upgrade Netty to version 4

### PR DESCRIPTION
**Pull request by DarkWeird**
### Contains

Just Upgrading netty to version 4.

### How to test

1. Start Client:
1.1. Check Singleplayer (create/load game and a bit dig)
1.2  Check Client Hosting (create/load game and a bit dig)
2. Start Server:
3. Open Multiplayer on Client.
3.1 before joining to server check request info from server (localhost)
4 Join on server and a bit dig..

### CODE REVIEW

**Comment by pollend** [comment]
netty fails to start correctly on java 11.

```
21:55:13.742 [main] DEBUG i.n.util.internal.PlatformDependent0 - direct buffer constructor: unavailable
java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled
	at io.netty.util.internal.ReflectionUtil.trySetAccessible(ReflectionUtil.java:31)
	at io.netty.util.internal.PlatformDependent0$4.run(PlatformDependent0.java:238)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:232)
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:293)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:92)
	at io.netty.channel.group.DefaultChannelGroup.<init>(DefaultChannelGroup.java:48)
	at io.netty.channel.group.DefaultChannelGroup.<init>(DefaultChannelGroup.java:74)
	at org.terasology.network.internal.NetworkSystemImpl.<init>(NetworkSystemImpl.java:137)
	at org.terasology.engine.subsystem.common.NetworkSubsystem.initialise(NetworkSubsystem.java:41)
	at org.terasology.engine.TerasologyEngine.initSubsystems(TerasologyEngine.java:295)
	at org.terasology.engine.TerasologyEngine.initialize(TerasologyEngine.java:225)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:411)
	at org.terasology.engine.Terasology.main(Terasology.java:174)
21:55:13.744 [main] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
21:55:13.745 [main] DEBUG i.n.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable
java.lang.IllegalAccessException: class io.netty.util.internal.PlatformDependent0$6 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @f973499
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591)
	at java.base/java.lang.reflect.Method.invoke(Method.java:558)
	at io.netty.util.internal.PlatformDependent0$6.run(PlatformDependent0.java:352)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:343)
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:293)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:92)
	at io.netty.channel.group.DefaultChannelGroup.<init>(DefaultChannelGroup.java:48)
	at io.netty.channel.group.DefaultChannelGroup.<init>(DefaultChannelGroup.java:74)
	at org.terasology.network.internal.NetworkSystemImpl.<init>(NetworkSystemImpl.java:137)
	at org.terasology.engine.subsystem.common.NetworkSubsystem.initialise(NetworkSubsystem.java:41)
	at org.terasology.engine.TerasologyEngine.initSubsystems(TerasologyEngine.java:295)
	at org.terasology.engine.TerasologyEngine.initialize(TerasologyEngine.java:225)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:411)
	at org.terasology.engine.Terasology.main(Terasology.java:174)
21:55:13.745 [main] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): unavailable
```

**Comment by DarkWeird** [comment]
Netty start correctly.
 But cannot apply optonal optimization for direct buffer.

Variants
We can suppress debug logging for netty.
We can add launch parameter for jvm.
We can disable this optimization

**Comment by pollend** [comment]
looks like I was wrong, I wasn't able to join a world. initially thought it was with the server. :

```
22:20:12.503 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 0
22:20:12.503 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
22:20:12.573 [nioEventLoopGroup-2-1] WARN  i.n.util.concurrent.DefaultPromise - An exception was thrown by org.terasology.network.ServerInfoService$$Lambda$355/0x0000000840c30040.operationComplete()
java.lang.NullPointerException: null
	at org.terasology.network.ServerInfoService.lambda$requestInfo$0(ServerInfoService.java:60)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
	at io.netty.util.concurrent.DefaultPromise.access$200(DefaultPromise.java:35)
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:501)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
22:20:14.525 [Thread-1] DEBUG c.j.d.entities.pipe.UnixPipe - Received packet: Pkt:FRAME{"evt":null,"data":{"assets":{"large_image":"515746954660151306"},"timestamps":{"start":1604730007000},"name":"Terasology","details":"Name: Player30385","state":"In Lobby","secrets":{},"application_id":"515274721080639504"},"cmd":"SET_ACTIVITY","nonce":"34f6875a-192b-4860-b9e3-f0941579d1cb"}
22:20:19.536 [Thread-1] DEBUG c.j.d.entities.pipe.UnixPipe - Received packet: Pkt:FRAME{"evt":null,"data":{"assets":{"large_image":"515746954660151306"},"timestamps":{"start":1604730007000},"name":"Terasology","details":"Name: Player30385","state":"In Lobby","secrets":{},"application_id":"515274721080639504"},"cmd":"SET_ACTIVITY","nonce":"49716e8d-cac9-4f21-9afe-d76298fe5ede"}
22:20:24.497 [Thread-1] DEBUG c.j.d.entities.pipe.UnixPipe - Received packet: Pkt:FRAME{"evt":null,"data":{"assets":{"large_image":"515746954660151306"},"timestamps":{"start":1604730007000},"name":"Terasology","details":"Name: Player30385","state":"In Lobby","secrets":{},"application_id":"515274721080639504"},"cmd":"SET_ACTIVITY","nonce":"4e769c3d-573a-4dd9-a1eb-a5d13ebfcffc"}

```

**Comment by DarkWeird** [comment]
@pollend 
Fixed.


Idk what will do with `class io.netty.util.internal.PlatformDependent0$6 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @f973499`

It is normal for java 11 and netty 4 - not blocker.

**Comment by pollend** [comment]
the warning is fine. It doesn't affect the connection.

**Review by jdrueckert — APPROVED** [review]
Didn't observe any issues during testing and seems fine code-wise as far as I can see.

**Pull request merged**
