### PR TITLE
Fixes for some of #3510

### PR DESCRIPTION
**Pull request by mwvdev**
### Contains

Fixes the following list of issues from #3510:

- Command line is built with string concatenation
- Container contents are never accessed
- Container contents are never initialized

Most of the affected classes are not under unit test, but I have run all unit tests locally to verify I didn't break anything and manually tested the affected parts by running the game.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
This pull request **fixes 5 alerts** when merging 6b8aeff09668494142bb0365d2b9be050fbd9a23 into 9118708ad3f34f0bc05572fe54ad47538c3164bb - [view on LGTM.com](https://lgtm.com/projects/g/MovingBlocks/Terasology/rev/pr-206838afcdde6327d9ea4d5e05776524d001ae4c)

**fixed alerts:**

* 3 for Building a command line with string concatenation
* 1 for Container contents are never accessed
* 1 for Container contents are never initialized

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Cervator** [comment]
Thanks for the PR @mwvdev ! We'll get it checked out when able :-)

Triggering another bot thing:

@GooeyHub: ok to test

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by jellysnake** [comment]
Tests out and looks good. Merging away

**Pull request merged**
