### PR TITLE
Unify color serialization

### PR DESCRIPTION
**Pull request by msteiger**
Currently, color is specified as hex-strings such as `AAAAAAFF` in the UI skin format and as integer array such as `[224, 224, 224, 255]` in the UI file format.

This PR is a step towards the unification of the gson `TypeAdapter*` hierarchy and the Terasology `TypeHandler*` hierarchy by merging the two classes.

I'm also breaking an unwritten law here by throwing an exception when the de-serialization fails. Previously, it returns `null` silently and crashes later with a NPE, while it now reports the failure in the logs and continues with the default value or binding. I think that this should be the default behavior for the other marshalling adapters, too.

Does that make sense, @immortius?

### CODE REVIEW

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/618/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Tried to test, main menu works fine.  Trying to start a JS world made the game go boom - same with Core after force compiling engine + Core + CoreSampleGameplay:

```java
01:30:49.435 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:DoorBottom.FRONT with id 7
01:30:49.435 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:DoorBottom.BACK with id 8
01:30:49.959 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
org.terasology.persistence.typeHandling.DeserializationException: Expecting integer array or hex-string, but found: double: 0.0
double: 0.0
double: 0.0
float: 0.0
float: 0.0
float: 0.0
integer: 0
integer: 0
integer: 0
long: 0
long: 0
long: 0
bytes: "\000\000\000"

	at org.terasology.persistence.typeHandling.extensionTypes.ColorTypeHandler.deserialize(ColorTypeHandler.java:55) ~[classes/:na]
	at org.terasology.persistence.typeHandling.extensionTypes.ColorTypeHandler.deserialize(ColorTypeHandler.java:31) ~[classes/:na]
	at org.terasology.persistence.typeHandling.Serializer.deserializeOnto(Serializer.java:96) ~[classes/:na]
	at org.terasology.persistence.typeHandling.Serializer.deserializeOnto(Serializer.java:151) ~[classes/:na]
	at org.terasology.persistence.serializers.ComponentSerializer.deserializeOnto(ComponentSerializer.java:202) ~[classes/:na]
	at org.terasology.persistence.serializers.ComponentSerializer.deserialize(ComponentSerializer.java:118) ~[classes/:na]
	at org.terasology.persistence.serializers.PrefabSerializer.applyComponentChanges(PrefabSerializer.java:164) ~[classes/:na]
	at org.terasology.persistence.serializers.PrefabSerializer.deserialize(PrefabSerializer.java:136) ~[classes/:na]
	at org.terasology.persistence.serializers.PrefabSerializer.deserialize(PrefabSerializer.java:116) ~[classes/:na]
	at org.terasology.entitySystem.prefab.internal.PrefabFormat.load(PrefabFormat.java:53) ~[classes/:na]
	at org.terasology.entitySystem.prefab.internal.PrefabFormat.load(PrefabFormat.java:36) ~[classes/:na]
	at org.terasology.assets.module.UnloadedAssetData$AssetSourceResolver.load(UnloadedAssetData.java:292) ~[gestalt-asset-core-5.0.1.jar:5.0.1]
	at org.terasology.assets.module.UnloadedAssetData.load(UnloadedAssetData.java:180) ~[gestalt-asset-core-5.0.1.jar:5.0.1]
	at org.terasology.assets.module.ModuleAssetDataProducer.getAssetData(ModuleAssetDataProducer.java:228) ~[gestalt-asset-core-5.0.1.jar:5.0.1]
	at org.terasology.assets.AssetType.lambda$reload$1(AssetType.java:356) ~[gestalt-asset-core-5.0.1.jar:5.0.1]
	at org.terasology.assets.AssetType$$Lambda$73/872669868.run(Unknown Source) ~[na:na]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_45]
	at org.terasology.assets.AssetType.reload(AssetType.java:354) ~[gestalt-asset-core-5.0.1.jar:5.0.1]
	at org.terasology.assets.AssetType.getNormalAsset(AssetType.java:383) ~[gestalt-asset-core-5.0.1.jar:5.0.1]
	at org.terasology.assets.AssetType.getAsset(AssetType.java:262) ~[gestalt-asset-core-5.0.1.jar:5.0.1]
	at org.terasology.assets.management.AssetManager.getAsset(AssetManager.java:206) ~[gestalt-asset-core-5.0.1.jar:5.0.1]
	at org.terasology.engine.modes.loadProcesses.LoadPrefabs.step(LoadPrefabs.java:44) ~[classes/:na]
	at org.terasology.engine.modes.StateLoading.update(StateLoading.java:242) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:414) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:369) ~[classes/:na]
	at org.terasology.engine.Terasology.main(Terasology.java:150) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144) [idea_rt.jar:na]
01:30:49.959 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
org.terasology.persistence.typeHandling.DeserializationException: Expecting integer array or hex-string, but found: double: 0.0
double: 0.0
double: 0.0
float: 0.0
float: 0.0
float: 0.0
integer: 0
integer: 0
integer: 0
long: 0
long: 0
long: 0
bytes: "\000\000\000"

	at org.terasology.persistence.typeHandling.extensionTypes.ColorTypeHandler.deserialize(ColorTypeHandler.java:55)
	at org.terasology.persistence.typeHandling.extensionTypes.ColorTypeHandler.deserialize(ColorTypeHandler.java:31)
	at org.terasology.persistence.typeHandling.Serializer.deserializeOnto(Serializer.java:96)
	at org.terasology.persistence.typeHandling.Serializer.deserializeOnto(Serializer.java:151)
	at org.terasology.persistence.serializers.ComponentSerializer.deserializeOnto(ComponentSerializer.java:202)
	at org.terasology.persistence.serializers.ComponentSerializer.deserialize(ComponentSerializer.java:118)
	at org.terasology.persistence.serializers.PrefabSerializer.applyComponentChanges(PrefabSerializer.java:164)
	at org.terasology.persistence.serializers.PrefabSerializer.deserialize(PrefabSerializer.java:136)
	at org.terasology.persistence.serializers.PrefabSerializer.deserialize(PrefabSerializer.java:116)
	at org.terasology.entitySystem.prefab.internal.PrefabFormat.load(PrefabFormat.java:53)
	at org.terasology.entitySystem.prefab.internal.PrefabFormat.load(PrefabFormat.java:36)
	at org.terasology.assets.module.UnloadedAssetData$AssetSourceResolver.load(UnloadedAssetData.java:292)
	at org.terasology.assets.module.UnloadedAssetData.load(UnloadedAssetData.java:180)
	at org.terasology.assets.module.ModuleAssetDataProducer.getAssetData(ModuleAssetDataProducer.java:228)
	at org.terasology.assets.AssetType.lambda$reload$1(AssetType.java:356)
	at org.terasology.assets.AssetType$$Lambda$73/872669868.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.terasology.assets.AssetType.reload(AssetType.java:354)
	at org.terasology.assets.AssetType.getNormalAsset(AssetType.java:383)
	at org.terasology.assets.AssetType.getAsset(AssetType.java:262)
	at org.terasology.assets.management.AssetManager.getAsset(AssetManager.java:206)
	at org.terasology.engine.modes.loadProcesses.LoadPrefabs.step(LoadPrefabs.java:44)
	at org.terasology.engine.modes.StateLoading.update(StateLoading.java:242)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:414)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:369)
	at org.terasology.engine.Terasology.main(Terasology.java:150)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
For more details, see the log files in J:\Dev\Terasology\Git\integrate\Terasology\logs\2016-04-27_01-29-56
```

May have to poke @immortius on IRC, I'm not sure he'll notice email notifications from here.

**Comment by immortius** [comment]
I guess my first question is what color values are doing in the UI file format at all. :P  Although I guess there is a niche use if the colors are options for a menu.

Beyond that... I don't see an issue. Are you planning to have the hex values used when deserializing prefabs too?

I cannot remember why the methods were different for different things exactly. I think I just kept the deserialization of skins separate due to the heavy use of combining values across the hierarchy. It makes sense for failed deserialization to return a default value if we want the code to be resilient to input errors.

**Comment by msteiger** [comment]
Thanks you for your feedback. Afaics, the deserialization of behavior node colors never worked. It just never caught anyone's attention, since the values are never read.

I hardened the `Serializer` class so it will skip over fields with malformed data and log the error.
Also added a few unit tests.

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/623/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Can confirm no more crashy :-)

I still see the error above with L&S, but then I see you noted that in one of the commits. Can we log better exactly what asset causes the issue? And in this case should we fix something up in L&S? It doesn't seem to actually get in the way in-game, seems to work OK.

**Comment by Cervator** [comment]
Hmm, I had missed the Italian translation commit, so rebased the merge on top but that caused this to not auto-closed as merged.

Closing as complete - it DID get merged!

**Pull request closed without merging**
