### PR TITLE
Telemetry minor improvements

### PR DESCRIPTION
**Pull request by GabrielXia**
### Contains

Some improvements for telemetry:

1. New telemetry keys in `menu.lang` (mentioned in #3011)
2. Remove snowplow logging (mentioned in pr #3016)
3. Fix a bug that restarting the game gives always the default server address in popup even the server address is modified in the previous game

### How to test

In the metrics menu, enable the telemetry or error reporting, and change the server address or owners in the `server popup`. Restart Terasology, the `server popup` will show the default address however the real address is modified in the previous game. This pr fixes the problem.

### CODE REVIEW

**Comment by GabrielXia** [comment]
Thanks for reviewing :) @rzats @oniatus @Cervator @skaldarnar @msteiger @qwc

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Build started sha1 is merged.
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Looks good and works out, tested locally and all seems well. Merged! :-)

**Pull request merged**
