### PR TITLE
Prompt new users to pick username

### PR DESCRIPTION
**Pull request by iojw**
### Contains

New players now always get assigned a generic username (Player#####) when they first run the game instead of the system username. Seems the code for this already existed so all I did was remove the part about the system username 🙂 

When accessing the Host Game or Join Game Screen for the first time, users will be prompted to choose a non-default username. They will only be prompted once.

### How to test

- Delete your config.cfg before loading up Terasology
- You will be assigned a generic username when the game first starts (you can check this in Player Settings)
- You will be prompted to change your username when you first access either the Join Game or Host Game screen
- 'Ok' sets the username, 'Cancel' does nothing
- You will not be prompted anymore after the first time.

### Outstanding before merging

None

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by skaldarnar** [comment]
If Jenkins reports three successes it must be good 😆 I like it, will merge after a quick test 😉

**Comment by iojw** [comment]
@skaldarnar Thanks! Only spotted a mistake really late and I was hoping Gooey wouldn't notice my commit amends 😆

**Comment by skaldarnar** [comment]
we can squash-merge the PRs anyways, so it's usually no problem to have follow-up commits fixing some minor mistakes 😉

**Pull request merged**
