### PR TITLE
[WIP] Health Overhaul

### PR DESCRIPTION
**Pull request by e-aakash**
### Contains

The contents removed by the new [Health Module](https://github.com/Terasology/Health).

### Outstanding before merging

- [ ] Need to complete work on Health module
- [ ] Make sure that migration does not break anything

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
This pull request **fixes 2 alerts** when merging bfaaf65722ed49da3450b92eec080ec39af171c0 into b0f2d8827869e544c3384b8821d1b71b0a097e0b - [view on LGTM.com](https://lgtm.com/projects/g/MovingBlocks/Terasology/rev/pr-47bc39a96776c40a956a392a138380b84eaf1e17)

**fixed alerts:**

* 2 for Dereferenced variable may be null

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Cervator** [comment]
Gooey: Test this please

@GooeyHub test this please

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Pull request merged**
