### PR TITLE
Fix 21 checkstyle issues.

### PR DESCRIPTION
**Pull request by mjuvekar7**
Fixed 21 checkstyle issues in 4 files:
- 12 issues to do with variable declaration order in UIText.java
- 4 issues to do with redundant modifiers in ThreadMonitorPanel.java
- 3 redundant modifiers in PojoEntityManager.java
- 2 redundant modifiers in UIFormat.java

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
Thanks :-)

The access modifiers are probably some of the more poorly defined rules we have in Checkstyle - I am not entirely sure if we risk breaking some of the engine magic by taking some things non-public. But that's not on you, the task as written would be approved with this merged. Just need to find the time to test it out.

In the meantime I'll trigger our bot for its testing

@GooeyHub: ok to test

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Merged along with #2682. While testing I discovered #2690 but could replicate it in the prior build so it must be unrelated.

Thanks!

**Pull request merged**
