### PR TITLE
Fix duplicate chat message notifications

### LINKED ISSUE #2990: When typing a chat message and another player sends chat two chat screens are open
When in a multiplayer session you are typing you have a fairly large chat window with many lines available visible. When you *receive* a message a smaller less intrusive window shows up to let you see new messages at a glance.

If both happen at the same time you get *both* windows:

2017-06-24 19_19_43-terasology - c__dev_terasology_git_terasology - terasology - _config_grad

That's silly. The typing window is already larger, just suppress the "preview" variant and show the new message normally. 

`ChatScreen` is one of the involved classes.

### PR DESCRIPTION
**Pull request by Derpthemeus**
### Contains

Fixes #2990 

### How to test

1. Start up 2 Terasology clients and connect to a server with client 1.
2. Connect to the server with client 2 and confirm that client 1 receives a popup notification.
3. Send a message from client 2 and confirm that client 1 receives a popup notification.
4. Open the chat window on client 1 (leave it open for the remaining steps).
5. Send a message from client 2 and confirm that client 1 sees the message, but does not receive a popup notification.
6. Disconnect client 2 from the server and confirm that client 1 sees the notification, but does not receive a popup notification.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
Belated thanks for the PR! Triggering our bot for testing :-)

@GooeyHub: ok to test

Anybody want to take this for a spin? Maybe @TheFlash98? :-)

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by TheFlash98** [comment]
Hey @Cervator tested the PR exactly how the instructions have been given and it works well on my machine. 🙂

**Comment by Cervator** [comment]
Thanks both! Appreciate the work. Merged :-)

@Derpthemeus added you to our credits, hoping to see more work from you!

**Pull request merged**
