### PR TITLE
Fixed showing of unnecessary scrollbar - follow-up from PR #2180

### LINKED ISSUE #2179: UIDropdownScrollable shows scrollbar even when it's unnecessary
The scrollbar shows up on that aren't longer than the given number of options. F.e., a menu with 3 options, and the setVisibleOptions is set to 5 will still show a scrollbar.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/31167652-uidropdownscrollable-shows-scrollbar-even-when-it-s-unnecessary?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by AlexanderGrooff**
Similar to PR #2180, but without the long list of previous commits. Fixes #2179.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
ok to test

Thanks! Out of time tonight but will check when able :-)

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/439/
Hooray Jenkins reported success with all tests good!

**Comment by msteiger** [comment]
Thanks Alex - I will look into this asap (Sunday hopefully).

**Comment by Cervator** [comment]
Checked on it and merged despite a slight issue - submitted #2185 for follow-up :-)

Thanks!

**Pull request merged**
