### PR TITLE
chore(persistence): replace transaction manager with Reactor

### PR DESCRIPTION
**Pull request by pollend**
this replaces the saveThreadManager with a singleSubject I think this change is a lot easier to follow then some of the strange logic with TaskMaster. 

- create a new world
- see if game saves from clock interval
- verify that game can be loaded from save

## Blockers
- [x] #5032

- 🯄 #5051 
  -  maybe no longer reproducible or otherwise unrelated?

Part of https://github.com/MovingBlocks/Terasology/pull/4798

### CODE REVIEW

**Review by DarkWeird — DISMISSED** [review]
1. Auto Saving - works
2. Loading saved game - don't works ( exit to main menu -> game -> load game)
3. Loading saved game with restart game - works

Loading without restart game:
1. stuck at await player spawn
2. chunks loads (Chunks present in heap)
3. I notice several LocalPlayerSystems in heap (via heap dump)
4. SaveTransactions is not present (it is right)
5. guess entities not loads(?)

**Comment by keturn** [comment]
> 2. Loading saved game - don't works ( exit to main menu -> game -> load game)
> 3. Loading saved game with restart game - works

I've heard people talk about problems loading more than one world before. Are the bugs you've noted here new in this branch, or are they problems that exist in develop?

**Comment by keturn** [comment]
[Reactor: ReadWriteStorageManager engine (persistence)](https://trello.com/c/Be5t9Wtr/212-reactor-readwritestoragemanager-engine-persistence)

**Comment by DarkWeird** [comment]
> > 2. Loading saved game - don't works ( exit to main menu -> game -> load game)
> > 3. Loading saved game with restart game - works
> 
> I've heard people talk about problems loading more than one world before. Are the bugs you've noted here new in this branch, or are they problems that exist in develop?

This problem is new.
And last problem is not resolved too

New problem have another symptoms. (Noted)

**Comment by pollend** [comment]
> > > 2. Loading saved game - don't works ( exit to main menu -> game -> load game)
> > > 3. Loading saved game with restart game - works
> > 
> > 
> > I've heard people talk about problems loading more than one world before. Are the bugs you've noted here new in this branch, or are they problems that exist in develop?
> 
> This problem is new. And last problem is not resolved too
> 
> New problem have another symptoms. (Noted)

I did tweak the behavior but I guess its still wrong.

**Comment by keturn** [comment]
I think the reason that the tests are failing is because `waitForCompletionOfPreviousSave` is not working. The test zips right to the assertions before the stuff on the other thread finishes.

I'm also frustrated because I really want Reactor to have a tidy interface for this sort of thing, instead of trying to add our own bookkeeping on top of it, but I have yet to figure out anything that's a good fit for the StorageManager's current API.

**Review by jdrueckert — COMMENTED** [review]
Code-wise, this looks reasonable to me, but I still need to test it. Hope I'll get to that tomorrow after work.

**Review by jdrueckert — APPROVED** [review]
Tests out fine.

**Pull request merged**
