### PR TITLE
chore[build]: Upgrade Gradle to 6.7

### PR DESCRIPTION
**Pull request by keturn**
Upgrades gradle from 6.4.1 to 6.7.

Gradle 6.7 contains significant changes under the hood to their Java compilation tasks. I want to make sure we're using those before doing more work on our build process.

Looks like a very uneventful upgrade. Only one new deprecation message popped up.

### How to test

Run builds and tests and whatnots in whatever ways you usually use in your workflow.

### CODE REVIEW

**Comment by DarkWeird** [comment]
@keturn 
Notification: Gradle 6.7 released at 14 Oct. :P

**Comment by keturn** [comment]
I noticed that today! There were a couple more release candidates between the one in this draft and the final release but I don't expect any difficulties with updating this one.

(feel free to steal this PR if I'm slow to get to it.)

**Comment by keturn** [comment]
Updated to gradle 6.7 final. Ready for test and review.

**Review by DarkWeird — APPROVED** [review]
works.

Warnings about Kotlin code only(previous PR)
And  gradle server not works (previous PR too)

**Pull request merged**
