### PR TITLE
Update CZ translation

### PR DESCRIPTION
**Pull request by Malanius**
### Contains
Czech translation updates:
- changed "enter-username-message" string to comply with changes as stated in #2921
- added translations for new strings (identity and telemetry mostly)
- fixed typos in few translations
- a little bit of reordering to be same as EN lang for better comparison

### How to test
1. Run the game
2. Switch to the Czech language
3. See everything translated :)

### Outstanding before merging
- nothing

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by jellysnake** [comment]
I don't speak Czech but I loaded it up in game and ran through a bunch of things and nothing broke.  
Also ran it through Google Translate and didn't find anything abnormal.  
Seems to be fine to merge.

**Comment by Cervator** [comment]
@GooeyHub: add to whitelist

Translation PRs might not get much out of the build testing, but anyway, with you on the whitelist that should be automatic now :-)

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
@Malanius PR merged - thanks!

@jellysnake thanks for checking it and feel free to merge after that amount of validation :-)

**Comment by Malanius** [comment]
@jellysnake Thanks for testing! Should be good as Czech is my native language :)
@Cervator Thanks for merging!

**Pull request merged**
