### PR TITLE
Introducing GraphicState

### PR DESCRIPTION
**Pull request by emanuele3d**
This PR extracts a number of opengl-related methods from the rendering process and places them in a new GraphicState class. 

The first commit mostly operates the extraction by moving the methods (unmodified) from one class to another. More interesting are the changes to the WorldRendererImpl, in particular the order of operations in its initRenderingSupport() method becomes crucial for the correct construction and setting of objects supporting the renderer.

The second commit takes the opportunity to go through the new class and refactor it. Many methods and variables have their name changed here. Also, the GraphicState class is modified in this commit to obtain a number of references to FBOs which are then refreshed only when necessary. Previously they were obtained through the LwjglRenderingProcess class, in some cases multiple times per frame.

The third commit adds javadocs and, to a lesser degree, comments throughout the GraphicState class.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/45/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Still looks like we're moving in a great direction :-)

This one time I can finally report finding an issue during testing though! For some reason starting a game gives me completely black blocks. Even if I hold a torch no light is visible, and the torch itself is mostly white. If I *place* a torch then I get ghostly white lighting in the local area. Screenie:

terasology-150424234410-1152x720


When I went and tried to change from default graphic settings the game crashed on saving the options:

```
23:44:15.067 [main] WARN  o.t.engine.internal.TimeBase - Delta too great (2541), capping to 1000
23:44:21.000 [main] INFO  o.t.r.n.l.m.v.VideoSettingsScreen - Video Settings: {"pixelFormat":24,"windowPosX":379,"windowPosY":235,"windowWidth":1152,"windowHeight":720,"fullscreen":false,"viewDistance":"moderate","flickeringLight":false,"animateGrass":true,"animateWater":false,"fieldOfView":90.0,"cameraBobbing":true,"renderPlacingBox":true,"blurIntensity":2,"reflectiveWater":false,"vignette":false,"motionBlur":false,"ssao":false,"filmGrain":false,"outline":true,"lightShafts":false,"eyeAdaptation":false,"bloom":false,"dynamicShadows":true,"oculusVrSupport":false,"maxTextureAtlasResolution":4096,"maxChunksUsedForShadowMapping":1024,"shadowMapResolution":1024,"normalMapping":false,"parallaxMapping":false,"dynamicShadowsPcfFiltering":false,"cloudShadows":false,"renderNearest":true,"particleEffectLimit":10,"frameLimit":60,"meshLimit":400,"inscattering":true,"localReflections":false,"vSync":false,"clampLighting":false,"fboScale":100,"dumpShaders":false,"screenshotSize":"normal size","screenshotFormat":"jpg","cameraSettings":{"cameraSetting":"normal"},"debug":{"enabled":false,"stage":"opaque_color","firstPersonElementsHidden":false,"hudHidden":false,"wireframe":false,"renderChunkBoundingBoxes":false,"renderSkeletons":false}}
23:44:21.420 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.NullPointerException: null
	at org.terasology.rendering.shader.ShaderParametersSSAO.applyParameters(ShaderParametersSSAO.java:95) ~[classes/:na]
	at org.terasology.rendering.opengl.GLSLMaterial.enable(GLSLMaterial.java:105) ~[classes/:na]
	at org.terasology.rendering.opengl.GLSLMaterial.restoreStateAfterUniformsSet(GLSLMaterial.java:601) ~[classes/:na]
	at org.terasology.rendering.opengl.GLSLMaterial.setFloat3(GLSLMaterial.java:392) ~[classes/:na]
	at org.terasology.rendering.assets.material.BaseMaterial.setFloat3(BaseMaterial.java:131) ~[classes/:na]
	at org.terasology.rendering.shader.ShaderParametersSSAO.initialParameters(ShaderParametersSSAO.java:88) ~[classes/:na]
	at org.terasology.rendering.opengl.GLSLMaterial.recompile(GLSLMaterial.java:138) ~[classes/:na]
	at org.terasology.rendering.ShaderManagerLwjgl.recompileAllShaders(ShaderManagerLwjgl.java:164) ~[classes/:na]
	at org.terasology.rendering.nui.layers.mainMenu.videoSettings.VideoSettingsScreen.onClosed(VideoSettingsScreen.java:237) ~[classes/:na]
	at org.terasology.rendering.nui.internal.NUIManagerInternal.popScreen(NUIManagerInternal.java:297) ~[classes/:na]
	at org.terasology.rendering.nui.layers.mainMenu.videoSettings.VideoSettingsScreen$7.onActivated(VideoSettingsScreen.java:229) ~[classes/:na]
	at org.terasology.rendering.nui.widgets.UIButton.activate(UIButton.java:138) ~[classes/:na]
	at org.terasology.rendering.nui.widgets.UIButton.access$100(UIButton.java:40) ~[classes/:na]
	at org.terasology.rendering.nui.widgets.UIButton$1.onMouseRelease(UIButton.java:81) ~[classes/:na]
	at org.terasology.rendering.nui.internal.CanvasImpl.processMouseRelease(CanvasImpl.java:227) ~[classes/:na]
	at org.terasology.rendering.nui.internal.NUIManagerInternal.mouseButtonEvent(NUIManagerInternal.java:558) ~[classes/:na]
	at org.terasology.rendering.nui.internal.NUIManagerInternalMethodAccess.invoke(Unknown Source) ~[reflectasm-1.11.0.jar:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:497) ~[classes/:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:278) ~[classes/:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:257) ~[classes/:na]
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:157) ~[classes/:na]
	at org.terasology.input.InputSystem.sendMouseEvent(InputSystem.java:393) ~[classes/:na]
	at org.terasology.input.InputSystem.processMouseInput(InputSystem.java:248) ~[classes/:na]
	at org.terasology.input.InputSystem.update(InputSystem.java:204) ~[classes/:na]
	at org.terasology.engine.modes.StateMainMenu.handleInput(StateMainMenu.java:140) ~[classes/:na]
	at org.terasology.engine.subsystem.lwjgl.LwjglInput.postUpdate(LwjglInput.java:65) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:463) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:374) ~[classes/:na]
	at org.terasology.engine.Terasology.main(Terasology.java:152) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_31]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_31]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140) [idea_rt.jar:na]
23:44:21.421 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
java.lang.NullPointerException
	at org.terasology.rendering.shader.ShaderParametersSSAO.applyParameters(ShaderParametersSSAO.java:95)
	at org.terasology.rendering.opengl.GLSLMaterial.enable(GLSLMaterial.java:105)
	at org.terasology.rendering.opengl.GLSLMaterial.restoreStateAfterUniformsSet(GLSLMaterial.java:601)
	at org.terasology.rendering.opengl.GLSLMaterial.setFloat3(GLSLMaterial.java:392)
	at org.terasology.rendering.assets.material.BaseMaterial.setFloat3(BaseMaterial.java:131)
	at org.terasology.rendering.shader.ShaderParametersSSAO.initialParameters(ShaderParametersSSAO.java:88)
	at org.terasology.rendering.opengl.GLSLMaterial.recompile(GLSLMaterial.java:138)
	at org.terasology.rendering.ShaderManagerLwjgl.recompileAllShaders(ShaderManagerLwjgl.java:164)
	at org.terasology.rendering.nui.layers.mainMenu.videoSettings.VideoSettingsScreen.onClosed(VideoSettingsScreen.java:237)
	at org.terasology.rendering.nui.internal.NUIManagerInternal.popScreen(NUIManagerInternal.java:297)
	at org.terasology.rendering.nui.layers.mainMenu.videoSettings.VideoSettingsScreen$7.onActivated(VideoSettingsScreen.java:229)
	at org.terasology.rendering.nui.widgets.UIButton.activate(UIButton.java:138)
	at org.terasology.rendering.nui.widgets.UIButton.access$100(UIButton.java:40)
	at org.terasology.rendering.nui.widgets.UIButton$1.onMouseRelease(UIButton.java:81)
	at org.terasology.rendering.nui.internal.CanvasImpl.processMouseRelease(CanvasImpl.java:227)
	at org.terasology.rendering.nui.internal.NUIManagerInternal.mouseButtonEvent(NUIManagerInternal.java:558)
	at org.terasology.rendering.nui.internal.NUIManagerInternalMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:497)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:278)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:257)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:157)
	at org.terasology.input.InputSystem.sendMouseEvent(InputSystem.java:393)
	at org.terasology.input.InputSystem.processMouseInput(InputSystem.java:248)
	at org.terasology.input.InputSystem.update(InputSystem.java:204)
	at org.terasology.engine.modes.StateMainMenu.handleInput(StateMainMenu.java:140)
	at org.terasology.engine.subsystem.lwjgl.LwjglInput.postUpdate(LwjglInput.java:65)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:463)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:374)
	at org.terasology.engine.Terasology.main(Terasology.java:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
For more details, see the log files in C:\Dev\Terasology\Git\integrate\Terasology\logs
```

So yay, finally something to review and look at this time! Well, kinda yay. Still progress! :D

**Comment by Cervator** [comment]
On further testing the crash seems to be pre-existing - happens in current develop. You have to load a world first then exit to main menu and change. I can change fine in the main menu before the first time I create a world.

@MarcinSc also noted there's some FBO stuff in the log when you resize the game window while in-world. Stuff like this:

```
23:51:51.321 [main] WARN  o.t.r.opengl.LwjglRenderingProcess - FBO sceneShadowMap has been overwritten. Ideally it would have been deleted first.
```

**Comment by emanuele3d** [comment]
Thank you @Cervator and @MarcinSc for the reports. The issues look familiar to me: in my work branch I think I solved them but this PR only does baby steps in that direction.

Let me double check and I'll get back to you guys.

**Comment by emanuele3d** [comment]
Update: 

* The problem reported by @MarcinSc is due to the ShadowMap's FBO being erroneously refreshed every time all other FBOs are refreshed. This is incorrect because most FBOs need to be refreshed when there's a full-screen resolution change, a window size change or a screenshot is being taken, but the shadow map should change only when its size is changed via the setting. This will be addressed in later PRs: bear with me.

* The crash happening when loading a saved game, going to main menu and then loading a new game, is something that *should* get fixed in later PRs: I encountered it already and although I do not recognize the specific context this time, it looks very familiar, with one FBOs being null when it shouldn't. By extracting the PostProcessor from the current LwjglRenderingProcess class and by refactoring what's left into a [BuffersManager](https://github.com/emanuele3d/Terasology/blob/RendererChangesBKP/engine/src/main/java/org/terasology/rendering/opengl/BuffersManager.java) class this problem should disappear as the regeneration of the FBOs gets much clearer. Given that the problem is already in develop I'd recommend to wait for the next PR, in which I am slated to do the PostProcessor extraction and the BuffersManager will begin its existence. Alternatively I can do those things in here, but then this PR will become considerably more complex.

* Finally, I can confirm the problem with the black blocks and that it shouldn't have occurred. I will now proceed to take my whip and self-flagellate. Then I'll fix it, sometimes over the weekend I hope.

**Comment by emanuele3d** [comment]
P.S. if you feel like it, you might want to checkout the last commit of my [work branch](https://github.com/emanuele3d/Terasology/tree/RendererChangesBKP) to verify that those issues do not occur and that I'm heading in the right direction.

**Comment by Cervator** [comment]
Just tested the final branch - yep, looks to work fine, no black blocks :-)

If it causes any headaches to break all these changes into smaller PRs it might not be worth it over a single big one. Your documentation of individual commits is superb. I think even if there's a dozen commits instead of 3 that'll still be doable to review.

For any actual reviewers able to keep up with you at that level, that is, which can be tricky to find :-)

Faster merges might be helpful in other ways too, like not drifting too far from develop. That might be easier for me to feel with my mega-workspace, as new engine tweaks coordinate with newer module tweaks that then break when I hope into your branch and vice versa when your branch tweaks stuff that'll need updates in modules.

If you want to just try a PR from the final branch now or next that's fine by me. I'll try to dig up details on any broken modules.

**Comment by emanuele3d** [comment]
Quick note to say that our 15 months old was sick with high fever over the past four days and this resulted in dehydration that needed to be treated at the hospital with an overnight stay, last night. That's why I haven't managed to progress on this. She's now well and I should be back on track over the next few days.

**Comment by Cervator** [comment]
Eep! Sorry to hear but glad all turned out fine. RL as always comes first, especially serious stuff like that :-)

In better news: Interesting last few days! @MarcinSc added an in-game computer system real quick that can display stuff on multi-block monitors. He even included a hook / support for later sourcing of data from some sort of game camera so we can have security cameras, heh. Thought you might find that potential interesting for any future camera work :-)

**Comment by msteiger** [comment]
Any objections to merging this?

**Comment by Cervator** [comment]
Yes, it is not ready - there is a rendering quirk not present in the "final" branch, probably popped up because of cherry-picking this PR out of the bigger pile of code.

If there isn't a lot more code or not likely enough review per small PR to justify the extra effort it might be worth just considering the whole final branch and get it over with :-)

**Comment by emanuele3d** [comment]
Again, sorry for the delay. Cervator is correct and the "rendering quirk" as he kindly put it is an outright rendering bug that shouldn't have made it into a PR in the first place. I thought I tested the offending commit but I guess I didn't. 

I've eventually decided to stay the course and fix this problem rather than skip ahead to the full set of changes available in my work branch. First because I need to learn how to fix these issues. Second because develop and this branch have enough changes from my work branch and it'd be a lot of manual work anyway to recombine everything.

So, bear with me, it will get done.

**Comment by Cervator** [comment]
No rush, take your time :-)

**Comment by emanuele3d** [comment]
I stand corrected. It wasn't a rendering bug, rather a bug in the logic department of my brain.

That been said, I wish I could ask Begla why he did things the way he did.

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/63/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Me too, I wish he'd come back :-)

Tests out fine now, so I merged it - thanks as always!

**Pull request merged**
