### PR TITLE
Work on OutlineNode and AmbientOcclusionNodes

### PR DESCRIPTION
**Pull request by emanuele3d**
### Contains
- Refactored OutlineNode to take advantage of the new architecture
- Split AmbientOcclusionPassNode into AmbientOcclusionNode and BlurredAmbientOcclusionNode
- Both new nodes take advantage of the new architecture.
- Created a new SetInputTextureFromFBO state change class: now in use in BlurredAmbientOcclusionNode but couldn't make it work in ApplyDeferredLightingNode [1]
- Minor changes to the RefractiveReflectiveBlocksNode

### How to test
- Run Terasology
- Create a new game or load an existing one
- Verify there have been no changes in the way the 3d world looks

[1] this is an issue with the way the default FBOs are implemented I think. Eventually I plan to implement them differently (not enum-based) and I hope many problems will go away.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Avalancs** [comment]
Hi emanuele3d!

I checked out your branch, but when I try to load/create a world, I get the following exception:
19:49:32.079 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
```
java.lang.NullPointerException: null
	at org.terasology.rendering.dag.stateChanges.SetInputTextureFromFBO.update(SetInputTextureFromFBO.java:188)
	at org.terasology.rendering.opengl.AbstractFBOsManager.notifySubscribers(AbstractFBOsManager.java:99)
	at org.terasology.rendering.opengl.fbms.DisplayResolutionDependentFBOs.swapReadWriteBuffers(DisplayResolutionDependentFBOs.java:130)
	at org.terasology.rendering.dag.nodes.ApplyDeferredLightingNode.process(ApplyDeferredLightingNode.java:86)
	at org.terasology.rendering.dag.NodeTask.execute(NodeTask.java:30)
	at java.util.ArrayList.forEach(Unknown Source)
	at org.terasology.rendering.world.WorldRendererImpl.render(WorldRendererImpl.java:452)
	at org.terasology.engine.modes.StateIngame.render(StateIngame.java:193)
	at org.terasology.engine.subsystem.lwjgl.LwjglGraphics.postUpdate(LwjglGraphics.java:190)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:422)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:368)
	at org.terasology.engine.Terasology.main(Terasology.java:152)
```

**Comment by emanuele3d** [comment]
Good catch @Avalancs. Did you by any chance start with Ambient Occlusion disabled? I can imagine in that circumstance the task would be null. I will harden the method with a null check.

**Comment by Avalancs** [comment]
Yes! I started with the default options, and there it is disabled. Enabled it and was able to load the world.

**Comment by indianajohn** [comment]
I tried to test this tonight, and ended up getting a crash with the following stack trace.

```
22:06:29.004 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.NullPointerException: null
	at org.terasology.rendering.dag.stateChanges.SetInputTextureFromFBO.update(SetInputTextureFromFBO.java:188)
	at org.terasology.rendering.opengl.AbstractFBOsManager.notifySubscribers(AbstractFBOsManager.java:99)
	at org.terasology.rendering.opengl.fbms.DisplayResolutionDependentFBOs.swapReadWriteBuffers(DisplayResolutionDependentFBOs.java:130)
	at org.terasology.rendering.dag.nodes.ApplyDeferredLightingNode.process(ApplyDeferredLightingNode.java:86)
	at org.terasology.rendering.dag.NodeTask.execute(NodeTask.java:30)
	at org.terasology.rendering.world.WorldRendererImpl$$Lambda$267/427226423.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.terasology.rendering.world.WorldRendererImpl.render(WorldRendererImpl.java:452)
	at org.terasology.engine.modes.StateIngame.render(StateIngame.java:193)
	at org.terasology.engine.subsystem.lwjgl.LwjglGraphics.postUpdate(LwjglGraphics.java:190)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:422)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:368)
	at org.terasology.engine.Terasology.main(Terasology.java:152)
```

Any ideas what could be happening?

**Comment by emanuele3d** [comment]
@indianajohn : I'd say it is the same problem encountered by Avalancs, above. It occurs when you create a new game or load an existing one and you have Ambient Occlusion disabled. Can you please confirm you can start a game with Ambient Occlusion enabled?

In any case I fixed it in my local repository. I'm just waiting some more feedback before I push the new commit.

**Comment by indianajohn** [comment]
Sorry about that, I swear I checked this thread for updates before posting but I guess I posted in a stale window.

Anyway, I can confirm that the crash goes away with SSAO enabled. However, I have a new issue to report too.

On my main PC (Windows, GeForce GTX 1070), everything works as expected in both VR mode and regular mode.

On my Macbook Air, starting the game with the default settings + SSAO results in a the entire world being mostly dark, except for a couple particle effects and random bits of light. The crosshairs and all other UI widgets are visible. If I go into settings after launching with SSAO on and disable SSAO, everything renders as normal. This happens for me on a clean clone of your branch. Furthermore, I cloned the develop branch and tried the exact same thing, and it works with SSAO enabled; i.e. the exact same sequence of input yields no problems in any circumstance.

**Comment by emanuele3d** [comment]
@indianajohn : thank you for reproducing the error. I just pushed a new commit that addresses the problem on PC at least.

Regarding the Macbook Air, what kind of GPU does it have?

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by indianajohn** [comment]
It's an Intel HD Graphics 5000 (the Macbook is this model https://support.apple.com/kb/sp678?locale=en_US). I guess I should also clarify that it's running MacOSX El Capitan.

**Comment by indianajohn** [comment]
Anyway, after pulling your latest branch the NPE upon launch with SSAO enabled is gone, of course. Just to disentangle the test case a bit:
-The latest develop branch renders fine on my Macbook Air Late 2013 with HD Graphics 5000.
-On the same machine, this branch exhibits the behavior shown in the below screenshot:

screen shot 2016-12-16 at 9 20 42 am

**Comment by emanuele3d** [comment]
Thank you @indianajohn for letting me know. 

The HD Graphics 5000 is an integrated GPU and integrated GPUs are known to cause problems to Terasology's rendering engine. So far it appears this is due to incomplete or incorrect OpenGL implementations within their drivers rather than a problem on Terasology's side. A proof of this is that on PCs with strongly compliant, discrete GPUs the same code works. A typical advice in this context is to install the latest drivers, but even that might not solve the problem.

Unfortunately the cruel state of affair is that we do not have the resources to support GPUs that are only partially compliant. Discrete GPUs tend to be strongly compliant and we tend to develop just for those, not even taking advantage of quirks that a particular hardware might have on other in some situations. But even if the problem did lie on Terasology's side, I can only solve issues that I can reproduce on my (Windows-based) PC.

If it can be of any consolation the architectural work I'm slowly bringing forward will make it much easier to migrate everything to more modern OpenGL releases, more modern libraries (Lwjgl 3.0 and LibGDX have been discussed) and potentially even allow multiple renderers in the same distribution, for the user or the application to choose from depending on the available hardware and the actual capabilities. 

Furthermore, I will go through another one or two rounds of node-refactoring. In particular I will address a number of FBO-related issues and I will simplify the associated code. The problem your Macbook system exhibits I suspect is related to FBO management. Perhaps I will inadvertently fix it by addressing other problems currently plaguing the rendering engine.

Sorry I can't be more helpful.

**Comment by emanuele3d** [comment]
@Cervator: I don't know how much more feedback I'm going to get on this PR. I suspect it's good to go.

**Comment by Cervator** [comment]
Tested around a little bit toggling the SSAO setting, didn't note any issues.

It is a pity we're breaking *something* by reworking the code, but with SSAO being a somewhat peripheral effect (I suppose?) with the Intel HDs already likely to encounter issues I'm thinking we can survive for a while that way. I expect we'll have a fun time when finally "done" with all the DAG stuff going back over various issues to see what then can be fixed :-)

@indianajohn thanks for noting that issue, if you end up curious to dig into it further feel free, but I think it would be a somewhat low priority issue.

**Comment by emanuele3d** [comment]
@Cervator: thank you for merging this PR. Regarding the SSAO issue, it is likely that users with integrated GPUs will not want to use more expensive effects such as SSAO. But of course I'm also not happy with breaking things that previously worked. I am hopeful however that many of these issues will be resolved in the next refactoring pass, starting immediately after this one is finished.

**Comment by emanuele3d** [comment]
By the way, I will nevertheless write an issue about the problem encountered by indianajohn. At some point we'll want to verify if it still occurs.

**Comment by emanuele3d** [comment]
I have opened issue #2683 on this matter.

**Pull request merged**
