### PR TITLE
remove temporary Vector3i allocations in getBlock

### PR DESCRIPTION
**Pull request by kaen**
### Contains

Some low-hanging optimization fruit for anything that calls `getBlock` in a tight loop (pathfinders or anything that analyzes the map).

### How to test

Call `getBlock` a lot and look at a profiler :)

The most obvious change is in allocations per second. I measured 2Ma/s before the patch, about 250Ka/s after. Also notice that GC stalls are much less frequent and that Eden heap space fills much less quickly :)

I wouldn't normally worry about object allocations but obviously the numbers are huge. After this change, `getBlock` can use CPU registers all the way until it indexes the massive data array behind it. Without it, we have to stop, find some space on the heap, create some object metadata, copy the values to far-away memory, recurse, unwrap the object (again going to far-away heap memory) and then finally index the array. In short, the actually runtime of `getBlocks` is improved a lot by this. There are some other call sites with similar issues that I will address in future PRs.

YourKit performance summary before:
performance before

summary after:
performance after

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
@GooeyHub: add to whitelist

@kaen: yay! :-)

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Hey @kaen - I just merged #2456 and #2460 which relate to this kind of optimization. At least one file is changed by your stuff as well, but I don't see any conflicts highlight. Do you want to double check anything, like any sort of impact on the metrics, or should this be fine to merge? Any particular steps to test it other than maybe just check the two benchmarks again?

Let me know if you want access to TeraBullet sometime for more victorious Vector work :-)

**Comment by flo** [comment]
@Cervator @kaen the optimizations are unrelated. I merged it. Thanks for the optimization @kaen

**Comment by Cervator** [comment]
Thanks @flo :-)

**Pull request merged**
