### PR TITLE
Overhauled groovy utility

### LINKED ISSUE #3099: Further options for new Groovy-based utility commands
With #2979 merged we now have the new [Groovy Wrapper](https://github.com/MovingBlocks/groovy-wrapper) in place for making easier and more powerful utility scripts than the somewhat awkward old `gradlew fetchModuleX` approach. Now we can has `groovyw module get X` instead!

I only prepared two initial options for fetching individual modules or all modules in a dependency tree. With that example in place I expect it will be fairly easy to go beyond that to include module creation in `module.groovy` and adding new *stub* scripts for facades, libs, and meta modules (each type would live in its own script like `facade.groovy`)

Likely there will be shared functionality between the scripts that could be centralized in a single include script of some sort. So here are some tasks:

- [x] Finish the module creation part of `module.groovy` (there is just a placeholder entry in the `switch` right now)
- [x] Create `facade.groovy` and make the new versions of retrieving and creating facades (shouldn't need to worry about dependencies so recursing isn't useful there). Good example to retrieve: https://github.com/MovingBlocks/FacadeServer (`gradlew fetchFacadeServer` -> `groovyw facade get Server`)
- [x] Create `lib.groovy` and retrieval and creation there. Also no dependencies/recursing there. Good example: https://github.com/MovingBlocks/CrashReporter (`gradlew fetchLibCrashReporter` -> `groovyw lib get CrashReporter`)
- [x] Create `meta.groovy` and retrieval plus creation (just an empty dir really) for meta modules. No dependencies or recursing needed, they're just storage repos. Good example: https://github.com/MetaTerasology/WildAnimals (`gradlew fetchMetaWildAnimals` -> `groovyw meta get WildAnimals`)
- [x] Centralize any shared logic resulting from the above tasks
- [x] Add entirely new option to *update* one, a set (dependencies), or all modules with a single command (so something like `groovyw module update X`, `groovyw module updateTree X`, and `groovyw module updateAll`)
- [x] Come up with some additional suggestions? Unsure if there is any point in bulk updating facades or libs. Maybe meta modules? Seems unlikely though.

Look in `config/gradle/utility.gradle` for how the old approach worked, which files to include or create, and so on. See also #2979 for more details about how the new system works.

### PR DESCRIPTION
**Pull request by Cervator**
_Edit: No longer WIP! Although I may still tweak at it, but I am happy with the amount of restructuring and cleanup now._

Please see the individual commits to learn about the individual changes. The usage text from `groovyw usage` should ideally be able to instruct the user sufficiently to know what's available and how to test it :-)

Can use `-remote SomeRemote` to target weird repos to see how that works out. For instance I'd use `groovyw module get BrokenModule -remote Nanoware` to fetch https://github.com/Nanoware/BrokenModule which is just a default initialized repo that doesn't have a `module.txt` so the script warns the user and places a default one into the module. The same exact logic makes sure that file exist when a user is creating a module from scratch

Can also vary the `gradle.properties` at the root of a project to mess with alternative GitHub homes globally (changes the default)

## Overview

Initial restructured approach built on top of #3246 but not ready yet. Still works and has some early improvements but I'm still working on it. Pushing to GitHub in part so I can switch local workspace easily, it might be cool to see `update-all` hit 140ish modules in one go but that's not necessarily ideal for testing ... :D

I'm using frequent commits to be able to highlight the changes better. The overall diff will be about as hard to read as the related all-at-once PRs as entire files change, get moved/renamed, etc, but look at the individual commits for clean diffs of very specific changes

As of this initial state everything should roughly work as with #3246 with some bug fixes. I mostly just restructured things and cut out the duplication in the type scripts. Currently they just hold a dummy method to prove the concept, next up I aim to make the common script seek type-specific updates by calling into those scripts

Execution entry has changed to where `groovyw` itself is hard coded to target the new `util.groovy` which then enters the `functions.groovy` class where it dynamically picks the type-specific script the user indicated, or advises if that didn't work. This way new scripts can be added very easily. It may even make sense to include an interface the type scripts must implement. Gasp, could unit tests be next?!?

All script files are now in `config/groovy` with only the wrapper scripts living in the root, so that's one *less* file to add clutter than before. Later on in my pending Gradle overhaul the `config` and `templates` also get consumed and end up under `gradle` for even less clutter, but that's for another day.

## Impact

When this is complete and merged the impact:

* Closes #3099 - the current issue requesting improvements
* Closes #3246 - this PR is built directly on top of that one
* Closes #3206 - includes / supersedes those changes
* Closes #3191 - same
* Closes #3176 - same
* Closes #3189 - same
* Should lead to updates that include https://github.com/MovingBlocks/DestinationSol/pull/242 and a separate PR to update the setup for DestSol

May be of interest to @digitalripperynr @mjuvekar7 @MaxBorsch and anybody else who enjoys utilities and logistics. Just keep in mind it isn't quite complete yet!

I've tried to write this PR as a solid example of how to do PRs well, to go in line with the new page https://github.com/MovingBlocks/Terasology/wiki/How-to-Work-on-a-PR-Efficiently in the wiki - feedback for that page and how this PR (and others) could be improved in general is also welcome

## How to test

Grab the changes and do command line things that start with `groovyw` - there is usage text to help educate the user and a bunch of validation that tries to catch unexpected input! You may want to use a throwaway workspace as the commands can heavily affect what sort of stuff is present in your workspace.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by digitalripperynr** [comment]
Glad to see that this is being worked on.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Have added more commits with several more ready locally and one interesting thought came to mind: I'm ending up with a template file check that could run for *both* retrievals of existing modules (example: modules get checked for the presence of a `module.txt` and if missing gets a placeholder with a warning logged for the user) as well as creation of new things (current behavior)

This means modules, facades, _anything_ really that drifts out of alignment with current templating goals would get some potential attention when retrieved. A sort of "Hey did you know it looks like this thing is missing? Might want to look into that" sort of thing. One of the main new additions to that may be a template module readme, that could thus slowly trickle out to existing modules rather than us spam-push to every single known place needing it in one go

Of course that could also get annoying if something has a reason to violate standards. But, really, wouldn't that indicate an issue with the standard? 🤔 💭

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Happy with it for now :-) Added an edit to the top post (the stuff before "Overview")

Would appreciate some testing and feedback. May still add new functions and tweak here and there but the restructuring / overhaul / refactoring bits are done for now so that would complete this PR and the linked issues/PRs.

Aiming to merge soon if no major issues are found so we can shove this into DestSol as well, pick up the module listing from there, and then I can rebase my Gradle overhaul on top of this.

**Comment by digitalripperynr** [comment]
Are you talking about my module listing PR ?
Is that fine or needs some work ?

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
@digitalripperynr I'm going to add in https://github.com/MovingBlocks/DestinationSol/pull/242 to this batch of changes, then push all of it (well, all that makes sense) back to DestSol so both places will be at the same level :-)

**Comment by Cervator** [comment]
Okay, last new bit of functionality for this PR is in. At least I *think* I'm finally done but every time I do stuff I get more ideas ... :p

https://github.com/MovingBlocks/DestinationSol/pull/242 has been manually merged in on the Terasology side of things, then given the same overhaul to make it generic and support all 4 current types of items. So for instance you can now do:

* `groovyw module list` -> gets you the Terasology modules available in a list (but wait! Not actually all of them as we have more than the max page size for the GitHub API allows ... boo. Separate improvement issue coming)
* `groovyw lib list` -> gets you the Terasology specific libs that are considered compatible for embedding in a mega-workspace. Currently I've set that to be TeraBullet, TeraMath, and the CrashReporter by adding  "Automation category: Terasology Library" to their repo description, which is handily available in the same API results

Should be able to apply all this to DestSol as well. I figured the repo description trick was the easiest to sort out the less obvious items for libs and facades, while modules and meta modules are already sorted via GitHub org (minus an occasional exclusion or two)

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
One more thing! As the prior commit details.

A welcome observation as I tweak and change: I am getting increasingly uncomfortable doing all this without having a bunch of unit tests watching my back. I can almost feel @oniatus' heart growing by two sizes as I think and type this :-)

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by digitalripperynr** [comment]
The usage details contains an example which has wrong syntax.

groovyw list libs --> groovyw libs list

Please fix. Everything else looks fine.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Fixed example and merged, thanks all :-)

Now to clean up all the related stuff and go apply it to DestSol as well sometime yay!

**Pull request merged**
