### PR TITLE
Request game server info without actually joining

### PR DESCRIPTION
**Pull request by msteiger**
This PR adds a new feature to the JoinGameScreen: a connection is established to the selected server trying to request some information such as world time, selected modules, etc.

The largest beef was about dealing with failed connections and exceptions in a multi-threaded environment. It should all work now, though ..

### CODE REVIEW

**Comment by Cervator** [comment]
Very nice - I especially like the module highlight which makes potential issues clear:

terasology _ pre alpha_2015-03-21_13-17-35

However, actually trying to use "Add New" to add localhost or a test entry didn't get any entries added for me :( No errors in the log.

**Comment by minnesotags** [comment]
I'm not sure what that is.... I think I created that VM last December?

**Comment by Cervator** [comment]
@minnesotags That's in-game time, hehe :-)

Several game days in a RL day :D

**Comment by msteiger** [comment]
Ahh right, the list of local servers was not updated. This should be fixed now.

Iirc, one real wall-clock day equals 48 in-game days.

**Comment by Cervator** [comment]
Retested and all good! Merged

Also: First official engine build done using the new dynamic droplets, woo! Done at the same time as three other test engine builds and a good dozen modules or so :D

**Pull request merged**
