### PR TITLE
Fix non working dialogs

### PR DESCRIPTION
**Pull request by Arcnor**
### Contains

Fix for dialogs not working

### How to test

1. Open Terasology
2. Try to download a module

The download button will do nothing. Same with other actions that show certain dialogs.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by msteiger** [comment]
Thanks!

**Comment by Cervator** [comment]
Much appreciated @Arcnor :-)

Will add you to the credits shortly. Let me know if you have a forum account for a contributor badge or if you'd like to help out with other stuff!

For reference since we didn't catch this via bug report the error thrown when clicking download on a module not yet present was:

```
14:32:23.044 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.IllegalArgumentException: Urn must not be an instance urn
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at org.terasology.assets.AssetType.isLoaded(AssetType.java:569)
	at org.terasology.assets.management.AssetManager.isLoaded(AssetManager.java:63)
	at org.terasology.rendering.nui.internal.NUIManagerInternal.createScreen(NUIManagerInternal.java:258)
	at org.terasology.rendering.nui.internal.NUIManagerInternal.pushScreen(NUIManagerInternal.java:287)
	at org.terasology.rendering.nui.layers.mainMenu.SelectModulesScreen.startDownloadingNewestModulesRequiredFor(SelectModulesScreen.java:373)
	at org.terasology.rendering.nui.layers.mainMenu.SelectModulesScreen.lambda$initialise$136(SelectModulesScreen.java:334)
	at org.terasology.rendering.nui.widgets.UIButton.activate(UIButton.java:135)
	at org.terasology.rendering.nui.widgets.UIButton.access$200(UIButton.java:40)
	at org.terasology.rendering.nui.widgets.UIButton$1.onMouseRelease(UIButton.java:81)
	at org.terasology.rendering.nui.internal.CanvasImpl.processMouseRelease(CanvasImpl.java:247)
	at org.terasology.rendering.nui.internal.NUIManagerInternal.mouseButtonEvent(NUIManagerInternal.java:569)
	at org.terasology.rendering.nui.internal.NUIManagerInternalMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:279)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:258)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:145)
	at org.terasology.input.InputSystem.sendMouseEvent(InputSystem.java:503)
	at org.terasology.input.InputSystem.processMouseInput(InputSystem.java:324)
	at org.terasology.input.InputSystem.update(InputSystem.java:271)
	at org.terasology.engine.modes.StateMainMenu.handleInput(StateMainMenu.java:138)
	at org.terasology.engine.subsystem.lwjgl.LwjglInput.postUpdate(LwjglInput.java:54)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:423)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:369)
	at org.terasology.engine.Terasology.main(Terasology.java:150)
```

**Comment by Arcnor** [comment]
Thanks @msteiger and @Cervator. No, I don't have a forum account, I might create one later (I just stumbled upon this project).

**Comment by Cervator** [comment]
I hope you do, any help is appreciated! :-)

Intro forum over here if you get to it: http://forum.terasology.org/forum/contributor-introductions.7/

**Pull request merged**
