### PR TITLE
Remove obsolete ColorSummaryFacet

### PR DESCRIPTION
**Pull request by NoUserAgent**

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by msteiger** [comment]
ok to test

**Comment by msteiger** [comment]
Sending a ping to @Josharias

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/317/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Is this just deleting obsolete map preview stuff? Any impact/relation to #1917 or #1780 ?

I figure not, but it does seem like that area is slowly changing. Previewing TTA doesn't seem to crash the game anymore, although it does look it up for a while and throws an exception:

```
15:46:11.544 [main] ERROR o.t.r.n.l.m.PreviewWorldScreen - Unable to load world generator: WoodAndStone:throughoutTheAges for a 2d preview
java.lang.NullPointerException: null
	at org.terasology.rendering.nui.layers.mainMenu.preview.FacetLayerPreview.<init>(FacetLayerPreview.java:90) ~[classes/:na]
```

(that is without the code from this PR, figure I'll wait to see if @Josharias wants to look at it)

**Comment by Josharias** [comment]
@Msteiger's stuff is a much improvement over these old mechanisms.  Out with the old,  in with the new!

I havent been able to give it a good testing this weekend.  But the code changes look good to me.

**Comment by Cervator** [comment]
Works for me :-)

**Pull request merged**
