### PR TITLE
Changed all (short-lived) tasks to execute from a single thread pool.

### PR DESCRIPTION
**Pull request by prestidigitator**
* ScheduledExecutorService thread pool can be modified and retrieved through (context-reachable) TaskManager object.
* TaskMaster objects each submit a limited number of concurrent tasks to the pool.
* TaskMaster.shutdown() no longer needs a special termination task, and has extra options for waiting.
* Added "getClientThreads", "setClientThreads N", "getServerThreads", and "setServerThreads N" commands

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by msteiger** [comment]
Gooey: Test this please

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/132/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Oooh, lots of javadoc, neat :-)

I haven't seen the formatting option of putting javadoc parameter explanations on the next line before. Does that still work properly at doc generation time? I might suggest checking on the format in a few places and trying out Checkstyle if you haven't yet, it spots a lot of that sort of stuff.

Normally I'm used to seeing two flavors of javadoc blocks:

```
/**
 * Some doc
 */
```

And the short version if only one line

`/** Some doc */`

Haven't seen the termination use **/ before, usually is just one  :-)

Thanks for catching the year updates for some of the file headers, others look to be coming in at 2013 instead of 2015

Need to actually spend a bit more time reviewing and testing, but the javadoc stuck out as a great addition yet formatted a little unusual (like starting on the leading line rather than next line) so wanted to mention that real quick to start :cake: 

Maybe related: #1296 since it talks about disposal

**Comment by prestidigitator** [comment]
@Cervator - Yes, the javadoc format works fine.  I can restyle it if you like.  No big deal.  No checkstyle error in the files I touched; I'm fastidious about that.  However, what I just did find is that javadoc complains loudly now about missing "param" tags, so simple comments like:

    /** Equivalent to {@link #foo(int, int) foo(1, 2)} **/

produce bitter error-like warnings about missing tags.  Ridiculous.  Forcing documentation where it doesn't make things clearer is a terrible idea.  It usually results in a bunch of useless stuff in the codebase like:

    /** ...
      * @param p1 A parameter
      * @param p2 A parameter
      **/

**Comment by Cervator** [comment]
Yeah our checkstyle rules are not entirely done yet, we need to cover Javadoc better both for nagging more in the right spots and nagging less when it isn't valid. If you spot a way to tweak the config then go for it!

That includes new formats too, like ending with **/ or putting parameter descriptions on the next line. Happy to do that if it makes more sense, just wanting to pick one and stick with it :-)

**Comment by prestidigitator** [comment]
Huh.  Looks like it's already configured to suppress those warnings about missing parameter tags, actually.  It's running "javadoc ..." out of the box that generates the warnings.  There are no errors or warnings during either "gradle build" or "grade javadoc" related to the documented classes (TaskManager, TaskManagerImpl, plus a couple methods in TaskMaster).

**Comment by Cervator** [comment]
It might be the IDE complaining, or it isn't looking at the right Checkstyle config :-)

We haven't made Checkstyle very naggy yet when it comes to Javadoc in general, although I really think we should. But part reason we haven't is wanting to identify a reasonable level of nag, so it'll complain about places that make sense, but not get overbearing

There is also a desire to focus doc towards what'll be part of the "Official Modding API" so to say. The good useful stuff you'd want to know about for modules, but not all the fluff only core engine devs care about.

**Comment by immortius** [comment]
Please do switch to using */ rather than **/. The former is the correct style. Also I would just include all the params - any decent IDE with generate both these things for you so shouldn't be a big deal. You don't actually have to include any text after the param statements if there is no comment worth including.

Also don't compress them to a single line. Again, a decent IDE will allow you to collapse comments if you desire.

**Comment by msteiger** [comment]
About CheckStyle: The JavaDoc checks are mostly broken at the moment and need to be re-implemented first. This could take a while, I hear. So we have to be either patient or find something else.

**Comment by prestidigitator** [comment]
@immortius - Okay.  Done.

**Comment by Cervator** [comment]
Big merge is done, how are we feeling about this one from a functional perspective beyond Javadoc / Checkstyle?

@prestidigitator - able to rebase on the latest version of develop? Looks like there are conflicts now after the merge. Let me know if you're not comfortable with rebase and would like a hand, just see if the conflicts are bad or not :-)

Speaking of Git I think you need to check your email config on your local Git setup vs your GitHub account as the commits aren't being linked fully to your account (usually the case if your local Git config has an email not listed on your GitHub account)

**Comment by prestidigitator** [comment]
@Cervator - Okay.  I'll check it out.  Both the e-mail and the merge, that is.  Thanks.

**Comment by Cervator** [comment]
Bump :-)

/me waves at @prestidigitator 

@immortius @msteiger does this otherwise look good to merge?

**Comment by prestidigitator** [comment]
@Cervator - Sorry.  Started a new job recently and it's been taking about 110% of my time.  Haven't forgotten; just haven't been able to spend more than a few minutes here and there recently.

**Comment by immortius** [comment]
Has some overlap with 176ae447a35ec53bf607b32f91f3a9a8d98f272a but not a problem (the new task management code would move into the threading manager).

**Comment by Cervator** [comment]
@prestidigitator no worries, quite understandable, especially these days :-)

**Comment by msteiger** [comment]
I find the changes this PR makes quite valuable and would like to see them merged. @prestidigitator, are you still up for it?

**Comment by Cervator** [comment]
Bump! As noted over in #2073 it would be sweet to get this back on track. @prestidigitator - ping! Halp pls! :D

**Comment by Cervator** [comment]
I went ahead and made a pointer issue (#2294) to this PR so we can close it for now. I also backed up the branch in case it still takes a while.

@prestidigitator: I hope you're doing well and make it back sometime, but no rush :-)

**Pull request closed without merging**
