### PR TITLE
Increase chunkloading speed

### PR DESCRIPTION
**Pull request by DarkWeird**
### Contains

Increase chunk loading speed for client and server (not world generation).
Maximum effect should be visible on SSDs. Or in multiplayer with 6+ players who are far apart

+ Seems, fix zombie thread, that prevent close client. (maybe #3738)

### How to test

Chunks:
1. Open Terasology
2. Load  world, which chunks generated with max view distance
3. try compare chunkloading speed before and after (load world before using PR and after)

Thread:
1. Open Terasology
2. Open Mutliplayer
3. Close Terasology( you can exit  from JoinServerScreen)
4. You haven't Terasology process in Task Manager/top/htop/etc

### CODE REVIEW

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by eviltak** [comment]
Thanks for the contribution @DarkWeird! Can you elaborate on how (why) these changes improve chunk loading times?

**Comment by DarkWeird** [comment]
@eviltak 
Its simply - 
Before:
1. Chunk generated or loaded from disk: it's not ready for rendering and interact
2. Chunk puts in ChunkFinalizer(LocalChunkProvider) or LightMerger(inner of ChunkFinalizer or RemoteChunkProvider)
2.1. LightMerger uses singleThreadPool with "one slot job"(Future Variable)
3. ChunkProvider checks chunk is ready in LightMerger via Future(almost true) and mark it ready.
Its takes 1-3 ticks for one chunk.

After:
1. Some chunks generated or loaded from disk
2. All these chunks puts in LightMerger
2.1. LightMerger uses singleThreadPool with queue of jobs 
3. ChunkProvider get all ready Chunks in LightMerger and mark it ready.
It's takes 1-3 ticks for many chunks.

Its was looks like bottleneck.

**Pull request merged**
