### PR TITLE
Removing biomes, to be moved to module

### PR DESCRIPTION
**Pull request by Adrijaned**
Works now; just protobuf needs to be recompiled

### CODE REVIEW

**Comment by Adrijaned** [comment]
Fixes #3567

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by jellysnake** [comment]
On the topic of Core needing to depend on this, A similar situation existing with my (languishing) Inventory PR #3419.
A solution proposed and partially hashed out was to switch to having a set of core modules, that can constitute similar to Core does at the moment. Biomes and Inventory would be good fits for this at present.

Alternatively we can instead look at making the core dependency on Biomes/Inventory/Others optional but that may require more work than it's worth given how they'd likely be enabled 9 times out of 10.

There was some write ups on this topic but we'll have to wait for Loremaster Cervator to share them (seeing as I've no idea where they were)

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by Adrijaned** [comment]
This should be nearly finished. Only the rendering bug remains, and the fact that 75e4b91 somehow broke movement...

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by Adrijaned** [comment]
Movement is no longer broken; just the rendering bug remains and this should be up for review!

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by Adrijaned** [comment]
Not sure if I didn't actually break something. Someone (on windows, presumably) still has to recompile the proto files (I couldn't get `protoc` to work)

**Comment by jellysnake** [comment]
I can't easily find the module in question so if you've made a repo for it then link it here. And if you haven't you might as well go ahead and make one.
That's the reason the build keeps failing, similar to the issue with the inventory pull.


Other than that, how did biomes end up breaking rendering? Where do they intersect that much?

**Comment by Adrijaned** [comment]
The module is in this PR? (it was added to the engine repo for now)

**Comment by Adrijaned** [comment]
Regarding the biomes and rendering - I believe there was a special case for grassBlocks somewhere in rendering code that was offseting the color a tiny bit based on humidity and the other two fields in the od biome - I might have messed up that a bit while removing the biomes, Only the rendering of grass is not working as expected, and only the _sides_ of grass are broken now, the green rendering as white.

**Comment by Adrijaned** [comment]
Thanks to an invaluable input from @vampcat, rendering now works correctly

**Comment by jellysnake** [comment]
Is this ready to be tested out and then ideally merged now? Or is there still some outstanding known tweaks/bugs to be made.

**Comment by Adrijaned** [comment]
This should be ready to review&merge, nothing outstanding I know about

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Pull request merged**
