### PR TITLE
Add animated water and grass options, remove environment effects option

### LINKED ISSUE #1144: Additional graphic options in GUI
Need to add MOAR OPTIONS! In-game in the video settings. Some might go in the advanced section but really they just need to get crammed in there somewhere already. Putting config.cfg entry in ( ) if I happened to notice

- [x] Bloom (bloom)
- [x] Remove environment effects in favor of split-out animated grass/water
- [x] Animated grass (animateGrass)
- [x] Animated water (animateWater) - wavy sea / water blocks essentially
- [x] Particle effects (particleEffectLimit) - slider value, 0 disables, 10 default
- [x] Disable fog (the one at the limit of the players view range - might not be an option yet)
- [ ] Disable "tunnel vision" (the corners being darkened - also may not be an option yet)
- [ ] Add option to water reflection to not even reflect the sky (as currently on any level other than sea level). Maybe slightly related to #1371. And/or change refraction quality
- [x] Volumetric fog (may not actually work but anyway)

Any other obvious ones? There are a few more in config.cfg I'm not sure if we want in the main graphic settings or not (some are good candidates for the advanced screen, certainly). There are probably also some options we don't even have in config.cfg yet that would be useful to have toggles for.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/2758307-additional-graphic-options-in-gui?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by tdgunes**
### Contains

Partially fixes #1144

### How to test

Additions can be seen in video settings menu.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
ok to test

Thanks @tdgunes ! :-)

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/446/
Hooray Jenkins reported success with all tests good!

**Comment by tdgunes** [comment]
@Cervator, trying to get familiar with the code, will continue to add more :-)

**Comment by Cervator** [comment]
Tested out and merged! Bring on more fixes any time :-)

**Pull request merged**
