### PR TITLE
Switch to TeraMath's Vector2i implementation - Part 1

### PR DESCRIPTION
**Pull request by msteiger**
Use `geom.Vector2i` in NUI and input-related code.
* Requires a trivial change in [Journal](https://github.com/Terasology/Journal).

Ping @Cervator asking for other compiler errors in other modules.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/203/

**Build Log**
*last 5 lines*

 ```
[...truncated 95 lines...]
	at hudson.model.Executor.run(Executor.java:240)
[ANALYSIS-COLLECTOR] Skipping publisher since build result is FAILURE
Notifying upstream projects of job completion
Setting status of 16cb06ee113b914647521c3d495626e87775ac95 to FAILURE with url http://jenkins.terasology.org/job/TerasologyPRs/203/ and message: Merged build finished.
```

Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/204/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Will try to check out when I get home :-)

**Comment by Cervator** [comment]
Broken module report:

- [ ] Durability
- [ ] Fluid
- [ ] IRLCorp
- [ ] Journal (as noted)
- [ ] Machines
- [ ] ManualLabor
- [ ] MasterOfOreon
- [ ] Minimap
- [ ] ModularComputers
- [ ] Pathfinding
- [ ] WoodAndStone
- [ ] Workstation

That should be most of them. There may be one or two more as I started getting indirect compilation failures when a dependency failed from the Vector2i change, and was unavailable for something else.

Yeah we totally need the PR --> Test all modules against it trick in Jenkins :-)

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/210/
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/211/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Bump - I see more commits. More changes or something to help modules not break via deprecations so we can fix modules are our leisure? Which is probably actually a good idea when able (to avoid PRs paired with big module PR sets)

Any other reviewers? @immortius @flo ?

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/215/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
@msteiger if you run out of time for fixing modules before your trip I can probably sort out the rest with the module PRs you've already gone through. Just let me know - I figure that's the only thing left before merging this :-)

**Comment by msteiger** [comment]
That would be great, yes. I hate to leave things behind unfinished. Thank you!

Pathfinding seems to have a few other compiler errors.

**Comment by Cervator** [comment]
Okies, no worries, we should be able to sort them out!

**Comment by Cervator** [comment]
Tests out fine in Core, started trying to pull module PRs, and GitHub started having issues :-)

Sleepy time soon will try again tomorrow

**Comment by Cervator** [comment]
Finished the remaining modules :-)

Didn't realize at first there were still some usages of the old classes in some places, nearly started fixing some of those before realizing those run into issues needing more "real" work. I guess that's what the deprecation is all about :D Will get fixed over time I figure.

**Pull request merged**
