### PR TITLE
Allow modification of jump speed using events

### PR DESCRIPTION
**Pull request by Josharias**
### Contains

An event that allows modifying the character's jump speed based off some other factors.  This could be used for things like:
1. Training a jumping skill (this is what I personally plan on doing)
2. Wearing springy boots
3. Drinking a super jumping potion

### How to test

This change should not affect current jumping behavior but allow extension.  After this is merged,  I have a jumping skill that will be added to ManualLaborEventualSkills.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by msteiger** [comment]
Looks good to me. It took me some time to understand what's going on. Maybe "speed" could be "force" and "get" could be "alter" or "adjust"? The class name would then be `AlterJumpForceEvent` - does that make sense?

**Comment by Cervator** [comment]
Yeah the name throws me off a bit, especially the `Get` part. Either "alter" or "adjust" sound better to me as well. Maybe `AffectJumpForceEvent` ? Which can be modified by `Effect` type interactions.

Alter does goes well with AlterationEffects the module though. Which come to think of it has both interesting words.

This is a great example of how to code something the event-based way. I brought up #2158 as related on Slack as we really need to develop and emphasize some good practices in this area :-)

Also:

jumpgood

**Comment by Cervator** [comment]
As for the subtly different feel in English (not that I'm a native speaker) 

* `Alter` suggests to me something like "This is totally getting changed somehow" 
* `Affect` instead is more vague, sort of a "this *may* get changed"

That may be completely subjective/arbitrary/wrong on my account though.

**Comment by msteiger** [comment]
Both sound good to me.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Josharias** [comment]
Better event naming complete.

**Comment by xrtariq2594** [comment]
This sounds like a great idea! Personally, more events to hook into and modify with other modules will open up the game more in terms of possibilities. This will also be useful for adding a JumpHeightPotion or JumpSpeedPotion into WaS.

**Comment by Cervator** [comment]
Tested out, much jumping was performed!

@Josharias & @xrtariq2594 start your implementation engines!

**Pull request merged**
