### PR TITLE
docs update: gradlew requires ./ to run

### PR DESCRIPTION
**Pull request by freyley**
### Contains

When attempting to run the directions in the README, I found that gradlew is a script in the repo, not a command that I should expect to find on my system, so I'm adding ./ to the doc to describe how to run it.

### How to test

Clone the repo and follow the instructions in the README.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by rzats** [comment]
Hi @freyley and thanks for the patch!

`gradlew game` is actually the correct way to launch the gradle wrapper on Windows - it runs the [gradlew.bat](https://github.com/MovingBlocks/Terasology/blob/develop/gradlew.bat) batch file instead of the *nix-specific [gradlew](https://github.com/MovingBlocks/Terasology/blob/develop/gradlew) shell script ([source](https://docs.gradle.org/current/userguide/gradle_wrapper.html#using_wrapper_scripts)). Can you mention this in the README?

**Comment by freyley** [comment]
Ah ha! That makes sense. I've updated it.

**Comment by rzats** [comment]
That sounds better 🙂 Merged and adding you to the credits in a minute!

**Pull request merged**
