### PR TITLE
UI tweaks for world preview / configure - Fixes #1873

### LINKED ISSUE #1873: UI tweaks for world preview / configure
Back when world configuration and preview were merged into one option we lost a couple bits of usability:

* It isn't at all obvious there are any configurable options hiding behind the "Preview" button so it should probably be relabeled somehow
* The preview is generated on clicking "Preview" which can take a while, especially if you're just wanting to tweak config. Probably the preview shouldn't generate until the player actually clicks the "Recompute" button on the preview screen (which then probably should also be relabeled a bit)

Should be a fairly easy fix I'd like to think :-)

May be relevant to @msteiger's interests

### PR DESCRIPTION
**Pull request by Limeth**

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by msteiger** [comment]
Test this please

**Comment by msteiger** [comment]
test this please

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/217/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Thanks for this!

After earlier bits of discussion on IRC I'm thinking "Details" might work well on the first button, as it can lead both into configuration and preview. If that sounds reasonable I can apply that tweak on top when merging after work sometime :-)

**Comment by msteiger** [comment]
There a few code style issues with that commit. Would you mind running CheckStyle or activating the CheckStyle plugin so you can eliminate them?

http://jenkins.terasology.org/job/TerasologyPRs/217/checkstyleResult/new/

**Comment by Cervator** [comment]
Some more Checkstyle info: https://github.com/MovingBlocks/Terasology/wiki/Checkstyle

I sometimes run Checkstyle on individual classes in IntelliJ if I touch them and fix up any additional issues in the class even if I didn't cause them. If the class is getting modified anyway might as well! :-)

**Comment by Cervator** [comment]
add to whitelist

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/218/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Merged, thanks :-)

There is one small indirect issue with this, in that previously some of the stuff was inside a try-catch block for plain Exception and I think that may have caught some quirks. Preview on a TTA world crashes now on attempting the preview - however, it crashed before too, just on going back to the main menu from the broken preview ;-)

I think that's part of a bigger issue with hardening world generation and previewing (@msteiger and @flo have talked about that recently). So I figure that can be kept separate and this merged anyway. I think the usability improvement is worth it.

**Pull request merged**
