### PR TITLE
Added gradle FlightRecorder profiling task

### PR DESCRIPTION
**Pull request by PAndaContron**
This PR adds a gradle task for FlightRecorder profiling.

### Contains

This PR adds a `profile` task to gradle. It is equivalent to the IntelliJ IDEA configuration added by #3475. Running it generates a `terasology.jfr` file in the root project directory which can be opened with Java Mission Control and reviewed for performance enhancement. This is mainly for people who don't use IntelliJ (like me).

### How to test

Run `gradlew jar profile` to start the game with the profiler. Once the game is finished, the `terasology.jfr` file will be created in the root project directory and can be opened with Mission Control to make sure everything is working properly.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
@GooeyHub: add to whitelist

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Tests out, was able to look at some profiling data - neat! Also adding you to the game credits already :-)

**Pull request merged**
