### PR TITLE
Issue #3629

### LINKED ISSUE #3629: Allow UI text to be specified in an array
Presently, multiline text has to be written in ui files on a single line, potentially resulting in absurdly long lines. The common work around to this is to specify text as an array of strings to be joined by newlines. This should be implemented for UIText, and potentially other widgets.

### PR DESCRIPTION
**Pull request by AahzBrut**
### Contains
Fixes #3629 
Allow UI text to be specified in an array

### How to test

Change string to array of strings in some of the *.lang files (menu_en.lang for example).
Launch the game, if there is no stack traces in log and corresponding string shows ok - it works.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
Tested out locally and merged - thanks! Also added you to the credits already :-)

**Comment by eviltak** [comment]
I'm reverting #3689 and #3678 since this solves #3629 in a much better way.

**Comment by skaldarnar** [comment]
@eviltak Are we sure the newline characters and other issues that lead to weird behavior (see https://github.com/MovingBlocks/Terasology/issues/3688) are fully covered, and that we don't run into them that easily?

**Comment by eviltak** [comment]
Yes! The issues were caused because of the changes made to UIText in those PRs. This PR, however, doesn't change anything in UIText; it simply allows strings specified in a translation resource to be deserialized as multiline string arrays.

**Pull request merged**
