### PR TITLE
Loop main menu background music

### PR DESCRIPTION
**Pull request by arpan98**
### Contains

Fix for #2527 
### How to test
- Open game
- Wait for music to stop 
- Wait for more than 3 minutes 29 seconds (Duration of Menu Theme Song)

### CODE REVIEW

**Comment by Cervator** [comment]
So this one kinda works! But a little too well :D

The `endListener` is a little *too* thorough. It replays the main menu music *every* time it ends, including when it *should* end.  For instance it starts playing again when the player enters a game (where there is either no music or the main game soundtrack may be enabled to play)

Probably it could have a little check added to make sure the player is actually still in the main menu. That might be enough of a fix.

On a related note of interest (no action needed here from you @arpan98 - just notes in general): This sort of side-steps #2364 since the abrupt stop now with this PR results in the music immediately replaying again. Yet the underlying issue there still exists, it just gets hidden by this. 

We need to remember that when trying to fix the other issue, which would likely involve music not being affected unless whatever context it cares about changes. Context changes several times in the main menu (loading modules, previewing a world, starting to load a game). Something like module availability cares about that (the preview screen needs to have the enabled modules available) so that context would change, but it shouldn't interfere with the menu music.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by arpan98** [comment]
Is there a better solution or could just a boolean to signify the end of music work?

**Comment by arpan98** [comment]
I added a boolean to keep track of whether the music needs to be stopped or not. Also lambdified the `endListener` as suggested by @rzats.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Can confirm it works properly now :-)

This PR has the advantage of working around the context swap, while #2545 (we ended up with two PRs for the same issue) adds the looping into the audio manager (but a bit too much so). Both have good parts, maybe they could be spliced together somehow.

For reference here is good logging for this PR being tested, playing Heroes exactly once:

```
03:00:08.174 [main] INFO  o.t.musicdirector.MusicDirectorImpl - Enqueued Heroes
03:00:08.178 [main] INFO  o.t.musicdirector.MusicDirectorImpl - Starting to play 'Heroes'
...
03:02:14.151 [main] INFO  o.t.musicdirector.MusicDirectorImpl - Enqueued Snowflakes
03:02:14.152 [main] INFO  o.t.musicdirector.MusicDirectorImpl - Removed Heroes
03:02:14.152 [main] INFO  o.t.musicdirector.MusicDirectorImpl - Enqueued Heaven
...
03:03:23.716 [main] INFO  o.t.musicdirector.MusicDirectorImpl - Song 'Heroes' ended
03:03:23.721 [main] INFO  o.t.musicdirector.MusicDirectorImpl - Starting to play 'Snowflakes'
```

**Comment by msteiger** [comment]
I suggest integrating the looping functionality into the AudioManager, as suggested in #2545

**Comment by flo** [comment]
@msteiger Do you mind if we merge this PR? Even if not perfect I think it is a solution that could work for now till someone does it a better way.

**Comment by msteiger** [comment]
Apologies for the late reply. How about merging #2545 instead? [The conflict](https://github.com/MovingBlocks/Terasology/pull/2545/conflicts) seems to be a small issue.

I can have a look if the original author is no longer available.

**Comment by arpan98** [comment]
Sorry for the long delay. What's the status on this? Does this need any changes?

**Comment by Cervator** [comment]
I think we need to retest this one and #2545 again, that one also just got re-awakened and has new commits. Ideally we'd grab the best from both PRs. Maybe you can look at the code there and advise on whether some of it could be merged together? Other PR needs a rebase at least, it has ended up with a bunch of "noise" in its history.

**Comment by arpan98** [comment]
This PR is a workaround for this specific case. #2545 seems more complete as it integrates the looping functionality into the AudioManager and only seems to need a few style fixes.

**Comment by Cervator** [comment]
Closing as finished by #2945 - thanks again @arpan98 :-)

**Pull request closed without merging**
