### PR TITLE
test: Move ModuleTestingEnvironment to engine-tests

### PR DESCRIPTION
**Pull request by keturn**
for https://github.com/MovingBlocks/Terasology/issues/4545
and https://github.com/Terasology/ModuleTestingEnvironment/issues/39

from ModuleTestingEnvironment commit adf9b6df0407a62c15092a82960d8711e28bb7b7

### Module Changes

No module changes are required at this time. The old ModuleTestingEnvironment code is still there and will keep doing what it does.

But as we make changes to better integrate that code with the other code in engine-tests, we're likely to make some API change somewhere so old MTE won't work with new engines past that point.

Migrating module tests _should_ be straightforward: change your import paths to the ones based in `org.terasology.engine.integrationenvironment`, and you even get to delete ModuleTestingEnvironment from your module.txt dependencies.

I have pushed `test/moveMTE` branches to some modules with these changes already.

### For Reviewers

The new files added under engine-tests/src/main/org/terasology/engine/integrationenvironment are almost direct copies of the https://github.com/Terasology/ModuleTestingEnvironment sources. I changed a few package paths and names here and there, but the logic is untouched; I recommend you treat them as old code and don't feel like you need to audit all 2600 lines.

There are a few _changed_ files in engine. Most of those are various null checks for things I bumped in to while testing this out. Most of those could go in to a separate PR if you wanted them to, but I think they're small enough that I don't expect that to be what makes or breaks whether this PR gets reviewed.

The most significant engine change is the one to core.TerasologyEngine, detailed in [this post from the 9th](https://github.com/MovingBlocks/Terasology/pull/5010#issuecomment-1121932609) and the one following it.

### How to test

Run engine tests (`unitTest` and `integrationTest`), run your module tests.

You could run the game just for funsies but since this is almost entirely changes in engine-tests, there shouldn't be any differences there. Unless I got one of the null checks _backwards._

### Outstanding before merging

- [x] #5013
- [x] #5014

### CODE REVIEW

**Comment by keturn** [comment]
[discord thread: #Architecture/integration tests](https://discord.com/channels/270264625419911192/973296224289566749/973298134870524004)

**Comment by keturn** [comment]
## The Bug

**Bug:** The world generators in `engine-tests/src/main/org/terasology/unittest/worlds/` were registered as `engine:stub`,
not `unittest:stub`.

_But only under MTE._ There is [another test][WorldGeneratorManagerTest] that shows it as `unittest:stub` as expected.

[WorldGeneratorManagerTest]: https://github.com/MovingBlocks/Terasology/blob/685a895a3e67cc72309ca7d57cf0a90c018ef212/engine-tests/src/test/java/org/terasology/engine/world/generator/internal/WorldGeneratorManagerTest.java#L31-L34

## The Cause

### Part I: The Engine Module

When we were straightening out the upgrade to gestalt v7, we had to revise the idea of the **engine module**:
the set of classes and resources that are not in their own gestalt Module,
but that need to be registered with _something_ in the ModuleEnvironment so they can be properly addressed.
Without it, gestalt-asset can't load assets from them, and gestalt-module cannot categorize their Components.

One of the factors was TeraNUI. 
Terasology had recently switched to using the independently packaged version of TeraNUI.
It is not distributed as a gestalt module, but it defines asset types
and has other classes that must be part of the API accessible to a Terasology ModuleEnvironment.

So I cobbled together this function [ModuleManager::loadAndConfigureEngineModule][engineModuleFunc],
which rougly defines the contents of the "engine module" as being things in the `org.terasology.engine` java package namespace,
and also anything loaded alongside a certain set of other classes.

```java
// the normal Package Module inclusion test
packageModule.getClassPredicate().test(clazz)
// OR anything loaded from the same classpath entry as that other stuff!
|| config.getUrls().contains(ClasspathHelper.forClass(clazz))
```

[engineModuleFunc]: https://github.com/MovingBlocks/Terasology/blob/685a895a3e67cc72309ca7d57cf0a90c018ef212/engine/src/main/java/org/terasology/engine/core/module/ModuleManager.java#L180-L224

We had also been working on splitting subsystems out from the Engine, 
and that "list of other classes" [grew][addSubsystems] to include all of the Engine's active subsystems:

```java
 // add all subsystems as engine module parts. (needed for ECS classes loaded from external subsystems)
 allSubsystems.stream().map(Object::getClass).forEach(this::addToClassesOnClasspathsToAddToEngine);
```

[addSubsystems]: https://github.com/MovingBlocks/Terasology/pull/4274 


### Part II: The Unittest Module

You can't write tests for a module system without letting your tests define at least a few things _outside_ the engine module.

We put those things in a [`org.terasology.unittest`][unittestPackage] package,
but didn't seperate it out any more than that.
We still wanted to be able to access those classes from our test cases—
the JUnit test runner [doesn't allow][junit201] for loading test cases inside of another ClassLoader like gestalt-module's,
which means they've still got to be on the classpath—
so it didn't seem worth the bother.

[unittestPackage]: https://github.com/MovingBlocks/Terasology/tree/v5.2.0/engine-tests/src/main/java/org/terasology/unittest
[junit201]: https://github.com/junit-team/junit5/issues/201

Despite that being neither in the engine module nor anywhere else you'd look for a module by default,
some ambitious auto-discovery code would find those classes and then [throw a fit][terasology4757]
about not being able to associate them with a module.

I figured the way to handle that would be for `engine-tests` to use some extension point to define its `unittest` module.
It had to be something that ran late enough to access the ModuleManager but _before_ that cranky auto-discovery code.
What did I find I could run at that time? [Subsystem initialization code][terasology4796]!

[terasology4757]: https://github.com/MovingBlocks/Terasology/issues/4757
[terasology4796]: https://github.com/MovingBlocks/Terasology/pull/4796


### Okay, Until It Wasn't

Somehow that worked okay for a while.
The tests that cared about which module the `org.terasology.unittest` classes got assigned to didn't run with that subsystem,
and the tests that ran with that subsystem were content as long as all the discovered classes were assigned to _something._

That lasted until I tried to [move the ModuleTestingEnvironment classes][terasology5010] from the module where they had been
in to `engine-tests`. The setup for those tests does use the `WithUnittestModule` subsystem,
and they do expect to be able to reference their WorldGenerator classes by a name that's _not_ in the engine module.

When those tests run, `WithUnittestModule` is loaded from the build output of the `engine-tests` project.

The `org.terasology.unittest` classes are _also_ loaded from the build output of the `engine-tests` project.

Suddenly we have a situation where our Frankenstein engine module looks at those classes and says
"hey, those come from the same place as a subsystem, they must be mine!"

The `unittest` module _registered_ by the WithUnittestModule subsystem would claim them too,
but the engine module is at the root of the dependency tree so it gets first dibs.

[terasology5010]: https://github.com/MovingBlocks/Terasology/pull/5010

**Comment by keturn** [comment]
## Proposed Fix

Fix: Do not add all EngineSubsystem class paths to the engine-module.

Because I don't want to get sidetracked by reorganizing DiscordRPCSubsystem, I've named it as a special case: https://github.com/MovingBlocks/Terasology/blob/1176bb13ecde2016090bd7d99fafdd2e19466a7b/engine/src/main/java/org/terasology/engine/core/TerasologyEngine.java#L108-L115

### Alternate Proposals

* Move DiscordRPCSubsystem out of `/subsystems` and back in to `/engine`, if it's sure it wants to be in the engine module.
* Move `org.terasology.unittest` out of `/engine-tests` to a new gradle subproject.
  This is not a bad idea (as long as you're not allergic to Yet Another Subproject). But it only fixes things for the `unittest` module. In comparison, reducing the number of ways to automatically trigger changes to the engine module makes things more stable for _all_ additions to modules and subsystems.

**Comment by keturn** [comment]
This PR is down to [one failing test on CI](https://jenkins.terasology.io/teraorg/job/Terasology/job/engine/job/PR-5010/7/testReport/org.terasology.engine.integrationenvironment/ChunkRegionFutureTest/Integration_Tests___createChunkRegionFuture_EntityManager__RelevanceSystem__MainLoop_/), where it seems to be failing _consistently._

I've tried a [number of things](https://discord.com/channels/270264625419911192/973296224289566749/973777038387331182) to reproduce locally, and I've been entirely successful—that is, It Works On My Machine every time.

Help on getting a reproduction environment would be much appreciated.

**Comment by keturn** [comment]
After some experimentation, I think #5013 and #5014 will improve things enough for these tests to pass.

**Comment by keturn** [comment]
[Move MTE classes to engine-tests](https://trello.com/c/3GcIjRP4/221-move-mte-classes-to-engine-tests)

**Comment by keturn** [comment]
Description updated with notes for reviewers.

My confidence has been a little shaken in this, but now that its tests are passing on CI, I think we should move ahead with it.

**Comment by keturn** [comment]
I think I found out what had been breaking things for some modules!

One was an extra comma: https://github.com/MovingBlocks/gestalt/issues/133

And the other was the module under test being in a weird state because it had been picked up from the classpath but its module.txt was not read for other reasons: [MovingBlocks/Terasology@`3cf39f5`](https://github.com/MovingBlocks/Terasology/pull/5010/commits/3cf39f5120da933a26aa7bac24fe85a88eb0883d)

I've pushed `test/moveMTE` branches for more modules now.

**Review by skaldarnar — APPROVED** [review]

**Comment by skaldarnar** [comment]
In the current setup MTE is separate from ˋengine-testsˋ and an explicit dependency of modules.

image

After this PR, MTE is a part of ˋengine-testsˋ and becomes an *implicit* dependency for every module.

image

**Comment by keturn** [comment]
> an _implicit_ dependency for every module

Implicit in the sense that it does not appear in `module.txt`, correct.

More specifically, `engine-tests` is a _test_ dependency when building a module, as declared here: https://github.com/MovingBlocks/Terasology/blob/650866742d828bfeff1283eda6072859f0776ca9/build-logic/src/main/kotlin/terasology-module.gradle.kts#L53-L55

**Comment by keturn** [comment]
One more detail on that: Most of what was in MTE wasn't really usable from module runtime (as Terasology/ModuleTestingEnvironment#39 pointed out); it didn't provide any assets or components that had a URI you could look up in a ModuleEnvironment.

There are a few exceptions, the most commonl of which are the WorldGenerators used in test scenarios. Those got moved to a module named `unittest` with sources in `engine-tests/src/main/org/terasology/unittest`.

For example: If you had a reference to one of those such as
```java
@UseWorldGenerator("ModuleTestingEnvironment:dummy")
```

it is now
```java
@UseWorldGenerator("unittest:dummy")
```

**Comment by keturn** [comment]
That does mean the `unittest` module has to be in the ModuleEnvironment your test runs in. The environment `@MTEExtension` constructs for you does add that implicitly, so you don't need to add `"unittest"` to your test suite's `@Dependencies`.

https://github.com/MovingBlocks/Terasology/blob/4a301c32359dcb87aacb0fe9994effcbf4cfc363/engine-tests/src/main/java/org/terasology/engine/integrationenvironment/TestingStateHeadlessSetup.java#L45-L46

**Pull request merged**
