### PR TITLE
Added a label for filter.

### PR DESCRIPTION
**Pull request by genuinelucifer**
Just adds a label for filter in select modules screen next to modules search box.
.
.
Got some free time so added it.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/497/
Hooray Jenkins reported success with all tests good!

**Comment by skaldarnar** [comment]
Thanks for the label! 

Rather unrelated: The module warning label text is quite long. If the game window is not wide enough the warning label wraps lines and flows into/under the modules box.

**Comment by Cervator** [comment]
> Rather unrelated: The module warning label text is quite long. If the game window is not wide enough the warning label wraps lines and flows into/under the modules box. 

Maybe we should split the label into two lines and/or give it its own little mini frame of sorts? The text can be just a little bit hard to read in spots.

**Comment by genuinelucifer** [comment]
@skaldarnar @Cervator Any suggestion(s) on how to implement a mini frame with self scrolling? My exams are over so I have lots of free time now. I would like to fix this issue completely.

**Comment by Cervator** [comment]
@genuinelucifer I would check on IRC on occasion, sometimes can be easier to find the right person there :-) Just try a few times if needed

**Pull request merged**
