### PR TITLE
Fix #2087 by not generating block entities again as they also get loa…

### LINKED ISSUE #2087: Extra entity events when loading game
Here is a sample output from my test game (with extra info added by system to expose the issue):
```
22:31:20.685 [main] INFO  o.t.e.m.l.InitialiseWorld - World seed: "hkNG4i9RrZnxArmtteZvybL2IDEOoHsD"
22:31:21.650 [main] ERROR o.t.n.e.s.EntityTransportAuthoritySystem - Activated component for block: (3, 41, 0)
22:31:21.679 [main] ERROR o.t.n.e.s.EntityTransportAuthoritySystem - Activated component for block: (4, 41, 0)
22:31:21.768 [main] WARN  o.t.l.nameTags.NameTagClientSystem - Can't create player based name tag for character as owner has no client component
22:31:21.770 [main] INFO  o.t.r.world.RenderableWorldImpl - New Viewing Distance: Moderate
22:31:21.777 [main] ERROR o.t.n.e.s.EntityTransportAuthoritySystem - Deactivated component for block: (3, 41, 0)
22:31:21.799 [main] ERROR o.t.n.e.s.EntityTransportAuthoritySystem - Activated component for block: (3, 41, 0)
22:31:21.801 [main] ERROR o.t.n.e.s.EntityTransportAuthoritySystem - Deactivated component for block: (4, 41, 0)
22:31:21.802 [main] ERROR o.t.n.e.s.EntityTransportAuthoritySystem - Activated component for block: (4, 41, 0)
```

The first two events are correct, however the remaining two are just waste of CPU.

Sometimes however it gets even worse. After the initial correct series of "activate", the additional deactivate+activate are issued in incorrect order (activate then deactivate), like here:
```
22:49:52.312 [main] ERROR o.t.n.e.s.EntityTransportAuthoritySystem - Activated component for block: (4, 41, 0)
22:49:52.399 [main] ERROR o.t.n.e.s.EntityTransportAuthoritySystem - Activated component for block: (5, 41, 0)
22:49:52.452 [main] ERROR o.t.n.e.s.EntityTransportAuthoritySystem - Activated component for block: (4, 41, 0)
22:49:52.464 [main] ERROR o.t.n.e.s.EntityTransportAuthoritySystem - Deactivated component for block: (4, 41, 0)
22:49:58.432 [main] ERROR o.t.n.e.s.EntityTransportAuthoritySystem - Activated component for block: (5, 41, 0)
22:49:58.435 [main] ERROR o.t.n.e.s.EntityTransportAuthoritySystem - Deactivated component for block: (5, 41, 0)
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29376782-extra-entity-events-when-loading-game?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by flo**
### Contains

Fix #2087 by not generating block entities again as they also get loaded from the save game.

### How to test

Please test loading of modules with active blocks like chests.

@MarcinSc  please test if this fix your issue and check if your active blocks work properly

@Cervator please test a few module for side effects

@immortius since this patch bluntly removes code, I would like to have your review.

Techinical steps to reproduce the bug and verify later on that it is fixed:

1. Create a system that listens for the activation of a custom component with @ForceBlockActive :
```
@ForceBlockActive
public class ActivationTestComponent implements Component {
}

@RegisterSystem(RegisterMode.AUTHORITY)
public class ActivationTestSystem extends BaseComponentSystem {

    private static final Logger logger = LoggerFactory.getLogger(ActivationTestSystem.class);


    @ReceiveEvent(components = {ActivationTestComponent.class})
    public void onTestComponentActivation(OnActivatedComponent event, EntityRef entity) {
        if (entity.hasComponent(BlockTypeComponent.class)) {
            logger.info("activated block type");
        } else {
            logger.info("activated entity");
        }
    }

    @ReceiveEvent(components = {ActivationTestComponent.class})
    public void onTestComponentDeactivation(BeforeDeactivateComponent event, EntityRef entity) {
        if (entity.hasComponent(BlockTypeComponent.class)) {
            logger.info("block block type");
        } else {
            logger.info("deactivated block type");
        }
    }
}
```
2. Add the component to a block prefab like chest.prefab
3. Start a game and get a instance of the block. e.g. "giveItem chest"
4. Place the block
5. quit (and thus save)
6. load the game and check look out for the line "activated entity". It should be there only once.

### Outstanding before merging

If anything. You can use neat checkboxes! Feel free to delete if not needed

- [x] Testing
- [ ] Review by Immortius

### CODE REVIEW

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/518/
Hooray Jenkins reported success with all tests good!

**Comment by flo** [comment]
Seems to also fix #1766 please test that also @MarcinSc 

Tested with slightly modified code of above scenario:
```
    @In
    private WorldProvider worldProvider;

    @ReceiveEvent(components = {ActivationTestComponent.class})
    public void onTestComponentActivation(OnActivatedComponent event, EntityRef entity) {

        if (entity.hasComponent(BlockTypeComponent.class)) {
            logger.info("activated block type");
        } else {
            logger.info("activated entity");
            LocationComponent locationC = entity.getComponent(LocationComponent.class);
            if (locationC != null) {
                Vector3f pos = locationC.getWorldPosition();
                logger.info("at" + pos.toString() + " is " + worldProvider.getBlock(pos));
            }
        }
    }

```

**Comment by Cervator** [comment]
I wonder if it would have an effect on  #2170? Seems mildly related.

Cool fix, I can check some modules a little later. Hoping @MarcinSc and @immortius can comment on the engine-y parts / fixes :-)

**Comment by Cervator** [comment]
Gave this a pretty solid amount of testing but I'm not super confident if I am reaching / understanding the use cases fully.

I put the test code (thanks @flo !) into a test branch of Portals with two sets of components/systems to test the first case and the second case:

https://github.com/Terasology/Portals/tree/test2254

Blocks "chest1" and "chest2" (appears like a brick to tell it apart from 1) will trigger their respective systems and log when activation and deactivation (only use case 1) happens.

Across a series of tests with Portals active (single player, multiplayer, reloaded from single into multi, second player online) I couldn't see any duplication of the logging at all. I also tried out JoshariasSurvival and Cities to check out some basics there, not to mention the Portal block as well.

Still would be good to have @MarcinSc test it and get comments from @immortius :-)

**Comment by Cervator** [comment]
Merging as assumed fixed - seems as much to me in any case and I can't find anything that breaks.

**Pull request merged**
