### PR TITLE
Splits CoreAssets and CoreBlocks from Core

### PR DESCRIPTION
**Pull request by Qwertygiy**
### Contains

Moves block templates, textures, and sounds from Core into CoreAssets, as well as all actual block-defining files from Core into CoreBlocks.

### How to test

There should be no differences in Core gameplay before and after this PR. All blocks, sounds, and textures that were previously available should remain available, as they've just been refactored.

### Outstanding before merging

Basic testing on my end worked as intended, but the following remain:

- [ ] Need to replace most instances of "core:resourcename" in other modules, replacing "core"/"Core" with the appropriate "CoreAssets" or "CoreBlocks".
- [ ] Need to confirm that all sounds and blocks that were previously functional remain functional.
- [ ] Need to confirm that CoreAssets and CoreBlocks can be safely used without Core.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by eviltak** [comment]
Thanks for the PR! Triggering bot to auto-test: 
@GooeyHub: add to whitelist

**Comment by jellysnake** [comment]
@GooeyHub: add to whitelist

Going to prod the bot to listen to evil more.

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Did some more testing and minor tweaking, merged! Thanks @Qwertygiy :-)

**Pull request merged**
