### PR TITLE
Make some TreeView classes accessible by modules.

### PR DESCRIPTION
**Pull request by flo**
### Contains
Makes some TreeView model classes accessible by modules by adding a @API annotation to them.

There are probably more tree view classes that need that annotation but for my local code to work I need those :).

### How to test

Minimalistic change, no gameplay test necessary.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by flo** [comment]
Pining @rzats  as he originally made this :)

**Comment by rzats** [comment]
Merged! Let me know when the module you're using these in is released 😃

**Comment by flo** [comment]
I used the tree view to make a "Toolbox" dialog that can be used to obtain blocks for now.

See

http://forum.terasology.org/threads/structure-templates.1550/#post-13839

**Pull request merged**
