### PR TITLE
More engine lifecycle rework

### PR DESCRIPTION
**Pull request by immortius**
Moved most of the remaining logic that shouldn't be in engine into subsystems, and it is now handled via generic lifecycle events.

Some particular focus on time-related behavior. Added support for altering the rate of game time. Fixed hibernation when alt-tabbed from the game.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/208/

**Build Log**
*last 5 lines*

 ```
[...truncated 2057 lines...]
Build step 'Publish JUnit test result report' changed build result to UNSTABLE
[ANALYSIS-COLLECTOR] Computing warning deltas based on reference build #207
Notifying upstream projects of job completion
Setting status of 3d789029dfb88e97a247a5037ef2d55124274ac3 to FAILURE with url http://jenkins.terasology.org/job/TerasologyPRs/208/ and message: Merged build finished.
```

Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/209/
Hooray Jenkins reported success with all tests good!

**Comment by flo** [comment]
Overall nice TerasologyEngine simplifiation/purification.

**Comment by flo** [comment]
I just tried to build with it, it breaks the Pathfinding module.

**Comment by flo** [comment]
I noticed the engien version is now 0.54.1-SNAPSHOT, so we would have to increment it to 0.55.0-SNAPSHOT

**Comment by flo** [comment]
hmm the modules haven't been released as stable version.

When we increment the engine version we would need a script or build task or something to do an automatic maxVersion incrment for all modules. @Cervator is something ready?

**Comment by msteiger** [comment]
One option would be to set maxVersion to `1.0.0` to avoid this issue without the need to update the value on every engine release. Or is there a reason not to do that?

**Comment by immortius** [comment]
Yes. If the maxVersion of a module was 1.0.0 and there is a breaking change that breaks it, then it won't be correctly marked as incompatible.

**Comment by Cervator** [comment]
Related forum thread - http://forum.terasology.org/threads/more-version-increments-to-avoid-dependency-issues.1270 :-)

Lots of wonderful ideas on how to handle everything, less so on the time availability to implement. Still on my short-list

Also, time dilation? Neat! Now we just need that IRL :-) I take it we in theory could push that to a neato EVE-like lag handling technique if needed.

**Comment by flo** [comment]
When the game does not have the focus when the loading finishes then the game is permanently paused. Might this be a bug introduced by the refactoring?

**Comment by immortius** [comment]
Hibernation restores the pause state from before hibernation began. This is perhaps incorrect. It might be best for hibernation to not pause the game, not sure.

**Comment by Cervator** [comment]
I'm personally a fan of being able to leave the window alone but active while working on other stuff. And wouldn't that have to be the case if connected to a server anyway? The client won't be able to pause time then.

But maybe I'm not entirely on top of what gets paused

**Comment by immortius** [comment]
The network system disables hibernation explicitly. But yeah, I think I'll just change it to do the frame rate limiting and remove the auto-pausing.

**Pull request merged**
