### PR TITLE
Moved more methods out of GameEngine

### PR DESCRIPTION
**Pull request by immortius**
Moved focus and mouse capture related methods out of engine and into DisplayDevice and InputSystem

### CODE REVIEW

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/182/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Small easy change. Tested real quick and pushed :-)

FYI ping for @flo & @emanuele3d

**Comment by Josharias** [comment]
Hrm, seems to have broken the headless server.

https://gist.github.com/Josharias/7fc2f11b13dc25115a84

**Comment by Cervator** [comment]
Doh, yep, nice catch. Hadn't thought to test that. Confirmed

```
java.lang.NullPointerException: null
	at org.terasology.input.InputSystem.isCapturingMouse(InputSystem.java:218) ~[classes/:na]
	at org.terasology.rendering.nui.internal.NUIManagerInternal.update(NUIManagerInternal.java:389) ~[classes/:na]
	at org.terasology.engine.modes.StateLoading.update(StateLoading.java:254) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:499) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:427) ~[classes/:na]
	at org.terasology.engine.Terasology.main(Terasology.java:144) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140) [idea_rt.jar:na]
23:33:03.612 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
```

**Pull request merged**
