### PR TITLE
bugfix: set opengl core profile to 3.3

### PR DESCRIPTION
**Pull request by pollend**
I configured the core profile to 3.3 hopefully this should work on intel embedded processors. I was able to validate this on my AMD graphics card but we need to test this on a couple different computers.

```
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL core profile version string: 4.6 (Core Profile) Mesa 21.0.0-devel (git-7d8d99e 2020-12-25 focal-oibaf-ppa)
OpenGL core profile shading language version string: 4.60
OpenGL version string: 4.6 (Compatibility Profile) Mesa 21.0.0-devel (git-7d8d99e 2020-12-25 focal-oibaf-ppa)
OpenGL shading language version string: 4.60
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 21.0.0-devel (git-7d8d99e 2020-12-25 focal-oibaf-ppa)
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
    GL_EXT_shader_group_vote, GL_EXT_shader_implicit_conversions, 

```
REF: https://github.com/MovingBlocks/Terasology/issues/4698

### CODE REVIEW

**Comment by jdrueckert** [comment]
Tried it out on intel integrated graphics:
```
17:06:30.324 [main] INFO  o.t.e.rendering.ShaderManagerLwjgl - GL_VENDOR: Intel
17:06:30.325 [main] INFO  o.t.e.rendering.ShaderManagerLwjgl - GL_RENDERER: Intel(R) HD Graphics 520
17:06:30.325 [main] INFO  o.t.e.rendering.ShaderManagerLwjgl - GL_VERSION: 4.6.0
```

Terasology and game world started fine and looked as expected. Not sure if there's anything to watch out for in particular?

**Comment by jdrueckert** [comment]
Had a try without this PR and everything looked and worked the same way 🤷

**Comment by pollend** [comment]
> Had a try without this PR and everything looked and worked the same way shrug

It depends on the graphics card and what driver they are using XD.

**Comment by Hume2** [comment]
I tested it. I still have the same issue. This time, I wasn't able to run a world, so I just opened the game and closed it. Here are the logs: https://drive.google.com/drive/folders/1YgcR4MkeLs1MOb7uMS8GTDU82eFR8pQH?usp=sharing

**Comment by pollend** [comment]
I think I made a mistake. window hints have to be defined before the window is created.
https://stackoverflow.com/questions/52592309/0110-error-glsl-3-30-is-not-supported-ubuntu-18-04-c

**Comment by Hume2** [comment]
I modified the commit and made another pull request: #4711
This one can be closed, I think.

**Pull request closed without merging**
