### PR TITLE
chore(rendering): remove usage of GL_ARB_framebuffer and reworked shadowmap and lightpass

### PR DESCRIPTION
**Pull request by pollend**
this migrates the ARB extension for framebuffer to the standard in GL 3.0 I believe this should let us play Terasology on osx again. with this change I also broke the the shadow pass but was able to resolve the shadow artifacting we were seeing for quite some time. This seems like a pretty significant change that resolves one of the more annoying problems with the rendering. 

before: 
image

after:
image

required PR: https://github.com/Terasology/CoreRendering/pull/63

### CODE REVIEW

**Comment by pollend** [comment]
image

**Comment by Cervator** [comment]
Well, it didn't *crash* per se, but I got a window on my map flashing between red and black plus some shader errors in the log. But it did run and load the main menu, I could even hear button clicky noises!

Full log:

```
> Task :facades:PC:game
Recognized argument: -homedir
Recognized argument: -noSplash
PathManager being initialized. Initial code location is /Users/cervator/dev/terasology/git_ws/mini/Terasology/engine/build/libs/engine-5.0.0-SNAPSHOT.jar
Switched it to expected working dir: /Users/cervator/dev/terasology/git_ws/mini/Terasology
installPath was null, running from IDE or headless server? Setting to: /Users/cervator/dev/terasology/git_ws/mini/Terasology
Found the natives dir: /Users/cervator/dev/terasology/git_ws/mini/Terasology/natives
22:15:07.300 [main] INFO  c.b.gdx.physics.bullet.NativeSupport - Loading JNBullet Library:bullet
22:15:07.352 [main] INFO  c.b.gdx.physics.bullet.NativeSupport -        Loaded from java.library.path: /Users/cervator/dev/terasology/git_ws/mini/Terasology/natives/macosx/libbullet-darwin-amd64.dylib
22:15:07.419 [main] INFO  o.t.engine.core.TerasologyEngine - Initializing Terasology...
22:15:07.419 [main] INFO  o.t.engine.core.TerasologyEngine - [buildNumber=, buildId=, buildTag=, buildUrl=, jobName=, dateTime=, displayVersion=alpha-20, engineVersion=5.0.0-SNAPSHOT]
22:15:07.420 [main] INFO  o.t.engine.core.TerasologyEngine - Home path: /Users/cervator/dev/terasology/git_ws/mini/Terasology
22:15:07.421 [main] INFO  o.t.engine.core.TerasologyEngine - Install path: /Users/cervator/dev/terasology/git_ws/mini/Terasology
22:15:07.421 [main] INFO  o.t.engine.core.TerasologyEngine - Java: 11.0.9.1 in /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
22:15:07.421 [main] INFO  o.t.engine.core.TerasologyEngine - Java VM: OpenJDK 64-Bit Server VM, version: 11.0.9.1+1
22:15:07.421 [main] INFO  o.t.engine.core.TerasologyEngine - OS: Mac OS X, arch: x86_64, version: 10.16
22:15:07.422 [main] INFO  o.t.engine.core.TerasologyEngine - Max. Memory: 3072 MiB
22:15:07.422 [main] INFO  o.t.engine.core.TerasologyEngine - Processors: 8
22:15:07.577 [main] INFO  o.t.e.c.s.c.ConfigurationSubsystem - Video Settings: {"pixelFormat":24,"windowPosX":270,"windowPosY":53,"windowWidth":1152,"windowHeight":720,"displayModeSetting":"${engine:menu#video-windowed}","animatedMenu":false,"chunkLods":0.0,"flickeringLight":true,"animateGrass":true,"animateWater":false,"fieldOfView":90.0,"cameraBobbing":true,"renderPlacingBox":true,"blurIntensity":2,"reflectiveWater":false,"vignette":true,"motionBlur":true,"ssao":false,"filmGrain":false,"outline":true,"lightShafts":true,"eyeAdaptation":true,"bloom":true,"dynamicShadows":true,"vrSupport":false,"maxTextureAtlasResolution":4096,"maxChunksUsedForShadowMapping":1024,"shadowMapResolution":1024,"normalMapping":false,"parallaxMapping":false,"dynamicShadowsPcfFiltering":false,"cloudShadows":true,"renderNearest":true,"particleEffectLimit":10,"frameLimit":60,"meshLimit":400,"inscattering":true,"localReflections":false,"vSync":false,"clampLighting":false,"fboScale":100,"uiScale":100,"dumpShaders":false,"volumetricFog":false,"screenshotSize":"${engine:menu#screenshot-size-normal}","screenshotFormat":"png","cameraSettings":{"cameraSetting":"${engine:menu#camera-setting-normal}"},"debug":{"enabled":false,"firstPersonElementsHidden":false,"hudHidden":false,"wireframe":false,"renderChunkBoundingBoxes":false,"renderSkeletons":false}}
22:15:09.078 [main] INFO  o.t.gestalt.module.ModulePathScanner - Discovered module: Explosives-1.1.1-SNAPSHOT
22:15:09.081 [main] INFO  o.t.gestalt.module.ModulePathScanner - Discovered module: BiomesAPI-4.1.1-SNAPSHOT
22:15:09.098 [main] INFO  o.t.gestalt.module.ModulePathScanner - Discovered module: CoreWorlds-2.0.0-SNAPSHOT
22:15:09.110 [main] INFO  o.t.gestalt.module.ModulePathScanner - Discovered module: Inventory-1.5.0-SNAPSHOT
22:15:09.117 [main] INFO  o.t.gestalt.module.ModulePathScanner - Discovered module: Health-2.0.0-SNAPSHOT
22:15:09.121 [main] INFO  o.t.gestalt.module.ModulePathScanner - Discovered module: Furnishings-1.1.1-SNAPSHOT
22:15:09.125 [main] INFO  o.t.gestalt.module.ModulePathScanner - Discovered module: Drops-1.2.0-SNAPSHOT
22:15:09.128 [main] INFO  o.t.gestalt.module.ModulePathScanner - Discovered module: CoreAdvancedAssets-1.3.0-SNAPSHOT
22:15:09.131 [main] INFO  o.t.gestalt.module.ModulePathScanner - Discovered module: CoreAssets-2.3.0-SNAPSHOT
22:15:09.143 [main] INFO  o.t.gestalt.module.ModulePathScanner - Discovered module: CoreRendering-1.1.2-SNAPSHOT
22:15:09.148 [main] INFO  o.t.gestalt.module.ModulePathScanner - Discovered module: CoreSampleGameplay-4.1.0
22:15:09.161 [main] ERROR o.t.g.module.TableModuleRegistry - Duplicate module CoreWorlds-2.0.0-SNAPSHOT discovered
22:15:09.161 [main] INFO  o.t.gestalt.module.ModulePathScanner - Discovered duplicate module: CoreWorlds-2.0.0-SNAPSHOT, skipping
22:15:09.169 [main] ERROR o.t.g.module.TableModuleRegistry - Duplicate module Inventory-1.5.0-SNAPSHOT discovered
22:15:09.169 [main] INFO  o.t.gestalt.module.ModulePathScanner - Discovered duplicate module: Inventory-1.5.0-SNAPSHOT, skipping
22:15:09.195 [main] ERROR o.t.g.module.TableModuleRegistry - Duplicate module Health-2.0.0-SNAPSHOT discovered
22:15:09.195 [main] INFO  o.t.gestalt.module.ModulePathScanner - Discovered duplicate module: Health-2.0.0-SNAPSHOT, skipping
22:15:09.197 [main] ERROR o.t.g.module.TableModuleRegistry - Duplicate module CoreAdvancedAssets-1.3.0-SNAPSHOT discovered
22:15:09.197 [main] INFO  o.t.gestalt.module.ModulePathScanner - Discovered duplicate module: CoreAdvancedAssets-1.3.0-SNAPSHOT, skipping
22:15:09.200 [main] ERROR o.t.g.module.TableModuleRegistry - Duplicate module CoreAssets-2.3.0-SNAPSHOT discovered
22:15:09.200 [main] INFO  o.t.gestalt.module.ModulePathScanner - Discovered duplicate module: CoreAssets-2.3.0-SNAPSHOT, skipping
22:15:09.433 [main] INFO  o.t.e.audio.openAL.OpenALManager - Initializing OpenAL audio manager
22:15:09.759 [main] INFO  o.t.e.audio.openAL.OpenALManager - OpenAL 1.1 ALSOFT 1.19.1 initialized!
22:15:09.759 [main] INFO  o.t.e.audio.openAL.OpenALManager - Using OpenAL: OpenAL Soft by OpenAL Community
22:15:09.759 [main] INFO  o.t.e.audio.openAL.OpenALManager - Using device: OpenAL Soft
22:15:09.759 [main] INFO  o.t.e.audio.openAL.OpenALManager - Available AL extensions: AL_EXT_ALAW AL_EXT_BFORMAT AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_BFORMAT AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_EXT_SOURCE_RADIUS AL_EXT_STEREO_ANGLES AL_LOKI_quadriphonic AL_SOFT_block_alignment AL_SOFT_deferred_updates AL_SOFT_direct_channels AL_SOFTX_events AL_SOFTX_filter_gain_ex AL_SOFT_gain_clamp_ex AL_SOFT_loop_points AL_SOFTX_map_buffer AL_SOFT_MSADPCM AL_SOFT_source_latency AL_SOFT_source_length AL_SOFT_source_resampler AL_SOFT_source_spatialize
22:15:09.760 [main] INFO  o.t.e.audio.openAL.OpenALManager - Available ALC extensions: ALC_ENUMERATE_ALL_EXT ALC_ENUMERATION_EXT ALC_EXT_CAPTURE ALC_EXT_DEDICATED ALC_EXT_disconnect ALC_EXT_EFX ALC_EXT_thread_local_context ALC_SOFT_device_clock ALC_SOFT_HRTF ALC_SOFT_loopback ALC_SOFT_output_limiter ALC_SOFT_pause_device
22:15:09.760 [main] INFO  o.t.e.audio.openAL.OpenALManager - Max mono sources: 255
22:15:09.760 [main] INFO  o.t.e.audio.openAL.OpenALManager - Max stereo sources: 1
22:15:09.760 [main] INFO  o.t.e.audio.openAL.OpenALManager - Mixer frequency: 44100
22:15:09.767 [main] INFO  o.t.e.c.s.lwjgl.LwjglGraphics - Starting initialization of LWJGL
22:15:09.771 [main] INFO  o.t.e.c.s.lwjgl.LwjglGraphics - Initial initialization complete
22:15:09.772 [main] INFO  o.t.s.discordrpc.DiscordRPCSubSystem - Initializing...
22:15:09.776 [DISCORD-RPC-THREAD] INFO  o.t.s.discordrpc.DiscordRPCThread - Waiting for auto-connecting...
22:15:09.777 [DISCORD-RPC-THREAD] INFO  o.t.s.discordrpc.DiscordRPCThread - Waiting for enabling...
22:15:09.778 [DISCORD-RPC-THREAD] INFO  o.t.s.discordrpc.DiscordRPCThread - Waiting for connection...
22:15:09.778 [DISCORD-RPC-THREAD] INFO  o.t.s.discordrpc.DiscordRPCThread - Connecting to Discord RPC...
22:15:09.986 [main] WARN  o.t.e.w.g.i.WorldGeneratorManager - Could not resolve dependencies for module: CoreSampleGameplay-4.1.0
22:15:10.183 [main] INFO  o.t.e.i.s.StorageServiceWorker - Performing action InitializeFromTokenAction
22:15:10.184 [Thread-1] INFO  o.t.e.i.s.StorageServiceWorker - Completed action InitializeFromTokenAction
22:15:10.274 [main] INFO  o.t.e.c.s.lwjgl.LwjglGraphics - Initializing display (if last line in log then likely the game crashed from an issue with your video card)
22:15:10.584 [main] INFO  o.t.e.c.s.lwjgl.LwjglGraphics - Initializing OpenGL
22:15:10.745 [main] INFO  o.t.e.rendering.opengl.GLSLShader - Dumped Shader Path: /Users/cervator/dev/terasology/git_ws/mini/Terasology/logs/shaders/fragment_engine-uiTexture_0.glsl
22:15:10.748 [main] WARN  o.t.e.rendering.opengl.GLSLShader - Shader 'engine:uiTexture' failed to compile for features '[]'.

Shader Info: 
No Info

22:15:10.788 [main] INFO  o.t.e.rendering.opengl.GLSLShader - Dumped Shader Path: /Users/cervator/dev/terasology/git_ws/mini/Terasology/logs/shaders/fragment_engine-font_0.glsl
22:15:10.789 [main] WARN  o.t.e.rendering.opengl.GLSLShader - Shader 'engine:font' failed to compile for features '[]'.

Shader Info: 
No Info

22:15:10.830 [main] WARN  o.t.e.c.s.config.BindsSubsystem - Input KEY_LSHIFT is already registered, can not use it as default for event class org.terasology.engine.input.binds.general.TabbingModifierButton
22:15:10.928 [main] WARN  o.t.e.c.s.config.BindsSubsystem - Input KEY_LSHIFT is already registered, can not use it as default for event class org.terasology.engine.input.binds.general.TabbingModifierButton
22:15:10.938 [DISCORD-RPC-THREAD] INFO  o.t.s.discordrpc.DiscordRPCThread - Connected to Discord RPC!
22:15:10.941 [DISCORD-RPC-THREAD] INFO  o.t.s.discordrpc.DiscordRPCThread - Updating the rich presence and keep the connection alive...
22:15:11.038 [main] INFO  o.t.e.i18n.TranslationSystemImpl - Discovered engine:menu_hi
22:15:11.040 [main] INFO  o.t.e.i18n.TranslationSystemImpl - Discovered engine:menu_de
22:15:11.042 [main] INFO  o.t.e.i18n.TranslationSystemImpl - Discovered engine:menu_sq
22:15:11.043 [main] INFO  o.t.e.i18n.TranslationSystemImpl - Discovered engine:menu_ro
22:15:11.044 [main] INFO  o.t.e.i18n.TranslationSystemImpl - Discovered engine:menu_fa
22:15:11.046 [main] INFO  o.t.e.i18n.TranslationSystemImpl - Discovered engine:menu_ja
22:15:11.048 [main] INFO  o.t.e.i18n.TranslationSystemImpl - Discovered engine:menu_uk
22:15:11.049 [main] INFO  o.t.e.i18n.TranslationSystemImpl - Discovered engine:menu_ar
22:15:11.051 [main] INFO  o.t.e.i18n.TranslationSystemImpl - Discovered engine:menu_fr
22:15:11.052 [main] INFO  o.t.e.i18n.TranslationSystemImpl - Discovered engine:menu_it
22:15:11.053 [main] INFO  o.t.e.i18n.TranslationSystemImpl - Discovered engine:menu_en
22:15:11.054 [main] INFO  o.t.e.i18n.TranslationSystemImpl - Discovered engine:menu_gl
22:15:11.055 [main] INFO  o.t.e.i18n.TranslationSystemImpl - Discovered engine:menu_pt
22:15:11.056 [main] INFO  o.t.e.i18n.TranslationSystemImpl - Discovered engine:menu_sv
22:15:11.057 [main] INFO  o.t.e.i18n.TranslationSystemImpl - Discovered engine:game
22:15:11.058 [main] INFO  o.t.e.i18n.TranslationSystemImpl - Discovered engine:menu_pr
22:15:11.058 [main] INFO  o.t.e.i18n.TranslationSystemImpl - Discovered engine:game_en
22:15:11.059 [main] INFO  o.t.e.i18n.TranslationSystemImpl - Discovered engine:menu_tr
22:15:11.060 [main] INFO  o.t.e.i18n.TranslationSystemImpl - Discovered engine:menu_nl
22:15:11.061 [main] INFO  o.t.e.i18n.TranslationSystemImpl - Discovered engine:menu_pl
22:15:11.062 [main] INFO  o.t.e.i18n.TranslationSystemImpl - Discovered engine:menu_id
22:15:11.063 [main] INFO  o.t.e.i18n.TranslationSystemImpl - Discovered engine:menu
22:15:11.065 [main] INFO  o.t.e.i18n.TranslationSystemImpl - Discovered engine:menu_cs
22:15:11.066 [main] INFO  o.t.e.i18n.TranslationSystemImpl - Discovered engine:menu_zh
22:15:11.067 [main] INFO  o.t.e.i18n.TranslationSystemImpl - Discovered engine:menu_es
22:15:11.068 [main] INFO  o.t.e.i18n.TranslationSystemImpl - Discovered engine:menu_hu
22:15:11.070 [main] INFO  o.t.e.i18n.TranslationSystemImpl - Discovered engine:menu_ko
22:15:11.072 [main] INFO  o.t.e.i18n.TranslationSystemImpl - Discovered engine:menu_ru
22:15:11.104 [main] INFO  o.t.engine.core.TerasologyEngine - Initialization completed in 3.68sec.
22:15:11.189 [main] INFO  o.t.e.rendering.opengl.GLSLShader - Dumped Shader Path: /Users/cervator/dev/terasology/git_ws/mini/Terasology/logs/shaders/fragment_engine-UILitMesh_0.glsl
22:15:11.194 [main] WARN  o.t.e.rendering.opengl.GLSLShader - Shader 'engine:UILitMesh' failed to compile for features '[]'.

Shader Info: 
No Info

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.esotericsoftware.reflectasm.AccessClassLoader (file:/Users/cervator/.gradle/caches/modules-2/files-2.1/com.esotericsoftware/reflectasm/1.11.9/fd51ad1705d5e27d8785550172a4ab0cb9b8ad23/reflectasm-1.11.9.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.esotericsoftware.reflectasm.AccessClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
22:15:11.443 [main] WARN  o.t.engine.registry.InjectionHelper - CameraTargetSystem wanted Physics injected but CoreRegistry has none.
22:15:11.443 [main] WARN  o.t.engine.registry.InjectionHelper - CameraTargetSystem wanted BlockEntityRegistry injected but CoreRegistry has none.
22:15:11.443 [main] WARN  o.t.engine.registry.InjectionHelper - CameraTargetSystem wanted WorldRenderer injected but CoreRegistry has none.
22:15:11.584 [main] WARN  o.t.engine.registry.InjectionHelper - CoreCommands wanted BlockManager injected but CoreRegistry has none.
22:15:11.593 [main] WARN  o.t.engine.registry.InjectionHelper - LocalPlayerSystem wanted WorldProvider injected but CoreRegistry has none.
22:15:11.593 [main] WARN  o.t.engine.registry.InjectionHelper - LocalPlayerSystem wanted DelayManager injected but CoreRegistry has none.
22:15:11.593 [main] WARN  o.t.engine.registry.InjectionHelper - LocalPlayerSystem wanted PhysicsEngine injected but CoreRegistry has none.
22:15:11.594 [main] WARN  o.t.engine.registry.InjectionHelper - CameraTargetSystem wanted Physics injected but CoreRegistry has none.
22:15:11.594 [main] WARN  o.t.engine.registry.InjectionHelper - CameraTargetSystem wanted BlockEntityRegistry injected but CoreRegistry has none.
22:15:11.594 [main] WARN  o.t.engine.registry.InjectionHelper - CameraTargetSystem wanted WorldRenderer injected but CoreRegistry has none.
log4j:WARN No appenders could be found for logger (org.apache.http.impl.conn.PoolingHttpClientConnectionManager).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
22:15:12.349 [o.t.e.r.n.l.m.a.AdvancedGameSetupScreen-0] INFO  o.t.e.c.module.ModuleListDownloader - Downloading modules ..
22:15:12.360 [main] WARN  org.terasology.nui.WidgetUtil - Contents of org.terasology.engine.rendering.nui.layers.mainMenu.MainMenuScreen@530e08a7 missing button with id 'storageServiceAction'
22:15:12.367 [main] WARN  o.t.engine.core.internal.TimeBase - Delta too great (2102), capping to 1000
2021-06-06 22:15:12.474 java[78018:2752979] [JRSAppKitAWT markAppIsDaemon]: Process manager already initialized: can't fully enable headless mode.
22:15:12.698 [o.t.e.r.n.l.m.a.AdvancedGameSetupScreen-0] INFO  o.t.e.c.module.ModuleListDownloader - Parsing content ..
22:15:13.486 [o.t.e.r.n.l.m.a.AdvancedGameSetupScreen-0] INFO  o.t.e.c.module.ModuleListDownloader - Retrieved 185 entries
22:15:28.207 [main] INFO  o.t.engine.core.TerasologyEngine - Shutting down Terasology...

```

**Comment by skaldarnar** [comment]
I can confirm the behavior observed by @Cervator. Red flashing window, I do hear main menu sounds (music and clicks), and my log looks pretty much the same.

```
11:27:33.439 [main] WARN  o.t.e.rendering.opengl.GLSLShader - Shader 'engine:font' failed to compile for features '[]'.

Shader Info:
No Info
```

**Comment by jdrueckert** [comment]
[Pre-GSoC Release](https://trello.com/c/1oMuhurE/125-pre-gsoc-release)

**Review by skaldarnar — APPROVED** [review]

**Pull request merged**
