### PR TITLE
Behavior gsoc2017 by @dkambersky

### PR DESCRIPTION
**Pull request by oniatus**
Set of PRs which has to be tested and merged together:

- https://github.com/MovingBlocks/Terasology/pull/3023
- https://github.com/Terasology/Pathfinding/pull/34
- https://github.com/Terasology/Behaviors/pull/7
- https://github.com/Terasology/WildAnimals/pull/22
- https://github.com/Terasology/GooeysQuests/pull/15 
- https://github.com/Terasology/LightAndShadow/pull/59
- https://github.com/Terasology/LightAndShadowResources/pull/21
- https://github.com/Terasology/StaticCities/pull/5

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Bump! I have pulled everything in this and related PRs on top of a rebased v2 engine branch. Looks mostly intact, but like there's something missing in Pathfinding - specifically in `CheckTargetSetNode` it tries to import:

```java
import org.terasology.logic.behavior.tree.Node;
import org.terasology.logic.behavior.tree.Status;
import org.terasology.logic.behavior.tree.Task;
```

Is that out of date? Those classes show as unknown as the `org.terasology.logic.behavior` package doesn't have a `tree` sub package anymore. I figured it might have been moved to the Behaviors module but I don't see it in there either.

Or maybe I'm still missing something? Pinging @dkambersky and @oniatus 

I'm trying to get a working branch with all the v2 stuff so I can set up builds in Jenkins for further project maintenance until v2 finally gets merged. But I need to figure out what's missing first :-)

Also, @kaen mentioned having a reworked Pathfinding as well with some very tasty features. That one might not be v2 though (less behavior, more basic pathfinding)

**Comment by Cervator** [comment]
Oh, wait. `CheckTargetSetNode` was introduced very recently by https://github.com/Terasology/Pathfinding/commit/6e52374b03282aa5e4f68cb75200e3323f8e4544 via https://github.com/Terasology/Pathfinding/pull/33 so it still uses the old approach. How do we update it, or is there a replacement? I expect it is used by the deer mating @arpan98 did

I saw another error with `PathfinderTestWorldMapGenerator` but that's instead related to the Zones changes in @Vizaxo's stuff (also present in my v2 branch). That one is pretty easy.

If those two issues are it then that's pretty nice :)

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by oniatus** [comment]
Strange, it seems as if some builds are failing in the publish test report step even if the build itself works.

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by oniatus** [comment]
Going to add this to the v2 PR and fix the build issue there as i suspect some build quirks due to the old base.

**Pull request merged**
