### PR TITLE
feat: add check for facet provider requirements

### LINKED ISSUE #4924: FacetProvider requirements should be verified
For example, BiomeProvider `@Requires` SeaLevelFacet, but code reaches BiomeProvider.process without a SeaLevelFacet provided: https://scans.gradle.com/s/3szw7vgxv4d2o/tests/:modules:DynamicCities:test/org.terasology.dynamicCities.settlements.SettlementEntityManagerTest/placeParcel(SettlementEntityManager,%20ModuleTestingHelper)?top-execution=1

If this had been checked up-front and responded with a clear error message, it would have saved me some time in trying to figure out why my WorldGenerator wasn't working.

@tolziplohu [says](https://discord.com/channels/270264625419911192/702893102481932308/895498118743875616):
> Huh. It looks like the annotations are used for ordering providers but not for verifying that they actually exist. That should actually be pretty easy to detect — just look for empty provider lists for required facets. I guess we just haven't considered that possibility.

### PR DESCRIPTION
**Pull request by MrGizmo123**
### Contains
Fixes #4924 

### Todo

- [x] Test that CoreGameplay world gen still works as expected
- [x] Test that focus gameplays' world gen still works as expected (JS, MR, LaS)
- [x] Test that logic correctly fails any attempt to add a facet provider with unsatisfied requirements
- [x] Fix failing tests
- [x] Write test case for new logic

### CODE REVIEW

**Review by engiValk — DISMISSED** [review]
Seems fine to merge.

**Comment by jdrueckert** [comment]
@MrGizmo123 I pushed a PR slightly changing the error log and adding throwing an `IllegalStateException`.
Thus, world generation fails and developers get direct and clear feedback when trying to test their world gen provider.
This can be tested, for instance, by adding `FloraFacet.class` to the [required facets in `CoreWorlds:BiomeProvider`](https://github.com/Terasology/CoreWorlds/blob/develop/src/main/java/org/terasology/core/world/generator/facetProviders/BiomeProvider.java#L37-L42) and trying to start a `CoreGameplay` world.

**Comment by jdrueckert** [comment]
Seems like the tests failed because the `Facet1Provider` in the test cases in `WorldBuilderTest` requires `Facet2Provider` but was added before it so far. This should be fixed now.

**Review by jdrueckert — DISMISSED** [review]

**Comment by jdrueckert** [comment]
I added a test case that tests that if facet providers are added in an incorrect order, an exception is thrown.

**Review by jdrueckert — APPROVED** [review]
It's been over 2 months now waiting for a review and while I would've loved to get one from @keturn who originally requested this feature, I believe it's more important to finally get this improvement in. We can always still revert or modify things afterwards in case we overlooked or misunderstood something about the feature request.

**Pull request merged**
