### PR TITLE
New asset: Group

### PR DESCRIPTION
**Pull request by casals**
### Contains
- New asset: Group
- Updates the build with gestalt version 5.1.4 (required by asset structure)

### Objective
- The new Group asset allows group configurations to be loaded from JSON files (assets/groups/.group). 
- Gestalt 5.1.4 contains a fix to a bug that would sometimes prevent an asset file to be loaded. This error appears as an `java.security.AccessControlException` exception ("access denied"), with the stack trace leading to `org.terasology.assets.format.AssetDataFile.openStream(AssetDataFile.java:99)` .

### Changes

- New asset structure: `Group`, `GroupBuilder`, GroupData`, GroupFactory`, and `GroupFormat`. The new implementation is hermetic and shouldn't affect any of the existing classes.
- Updates both `gestalt-module` and `gestalt-asset-core`  to version 5.1.4 in `build.gradle`

### Usage

- Make sure to thoroughly rebuild the project to avoid broken references using `gradlew clean cleanIdea idea jar` (so that the new gestalt version can be properly used)
- The new asset structure is demonstrated in the [WildAnimalsMadness](https://github.com/casals/WildAnimalsMadness) module

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
@GooeyHub: add to whitelist

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by casals** [comment]
Removed leftovers from the previous gestalt debugging (including generic exceptions, replaced with more appropriate ones) and included javadoc for classes/fields. Also rebased to remove merge commits.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Briefly validated that the game still works after the merge, looking forward to trying it out in WildAnimalsMadness soon 👍

**Pull request merged**
