### PR TITLE
Fix the broken viewing of behavior trees.

### PR DESCRIPTION
**Pull request by flo**
This fixes the broken viewing of behavior trees (e.g. when you have spawned a deer in the wild animals module and then press F5 and select the behavior of the deer).

### CODE REVIEW

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/418/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Good to see code from you again @flo :-)

Tests out good. Curiously, did you run across @oniatus ? New contributor who showed up very recently and started looking at pathfinding and the BTs (like with https://github.com/oniatus/Pathfinding/commit/965dd6889a6b460400c286cc25dfd3aebb68d8b3)

**Comment by haftsteind** [comment]
And injecting the Context looks cleaner to me than [my change](https://github.com/oniatus/Terasology/commit/6f3042d1afe7191be901099cdb5cfc35c15fe23c) which hardwires the CoreRegistry.
Thanks for the update @flo. I will update my branch the next days.

So much to read & learn, so little time  :sunglasses:

**Comment by oniatus** [comment]
And injecting the Context looks cleaner to me than [my change](https://github.com/oniatus/Terasology/commit/6f3042d1afe7191be901099cdb5cfc35c15fe23c) which hardwires the CoreRegistry.
Thanks for the update @flo. I will update my branch the next days.

So much to read & learn, so little time :sunglasses:
/+ too many accounts :D

**Comment by flo** [comment]
@Cervator No, I didn't have seen him earlier. It just coincidence that I just decided to work on that topic.

@oniatus CoreRegistry is deprecated and I hope It can be removed some day. I worked a lot on removing it but doing so wasn't much fun and it was and is quite a lot of work. 

It's nice to see some action in that area. I think creatures could make the game much more interesting. Are you sometimes in the IRC channel?

**Pull request merged**
