### PR TITLE
Allow climbing ladders with jump/crouch keys.

### LINKED ISSUE #1345: Enhance ladder climbing to support jump/crouch keys [$5]
Climbing ladders have been hugely improved by @meniku yay! One idea remains: allow the jump (space) and crouch (ctrl) keys to also let you ascend and descend while climbing, just like they work during flying/swimming

<bountysource-plugin>
---
There is a **[$5 open bounty](https://www.bountysource.com/issues/5773062-enhance-ladder-climbing-to-support-jump-crouch-keys?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by oijazsh**
A minor change to allow the use of the jump key and crouch keys to allow climbing up and down ladders respectively. Fixes #1345.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
ok to test

Hello @oijazsh and thanks! :-)

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/447/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Merged! And added to credits :-)

There was a $5 bounty on that issue, feel free to claim it on Bountysource. If you don't want to cash it out you can just add it to a different issue of your choice.

https://www.bountysource.com/issues/5773062-enhance-ladder-climbing-to-support-jump-crouch-keys?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github

**Comment by Cervator** [comment]
By the way let me know if you have or make a forum account so I can set you up with a contributor badge there :-)

**Pull request merged**
