### PR TITLE
Allow multijumping capabilities and modification of multijumping using events

### PR DESCRIPTION
**Pull request by xrtariq2594**
### Contains

This PR adds basic multijumping functionality to the base engine .

### How to test

In the CharacterMovementComponent class, change the numberOfJumpsMax value to something greater than 1. Load up the game and see if you jump that same number of times.

### Outstanding before merging

- [ ] Need to consider adding more functionality for multijumping. Like different levels of force per jump.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
@GooeyHub: add to whitelist

Yay!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Works beautifully, haha! Very much "Not fly, just jump well!"

We can add more functionality later, would like to merge this right now. Name seems fine to me too. @Josharias any comments/concerns or looking good?

**Pull request merged**
