### PR TITLE
Add unit tests to the FontUnderline class

### PR DESCRIPTION
**Pull request by jmryan64**
…ineTest.java

Added 4 unit tests for the FontUnderline class

### Contains

Added 4 unit tests for the FontUnderline class under rendering for the isValid() and markUnderlined() methods.

### How to test

Run them :)

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by jellysnake** [comment]
Hey there, welcome to the project. I'm just gonna trigger the build bot and then I'll take a quick look over shortly

@GooeyHub: ok to test

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Hey @jmryan64 - see https://github.com/MovingBlocks/Terasology/pull/3540#issuecomment-441308100 :-)

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Pull request merged**
