### PR TITLE
build: upgrade minimum compatible version to Java 11

### PR DESCRIPTION
**Pull request by keturn**
This updates the project's gradle configuration to use the Java 11 compatibility level. IntelliJ IDEA will recognize this configuration when determining which languages features are available.

## Requires
- [x] https://github.com/MovingBlocks/Terasology/pull/4942  
    CI must have a Java 11 environment to build in before we have developers making commits for Java 11.

### CODE REVIEW

**Comment by keturn** [comment]
[Java Version](https://trello.com/c/Gn9Fmcov/178-java-version)

**Comment by keturn** [comment]
Build passed its unit tests, but crashed during the javadoc task? That's certainly not what I expected. Maybe I didn't put enough RAM in the pod configuration?

(Yet unknown if integration tests pass, because that stage only runs after javadoc completes.)

**Comment by keturn** [comment]
- CI test run #4: re-build with the same configuration. Failed in an earlier stage.
- CI test run #5: increased pod memory limit to 6Gi, matching the old java8 precached pod configuration. Build succeeded.

**Comment by keturn** [comment]
The LGTM service has a Java 8 build environment.

There's been no news posted to their blog since they were acquired by GitHub two years ago.  
I can't connect to their discourse forum.

Would we be okay with dropping the LGTM GitHub integration?

**Review by jdrueckert — APPROVED** [review]

**Comment by keturn** [comment]
I really expected to run in to the #3992 failure at this point, but it looks like all the tests are passing in this run, so hooray?

**Comment by keturn** [comment]
wait, I _do_ get that  failure locally. :confused:

**Comment by keturn** [comment]
I think we have not been running the TypeHandlerLibrary tests ever since the unitTest / integrationTest split :cry:

**Pull request merged**
