### PR TITLE
Fix for #1516

### PR DESCRIPTION
**Pull request by immortius**
Improved error handling around network events.
Added reporting of network events lacking default constructors.
Prevent crashes relating deserializing events without default constructors.

### CODE REVIEW

**Comment by flo** [comment]
I had a look at the pull request: I think it are good changes.

If I understand it correctly it is also introducing the sending of block entities via block position. Is there a specific use case you are adding this for? Why wasn't this a problem before?

**Comment by Cervator** [comment]
Thanks for the logging clarifications :-)

Would like to merge this and maybe do a stable build soon, I think we're through the recent weeds

**Comment by immortius** [comment]
@flo It doesn't introduce block entity replication via block position, that was already there.

Block entities are replicated by block position because a block may change to be a network entity from not being one, causing it to be replicated. Meanwhile a client may have an entity for the block already from local interactions. The block position allows the replicated block to be merged onto the client's entity. Otherwise clients could end up with multiple entities for the same block. It... may not be the best solution on reflection.

**Comment by Cervator** [comment]
Also thanks :-)

Protip for anybody who didn't spot it: with @immortius putting "#1516" in the branch name like that Waffle.io was able to tag the issue with "in progress" and an owner. Kinda cool.

Pity it didn't get one step smarter and then actually close it when this was merged, even without an obvious "fixes #1516" in the body of the PR

Argh wish Waffle was open source and/or getting more attention.

**Pull request merged**
