### PR TITLE
Create a new overloaded method for WorldProvider.setBlock(), which ta…

### PR DESCRIPTION
**Pull request by MaloJaffre**
…kes a Vector3f.

See https://trello.com/c/WqgcMjaq.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/363/
Hooray Jenkins reported success with all tests good!

**Comment by msteiger** [comment]
Thank you for your contribution. I don't think that this method should be in there, though.

It doesn't provide significant functionality and it would be inconsistent with the other getters/setters. Maybe we might even want to remove the `getBlock(Vector3f)` method.

@Cervator Where does the Trello requirement card come from?

**Comment by Cervator** [comment]
It was initially raised in the Suggestion forum, in the backlog thread I just cleared out and turned into Trello cards, where this is https://trello.com/c/WqgcMjaq/6-add-overload-to-setblock-to-take-a-vector3f-and-convert-it-to-a-vector3i-automatically-like-getblock

I didn't think much of it, seemed like fair utility, but I don't know the code in the area. If it doesn't make sense we can close it out :-)

I've got some more stuff to move into Trello, when we're more stable there I can repost in the forum for some initial review of backlog items then enable Slack integration so any new cards will be more visible for review.,

**Comment by MaloJaffre** [comment]
If this PR is useless, we can close this and the trello card.

**Comment by Cervator** [comment]
Closed Trello card and am closing this PR unmerged. Sorry about the trouble @MaloJaffre - the initial import of issues into the backlog were just old entries from the forum that haven't had much review. When Trello is more fully set up we should do some review to disqualify anything else we don't actually want.

**Pull request closed without merging**
