### PR TITLE
Placed scrollable menus

### PR DESCRIPTION
**Pull request by AlexanderGrooff**
Regarding #2178. Replaced UIDropdown with UIDropdownScrollable on two menus in the Create Game menu:
1. Game templates, with three visible options;
2. World generator, with three visible options.

This works well with PR #2180.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by msteiger** [comment]
Ok to test

**Comment by msteiger** [comment]
Thanks! I will look into this asap (probably tomorrow night)

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/438/
Hooray Jenkins reported success with all tests good!

**Comment by msteiger** [comment]
Sorry, I need a few more days before I can review the whole thing.

**Comment by Cervator** [comment]
I got it, no worries :)

Been feeling a little sick, but getting better.

Thanks @AlexanderGrooff !

**Pull request merged**
