### PR TITLE
feat(JOML): migrate BlockRegionComponent logic

### PR DESCRIPTION
**Pull request by pollend**
Fairly straightforward migration of BlockRegionComponent. along with some thoughts from looking at how the logic works: https://github.com/MovingBlocks/Terasology/issues/4295 . I also need separate PR's in these modules for this API change: 

- [ ] [Furnishings](https://github.com/Terasology/Furnishings/pull/4)
- [ ] [Health](https://github.com/Terasology/Health/pull/55)
- [ ] [IRLCorp](https://github.com/Terasology/IRLCorp/pull/29)
- [ ] [LightAndShadow](https://github.com/Terasology/LightAndShadow/pull/176)
- [ ] [Machines](https://github.com/Terasology/Machines/pull/42)
- [ ] [MultiBlock](https://github.com/Terasology/MultiBlock/pull/11)
- [ ] [Rails](https://github.com/Terasology/Rails/pull/63)
- [ ] [Smithing](https://github.com/Terasology/Smithing/pull/11)
- [ ] [StructureTemplates](https://github.com/Terasology/StructureTemplates/pull/48)
- [ ] [WoodAndStone](https://github.com/Terasology/WoodAndStone/pull/63)
- [ ] [WorkstationCrafting](https://github.com/Terasology/WorkstationCrafting/pull/17)

```bash
gh pr checkout 4296
for m in Furnishings Health Smithing WoodAndStone WorkstationCrafting StructureTemplates MultiBlock Machines; do
    pushd modules/$m
    git fetch
    git checkout feature/joml-migrate-blockregion
    popd
done
```

### CODE REVIEW

**Comment by jdrueckert** [comment]
Seems to be missing a change on `StructureTemplates`:
```
> Task :modules:StructureTemplates:compileJava FAILED
/media/jdr/Development/Git/Terasology-omega/modules/StructureTemplates/src/main/java/org/terasology/structureTemplates/internal/systems/ProtectedRegionServerSystem.java:75: error: for-each not applicable to expression type
        for (Vector3i pos: blockRegionComponent.region) {
                                               ^
  required: array or java.lang.Iterable
  found:    BlockRegion
```

**Comment by jdrueckert** [comment]
nvm, branch is up, was only missing in the PR description. added it.

**Comment by jdrueckert** [comment]
same for `MultiBlock`

**Comment by jdrueckert** [comment]
Change missing for `Machines`:
```
> Task :modules:Machines:compileJava FAILED
/media/jdr/Development/Git/Terasology-omega/modules/Machines/src/main/java/org/terasology/fluidTransport/systems/FluidTankClientSystem.java:183: error: cannot find symbol
            size = blockRegion.region.size().toVector3f();
                                     ^
  symbol:   method size()
  location: variable region of type BlockRegion
/media/jdr/Development/Git/Terasology-omega/modules/Machines/src/main/java/org/terasology/fluidTransport/systems/FluidTankClientSystem.java:184: error: cannot find symbol
            min = new Vector3f(blockRegion.region.min().toVector3f()).sub(location.getWorldPosition());
                                                 ^
  symbol:   method min()
  location: variable region of type BlockRegion
```

**Comment by jdrueckert** [comment]
change missing for `IRLCorp`:
```
> Task :modules:IRLCorp:compileJava FAILED
/media/jdr/Development/Git/Terasology-omega/modules/IRLCorp/src/main/java/org/terasology/irlCorp/systems/MultiBlockTankAuthoritySystem.java:95: error: cannot find symbol
            healthComponent.maxHealth = (int) (actAsBlock.block.getArchetypeBlock().getHardness() * ((blockRegion.region.sizeX() * blockRegion.region.sizeY() * blockRegion.region.sizeZ()) / 4f));
                                                                                                                        ^
  symbol:   method sizeX()
  location: variable region of type BlockRegion
/media/jdr/Development/Git/Terasology-omega/modules/IRLCorp/src/main/java/org/terasology/irlCorp/systems/MultiBlockTankAuthoritySystem.java:95: error: cannot find symbol
            healthComponent.maxHealth = (int) (actAsBlock.block.getArchetypeBlock().getHardness() * ((blockRegion.region.sizeX() * blockRegion.region.sizeY() * blockRegion.region.sizeZ()) / 4f));
                                                                                                                                                     ^
  symbol:   method sizeY()
  location: variable region of type BlockRegion
/media/jdr/Development/Git/Terasology-omega/modules/IRLCorp/src/main/java/org/terasology/irlCorp/systems/MultiBlockTankAuthoritySystem.java:95: error: cannot find symbol
            healthComponent.maxHealth = (int) (actAsBlock.block.getArchetypeBlock().getHardness() * ((blockRegion.region.sizeX() * blockRegion.region.sizeY() * blockRegion.region.sizeZ()) / 4f));
                                                                                                                                                                                  ^
  symbol:   method sizeZ()
  location: variable region of type BlockRegion
```

**Comment by skaldarnar** [comment]
Without #4301 there's a failing test (as expected):
```
org.opentest4j.AssertionFailedError: expected: <( 5.000E-1  5.000E-1  5.000E-1)> but was: <( 1.500E+0  1.500E+0  1.500E+0)>
```

Updating the branch now to see that it is indeed fixed.

**Review by jdrueckert — APPROVED** [review]

**Review by skaldarnar — DISMISSED** [review]

**Review by skaldarnar — DISMISSED** [review]

**Review by jdrueckert — APPROVED** [review]

**Review by jdrueckert — APPROVED** [review]

**Pull request merged**
