### PR TITLE
Italian translation update

### PR DESCRIPTION
**Pull request by Trekmarvel**
### Contains

New translation with updated strings.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by msteiger** [comment]
add to whitelist

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/622/
Hooray Jenkins reported success with all tests good!

**Comment by msteiger** [comment]
Thank you, @Trekmarvel - what's your experience with the new Weblate interface? Does it work ok?

**Comment by Trekmarvel** [comment]
@msteiger I don't know if the problem with the menu translation in italian on weblate is solved with the latest version. With other projects (Launcher and CrashReporter) works fine.

**Pull request merged**
