### PR TITLE
Update Credits.md

### PR DESCRIPTION
**Pull request by skate54345**
### Contains

Adds credits for new block sound effects that were added

### How to test

Spawn new blocks and hit/destroy them with audio output set up in your testing environment

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by jellysnake** [comment]
Is there a particular reason why this is not part of #3297? It seems like this should be simply part of that PR.
Unless I'm missing something here.

**Comment by Cervator** [comment]
Yeah same PR is fine. If I were to wager a guess then this PR might have come about from a separate edit via the website rather than continuing in a local workspace with the branch from the other PR :-)

**Comment by skate54345** [comment]
@Cervator Yeah, I did this one through the site since it was so quick.  My mistake

**Pull request merged**
