### PR TITLE
Toggle Fall Damage. Command - damageStop

### PR DESCRIPTION
**Pull request by krishnasism**
### Contains

Added damageStop command to toggle damage infliction by fall.
### How to test

Start game with core gameplay.
Fall and test that there is damage. Add command to console - "damageStop" and damage infliction by fall will be toggled. To stop the feature simple enter "damageStop" again to the console.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by nihal111** [comment]
Also went through the issue and found that your solution is only specific to Vertical Fall damages instead of a complete God-mode. Refer to @portokaliu's comment [here](https://github.com/MovingBlocks/Terasology/issues/2837#issuecomment-288017321)

**Comment by portokaliu** [comment]
If we were to nitpick problems in the code, the above mentioned issue about vertical collisions is true, the text for the command is not exactly its description (I kinda see you copy-pasted), thus also related to the permission level to stop damage, which should be cheat.

I'm also not exactly sure that the new HealthCommands class created when the event is processed would ever have the correct values of the player's current settings (the new class would listen to the event after it's created I think)

**Comment by SkySom** [comment]
I feel like toggleFallDamage or something would be be a better command name?

**Comment by Cervator** [comment]
Closing from inactivity and from being a relatively minor change that would be easy to remake in a new branch without the undesired style changes and with a better logic approach. Conflicts in the way now too.

I appreciate the effort @krishnasism and hope you might still be interested in trying out some new code sometime. It seems like we still are forming an opinion on how to best approach damage negation (see #2843 or #2837) so it would probably be easier to restart this from scratch at some point with more discussion done.

**Pull request closed without merging**
