### PR TITLE
[GSOC] Sample PR adding simple content

### PR DESCRIPTION
**Pull request by oitsjustjose**
So, to prove that I'm able to set up a development workspace and have a good understanding of Gradle, JSON, Java (and I supposed GitHub?), here's a very simple modification to the game.

It adds a new tool: a drill (texture made by myself from another project) - whose ability to break blocks is relatively limitless and impressive.

In addition, I've replaced the code for CoreSampleGameplay "giving" the player a pickaxe, shovel and axe to just giving the player one of these.

Obviously not expecting this to be merged, but I hope it's considered as a rite of passage!

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
I would say this counts - although you've got tabs in there instead of spaces! We follow the one true faith here, death to tabs! :D

You might also want to add a build.gradle to that temporary module dir, copied from Core. Regular module dirs under the Terasology org don't get one as Gradle will copy one in automatically. The "embedded" modules here in the engine repo are expected to have a copy. For now. They too shall one day perish in favor of true independent modules living under the Terasology org leaving the engine cleansed of all content!

@GooeyHub: ok to test

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by oitsjustjose** [comment]
Tabs instead of spaces - got it.

Is that everywhere (gradle files, prefabs, Java code) or just specifically the module files?

**Comment by Cervator** [comment]
> Is that everywhere (gradle files, prefabs, Java code) or just specifically the module files?

@oitsjustjose everywhere! Space all the things :D Well, in text-based files anyway.

**Comment by rzats** [comment]
Content like this generally lives in a separate module - these are located in different repos under the [Terasology organisation](https://github.com/Terasology). I've created a [new repository for the module](https://github.com/Terasology/Drills) and invited you to a team that has push access to it. Please move the module to that repo (and let us know when you've done so!)

**Pull request closed without merging**
