### PR TITLE
bugfix: migrate deprecated texture2D

### PR DESCRIPTION
**Pull request by pollend**
found we have some old references for texture2D
```
13:14:24.593 [main] WARN  o.t.e.rendering.opengl.GLSLShader - Shader 'CoreRendering:chunk' failed to compile for features '[]'.
Game output: 
Game output: Shader Info: 
Game output: ERROR: 0:506: Invalid call of undeclared identifier 'texture2D'
Game output: ERROR: 0:509: Use of undeclared identifier 'maskColor'
```

ref: https://github.com/Terasology/CoreRendering/pull/72

### CODE REVIEW

**Comment by keturn** [comment]
I get an error with the splashscreen, which doesn't close and it's showing uninitialized memory.

```
Exception in thread "splashscreen-loop" java.lang.RuntimeException: 0(9) : error C7532: global function texture requires "#version 130" or later

	at org.terasology.splash.glfw.graphics.Shader.checkStatus(Shader.java:87)
	at org.terasology.splash.glfw.graphics.Shader.compile(Shader.java:78)
	at org.terasology.splash.glfw.graphics.Shader.createShader(Shader.java:119)
	at org.terasology.splash.glfw.graphics.Shader.loadShader(Shader.java:146)
	at org.terasology.splash.glfw.graphics.Renderer.setupShaderProgram(Renderer.java:408)
	at org.terasology.splash.glfw.graphics.Renderer.init(Renderer.java:77)
	at org.terasology.engine.GLFWSplashScreen.run(GLFWSplashScreen.java:103)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by pollend** [comment]
> I get an error with the splashscreen, which doesn't close and it's showing uninitialized memory.
> 
> ```
> Exception in thread "splashscreen-loop" java.lang.RuntimeException: 0(9) : error C7532: global function texture requires "#version 130" or later
> 
> 	at org.terasology.splash.glfw.graphics.Shader.checkStatus(Shader.java:87)
> 	at org.terasology.splash.glfw.graphics.Shader.compile(Shader.java:78)
> 	at org.terasology.splash.glfw.graphics.Shader.createShader(Shader.java:119)
> 	at org.terasology.splash.glfw.graphics.Shader.loadShader(Shader.java:146)
> 	at org.terasology.splash.glfw.graphics.Renderer.setupShaderProgram(Renderer.java:408)
> 	at org.terasology.splash.glfw.graphics.Renderer.init(Renderer.java:77)
> 	at org.terasology.engine.GLFWSplashScreen.run(GLFWSplashScreen.java:103)
> 	at java.base/java.lang.Thread.run(Thread.java:829)
> ```

looks like I forgot to add this to the header

` #version 330 core`

**Comment by pollend** [comment]
@keturn needed to update the version to compile the shader

**Review by keturn — APPROVED** [review]
yep, that fixed the splashscreen. :+1:

**Pull request merged**
