### PR TITLE
PerformanceMonitorRefactoring (reduced)

### PR DESCRIPTION
**Pull request by emanuele3d**
This PR is a subset of #1751: it only contains its first commit in case the second commit of 1751 is a step too far. If 1751 gets merged this PR should auto-close. 

See commit description for further specific details. Also notice that 1751 holds comments this PR's [single commit](36cf9bf23b42f76793a5d5968ef4e25986aa9706).

### CODE REVIEW

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/121/
Hooray Jenkins reported success with all tests good!

**Comment by msteiger** [comment]
I'd like to merge this before #1751, since it should considerably reduce the number of changes there. That would make it easier to review.

**Comment by Cervator** [comment]
I'm happy to merge fast if all is well :-)

@emanuele3d on the extra spacing yeah I used to like that myself but it starts getting into tabs vs spaces land - it might not always look right and different people might end up using it differently leading to inconsistent code style.

Probably just grouping variables together if they share similarities is enough :-)

**Comment by emanuele3d** [comment]
@msteiger: interesting that you mention merging this first to make #1751 easier to review. So my links in #1751's description to the individual commit's diffs are not helpful in breaking down the PR into more easily reviewable chunks? I mean, this PR is the first half of #1751. If you want to review the second half alone the link to the appropriate diff is in the PR's description. That doesn't help for reviewing purposes?

@Cervator: thank you for letting me know about the extra spacing problems. I will remove the extra spaces and add some empty line to separate groups of variables.

So, this PR nor #1751 is quite ready yet. And given what msteiger says I now need to understand if I should do changes to the first commit here in 1752 or in 1751.

**Comment by emanuele3d** [comment]
Closing as #1751 is a superset of this PR and seems to be heading for a merge.

**Pull request closed without merging**
