### PR TITLE
JoshariasSurvival is now selected as the first default gameplay template

### PR DESCRIPTION
**Pull request by xrtariq2594**
### Contains

Provides a solution to issue #2352, and also adds an "Enable All" button to the module selection screen, which selects all available mods.

**EDIT**: Reverted "Enable All" changes.

### How to test

- Delete the user config file (somehow, perhaps by cloning a fresh copy of the engine?)
- Make sure "JoshariasSurvival" template is downloaded and included.
- Load up the game
- Go to the "Create Game" screen.
- It should be selected by default.

### Credits

@Cervator: For giving me advice on this matter.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Looks like it works! With two small enhancements needed: with JS set as the default template the `CreateGameScreen` just picks the first available world gen, no sorting or preference. Yet JS has config to indicate its preferred world gen (in `module.txt` from JoshariasSurvival):

`"defaultWorldGenerator" : "Core:FacetedPerlin"`

That's respected when the user *changes* the gameplay template ("Perlin" gets picked) but as-is "Flat" gets picked by default, which is kinda boring :-)

Secondly the entry in `default.cfg` results in CoreSampleGameplay remaining enabled even for JS, so you get the Core goodie chest in JS where you should start with a blank inventory. It also enables both JS and CSG if you run a headless server. With `"coresamplegameplay",` removed it looks good :-)

Btw you can simply delete `config.cfg` to simulate a clean start without existing config.

One tricky scenario remains: what if JS is not available. The CreateGameScreen should be handling it gracefully, but the default config less so when executed as a headless server?

I tested it out by building the app locally `gradlew distApp` then copied in a few modules (also noted https://github.com/Nanoware/Terasology/issues/84 as something broke there for local workspaces) but not JS. Headless server attempted to start with JS but failed :(

```
01:38:08.677 [main] INFO  o.terasology.engine.TerasologyEngine - Initialization completed in 1.81sec.
01:38:08.984 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.NullPointerException: null
	at org.terasology.engine.module.StandardModuleExtension.isGameplayModule(StandardModuleExtension.java:55)
	at org.terasology.engine.subsystem.headless.mode.StateHeadlessSetup.createGameManifest(StateHeadlessSetup.java:129)
	at org.terasology.engine.subsystem.headless.mode.StateHeadlessSetup.init(StateHeadlessSetup.java:104)
	at org.terasology.engine.TerasologyEngine.switchState(TerasologyEngine.java:503)
	at org.terasology.engine.TerasologyEngine.changeState(TerasologyEngine.java:486)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:367)
	at org.terasology.engine.Terasology.main(Terasology.java:139)
01:38:08.984 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
```

So for now it may be easier to just leave it as a convenience in the UI but not in the default config :(

I confirmed with the same build that the UI handles the lack of JS the module just fine. Just headless breaks with the default config change.

**Comment by xrtariq2594** [comment]
Hmm, I'll look into simulating a change to respect the world gen.

I'll remove that entry from the default config file.

Huh, I'll have to discuss that matter more in the Slack chat.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Initial testing looks good from a UI perspective. Then headless server testi.. :zzz: :sleeping:

**Comment by Cervator** [comment]
Bump - @xrtariq2594 did you have one more commit to add to this? Either a strategy to gracefully default to JS for headless if present or just leave that as it was before?

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
That did it - all set! Thanks :-)

**Pull request merged**
