### PR TITLE
chore: migrate ssao 330

### PR DESCRIPTION
**Pull request by pollend**
migrate ssao for opengl 330, can be verified by enabling ssao from the settings.

### CODE REVIEW

**Comment by pollend** [comment]
PR: https://github.com/Terasology/CoreRendering/pull/42

**Comment by jdrueckert** [comment]
I had a look at this in-game, but honestly, I have no idea how I can properly test this.
I don't really see a difference with or without SSAO checked in the settings.
Guess I just don't know what to look out for.
I mean at least it didn't crash or look completely weird or anything...

**Comment by pollend** [comment]
SSAO is a cheap way to approximating ambient occlusion. just look at the corners of blocks the shadows are better with SSAO then the vertex border stuff we do to kind of approximate the shadows at the corner of blocks. 

with SSAO
image

without SSAO

image

**Comment by jdrueckert** [comment]
[OpenGL migrations](https://trello.com/c/0nyhaO6R/124-opengl-migrations)

**Pull request merged**
