### PR TITLE
feat(JOML): add orientation for Rotation

### PR DESCRIPTION
**Pull request by pollend**
This is a simple change for the orientation of the Rotation. This is just an api change that should help with migrating changes for orientation. there are no direct impacts at the moment. I also updated the test case to test for consistency.

### CODE REVIEW

**Review by DarkWeird — APPROVED** [review]
looks good.

**Comment by pollend** [comment]
I think this looks good other then the naming I had concerns with for rotation.

**Review by jdrueckert — CHANGES_REQUESTED** [review]
Compilation fails with 
```> Task :engine-tests:compileJava
/home/jenkins/agent/workspace/Terasology_engine_PR-4124/engine-tests/src/main/java/org/terasology/testUtil/TeraAssert.java:145: error: method assertEquals(Quaternionfc,Quaternionfc,float) is already defined in class TeraAssert
    public static void assertEquals(Quaternionfc expected, Quaternionfc actual, float error) {
                       ^
```
@pollend @DarkWeird Please have another look.

**Comment by pollend** [comment]
@jdrueckert I had to create a new PR since this commit is before bullet and NUI.

**Pull request closed without merging**
