### PR TITLE
Made UITextHint widget

### LINKED ISSUE #2740: UI Widget Proposal: UITextHint
Hello there

# Write a proposal for a new UI widget: UITextHint

**What is UITextHint?**
Nowadays, people are lazy. They just DON’T want to hover over a UIText to see the tip! To make it as easy as possible for our users to gain important information, we should use a UITextHint! It’s basically a string of text that displays on the UIText (or any other input system), that goes away whenever the user writes something. This information could contain for instance information on what to write, a quote, or even an aesthetic meme.

**What is UITextHint’s purpose?**
As described above, people are lazy! This UITextHint could make the user’s life easier. Every single piece of modern software has this functionality, so I think a game such as Terasology should have this as well.

**How can developers implement this?**
This is a tricky question. Mainly my idea would be having a new attribute added to NUI, usable for UIText widgets. This could make it even easier, as it’s just one line of code really. This however would need some cooperation from the NUI developers. But once this cooperation is there, it’s really easy to implement a new sweet UITextHint widget.
So there are really two options; one would be adding a new Widget which would be called UITextHint, the other would be adding an attribute.

**How should this Widget be exposed?**
Quite easy for this one, basically just the text which is displayed by the hint, and perhaps some extra options such as the shade of the text? (Color)?
Most of the hints aren’t the same color as actual text, but slightly lighter, darker color. (ARGB-Color?)

**Personal point of view on this module**
As an avid supporter of hints, I think this would be extremely useful for UI-intensive modules, such as my own LOTRModule which I still have to start working on. :) 
I’d personally really prefer the new attribute, as this would be easier for everyone, more powerful and requires less lines of code.

**Hint example screenshot:**

text-field-nocomment

If anything is unclear to you, please tell me so I can improve.
Thanks

### PR DESCRIPTION
**Pull request by arpan98**
### Contains

Fixes #2740 
Added a new widget called `UITextHint` exposing the additional field `hintText`.
Added a field called `hintTextColor` in `UIStyle` which is defined in `default.skin`.

### How to test

Added it to the `migTestScreen`. 

### Outstanding before merging
Decide the hint text color, and whether it needs to be exposed to ui as suggested in the original issue.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Thanks for the PR! Out of time tomorrow but hoping maybe @rzats can check this out soon. Otherwise I'll circle back around later to check it out :-)

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by arpan98** [comment]
Sounds reasonable. I integrated the functionality into UIText. Have a look now.

**Comment by Cervator** [comment]
@rzats - ping! Would you approve these changes now after the latest commit? :-)

**Comment by rzats** [comment]
I definitely will! Should we merge this now?

**Comment by Cervator** [comment]
> I definitely will! Should we merge this now?

If you approve it, merge it! Small stuff like this anyway :-)

**Comment by Cervator** [comment]
Merged :-)

Thanks @arpan98, especially for continuing to add examples on the `migTestScreen` !

If you feel like expanding on that sometime I'm adding issues at https://github.com/Terasology/TutorialNui/issues for more complete examples and usage docs of various UI elements

**Pull request merged**
