### PR TITLE
Fix for issue #1890

### PR DESCRIPTION
**Pull request by andrelago13**
Temporary fix for issue #1890. (temporary because I intend to replace the module description panel by a tabbed panel)

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
Gooey: Test this please

ok to test

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/337/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Tests out fine, including the language switch, nice! Added to credits too, and tagged three of you in the forum as well, missing an account for @Netopya tho :-)

**Comment by andrelago13** [comment]
Great!

**Pull request merged**
