### PR TITLE
NUI editor: additional settings and finishing touches

### PR DESCRIPTION
**Pull request by rzats**
### Contains

Various improvements to the NUI screen/skin editors; see rzats/gsoc-nui-editor#10, rzats/gsoc-nui-editor#13 and rzats/gsoc-nui-editor#14.

- Added a 'Preview screen locale' setting - this will change the language of the editor's preview widget (but not the NUI editor or the game itself). Useful for reviewing things such as long UI strings that may break interface rendering!
- Added a "Close" button to the editors (as an alternative to ESC & F10/F11) and a "Delete" option to tree view node context menues (as an alternative to DELETE).

### How to test

Press F10/F11 in the main menu to run the NUI screen/skin editors, then verify that all of the above work as intended :smile:

### Outstanding before merging

- [ ] Implement the features from rzats/gsoc-nui-editor#13 (tree view to widget binding).
- [x] Review the source code's Javadoc, modify and fill stubs where appropriate.
  - [x] Also fix Checkstyle warnings where appropriate.
- [x] Autosave the asset changes to a temporary JSON file, then add an option to apply the changes to the actual asset file.
- [x] Add a popup to warn the user that changes will be lost on asset change.
- [x] Automatically edit newly added attributes.
  - [x] Automatically edit the IDs of newly added widgets.
- [x] A "Debug Tools" menu with options to show different dev tools (console, UI editor, skin editor, BT editor).
- [x] When the editor's strings are somewhat finalized, internationalize them all!

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
I know there has been a good amount of chat about this one on Slack and there are still two unchecked boxes up top, but is this getting close enough where I can help any with merge testing or anything? :-)

I noticed the issue the top unchecked box leads to has already been closed as well. Feels like this one is close!

**Comment by rzats** [comment]
@Cervator: the top item is still a WIP. It's mostly a visual extra though, so at this point testing would be really appreciated :smiley:

**Comment by Cervator** [comment]
Played around with it some :-) Probably not as thoroughly as @flo would. Works well for me!

Curious question: should something like alignments where there is a finite set of options be editable via drop-down or other selection of just the valid values? Anything that can be backed by an enum so to say. Maybe still with free-form available.

Should there be a "duplicate" option for some things? Like if you're adding a bunch of similar fields.

I realize those are more future suggestions to probably put in a list somewhere rather than actual feedback on this PR ... :D

I did manage to crash the game at one point by attempting to add a widget of type `engine:Port` : 

```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Cannot construct 'engine:Port' - no accessible default constructor
```

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by flo** [comment]
With the option to save (module assets) with a single click I think we got an very important extra feature added.

You checked "Autosave" above as implemented feature, but it does not seem to be implemented. Although we warn now the user about unsaved changes when he switches the asset which is good.

**Pull request merged**
