### PR TITLE
Added more teleport commands

### LINKED ISSUE #2534: More teleport commands
We currently have `teleport` which ports the player to a given `x`, `y`, `z` coordinate, but we do not have player to player teleport variants. We should add:

* `teleportMeToPlayer <String>`
* `teleportPlayerToMe <String>`
* `teleportPlayerToPlayer <String> <String>`

The `<String>` parameter should be both usable with player names or a player id (in case of unusual characters). I think `kick` may already work that way.

Actually writing the command variants probably won't be too difficult, other than maybe figuring out where another player is (can likely check out the `kick` command to see how to look up a player). However, there may be an outstanding issue with how some commands are registered for multiplayer scenarios (headless, pure client connections without a local server). If so that may become a bit of a blocker for making this easy.

Check out the discussion in #1619 and the attempted implementation of related fixes in #2217 which includes work on the base teleport command. That PR stalled and may provide some inspiration or clarify any obstacles. I'm not sure if @HashCode55 is still around to help with the topic or finish that PR, but it is probably fair at this point to drag any useful code from there into a new PR.

If the multiplayer command registration issue gets in the way of this issue it may be a usable workaround to solely play on a client-server instance of the game (not headless), since then at least the primary player has the server side authority stuff needed to execute the commands while affecting other players, even if secondary players cannot.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/38395074-more-teleport-commands?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by portokaliu**
This change added the (maybe) much needed commands to influence more than the local player and more than one player's position at the same time.

Commands added with this commit would be:
- `teleportMeToPlayer <String>`
- `teleportPlayerToMe <String>`
- `teleportPlayerToPlayer <String> <String>`
- `teleportAllPlayersToLocation <float> <float> <float>`
- `teleportAllPlayersToPlayer <String>`

This in turn fixes #2534 which required some of these changes. The last two commands were added for event convenience ( like when you want to bring all people on the server to a certain location to see something or try something ) 

The commands that influence other player's locations need 'userManagement' permissions, while the ones that only influence your location require 'cheat' permissions.

To test, you can use any of the command while on a server. 

I've only tested this on a local server and it worked well with 2 players (with different permission levels, and both of them using commands)

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by portokaliu** [comment]
I've thought about something that might affect one of the commands. We could have a boolean modifier to the teleportAllPlayersToPlayer command that, if true, sets the movement modes of all teleported players to the user they teleported to. This would mean that if you are in 'ghost' mode and want to teleport everyone to you, you have the ability to set all of them to 'ghost' mode with that one command (so they don't fall to the ground or something)

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by portokaliu** [comment]
Don't mind me, just getting used to git...

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Tested around some with three local clients. Looking good! Thanks :-)

**Pull request merged**
