### PR TITLE
build(IntelliJ): update annotation paths and other configurations

### PR DESCRIPTION
**Pull request by keturn**
Updates IntelliJ's configuration with the newer location of Terasology annotations. Assorted other updates to `/.idea/` while we're here. See individual commit messages for details.

If you squash-merge this, please be sure the contents of those commit messages are included!

### How to test

I wrote this on IntelliJ 2021 Ultimate edition under Linux. It would be good to have someone test

- [ ] under Windows
- [x] using IntelliJ Community Edition

The primary thing to look out for is diff thrashing. The intention behind checking this in is to provide a configuration that _matches_ what we use in practice. If your IDE makes changes to these files every time you start it (leaving your working directory "dirty") it may defeat the purpose.

**However,** it might be confusing for IntelliJ if git makes changes to these files _while you have IntelliJ open._ Before reporting problems with this PR, try

1. Closing IntelliJ
2. pulling this branch (or resetting local changes if you already have this branch checked out)
3. Start IntelliJ
    + look for changes with git status or git diff
    + [anything else you need to do to make sure the project is not broken in IntelliJ]
4. Close IntelliJ
    + look for changes with git status or git diff

### CODE REVIEW

**Comment by jdrueckert** [comment]
Successfully tested with IntelliJ Community Edition 2021.1.3 (on Linux, though).

**Comment by skaldarnar** [comment]
Tested this on Mac with IntelliJ IDEA 2021.1.3 (Community Edition). 

As I did some Scala development with the same IDE and have the respective plugin installed, I do see a diff from just opening the project in IntelliJ.
```diff
diff --git a/.idea/codeStyles/Project.xml b/.idea/codeStyles/Project.xml
index 71ae82796..53141068f 100644
--- a/.idea/codeStyles/Project.xml
+++ b/.idea/codeStyles/Project.xml
@@ -13,6 +13,9 @@
     <JetCodeStyleSettings>
       <option name="CODE_STYLE_DEFAULTS" value="KOTLIN_OFFICIAL" />
     </JetCodeStyleSettings>
+    <ScalaCodeStyleSettings>
+      <option name="MULTILINE_STRING_CLOSING_QUOTES_ON_NEW_LINE" value="true" />
+    </ScalaCodeStyleSettings>
     <codeStyleSettings language="JAVA">
       <option name="RIGHT_MARGIN" value="140" />
       <option name="WRAP_COMMENTS" value="true" />
```

**Comment by keturn** [comment]
yeah, code styles are another thing we're probably due for another look at, especially with the recent focus on reducing the warnings from checkstyle and other analytics.

But that's not particular to this PR, is it?

**Comment by skaldarnar** [comment]
> But that's not particular to this PR, is it?

No, I don' think so. It's just a general flaw of Jetbrain's desing decisions...

**Pull request merged**
