### PR TITLE
Pull in TeraMath compatibility, remove engine's Vector3i

### PR DESCRIPTION
**Pull request by Josharias**
Use the newest version of TeraMath from https://github.com/MovingBlocks/TeraMath/pull/26

Rename org.terasology.math.Vector3i into org.terasology.math.Vector3iUtil and make all its unique methods static. 

I have a large number of the modules in my working copy as well and will make appropriate PRs on those repos as well in the next day or so.

### CODE REVIEW

**Comment by Josharias** [comment]
Cervator,  Would you be able to walk me through the process of using the new TeraMath library after it is merged?  Likely its just updating a version number someplace, right?

**Comment by Cervator** [comment]
Yeah TeraMath isn't fully set up the "formal" way when it comes to releases. 

There is a version tag in https://github.com/MovingBlocks/TeraMath/blob/develop/gradle.properties you can increment either in your PR or after merging it. 

http://jenkins.terasology.org/view/Libs/job/TeraMath/ should build automatically after the merge and will publish a snapshot to Artifactory's libs-snapshot-local (as said no release / non-snapshot setup is live yet)

After a new version is in Artifactory the engine should pick it automatically due to https://github.com/MovingBlocks/Terasology/blob/develop/engine/build.gradle#L124 still being configured to using the very latest version it can find

Really we should make a proper release job that makes non-snapshots and changing the engine dependency to a hard-set version, but that can wait till after this sometime. I want to go over the release-needing jobs in Jenkins soon enough :-)

@msteiger + @skaldarnar either or both of you should probably test/merge this. If you review and are happy with it yet want me to run it through my mega-workspace to catch any broken modules let me know and I can do that.

**Comment by Josharias** [comment]
Light And Shadow is remaining.  I accidentally mixed the change in with something else.

**Comment by Josharias** [comment]
Yes,  I can confirm that it automatically picks up the new TeraMath library.  Thanks for merging that @msteiger.

**Comment by Cervator** [comment]
So should we start clicking buttons or doing Git stuff manually to get this PR + friends merged? :-)

**Comment by Josharias** [comment]
All this looks good from my perspective.  I have made PRs from local branches in the the modules I had in my workspace to hopefully make this process easier.  @Cervator,  maybe you would be best suited to merge the modules and then i[date them in your mega workspace and fix the few strays that have been missed.  Or maybe it might be easier just to do the module fixes yourself and commit?  Dunno.  It is just a lot of noise no matter the angle you look at it.

**Comment by Cervator** [comment]
Yep I can do the main PR merge then grab all the module PRs and finally catch any stragglers. Just need to find some time for it.

**Comment by Cervator** [comment]
Test this please

(Yay the PR builder plugin is working!)

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/2/
Jenkins Success Message

**Comment by Cervator** [comment]
Finally got through this and all the modules! Thanks for priming some of them, especially with a branch instead of a fork, made it a fair bit easier :-)

28 modules changed in total. Notification spam inc!

**Comment by Cervator** [comment]
Hmm, trickier than I thought! Local builds are fine. Module builds in Jenkins break

Been testing with AnotherWorld: http://jenkins.terasology.org/view/Modules/job/AnotherWorld/64/console

This has happened before where a newer snapshot has been reluctant to start resolving in Jenkins, but I outright deleted the entire Gradle cache on the server and added --refresh-dependencies to the module build template. I also wiped my local Gradle cache in case I had a false positive on things looking good. I also rebuilt the engine in Jenkins after the cache wipe and verified the newly pulled TeraMath looked to be the right version.

I noticed the TeraMath.calcBlockPos in BeachDecorator is deprecated, as is what it uses in the engine TeraMath wrapper.

But still, it works in IntelliJ locally, but not in Jenkins. What gives? I'm confused and sleepy, out of time for tonight :-)

**Comment by Cervator** [comment]
Found it after another evening sunk into fun triage - the Artifactory plugin for Jenkins fixed a bug we have been getting a free ride on for ages ;-)

I updated the plugins as part of the dynamic builder setup. Didn't matter at first since the couple PRs I merged were inconsequential when related to dependency resolution.

TeraMath/Vector3i change hit - boom! The module jobs were suddenly respecting the resolution repo setting for where to get dependencies, and with their correct config weren't pointing to the right place to get the latest engine dependency (or so - TeraMath itself seemed fine)

So now we can finally do it right, but at nearly 1 am I'm not awake enough or staying around long enough to fix. But at least I know *what* to fix now ;-)

**Pull request merged**
