### PR TITLE
PerformanceMonitor: augmented javadocs, some refactoring

### PR DESCRIPTION
**Pull request by emanuele3d**
I wanted to learn more about the PerformanceMonitor, in the context of creating a new set of metrics that can be seen pressing the F4 key. In the process of going through the code I saw a number of
opportunities for improving the javadocs and, to a minor extent, improving the readability of the code.

This PR attempts to fullfill those opportunities. 

The [first commit](36cf9bf23b42f76793a5d5968ef4e25986aa9706) should be relatively uncontroversial: it just adds or refine javadocs to PerformanceMonitor and does some minor refactoring to PerformanceMonitorImpl. I imagine however the wording on some of the javadocs could be further refined.

The usefulness of the [second commit](ba965b1cd7c842d3433a9c28fdfb17c9d02173cc) is perhaps more debatable: primarily it makes the rollCycle() method more concise and readable by explicitly defining and instantiating (once) procedure classes rather than using anonymous ones. Furthermore it refactors getRunningMean() and getAllocatedMean() using a similar strategy.

Should the second commit be a step too far, I will anyway submit shortly a second, parallel PR including only the first commit. Cervator suggests that if this PR goes through the other one will be automatically closed. If this PR is too much, the other one will represent plan B.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/120/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Tests out fine :-)

Looked at the code and it doesn't look crazy or anything. Just tweak the spacing and I say we merge it.

One maybe to look at - the "Memory Allocations" section you can toggle to with F4 lists the entries in ms - does that make sense? How is it a memory allocation?

That's probably pre-existing though

**Comment by emanuele3d** [comment]
Yes, I think I'm going to fix the ms thing in memory allocation, but it's elsewhere, it doesn't actually have anything to do with the PerformanceMonitor but how the data from it is formatted.

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/130/
Hooray Jenkins reported success with all tests good!

**Comment by emanuele3d** [comment]
Ok, I think I've addressed all comments. I also added a few minor last minute changes marked in the third commit's description as "new". 

For those who had a look at the **second commit**, here's the [diff](51f52f77f8ec14630cacda55ef315de52222c384) with the third commit.
For those who had a look only at the **first commit**, here is a [diff](https://github.com/emanuele3d/Terasology/compare/36cf9bf...51f52f7) with the third commit.

I will now close #1752 as it appears this PR might go through after all.

**Comment by Cervator** [comment]
Looked over the additional changes some and tested again, all seems well (and so thoroughly documented!) so I'm merging :-)

**Comment by emanuele3d** [comment]
Yay! Thank you!

**Pull request merged**
