### PR TITLE
# Attempt to fix issue 2591

### LINKED ISSUE #2591: Resizing not working properly
### What you were trying to do
Resize window

### What actually happened
window resized but not the "rendering area" (something like #2490 but for blocks)
Skybox and water are rendered as expected
outline is visible on line between rendered zone and empty one (when outline is enabled in options)

### How to reproduce

* Step 1 turn on outilne in graphic settings
* Step 2 resize window before joining server or opening local game (after loading world it won't work)
* Step 3 see weird things going on

###More sophisticated explanation

After starting Terasology, entering game and resizing this bug occurs. After quitting game without quitting Terasology, entering game again and resizing bug #2490 occurs but not this one, and bug 2490 stays on the screen even after quitting game and resizing window again (skybox rendering width stays the same all the time when bug #2490 occurs)

### Log details and game version  

version 1 836 alpha 2016-11-05T03:55:30Z
[Terasology-.log.txt](https://github.com/MovingBlocks/Terasology/files/573349/Terasology-.log.txt)
[Terasology-init.log.txt](https://github.com/MovingBlocks/Terasology/files/573350/Terasology-init.log.txt)
[Terasology-menu.log.txt](https://github.com/MovingBlocks/Terasology/files/573348/Terasology-menu.log.txt)
[Terasology-mmo.to-188.68.52.110-25778.log.txt](https://github.com/MovingBlocks/Terasology/files/573351/Terasology-mmo.to-188.68.52.110-25778.log.txt)

### screens  
http://i.imgur.com/2KSFJex.png
http://i.imgur.com/NhzE3DE.png

### Computer details

OS: Ubuntu 16.10 yakkety
Kernel: x86_64 Linux 4.8.0-26-generic
Resolution: 1366x768
CPU: Intel Core i5-5200U CPU @ 2.7GHz
GPU: GeForce 920M (Nvidia drivers 370.28)
RAM: 7886MiB
Java version: 1.8.0_111

### PR DESCRIPTION
**Pull request by emanuele3d**
### Contains
Attempt to fix #2591 

### How to test
Follow the instructions in #2591  on how to reproduce the problem and verify it no longer occurs.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Tried this out along with the steps from #2591 I couldn't provoke any issues at all with the outline shader, although I didn't hit that in the first place (didn't do as many different things as @Halamix2 though so I could just have missed it)

It might also be that the resizing got a little better. One spot I got black background when resizing the window larger, one time I got the pure sky background without blocks, and one other time it *almost* resized correctly (only a slight margin missing that was way smaller than the resize difference, showing sky)

The water issue was also present, so #2528 and #2490 remain valid. One observation I made is that after you "fix" the water (by messing with the graphic settings) it renders with an offset (screenie below). It isn't quite in the right place. The margin also shifts a bit when I turn from side to side, like the camera isn't quite in sync with the position / facing in the world. Maybe that helps suggest further areas for investigation :-)

Since it doesn't seem to hurt and might be helping I'm merging this, should also make it easier for @Halamix2 to check on the fix for #2591 

Thanks for the quick response @emanuele3d !

terasology-161105233531-1747x997

**Comment by emanuele3d** [comment]
As mentioned elsewhere I think this fixes #2490 rather than #2591. Sorry about the mix up.

@Cervator: can you find the steps to reproduce the problem shown in the screenie? Not so much the water problem but the world rendering not covering the whole window.

**Comment by emanuele3d** [comment]
Edited PR subject and description to reflect this is a fix for #2490. 

Issue #2591 is still at large, although I have seen an NPE in the log complaining the outline (sobel) shader was not found. I'll have to investigate.

**Pull request merged**
