### PR TITLE
Add Open Code of Conduct to the repo.

### PR DESCRIPTION
**Pull request by MaloJaffre**
See #1975.
I set the report adress to cervator@gmail.com, we can change it later.
~~I also use a little antispam trick.~~

### CODE REVIEW

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/387/
Hooray Jenkins reported success with all tests good!

**Comment by msteiger** [comment]
Is this an official document?

I don't think that the anti-spam trick is necessary since the address can be easily extracted from the git commit author line.

**Comment by MaloJaffre** [comment]
This is https://github.com/todogroup/opencodeofconduct.

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/392/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Yeah I wouldn't worry about anti-spam, there are doubtlessly so many tricks out there to parse the real email back out. I'm not too concerned having my email in more places, thank you for thinking about it though! :-)

@msteiger this is a sort of response to a recent effort in open source land to reach out to contributors and ensure them there are options to direct complaints for a particular project. I noted it briefly as a line item in #1975 - see https://github.com/todogroup/opencodeofconduct

We probably should have some sort of formal decision/review on "joining", maybe in a forum thread or a soonish minimal dev meeting to do final sign-off on Alpha. Just a few people with no objections would be enough of a quorum IMHO. Maybe we should do some edits. For any general complaints we could forward to the forum's contact form rather than just me directly, or make an email forward. But that in turn might defeat the whole purpose of knowing you're not complaining to the person you're wanting to complain about :-)

I'm trying to get on top of all the PRs you two submit so I can get back on documentation including this - think I'm almost there :D

**Comment by Cervator** [comment]
Working on a doc overhaul at present. Both involves files here in this repo including this one, along with the main wiki and even the Launcher as it has a nice CONTRIBUTING doc I'm grabbing as well.

Got too late for tonight to finish though so will aim to merge tomorrow :-)

**Comment by Cervator** [comment]
Merged this in with minimal tweaks. Changed email to abuse@terasology.org which forwards to me (and anybody else who wants a forward). Some more details on doc work: http://forum.terasology.org/threads/engine-v1-0-0-alpha-rc-1-and-a-terasology-panel-at-betterthanminecon.1427/#post-12773

**Pull request merged**
