### PR TITLE
Type handling (serialization) improvements

### PR DESCRIPTION
**Pull request by eviltak**
A follow up of #3453, this PR simplifies the interface used to serialize objects and makes it extremely easy to serialize arbitrary objects using either Protobuf or Gson. `TypeHandlingIntegrationTest` shows how easy it is to serialize an arbitrary generic object with supertype references in fields (the test linked below includes both serialization and deserialization via Protobuf):

https://github.com/MovingBlocks/Terasology/blob/c9fd8934282be2d0bf57968a6e1c9ecc8cffc5b0/engine-tests/src/test/java/org/terasology/persistence/typeHandling/TypeHandlingIntegrationTest.java#L87-L111

For context, the class being serialized in the above test is this (where `Animal` is an abstract class with two subclasses):

```java
    private static class SomeClass<T> {
        private T data;
        private List<T> list = Lists.newArrayList();
        private Set<Animal> animals = Sets.newHashSet();
    }
```

# Changes
- Remove `DeserializationContext`
- Add factories for type handlers (`Rect2f`, `Rect2i`, `Region3i`) previously relying on `DeserializationContext.deserializeAs` which look up the type handlers they need
- Remove `SerializationContext.create(T, Class<? extends T>)`
- Rename `SerializationContext` to `PersistedDataSerializer`
- Rename `PersistedDataSerializer.createXYZ` methods to `serializeXYZ`
- Add `ArrayTypeHandler` (+ Factory)

# TODO
- [x] Add null handling in every TypeHandler -- null/default value handling takes place in `ObjectFieldMapTypeHandler` but still look for a better way to easily handle null values without having to `if(value == null) { return serializer.serializeNull(); }` in every single type handler
- [ ] Further simplify external Gson and Protobuf serialization workflow 
- [x] ~Load types from name via a `ClassLoader`(s) in `RuntimeDelegatingTypeHandler`to stay within the sandbox~ To be handled in a later PR
- [ ] Rebase onto `develop` after #3453 is merged

## Broken modules
- [ ] Dialogs (used by L&S)
- [ ] DynamicCities
- [ ] LightAndShadow - GSOC sensitive
- [ ] MasterOfOreon - GSOC sensitive
- [ ] Tasks (used by L&S)
- [ ] TutorialDynamicCities

### CODE REVIEW

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Tested this out to continue efforts earlier on Slack - I still get an error on JoshariasSurvival :-(

```
22:03:14.397 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab ManualLabor:ToolAssemblingBaseProcessPart with inputs [/ManualLabor/assets/prefabs/processDefinitions/ToolAssemblingBaseProcessPart.prefab]
22:03:14.499 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.IllegalStateException: Data is not an array: bytes: ""

	at org.terasology.persistence.typeHandling.protobuf.ProtobufPersistedData.getAsValueArray(ProtobufPersistedData.java:394)
	at org.terasology.persistence.typeHandling.protobuf.ProtobufPersistedData.iterator(ProtobufPersistedData.java:401)
	at org.terasology.persistence.typeHandling.coreTypes.CollectionTypeHandler.deserialize(CollectionTypeHandler.java:56)
	at org.terasology.persistence.typeHandling.TypeHandler.deserializeOrNull(TypeHandler.java:68)
	at org.terasology.persistence.typeHandling.Serializer.deserializeOnto(Serializer.java:96)
	at org.terasology.persistence.typeHandling.Serializer.deserializeOnto(Serializer.java:153)
	at org.terasology.persistence.serializers.ComponentSerializer.deserializeOnto(ComponentSerializer.java:197)
	at org.terasology.persistence.serializers.ComponentSerializer.deserialize(ComponentSerializer.java:114)
	at org.terasology.persistence.serializers.PrefabSerializer.applyComponentChanges(PrefabSerializer.java:164)
	at org.terasology.persistence.serializers.PrefabSerializer.deserialize(PrefabSerializer.java:136)
	at org.terasology.persistence.serializers.PrefabSerializer.deserialize(PrefabSerializer.java:116)
	at org.terasology.entitySystem.prefab.internal.PrefabFormat.load(PrefabFormat.java:55)
	at org.terasology.entitySystem.prefab.internal.PrefabFormat.load(PrefabFormat.java:36)
	at org.terasology.assets.module.UnloadedAssetData$AssetSourceResolver.load(UnloadedAssetData.java:292)
	at org.terasology.assets.module.UnloadedAssetData.load(UnloadedAssetData.java:180)
	at org.terasology.assets.module.ModuleAssetDataProducer.getAssetData(ModuleAssetDataProducer.java:228)
	at org.terasology.assets.AssetType.lambda$reload$2(AssetType.java:359)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.terasology.assets.AssetType.reload(AssetType.java:357)
	at org.terasology.assets.AssetType.getNormalAsset(AssetType.java:386)
	at org.terasology.assets.AssetType.getAsset(AssetType.java:262)
	at org.terasology.assets.management.AssetManager.getAsset(AssetManager.java:223)
	at org.terasology.engine.modes.loadProcesses.LoadPrefabs.step(LoadPrefabs.java:42)
	at org.terasology.engine.modes.StateLoading.update(StateLoading.java:240)
	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:458)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:421)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:397)
	at org.terasology.engine.Terasology.main(Terasology.java:154)
22:03:14.499 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
```

Conflict resolution is easy enough, but like #3449 this seems to break at least one module - I suspect the same small list as https://github.com/MovingBlocks/Terasology/pull/3449#pullrequestreview-141360142 but am finding it a little trickier to rush through broken files to confirm the next broken module in the list. Could you please pull those modules and see if you can create fix PRs for them please, if more than just Dialogs is broken?

- [ ] Dialogs (used by L&S)
- [ ] DynamicCities
- [ ] LightAndShadow - GSOC sensitive
- [ ] MasterOfOreon - GSOC sensitive
- [ ] Tasks (used by L&S)
- [ ] TutorialDynamicCities

Last time around I tested with Light & Shadow and MasterOfOreon since they cover a ton of dependencies. I neglected testing JS which was silly. I also checked out Record & Replay for that sake. Did both some single player, multiplayer, and reloading a saved world.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Can confirm the latest commit seems to fix JoshariasSurvival 👍 

Would love to merge but can't sink the extra time into also fixing modules right now. Maybe tomorrow during some quiet time as we don't need to test JS right away - although it certainly would nice to also have this one thrown in!

**Comment by Cervator** [comment]
Made associated module issues, although I can't assign them to any of the people I'm pinging as they aren't public members of the Terasology org - am happy to help make that happen if needed :-)

Or rather, I started making issues and testing things, but I'm finding additional stuff so I won't be able to finish tonight. It tends to be easier to fix modules in a mega-workspace then build again to see the next error. Hard to leave broken modules in place and then dance around them trying to test other things. There are runtime errors in addition to compile time, for instance GooeysQuests fully compiles but also crashes at runtime. Maybe we can make an initial set of PRs then try with those merged locally.

@eviltak I pinged you in the issues and am also listing them here as an overview, but without public org membership I can't actually assign the issues. GitHub is funny like that.

## Modules that do not compile

Easy enough to provoke: Try to compile the things! :-)

- [ ] https://github.com/Terasology/Dialogs/issues/8
- [ ] https://github.com/Terasology/Tasks/issues/7
- [ ] https://github.com/Terasology/DynamicCities/issues/33
- [ ] https://github.com/Terasology/LightAndShadow/issues/74
- [ ] https://github.com/Terasology/MasterOfOreon/issues/29

## Indirectly affected as dependencies

Can't test without modules above fixed

* ManualLabor
* QuestExamples
* TutorialDynamicCities (probably fine)
* MedievalCities (probably fine - just assets)

## Compile OK but issues found with this PR

- [ ] https://github.com/Terasology/GooeyDefence/issues/30 - crash on auto-save with certain activities present
- [ ] https://github.com/Terasology/GooeysQuests/issues/31 - crash on world init

**Comment by Cervator** [comment]
Note: merged into a parking branch for merging at some point via #3490

**Pull request merged**
