### PR TITLE
Fixes for item use cooldowns

### PR DESCRIPTION
**Pull request by Josharias**
### Contains
- A fix to let items use just a single cooldowntime property on the ItemComponent.
- A improvement to the cooldown system that enforces validation on both the client and server side to see if an action is attempted while still cooling down.

As an implication of getting setting this data also on the server side,  this data will also be sent to other remote clients so that they can show other characters doing an action.
### How to test
- Use an item
- Attack with a weapon
- Attack with bare hand
- Press and hold attack to ensure no machine gun-ing happens

### Outstanding before merging
- [ ] There is a problem with single player which causes the authority to skip sending the activation event.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Josharias** [comment]
There is a problem with single player which causes the authority to skip sending the activation event.  Need to address this before proceeding.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Interesting!

I can confirm this appears to fix #2581 :-)

However, in an interesting coincidence it seems to allow for an error I saw get reported just yesterday in an unrelated fashion for a different reason. Or it just made it worse. Or it just *felt* worse because humans don't get along with probabilities. See #2597 for details. I was able to replicate with an older Omega build so merging!

Nice catch and fix :-)

**Pull request merged**
