### PR TITLE
Use multiple stacks to give blocks. This closes #2607

### LINKED ISSUE #2607: give more than 127 blocks in one command (use multiple stacks?)
What you were trying to do:
Give myself more than 99 blocks with the giveBlock command with a single command.

What actually happened
The sound of collecting items played, no error was returned and the 999 blocks I asked for were nowhere in sight.

How to reproduce:
* Open console and type "give stone 999"
* Observe no stone has been given.

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/39261328-giveblock-multiple-stacks?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github).

### PR DESCRIPTION
**Pull request by J0hnCena**
### Contains
Makes the giveBlock command send multiple times, until quantity runs out. The command is limited to 99 blocks per stack, since that is the max stack size. Fixes #2607. 

### How to test

Press (F1) to bring up the console. Use the giveBlock command by typing give <item> <quantity>. Pull up the inventory with (i) to see if none of the stack sizes are above 99 and if the correct number of blocks were given.

### Outstanding before merging

Would you like me to add a constant somewhere to reference the max stack size or call maxStackSize from ItemComponent?

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
Thanks @J0hnCena :-) Sorry for taking a while to get to engine PRs these days, the activity over in module land is intense and connected to most the GCI tasks.

I think your TODO about better referencing the max stack size later is fine. ItemComponent itself has a TODO about moving more inventory stuff around, so the area will get hit later anyway.

Going to try setting our build bot on this, been having trouble getting it to line up with itself lately. The commit status report ends up referring to two differently named contexts, I just tried applying another change for that and went hunting for a PR not yet tested!

@GooeyHub: ok to test

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by portokaliu** [comment]
Quick question about this: rather than sending multiple events regarding the same command, why not just change the code in the InventoryAuthoritySystem to match the necessity?

**Comment by portokaliu** [comment]
Any update on this one? Progress specification if not a complete submit would be nice (or a reasoning for submitting as is would work as well)

**Comment by J0hnCena** [comment]
Sorry it took awhile to respond; I've been busy with finals. I looked into changing the giveItemToSlots method in InventoryAuthoritySystem as you said. However, in order to change InventoryAuthoritySystem instead of BlockCommands, I need to change the variable type of stackCount in ItemComponent as well as stop the cast in BlockItemFactory. I'll add another commit with those changes instead. Let me know which one you think we should use.

**Comment by J0hnCena** [comment]
Whoops forgot I stashed my changes, hold on.

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Pull request closed without merging**
