### PR TITLE
Minor UI tweak in module list for gameplay modules.

### PR DESCRIPTION
**Pull request by mjuvekar7**
The UI now checks for dependencies while selecting the color to use to display gameplay modules.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by skaldarnar** [comment]
@GooeyHub ok to test

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by skaldarnar** [comment]
Thanks for the report @oniatus, merged it!

**Pull request merged**
