### PR TITLE
Updated lwjgl, slf4j, miglayout, netty, groovy

### LINKED ISSUE #1464: Upgrade to LWJGL 2.9.2
So LWJGL 2.9.2 is out: http://forum.lwjgl.org/index.php?topic=5617

It is supposedly the *last* release of LWJGL 2, with 3 now building and being used experimentally - http://blog.lwjgl.org/welcome-to-lwjgl-3/

@msteiger - your applet fix is in there, woo! http://legacy.lwjgl.org/changelogs/2.9.2-changelog.txt

This is the first release in a *year* - the clean list of changes is pretty minor, but not sure how much extra stuff of interest in the changelog. We should probably review and do the upgrade sometime, then take out the applet hack

Also brings an interesting thought to mind, although we don't have to deal with it for a while: Upgrading to v3, which is a total rewrite. Maybe that's something for a Terasology 2.0.0? Maybe paired with more abstract rendering with a new LWJGL 3 renderer to test out the ability to entirely use an alternative renderer? Or do we want to deal with that (just the abstraction) earlier?

In any case - low priority, but wanted to put an issue in for it and add some thoughts :-)

### PR DESCRIPTION
**Pull request by msteiger**
Closes #1464 

@immortius I wasn't able to upgrade gestalt-module (from 2.1.0 to 2.2.2) and/or reflections (from 0.9.9-RC1 to 0.9.9). 

`APIScanner.scan()` crashes on the inner class `PlaySoundNode$PlaySoundTask`. It is enumerated by `getTypesAnnotatedWith(API.class)` but calling `getAnnotation(API.class)` returns null.

### CODE REVIEW

**Comment by Cervator** [comment]
Should this be paired with a quick PR also doing the upgrade for the applet + undoes that signing hack?

**Comment by msteiger** [comment]
Sounds reasonable. I just updated the applet and removed the workaround for 2.9.1. Everything should be in place now.

Merging this PR should also trigger an applet deployment.

See https://github.com/MovingBlocks/FacadeApplet/commit/cc681ae62f98053a5f56b155ae3b33ff6b6204e9

**Comment by Cervator** [comment]
Got a wee bit late for me to merge this tonight (past midnight) so I'll try it tomorrow. Gives @immortius a chance to check on Gestalt if desired too :-)

**Comment by immortius** [comment]
I don't think there is any rush on the gestalt end, I'll see if I can reproduce next time I'm looking to change Terasology to use additional gestalt functionality.

**Comment by Cervator** [comment]
That works :-)

Merged and we are (briefly) out of PRs again, wee!

**Comment by immortius** [comment]
I worked out what was going wrong with gestalt-module's APIScanner, will be fixed next version.

**Comment by Cervator** [comment]
@immortius - cool :-)

@msteiger - i often test after a full `gradlew clean cleanIdea idea` so I think it worked fine first try. Good note though if anybody else doesn't and runs into quirks!

**Pull request merged**
