### PR TITLE
Replace VecMath with TeraMath

### PR DESCRIPTION
**Pull request by msteiger**
This PR replaces VecMath as far as possible with TeraMath. Some BulletPhysics-related content still uses VecMath through a wrapper.

This is mostly a simple replacement of methods. It does not refactor existing code, but allows us to do so later.

**TODO** (in a follow-up)
* Extract/adapt BulletPhysics `Transform` utility class in TeraMath
* Throw out duplicate Vector2i / Vector3i classes
* Refactor geometry classes in o.t.math (Rect / Vector3fUtil / etc. )
* Maybe remove VecMath from the collection of allowed libs for modules?

I wrote and reviewed this carefully. Please review it again to ensure that I did it right :smile: 
Note that TeraMath should be merged first (and uploaded to Jenkins with a proper version name (1.0.0?) and build.gradle needs updating).

Requires https://github.com/MovingBlocks/TeraMath/pull/23

### CODE REVIEW

**Comment by Cervator** [comment]
Started reviewing this some at last :-)

Checked out the branch in my main workspace, 80 compile errors from modules due to just Vector3f being used with the old vecmath import. Woo!

Is replacing the old `import javax.vecmath.Vector3f;` with new `import org.terasology.math.geom.Vector3f;` the correct fix? I don't mind fixing some/all of those but want to be sure I'm doing it right

I tried it for Cities and after also cleaning reflections it looks like it works :-)

Looking deeper in more modules I also found `import javax.vecmath.Quat4f;` and tried replacing with `import org.terasology.math.geom.Quat4f;` but still got a compile error on org/terasology/itemRendering/systems/AnimateRotationClientSystem.java:57 in ItemRendering where it looks like the parameters are now off

Actual: `rotationAmount.interpolate(Quat4f, float);`
Expected: `rotationAmount.interpolate(Quat4f, Quat4f, float);

There were only like 4 hits for that change at least. Advice? :-)

**Comment by Cervator** [comment]
Talked to @msteiger a bit on IRC, who volunteered to merge later and then fix some of the affected modules. Everything looks good, there's a tiny merge conflict that's a non-issue, just need to accept in changes from both sides.

**Comment by msteiger** [comment]
I fixed all merge conflicts (there were lots!) so it can be integrated in the develop branch. 

**I'd like to merge this PR today**

Please let me know if you see a reason for not doing that.

**Comment by Cervator** [comment]
Huh, what else was conflicting? I just saw a single file last I checked. Maybe we merged some stuff since I checked.

Thanks for all the work on this including merge and module fun :-)

Just one unit test failed, that's not bad! http://jenkins.movingblocks.net/job/Terasology/1301/testReport/junit/org.terasology.logic.location/LocationComponentTest/worldRotationCombinedWithParent/ :D

**Comment by Cervator** [comment]
Okay, ran through some more testing and added a bunch more compile fixes from all the extra modules in my workspace :-)

A few need a bit more work, so I submitted an issue to the TeraMath tracker with details. There may also be some quirks here and there - I noticed the deer in WildAnimals not moving again (there were substantial fixes needed in Pathfinding), unsure if that's just my workspace (again) or an actual issue.

**Pull request merged**
