### PR TITLE
Added death screen instigator and death screen damageType

### PR DESCRIPTION
**Pull request by VaibhavBajaj**
## Purpose

Added Death Screen DamageType for any event. Also added DeathScreen instigator for any death where player is killed by other AI or player.

## Testing
You can test DamageType by simply falling from a great height. Instigator can be tested by being killed from Skeleton in GooeysQuests.

### CODE REVIEW

**Comment by VaibhavBajaj** [comment]
@Cervator Guess we are back to this branch. Here are the changes I discussed with you earlier

**Comment by Cervator** [comment]
Righto. No time to test tonight, but poking others for any remaining review. We can rebase this clean of some of the silly commits :-)

Oh, also:

@GooeyHub: ok to test

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by VaibhavBajaj** [comment]
Rebasing would be great.

**Comment by iojw** [comment]
@VaibhavBajaj : I took a look at this and I have a few suggestions if you're open:

- Didn't you mention that you were going to add the instigator as well? This could be done in a similar way to how the damage type is retrieved, just add an additional label and store the data using `event.getInstigator()` instead. In fact, you could even provide information what tool caused the damage using `event.getDirectCause()`, which might be useful if players get killed with a item like a special sword.
- You seem to have added .iml files, which shouldn't be have added since they're in the default TS .gitignore. You might want to consider updating your local .gitignore with the one from the main repo.
- Since you have decided to go with the `DoDamageEvent` approach, you can revert all the changes made to the other files from the previous approach like `CharacterComponent`, `ClientInfoComponent` and `HealthAuthoritySystem`.

🙂

**Comment by iojw** [comment]
@VaibhavBajaj : Any updates on this one? I could just submit a separate PR putting some changes on top of this one if you're a little busy. This is one of the simpler PRs which could probably be merged soon 🙂.

**Comment by VaibhavBajaj** [comment]
@iojw I completely forgot about this one :P. I would be able to wrap this up today or sometime tomorrow unless you have already done so.

**Comment by VaibhavBajaj** [comment]
@iojw Hey, if you want to go ahead with deathScreen modifications, by all means go ahead. I have confirmed I will have free time tomorrow but my Mid Term 3 is coming up day after and I will have to prep for that. If you could wait till Saturday, I would be able to wrap it up else please go ahead. If you face any questions with parts of code, you can ping me on webchat or more preferably comment on the PR since then I am sent an email and I check my emails.

**Comment by iojw** [comment]
@VaibhavBajaj No problem there's no hurry at all. I was just pinging you as I thought you might have missed it.

**Comment by Cervator** [comment]
@VaibhavBajaj & @iojw - either of you have a moment to finish this one off so we can merge it? :-)

**Comment by iojw** [comment]
@cervator: A bit swarmed at the moment, will finish this up soon!

**Comment by Cervator** [comment]
@iojw no problem at all! :-)

**Comment by jellysnake** [comment]
@iojw @VaibhavBajaj
What's the relation between this and #2809?
I know iojw is working on the other pull, so what's happening with this one? Is it to be merged with iojw's?

**Comment by iojw** [comment]
@jellysnake This can be closed when #2809 is merged. The commits with this one are a little messed up, so I cleaned them up in another PR.

**Comment by oniatus** [comment]
Closed via #2809 and also thanks to @VaibhavBajaj for the initial work 👍

**Pull request closed without merging**
