### PR TITLE
Added Unified Utility Script for Groovy Wrapper

### PR DESCRIPTION
**Pull request by digitalripperynr**
Hello!
I just completed this script.
Please review the changes.
I will add the help section once the working is verified.

The new syntax is:
`groovyw util <type> <command>`

where `type` is either module, facade, lib or meta

For example:
`groovyw util module get Sample`

Thanks :D

(Also, looks like I messed up some of the commits. Please ignore 😋 )

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by digitalripperynr** [comment]
wait... I can fix this conflict...

**Comment by digitalripperynr** [comment]
idk how to fix this....  :(

But the script works for sure :D

**Comment by mjuvekar7** [comment]
`groovyw util module create Something` is throwing errors

> We're doing a create
User wants to create a Module named: Something
Caught: groovy.lang.MissingMethodException: No signature of method: util.createModule() is applicable for argument types: (java.lang.String) values: [Something]
groovy.lang.MissingMethodException: No signature of method: util.createModule() is applicable for argument types: (java.lang.String) values: [Something]
	at util.performAction(util.groovy:295)
	at util$performAction.callCurrent(Unknown Source)
	at util.run(util.groovy:397)
	at org.gradle.wrapper.GroovyBootstrapMainStarter.start(GroovyBootstrapMainStarter.java:33)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
	at org.gradle.wrapper.GroovyWrapperMain.main(GroovyWrapperMain.java:61)

**Comment by digitalripperynr** [comment]
I fixed the module creation issue.
Please verify...

**Comment by jellysnake** [comment]
Unfortunately I've noticed quite a few issues with this script

* Running `groovyw util module` gives an out of bounds error.
    * As does `facade`, `meta` and `lib`
* `groovyw util module recurse` doesn't work, simply gives Unrecognised command
    * Also does for `facade`, `meta` and `lib` but this is most likely intentional.
* `groovyw util module list-remotes Core` fails on a no directory found error
    * However running on a module that has been retrieved does work. It's only the items obtained when setting up the environment that fail.
    * As does `add-remote`
    * As does using `facade` instead of `module`
* `groovyw util module create` gives a Missing Property error
    * However did create a directory with both a `build.gradle` and a `.gitignore`
    * As did `facade`, `meta` and 'lib'
    * Additionally `meta` used the directory `metas` instead of `meta`
    * As a note, `gradlew idea` failed on these created items but the `list-remote` and `add-remote` commands do work on them.
* `groovyw util facade get Server` fails to find the Facade
    * running with `FacadeServer` does work however is not in line with the previous command, both in the created directory name and in having to include *Facade*

On general notes I think the overall code quality could be improved. There's methods dumped everywhere in the file with no seeming attempt at organising them. There's variables defined in between method declaration. I'm noticing a lack of comment or internal docs, which should still be there even though it's a groovy script. I would also like to see some of the methods broken up more, like the `retrieveItem` method

I'm also questioning the effectiveness of consolidating everything but that's a discussion that should be held independent of the GCI task

**Comment by Cervator** [comment]
I'm closing this for now, please restart in a fresh branch - are you still using the web editor? We *need* valid diffs to be able to review things better.

Most the point of this GCI task was to arrive at a well-cleaned and streamlined script, more-so than it actually working (that's a natural requirement) - I'm still not entirely convinced myself if a single script approach would work well, that's part reason I wanted to see it in action :-)

**Comment by digitalripperynr** [comment]
I'm really sorry for all of this...I will fix and create a new PR soon.
Thanks

**Pull request closed without merging**
