### PR TITLE
Add new checkbox textures, UILabel modes, enabled binding, make volumetric fog label gray

### PR DESCRIPTION
**Pull request by tdgunes**
### Contains

A partial fix for #2277 (previously #2274 and #2275)

### How to test

Check Volumetric Fog setting's checkbox and label, both their color should be more greyish.

screen shot 2016-04-07 at 23 25 53

### CODE REVIEW

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/575/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Checks out! 

Hah, hah, hah ;-)

I looked at it via `showScreen migTestScreen` as well, although in this case it is easier to compare on the Video Settings screen. Still pretty hard to see a difference between disabled and enabled - could it be clearer if the disabled background was slightly more light gray? Or even had subtle lighter gray marks of some sort, maybe even horizontal + vertical lines to put the checkbox in jail, so to say?

If you play with it and find an improvement feel free to just shove it into any more meaty PR that comes along sometime :-)

Thanks!

**Comment by Cervator** [comment]
Slight addendum just for change notes: I took inspiration from this (read: shamelessly copy pasted) to also disable the Oculus Rift checkbox since that doesn't work at present either :-)

**Comment by emanuele3d** [comment]
Odd about oculus. In one of my last PRs i could see the double image on
screen. It doesn't achieve stereoscopic vision or does it currently crash
the application?

**Comment by Cervator** [comment]
@emanuele3d the current Oculus support was written against the DK1 with a waaay outdated SDK version. The option may work to where it lets a double image render to a normal screen, but I can't imagine it'll actually work with a Rift like you'd expect (turning your head, etc). Plus I believe the latest SDK version forces the use of direct HMD mode while our original version was probably for extended desktop (letting you see the double image in the first place without mirroring)

Like the volumetric fog option having it available in-game does enable some sort of feature for developing further, but it isn't end-user ready so I'd rather not get the hope of players up just yet :-) For testing 3d wizard PRs we might want to un-disable manually briefly if testing out the basics make sense.

**Comment by emanuele3d** [comment]
@Cervator: ah, I understand now, thank you. I wonder if we should remove all the oculus-related code then. It would make maintenance and further development easier.

**Comment by Cervator** [comment]
@emanuele3d maybe. I don't know enough about what we have and how many changes would be needed. Since some of the GSOC proposals involve VR I'd wait till after we know what topics get picked though.

Ultimately we should probably aim for an open VR standard, I don't know how Oculus specific what we have is. Maybe being able to render the double image is a worthwhile piece of code for future reuse. Unsure :-)

**Pull request merged**
