### PR TITLE
Empty space input for chat/console handling

### PR DESCRIPTION
**Pull request by ThompsonTyler**
### Contains

Fixes the problems addressed in #2834 

Inputting a string of empty spaces into either console or chat treats it as an empty message. (Does not send that message)
Inputting an empty message into console does nothing.
Inputting an empty message into chat closes the chat box.
Any messages are trimmed(white space before and after messages is removed)

### How to test

Open up chat, try sending an empty message.
Open up chat, try sending a message with only spaces in it.
Open up console, try sending an empty message.
Open up console, try sending a message with only empty spaces in it.

Check that console and chat both trim the message before it is sent.

### Outstanding before merging

Nothing that I know of!

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by ThompsonTyler** [comment]
Hey Nihal, Fixed up the console a bit, UI does run first, but it calls the super onto UIText, so implementing in UIText causes an empty input to trigger the above and let it do with it as it wants to. I changed the console a bit because it was still sending commands of empty strings, just wasn't doing anything with them, so I added a check for it.

I also caused it to not write the commandline to "" because UICommandEntry already does it, and that would instead just be back to back writing the exact same thing.

As for the hinttext, When the UIText is completely empty it is in a state that will show the hint text if available(Nothing has this actually used from what I can tell, so can't really show it) But if the text is empty then isShowingHintText is true. With out the check and actions in UIText it results in the problem of hitting enter on an empty string triggering the if state that is now an if-else and adding a space(Enter's "key character" is a space).


As for console not exiting, this was something I asked @Cervator  about for what it should do, he had said both should just act as if you typed nothing/did nothing, but shouldn't close the console window. Could add this logic if you feel that it is the more correct approach, I wasn't really sure which would feel more correct, both seem fine to me.

**Comment by skaldarnar** [comment]
@GooeyHub ok to test

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by jellysnake** [comment]
@ThompsonTyler How's the work going on this? Are you able to add the features oniatus requested/have comments on those features?

**Comment by ThompsonTyler** [comment]
Hey, sorry. Been busy lately and then kind of forgot what issues were addressed in which way to go back and fix stuff up.

Should be able to make that fix real quick, makes sense to me.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Pull request merged**
