### PR TITLE
Fixes the LGTM error "Inconsistent equals and hashCode"

### PR DESCRIPTION
**Pull request by mwvdev**
### Contains

Fixes the LGTM hashCode error in #3510.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
This pull request **fixes 6 alerts** when merging 7d8ea300dfe4c919d62217782d936513e34b70e8 into 9118708ad3f34f0bc05572fe54ad47538c3164bb - [view on LGTM.com](https://lgtm.com/projects/g/MovingBlocks/Terasology/rev/pr-df250ecc46a67a8afd721f3c0ba1e0431848d832)

**fixed alerts:**

* 6 for Inconsistent equals and hashCode

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Cervator** [comment]
Thanks for the fixes :-)

I'm not really very knowledgeable about `hashCode` generation - usual example code seems to include some random numbers and the hash codes for any fields added in. Any particular reason or tactic behind the choice you made @mwvdev ?

Poking @vampcat or anybody else who might have some additional feedback

@GooeyHub: add to whitelist

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by jellysnake** [comment]
So from what I gather this hashcode implementation is calling the hashcode on the class object, rather than the instance.
This is consistent with the current equals. At the moment equals will be true if the two objects are both of type `UnbindFbo`. Hence the logical extension is that all instances of `UnbindFbo` should hash to the same value.

This is done by using the hash function for the _class_ object rather than an instance.

**Comment by mwvdev** [comment]
@jellysnake Exactly. I noticed that the objects were stateless and the only "identifying" part of the object was its class. For stateless objects I think this is a good way to do it.

**Pull request merged**
