### PR TITLE
Add UITabBox

### PR DESCRIPTION
**Pull request by jellysnake**
Add a UI Tab as per issue #2695.

An example on it's use can be seen [here](https://github.com/Terasology/TutorialNui/pull/2)

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by rzats** [comment]
@jellysnake: I'll try and review this (along with the other widget PR) over the weekend - sorry for the delay. AFAIK the relevant Google Code-In tasks were already approved.

**Comment by jellysnake** [comment]
Cool, thanks. The other pull (radial widget) still needs a couple of fixes, so don't feel in any hurry at all to review that one :)

**Comment by mjuvekar7** [comment]
Experiencing a weird issue with the PR [here](https://github.com/Terasology/TutorialNui/pull/2). Please check the comments there.

**Comment by Cervator** [comment]
Checked this out along with the TutorialNUI addition - looks good, thanks! :-)

**Pull request merged**
