### PR TITLE
New SetRenderBufferMask StateChange

### PR DESCRIPTION
**Pull request by vampcat**
- Adds a new SetRenderBufferMask StateChange
- Moves the MarkerTask in RenderTaskListGenerator so that it's not the first class in file

### CODE REVIEW

**Comment by vampcat** [comment]
This was supposed to be based on an earlier branch (Resizing Issues PR), and so only the last commit actually belongs to this Branch. Please ignore the other commits for now.

@Cervator This should fix every last one of the problems (as far as I know). Go ahead, and try to break it!
@emanuele3d Tagging for review!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by vampcat** [comment]
Even in this new set of commits, only the 7cfe6fc commit is relevant, the other two are from a different branch. I'll squash all commits into one once the other PR gets merged.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by vampcat** [comment]
This PR has been broken down into smaller PRs, and so I'm closing this one.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by vampcat** [comment]
Closed, in favour of making 2 new PRs (and because of some rebasing issues).

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Pull request closed without merging**
