### PR TITLE
Fixes LGTM logger errors and warnings

### PR DESCRIPTION
**Pull request by mwvdev**
### Contains

Fixes the following LGTM errors and warnings from #3510:

- Missing format argument
- Unused format argument

Note that the logging statements previously would log less information than expected, since the unmatched argument would simply be omitted from the formatted log statement.

### How to test

Either reproducing the conditions that cause the logging to occur, or instead forcing the condition to occur by attaching a debugger and manually changing the state to force the logging code path.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
This pull request **fixes 9 alerts** when merging 09933aa2a4da9d293a900c18ca9462913235cf01 into 9118708ad3f34f0bc05572fe54ad47538c3164bb - [view on LGTM.com](https://lgtm.com/projects/g/MovingBlocks/Terasology/rev/pr-df0a203ea63ac7fcf4cc5dba81ae580337315875)

**fixed alerts:**

* 8 for Unused format argument
* 1 for Missing format argument

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Cervator** [comment]
Thanks for the cleanup! :-)

Added you to the game credits while I was in there

**Comment by mwvdev** [comment]
No problem! Thanks for the credit :-)

**Pull request merged**
