### PR TITLE
Add "search" command. Fixes #1525

### LINKED ISSUE #1525: "Search" command
We are getting quite a few commands, blocks, items, etc. I think a "search" command would be a great utility if you're curious about all commands that relate to "health" (in the command name or description), blocks or items that relate to "wood" (in name or description), even cross-category for something like "hunger" (all related commands and all items that have hunger in name/description/attribute)

Maybe something for @Limeth if curious, or anybody else looking for something interesting to do :-)

### PR DESCRIPTION
**Pull request by Limeth**

### CODE REVIEW

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/220/
Hooray Jenkins reported success with all tests good!

**Comment by Limeth** [comment]
Not finished, work still in progress.

**Comment by Limeth** [comment]
Okay, should be AFAIK ready. Please review the prefab and block searching mechanic, I'm not sure if it is correct.

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/221/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Thanks for this :-) Out of time tonight but will check as soon as able to

**Comment by Cervator** [comment]
Tried it out - awesome! Works exactly how I had pictured it. Should come in handy from time to time :-)

I tweaked the help text real quick as it looked like it was from when only commands were searched + added the command to the readme.

Thanks!

**Pull request merged**
