### PR TITLE
Fix checking twice the same conditional in EnvironmentEffectsBinding.

### PR DESCRIPTION
**Pull request by MaloJaffre**
See http://jenkins.terasology.org/job/Terasology/1596/findbugsResult/type.-936980778/.
I don't know if it have an impact but it's easily repaired.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by msteiger** [comment]
add to list

**Comment by msteiger** [comment]
add to whitelist

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/358/
Hooray Jenkins reported success with all tests good!

**Comment by msteiger** [comment]
Good catch - thanks!

**Comment by Cervator** [comment]
Huh yeah that's a classic bug. Probably did have an impact but we checked it too rarely. Appreciate the fix :-)

**Pull request merged**
