### PR TITLE
Command parameter handling simplification

### PR DESCRIPTION
**Pull request by immortius**
* Varargs and array params are treated the same (must be at the end of the command params)
* Array params are always optional, and will be sent an empty array if not provided with any values
* The string parameters for array params are not escaped/unescaped, joined into a string or anything like that. Instead when an array param is reached, all remaining string params are sent to it and converted into an array.

From a user perspective, all commands are just a list of whitespace separated parameters with the option to use quotes to effective escape spaces. (TODO: consider allowing quotes to be escaped). From a developer perspective, they are allowed to have either a vararg or array param at the end of their methods.

An example method/usage:

```
@Command
public String test(@CommandParam("first") String first, @CommandParam("additional") String ... additional) {
  return 'first' + " " + Arrays.asList(additional).toString();
}
```

Usage:
test "one" "two" "three" "four"
> 'one' [two, three, four]

test "one"
> 'one' []

### CODE REVIEW

**Comment by Cervator** [comment]
Tested out and merged - getting there! Module commands work now, multiplayer is still a little sketchy, but at least it doesn't crash on *any* command, just the known issue with kickUser :-)

Will put in another follow-up with some details

Thanks!

**Comment by Limeth** [comment]
The ```test``` command should only work when 2 or more parameters are provided

```
Please, provide required arguments marked by <>.
test <String first> <String remainder> (String remainder)...
```

Although, when I run this: ```test hello.```,
the command works (and shouldn't) and this is what gets printed out: ```hello. []```

**Comment by Cervator** [comment]
Should we make a separate reminder issue to fix that sometime? Yeah if there are two mandatory args it makes sense it would complain if only given one. Unless the issue is somehow the vararg/array arg get flagged mandatory but shouldn't be.

Man I can't stop thinking about @Arrrrg as an annotation :D

**Comment by immortius** [comment]
The test command is working as intended based on my description of how varargs should work. Which is the same as how varargs work in java. I do not consider this a bug.

**Comment by Cervator** [comment]
Shouldn't it print with this distinction then?

`test <String first> <String remainder> (String remainder)`
vs
`test <String first> (String remainder) (String remainder)`

Dunno if we'd want to distinguish having a mandatory first vararg vs it being entirely optional, or in that case use a normal arg first, then the vararg.

**Comment by Limeth** [comment]
You beat me, @Cervator .

**Comment by immortius** [comment]
@Cervator you are correct, it should display that way.

I think if the developer wants at least one value, they can add an extra single param before the vararg, same as the standard mandatory first value trick for java vararg methods.

```
public void (String first, String ... additional);
```

I think it would be more confusing to the developer if vararg params did require one value by default, because it behaves differently to how they work in Java. Additionally, varargs with no values is provided with an empty array, not null, which is different to other optional parameters.

I think this will also work well with optional parameters using Guava's Optional<>, since these would look like:

```java
public void command(@CommandParam("required") String required, @CommandParam("optional") Optional<Vector3f> optional, @CommandParam("additional") String ... additional);
```

Without requiring additional thought around making ```additional``` optional.

**Pull request merged**
