### PR TITLE
Support custom filters in Tree and FloraProvider

### PR DESCRIPTION
**Pull request by msteiger**
Realized through a method

    protected List<Predicate<Vector3i>> getFilters(GeneratingRegion region)

### CODE REVIEW

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/306/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Neat :-) What does it actually result in / how to test?

**Comment by msteiger** [comment]
The Perlin world generator should work as before. Cities uses additional filters to remove grass/flowers from roads and trees from settlements:

image

A similar settlement in the 3D view:

image

**Comment by Cervator** [comment]
Ahhh! Alright, that makes sense now. Thanks for the extra details :-)

Hoping to spend a good chunk of time on reviewing PRs etc tomorrow.

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/307/
Hooray Jenkins reported success with all tests good!

**Comment by msteiger** [comment]
The last commit also halves the general tree density. Forests still look like forests, but less overcrowded.

image

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/308/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Merged in after doing a TeraMath v1.1.3 release so Cities will work. Thanks as always :-)

**Pull request merged**
