### PR TITLE
Restore Chunks.proto.

### PR DESCRIPTION
**Pull request by MaloJaffre**
See #2118.
Git is fantastic !

### CODE REVIEW

**Comment by msteiger** [comment]
Thanks for digging that up again!

Is this the code from 803dd97140b9502d1e3cd9 ? The protobuf compiler is in [protobuf/compiler](https://github.com/MovingBlocks/Terasology/tree/develop/protobuf/compiler).
Can you confirm that the code actually generates the `java` file? Maybe the file was modified and got deleted by accident. Then we would need to reconstruct those changes from the java file.
Maybe @immortius deleted it on purpose - is the `Chunks` class still in use?

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/389/
Hooray Jenkins reported success with all tests good!

**Comment by MaloJaffre** [comment]
Chunks doesn't seem to have any uses.
Sorry for the noise, I will create a new commit to delete ```ChunksProtobuf.java```.

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/390/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Git is indeed neat! Cool resurrection, I was wondering if it was still hiding somewhere. Weird that we had deleted one but not the other :-)

**Pull request closed without merging**
