### PR TITLE
removing obsolete interfaces and classed

### PR DESCRIPTION
**Pull request by adam83112**
### Contains

Removing obsolete Noise2D and Noise3D interfaces, and some onsolete Noise classes.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
Hi @adam83112 and thanks for the PR :-)

Was this inspired by #2043? If so I must apologize for not having moved it to engine v2.0.0 yet. We didn't get it finished in time for the v1.0.0 release and there are still usages in the module ecosystem (like WeatherManager), so we can't remove them yet.

Since we're still in Alpha we're considering API violations on a case-by-case basic, if they're relatively trivial. If each current module using these classes was updated first we might be able to merge it early, but I'm not sure how much effort that would be.

**Comment by adam83112** [comment]
No, I just wanted to remove some warnings and unused code. But if you have a different approach, these changes can wait.

**Comment by Cervator** [comment]
We definitely want to remove warnings and unused code, yep. We are just also trying to hold ourselves to the principles of [Semantic Versioning](http://semver.org) :-)

It is generally easier to fix Checkstyle, Findbugs, and related warnings, as those generally do not impact API. The thing to be careful with there is not changing too many files at once as then that sort of work could impact functional changes other people are working on, causing conflicts.

I'll go ahead and close this, unless you are up for hunting down and adjusting usages across all [game modules](https://github.com/Terasology) as well - but it might be tricky even finding exactly which modules are using these classes. If you're interested let me know and I can help make a list and we can re-open this.

In any case thanks for your interest! I hope you might like to do more code, will be happy to come up with ideas if needed :-)

**Comment by adam83112** [comment]
I think you are right. It is too early for cleanup code. I will take some of existing task, but it will be quite easy because I am a C# programmer :-)

**Comment by Cervator** [comment]
Excellent! Looking forward to it :)

**Pull request closed without merging**
