### PR TITLE
Create extras submenu

### LINKED ISSUE #3468: Move Record and Replay UI elements (and more?) into a sub-menu
### Suggestion

Since Record and Replay is not relevant most part of the time, their buttons should be moved from the main menu to somewhere else.

### PR DESCRIPTION
**Pull request by andrasveto**
### Contains

Fixes #3468

Screens:
- engine:menu#start-record
- engine:menu#start-replay
- engine:menu#credits
- engine:menu#telemetry-button
- engine:menu#crash-reporter
moved to new menu item engine:ExtrasMenuScreen

### How to test

Changes visible on main menu screen on game launch

### Outstanding before merging

- [ ] Will need translation work for engine:menu#extras-title

First pull request, so please let me know what should be changed 😄 I added the extras title to be consistent with the settings screen; not sure if that's necessary.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
Hey @andrasveto thanks for the quick response to a new item. Welcome! :-)

Your PR looks pretty good. A few comments:

* Can you think of a reason to have two translation entries instead of one that's just used both for the button and the title? I'd probably just include a single "extras-label" then use it in both places
* You should add the translation key(s) to `menu.lang` as well. It is essentially the blueprint with then the `en` file naturally holding the values for English
* So long as both those files are modified you're good for translation on this PR 👍 The other languages where the key is missing will get flagged in our translation site next time it is updated
* It helps if you confirm if you've tested the actual functionality of the moved buttons, just in case they might have been hooked up to something in their existing position :-)

Going to trigger our bot for automated testing. Just a few tweaks and this should be merge-ready!

@GooeyHub: ok to test

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by andrasveto** [comment]
Thanks for the review, @Cervator! I've consolidated translation entries and added the key to menu.lang.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Appreciate the tweaks! Tested this out and merged :-)

I had two more trivial review comments but forgot to post them before merging. Fixed during merge with commit https://github.com/MovingBlocks/Terasology/commit/72d19c9e0c2c6d73781ebe41c3c4ca27d0c481bf if you'd like to see what. Also added you to the game credits there! 

Original comments that go with those changes (and one tiny line break for a long line):

> We multiline just about everything for consistency, so this would be on the full three natural lines. Another thing I'll just tweak real quick while merging :-)

> Minor detail here: in this file the value needs to be the same as the key to indicate the default setup. Really, you'd think we could just go without this file, and maybe if we tidy up the system we can. For now I'll just change it to "extras-label" during a merge :-)

**Pull request merged**
