### PR TITLE
Update menu_ru.lang

### PR DESCRIPTION
**Pull request by naiffuR**
### Contains

Brief description of what the PR does like "Fixes #12345"

### How to test

Brief description of how to test / confirm this PR before merging

### Outstanding before merging

If anything. You can use neat checkboxes! Feel free to delete if not needed

- [ ] Need to consider use case x
- [ ] Still have to adjust the wiki doc
- [ ] Will need translation work

Edit

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by msteiger** [comment]
Great! Thank you!

**Comment by Cervator** [comment]
Added you to the credits @naiffuR - should be visible shortly! :-)

Feel free to introduce yourself in the forum sometime if you like, you can get a contributor badge there if so. Happy to have any more improvements, be they more translations or anything else.

http://forum.terasology.org/forum/contributor-introductions.7/

**Comment by naiffuR** [comment]
Hi! This winter I signed up for the forum under the name Ruffian and previously made translation of game text into Russian language. I will be glad to help with translation into Russian language.

**Comment by Cervator** [comment]
Excellent! I added the contributor badge to your forum account :-)

More help with Russian would be appreciated. Usually they would be doable via translate.terasology.org but its Git setup needs some maintenance as it fell behind what we have here on GitHub. Should be sorted out over the next few days.

**Pull request merged**
