### PR TITLE
Cleanup for tree assets

### PR DESCRIPTION
**Pull request by skaldarnar**
* renaming: "birk" -> "birch"
* introduced "trunk" block tiles for pine and birch tree (for top and bottom of logs)
* updated the block definitions with displayname and used tiles

### CODE REVIEW

**Comment by skaldarnar** [comment]
Due to the renaming every module explicitly referencing the birch trunk needs to be updated - that are probably only TtA (@MarcinSc) and @Josharias Survival... any other world generators or crafting systems I'm forgetting?

**Comment by Josharias** [comment]
Core module has a few references to Birk still.  
Josharias survival has a non-breaking reference to Birk that can be changed afterwards.  
TtA  has its own Birch block and doesnt need modifications.

**Comment by immortius** [comment]
This is where gestalt-assets-core#7 would come in useful (asset redirects), but that lies in the future.

**Comment by Cervator** [comment]
Birk birk birk - merged and remaining hits renamed, including ManualLabor

**Pull request merged**
