### PR TITLE
Clean up UI classes & Save screenshots regularly

### PR DESCRIPTION
**Pull request by ar0ne**
### Contains

I've refactored UI classes, add better structure and improve design.

### How to test

Check that SelectGame, Record&Replays, ModuleDetails, GameDetails screens work properly and look better.

### Outstanding before merging

- [x] I added few TODOs, need a method from another [PR #3459](https://github.com/MovingBlocks/Terasology/pull/3459) (but we still could merge it firstly and I'll fix it later).

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Also: Unsure if this PR or #3459 (didn't notice until I was testing this merged on top of the other) but I get a failure now on trying to delete saved games. Reverting back to develop I couldn't replicate the issue anymore:

```
16:23:42.294 [main] ERROR o.t.r.n.l.mainMenu.SelectionScreen - Failed to delete saved game
java.nio.file.DirectoryNotEmptyException: saves\Game 127
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:266)
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
	at java.nio.file.Files.delete(Files.java:1126)
	at org.terasology.utilities.FilesUtil$1.postVisitDirectory(FilesUtil.java:64)
```

Couldn't replicate the "skip" bug with this merged :-) (with no saved games you skip game selection both entering create came and coming back to the main menu - that wasn't happening on the return trip recently)

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by ar0ne** [comment]
Hey @Cervator,
Does it look better now?:)
img

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Went over the diff somewhat loosely, nothing really stuck out. Tested the generally affected areas in a few different ways and all looks well :-)

I have a few minor suggestions but they're just tiny tweaks at this point. Everything is looking quite good including the new setup on the game details page!

A few potential follow-ups:

* Making a separate issue for the `GamePreviewImageProviderTest` tests that oddly seem to fail on Windows
* On game details i don't see a value for "Seed" in the game info details, although it shows up in the world details. Maybe because of the distinction between universe seed and world seed now?
* Maybe cut the linebreaks in that box then shrinking it slightly vertically and hopefully avoiding the scrollbar. That would let the screenshot grow just a bit to maybe wipe out its horizontal margin (on default resolution anyway)

**Pull request merged**
