### PR TITLE
fix missing label in secondary input mapping description.

### PR DESCRIPTION
**Pull request by MaloJaffre**
see issue #2064.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
ok to test

**Comment by msteiger** [comment]
Looks good to me. Haven't tried it out though.

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/355/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Tested it out. All is well. Thanks @MaloJaffre ! :-)

**Pull request merged**
