### PR TITLE
Warn modules

### LINKED ISSUE #2129: Disclaimer to warn user about enabling unsupported or all modules
We already removed the "Enable All" buttons but users are still manually enabling all modules including those not even present in the stable lineup but available anyway via meta-server lookup in-game.

We should warn more about that: 

- [ ] Add small label by the "Modules" button on the create world screen with something like "Advanced usage only!"
- [ ] Add a label on the Modules screen in red: "WARNING: Enabling extra modules, especially *all* or those not in the stable lineup can cause game crashes or broken worlds. Please handle with care"
- [ ] Anything else that's easy to include? Maybe a warning label with the count of extra modules not requested by the active gameplay template? Could even make the text color *angrier* the more extra modules you add :-)

Related: #2128, #1911, #1891

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29827846-disclaimer-to-warn-user-about-enabling-unsupported-or-all-modules?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by genuinelucifer**
Fixes #2129 and #2077

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
add to whitelist

Huzzah :-)

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/486/
Hooray Jenkins reported success with all tests good!

**Comment by genuinelucifer** [comment]
> add to whitelist
umm. sorry. I didn't understand.

**Comment by Cervator** [comment]
Hehe the whitelist note was just for our robot @GooeyHub - it makes future engine PRs from you automatically start building in Jenkins without us having to OK it first :D

It is getting late and I'm doing some forum announcement stuff, probably won't get a chance to review until Friday/Saturday but am looking forward to it :-)

**Comment by genuinelucifer** [comment]
Ooh. My bad.
.
I'll start work on the next issue. Review it whenever you get time. :)

**Comment by genuinelucifer** [comment]
My exams have started so I am unable to do much work on the issue till 17th March. I'll definitly try to work on it. But, after 17, I'll surely resume work on it.

**Comment by Cervator** [comment]
Tested it out again and merged, thanks so much!

Best of luck with your exams, we'll still be here when you finish :D

One small extra you could add when you're back: a "Filter:" label by the new box that'll filter the modules so it is clear what it does :-)

**Comment by genuinelucifer** [comment]
> Best of luck with your exams, we'll still be here when you finish :D

Thanks :D

> One small extra you could add when you're back: a "Filter:" label by the
new box that'll filter the modules so it is clear what it does :-)

Will do

**Pull request merged**
