### PR TITLE
Gradle deprecations

### PR DESCRIPTION
**Pull request by soloturn**
send @PurityLake  https://github.com/MovingBlocks/Terasology/pull/5140 again, cherry picked to tip of develop branch and thus conflicts resolved, and @BenjaminAmos comments addressed.

### CODE REVIEW

**Comment by soloturn** [comment]
@jdrueckert this time i messaged in discord, in general dev topics, terasology :)

**Comment by jdrueckert** [comment]
> @jdrueckert this time i messaged in discord, in general dev topics, terasology :)

Yup, just saw that, thank you :+1: And look at that, you got three people's attention in less than a day :grin: 
@BenjaminAmos mentioned on Discord that he's on it so I'll leave you(r PR) in his very capable hands :slightly_smiling_face:

**Review by BenjaminAmos — APPROVED** [review]
These changes all seem fairly minor and harmless.

Upgrading protobuf hopefully should not break server compatibility but I don't think we've ever guarenteed compatibility between game versions anyway. If we're going to break it, now's the time to do it.

**Comment by BenjaminAmos** [comment]
One of the integration tests has failed ([`ExampleTest.testClientConnection()`](https://jenkins.terasology.io/job/Terasology/job/engine/job/PR-5153/lastBuild/testReport/junit/org.terasology.engine.integrationenvironment/ExampleTest/Integration_Tests___testClientConnection__/)), so I'm going to try and re-run that to unblock merging. It looks like random failure, rather than a regression.

**Pull request merged**
