### PR TITLE
Network code documentation

### PR DESCRIPTION
**Pull request by engiValk**
Signed-off-by: engiValk <adamkenyon554@gmail.com>

### Contains

Adding Javadoc to all the network code to make use and readability easier.

### Outstanding before merging

Do not merge until all docs are done. This is just one file for now.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
@GooeyHub: add to whitelist

Thanks for getting this started @engiValk - you walk paths untrodden for many moons, but great treasures await :-)

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Bump - @engiValk are you intending to add more to this in the near future? If not I'd like to merge it soon to avoid having the PR go stale :-)

One general request: Several `@param` tags remain undocumented, even if they're somewhat generic (like the `entityManager` being passed in) could you try to find something minimal that would add a little something and cover the param having some sort of doc? Maybe some tiny bit of context for what the param is getting used for

**Comment by Cervator** [comment]
Merged this to get it out of the way, can start new PRs in the future if there are long breaks between updates :-)

**Pull request merged**
