### PR TITLE
Fixes #2321 Update disabled for modules not on meta-server

### LINKED ISSUE #2321: NPE on clicking "Update" for a module that's not in the meta-server yet
At present you can have a local module that hasn't yet been added to the meta server. Despite the module list helpfully declaring there is "none" available online the "Update" button remains active and results in an NPE if clicked.

Doesn't crash the game, but is a bit silly. If there is no version available online (let alone an updated version) the "Update" button probably should be disabled.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/34459503-npe-on-clicking-update-for-a-module-that-s-not-in-the-meta-server-yet?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by nihal111**
### Contains

Fix for #2321 

### How to test

- Create a new module using "gradlew createModuleMyTestModule"
- Create a new single player game
- Go to Modules menu
- Find MyTestModule and check Update button

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
@GooeyHub: add to whitelist

Tests out fine! Thanks :-)

Holding this PR for a moment since it is based on the branch for #2497 so merging this would also include that and I wanted to give @emanuele3d a chance to respond to that real quick

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by msteiger** [comment]
Thanks for your contribution. I'd rather compare to the actual availability like the `onlineVersion` button does. Checking the button text is very fragile - if someone renames or translates the text, this logic will break.

**Comment by nihal111** [comment]
@msteiger @Cervator Does this look good now?

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Tested again and merged! Thanks :-)

**Pull request merged**
