### PR TITLE
uncover timezone and rename

### PR DESCRIPTION
**Pull request by GabrielXia**
### Contains

Follows-up to #3075, uncover timezone info in telemetry

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GabrielXia** [comment]
As mentioned in #3016 Rename `MonsterKilled` to `CreatureKilled` :)

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GabrielXia** [comment]
In this commit:https://github.com/MovingBlocks/Terasology/pull/3083/commits/8db1d3570bd2d7cfd6b23e4a62a553cc800e3df0 If a metric such as `BlockDestroyedMetric` has no data, this is to say, there is no block destroyed record, then we don't send this metric. Does it make sense?

How to test: Don't destroyed blocks in a game, `Metrics Menu` shows that there is not blocks destroyed. Then exit to the main menu, the `BlockDestroyedMetric` is not sent to the server. (In before, it will be sent)

**Comment by GabrielXia** [comment]
Update to https://github.com/MovingBlocks/Terasology/pull/3083/commits/04154ee68a98c0bc5d3464cc5357456df53b5c4f

1. In `fetchMetricAndSend` method, found two args not needed, so removed them
2. Add a `filterMetricMap` method takes `TelemetryConfiguration` as a param in stead of `bindingMap`, so that an other module could use it, e.g. https://github.com/GabrielXia/TelemetryApiTest/blob/master/src/main/java/org/terasology/telemetry/metrics/TelemetryApiTestMetric.java

p.s. I wrote a draft doc about the tutorial module: https://github.com/GabrielXia/TelemetryApiTest/wiki thanks for suggestions :)

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
> In this commit:8db1d35 If a metric such as BlockDestroyedMetric has no data, this is to say, there is no block destroyed record, then we don't send this metric. Does it make sense?

> How to test: Don't destroyed blocks in a game, Metrics Menu shows that there is not blocks destroyed. Then exit to the main menu, the BlockDestroyedMetric is not sent to the server. (In before, it will be sent)

I'm thinking if 0 is a valid value (which it would be for blocks destroyed) then it should be set as a default value during initialization somewhere. Then it will also qualify for sending, right? Some metrics probably should just have good defaults like that.

Anyway: tested out real quick and merged! Thanks :-)

**Comment by GabrielXia** [comment]
@Cervator Thanks for the tests and suggestions.

For example, the blocks destroyed metric includes block type -> block destroyed number. The metric will add a new block only if there is a new kind of block destroyed. Do you think we should set some default block type and set their value to 0? If so, which are those default blocks?

**Comment by Cervator** [comment]
Ahh, gotcha, it is a map. Okay. Hmm. At that point I don't know if it matters enough to throw in something special, like 0 destroyed air blocks. Up to you / how it might help the graphs look better :-)

**Pull request merged**
