### PR TITLE
chore: remove stray compiler outputs

### PR DESCRIPTION
**Pull request by keturn**
accidentally added in #3708.

found while working on #3954 but I figured I'd make a separate PR for this for ease of reviewing.

### CODE REVIEW

**Comment by DarkWeird** [comment]
@keturn  is ```out```  directory generated by IDE?

**Comment by keturn** [comment]
Yep

**Comment by DarkWeird** [comment]
> Yep

Then need add gitignore rule, isn't it?

**Comment by keturn** [comment]
Oh, that would make sense to include in this same PR, yes. Added.

**Pull request merged**
