### PR TITLE
[WIP] Behavior Tree rework

### PR DESCRIPTION
**Pull request by dkambersky**
This is by no means ready, as it will be breaking on many levels related to behavior, and it'll probably get merged in only when done.

The PR is here mainly for review within GSoC, with some code unfinished and some removed (for now) - e.g. Gooey's  Quests behaviors, Work related stuff (used in Light&Shadow), etc. 

What works, at the point of writing this: the new behavior tree implementation. 
What doesn't: most of the 'meat'. Refer to the kanban board and blog:

Project board: 
https://github.com/orgs/Terasology/projects/7

Blog:
https://dkambersky.github.io/tera/

This PR is accompanied by these PRs in related repos:

- [Behaviors](https://github.com/Terasology/Behaviors/pull/5) 
- [Pathfinding](https://github.com/Terasology/Pathfinding/pull/32)
- [WildAnimals](https://github.com/Terasology/WildAnimals/pull/17)

### Outstanding before merging

Phase 1:
- [x] Interruption / event handling 
- [ ] Unified Entity / Actuator interface - or Actions that fit that purpose
- [ ] NUI editor fix-up (mainly the realtime display and saves

Then Phase 2 and Phase 3 - outline at the links above

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
@GooeyHub: add to whitelist

@dkambersky: awesome!

Pinged some people for review, also poking @kaen who hasn't accepted the team invite yet so I can't assign review :-)

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by Cervator** [comment]
Belated follow-up: the failing check is 10 unit tests that seemingly break - probably need updates or replacements to fit the new approach: http://jenkins.terasology.org/job/TerasologyPRs/1648/testReport/

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Pull request merged**
