### PR TITLE
Fixes MovingBlocks/Terasology#1633

### PR DESCRIPTION
**Pull request by gtugablue**

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
ok to test

Hello @gtugablue and thanks for the nice looking fix! Much appreciated. Will try to find a moment to test here within a day or two, or maybe somebody else will grab it :-)

Are you new to the project or do we know you by a different name on IRC or in the forum?

**Comment by Cervator** [comment]
Gooey: Test this please

One of these days, @GooeyHub, one of these days! *shakes tiny fist*

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/310/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Thanks for the fix! I checked it out and it looks good (and helped me find a different bug - #2012)

Added to credits too. Hope to see more work from you all! :-)

**Comment by gtugablue** [comment]
As you've already noticed, I'm part of the group of students from Porto that chose Terasology as the project to study in the Software Engineering course unit.
It's been a pleasure to work with this project. Thanks a lot for your help!

**Pull request merged**
