### PR TITLE
chore: Remove all the remaining occurences of SurfaceHeightFacet

### PR DESCRIPTION
**Pull request by 4Denthusiast**
This finishes the update that started with https://github.com/MovingBlocks/Terasology/pull/4237 by removing the deprecated SurfaceHeightFacet and the compatibility providers. It should only be merged once all of the remaining module PRs referencing that initial PR are merged.

### CODE REVIEW

**Comment by 4Denthusiast** [comment]
In the first commit, I forgot to actually remove SurfaceHeightFacet. In the second one, I accidentally made some other incorrect changes, so I reverted that before removing just SurfaceHeightFacet in the third one. It should all be correct now.

**Comment by jdrueckert** [comment]
Fails compilation in omega with
```
> Task :modules:AlchemyPlantGenerator:compileJava FAILED
/media/jdr/Development/Git/Terasology-omega/modules/AlchemyPlantGenerator/src/main/java/org/terasology/AlchemyPlantProvider.java:17: error: cannot find symbol
import org.terasology.world.generation.facets.SurfaceHeightFacet;
                                             ^
  symbol:   class SurfaceHeightFacet
  location: package org.terasology.world.generation.facets
/media/jdr/Development/Git/Terasology-omega/modules/AlchemyPlantGenerator/src/main/java/org/terasology/AlchemyPlantProvider.java:24: error: cannot find symbol
@Requires(@Facet(SurfaceHeightFacet.class))
                 ^
  symbol: class SurfaceHeightFacet
/media/jdr/Development/Git/Terasology-omega/modules/AlchemyPlantGenerator/src/main/java/org/terasology/AlchemyPlantProvider.java:57: error: cannot find symbol
        SurfaceHeightFacet surfaceHeightFacet = region.getRegionFacet(SurfaceHeightFacet.class);
        ^
  symbol:   class SurfaceHeightFacet
  location: class AlchemyPlantProvider
/media/jdr/Development/Git/Terasology-omega/modules/AlchemyPlantGenerator/src/main/java/org/terasology/AlchemyPlantProvider.java:57: error: cannot find symbol
        SurfaceHeightFacet surfaceHeightFacet = region.getRegionFacet(SurfaceHeightFacet.class);
                                                                      ^
  symbol:   class SurfaceHeightFacet
  location: class AlchemyPlantProvider
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
4 errors
```

**Comment by 4Denthusiast** [comment]
Huh, odd. That didn't show up in my search for occurrences of "SurfaceHeightFacet" in the Terasology organisation.

**Review by jdrueckert — APPROVED** [review]
LGTM

**Pull request merged**
