### PR TITLE
GSOC 2018: First batch of UI changes for multi-world

### PR DESCRIPTION
**Pull request by Cervator**
Setting up PR to merge from its topic branch to develop. 

In short this batch overhauls the create game UI workflow, fixing some issues with previewing worlds in the process, but temporarily disabling support for _advanced_ configuring of Heightmap. Going straight to playing a gameplay template that defaults to a heightmap world works fine, just more work is needed to hook up a new-style preview for those.

Disclaimer: While the UI suggests multiple worlds can currently be added only the selected world will be available for the player with this PR. I might add a quick note about that to the UI while merging.

* Includes: #3367, #3370, #3372, #3377, #3383, #3385, #3398
* Fixes / completes: #1780, #1917, #2068
* Mildly related: #1743 (music restarts due to context/env change - still happens, but the area affected was very close to this item)

See https://forum.terasology.org/threads/gsoc-2018-multiple-worlds.2168 and the linked blog entries for further GSOC project details :-)

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Tested out some more and resolved conflicts. See https://github.com/MovingBlocks/Terasology/commit/1bbc7402ba8cf9ecc40659f089f6d0fbd9a916b0 for some of the extra work beyond basic conflict resolution.

Merged and have also closed affected issues. Thank you @TheFlash98, @msteiger from past work, @nihal111 from helping out, and so on! :-)

**Comment by TheFlash98** [comment]
[theflash98 & multi-world](https://trello.com/c/dYU1iOul/38-theflash98-multi-world)

**Comment by TheFlash98** [comment]
[theflash98 & multi-world](https://trello.com/c/dYU1iOul/38-theflash98-multi-world)

**Pull request merged**
