### PR TITLE
Added gson to whitelist

### PR DESCRIPTION
**Pull request by nihal111**
This is linked to https://github.com/Terasology/Books/pull/14
The referenced PR makes a change to the Books module such that recipes (icon images) are now loaded dynamically. The book's page contains a mixture of text and recipes.
Such a page looks like this: 

> Following are some recipes <recipe **{\"blockIngredients\": 2, \"itemIngredients\": [\"WoodAndStone:stone\", \"WoodAndStone:stone\"], \"blockResult\": null, \"itemResult\": \"WoodAndStone:toolStone\", \"resultCount\": 1}**><l><l><l>Some More Text<l><l><recipe **{\"blockIngredients\": 2, \"itemIngredients\": [\"WoodAndStone:stone\", \"WoodAndStone:stone\"], \"blockResult\": null, \"itemResult\": \"WoodAndStone:toolStone\", \"resultCount\": 1}**>More Text

The recipe tags are extracted and the content is parsed as JSON. This is used to dynamically create new recipes (editable books).
Gson is required for this purpose of parsing and needs to be added to the whitelist.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by SoniEx2** [comment]
Is this really needed? Wouldn't it be better to allow GSON to be a module?

**Comment by Cervator** [comment]
IMHO it is a fair concern to double check that nothing dangerous happens if we add GSON to the whitelist. Anybody want to research/comment on that one?

On the other hand the JSON bundled via module thing ... *maybe* that would make sense one day, or maybe instead allow modules to declare external dependencies via `module.txt` (still subject to the whitelist). But I think dealing with that level of complexity is probably beyond the scope of this PR (especially keeping two segregated copies)

**Comment by flo** [comment]
I would recommend to use Prefabs to represent the recipes and then reference those prefabs by name in the translatable text. Makes it more readable and makes it use the standard way in terasology to represent data

**Comment by nihal111** [comment]
@flo Sound like a good idea. Closing this PR in an attempt to do this the prefab way.

**Pull request closed without merging**
