### PR TITLE
chore(JNA): update JNA to 5.6.0,  remove com.sun.jna from jopenvr.jar

### LINKED ISSUE #4146: jopenvr.jar contains outdated version of JNA
I tried to add a feature involving version 4.5.2 of JNA Platform, but it failed at runtime with

> Exception in thread "main" java.lang.NoSuchMethodError: 'java.util.List com.sun.jna.platform.unix.Resource$Rlimit.createFieldsOrder(java.lang.String[])'

I believe that when JNA Platform went to extend the Structure class from JNA, it found the one in `engine/libs/jopenvr.jar` instead of the one provided by the gradle dependency.

### LINKED ISSUE #4151: Natives loading issue (with JNA?) on Win10 + Java 11
We've had two user reports now with the same error on Windows 10 running the game via Java 11 resulting in the attached log entry. One user can be a fluke, two not so much. Difficulty might be in how to test any attempted fixes since we've only encountered two systems that trigger it, today's instance was with Discord user `oil_boi`

Only idea I've got for something to try would be to straighten up our usage of JNA via #4146 but that's a stab in the dark. If we do figure something out there we might want to retest this, or in the absence of an available tester able to provoke the issue close this after we've done _something_ in the area with the hope that this might have been resolved - can always re-open if it triggers again later.

On a semi-related note there is https://github.com/MovingBlocks/Terasology/wiki/Troubleshooting-Developer#ldso-dl-lookup-failures where _some_ Java 11s on Ubuntu at least can fail to load LWJGL. Highly unlikely to be related as that issue seems to be a legit problem unrelated to us, see [here](https://bugs.launchpad.net/ubuntu/+source/openjdk-lts/+bug/1838740) or [there](https://bugs.launchpad.net/ubuntu/+source/gcc-7/+bug/1764701) - but it does make me wonder if other JDK variants would encounter this issue or if it is again very specific to a given JDK. Hard to test though. The Java 11 we ship with the launcher has hit this failure.

```
PathManager being initialized. Initial code location is C:\Users\jorda\Desktop\TerasologyLauncher-windows64-4.1.1\games\DistroOmega\1099\libs\engine-3.3.0-SNAPSHOT.jar
Switched it to expected working dir: C:\Users\jorda\Desktop\TerasologyLauncher-windows64-4.1.1\games\DistroOmega\1099
installPath was null, running from IDE or headless server? Setting to: C:\Users\jorda\Desktop\TerasologyLauncher-windows64-4.1.1\games\DistroOmega\1099
Found the natives dir: C:\Users\jorda\Desktop\TerasologyLauncher-windows64-4.1.1\games\DistroOmega\1099\natives
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\jorda\AppData\Local\Temp\jna-101312778\jna3303093479537907948.dll: Can't find dependent libraries
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.load0(Unknown Source)
        at java.lang.System.load(Unknown Source)
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:851)
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:826)
        at com.sun.jna.Native.<clinit>(Native.java:140)
        at com.sun.jna.Pointer.<clinit>(Pointer.java:41)
        at com.sun.jna.Structure.<clinit>(Structure.java:2078)
        at com.sun.jna.platform.win32.KnownFolders.<clinit>(KnownFolders.java:20)
        at org.terasology.engine.paths.PathManager.useDefaultHomePath(PathManager.java:177)
        at org.terasology.engine.Terasology.handleLaunchArguments(Terasology.java:400)
        at org.terasology.engine.Terasology.main(Terasology.java:133)
```

The above execution was via `java -jar` whereas running via launcher failed quietly with something like this: 

```
14:51:48.605 [main] INFO  o.terasology.engine.TerasologyEngine - Initializing Terasology...
14:51:48.629 [main] INFO  o.terasology.engine.TerasologyEngine - [buildNumber=2315, buildId=2315, buildTag=jenkins-Terasology-2315, buildUrl=http://jenkins.terasology.org/job/Terasology/2315/, gitBranch=develop, gitCommit=112d30ed521ae27f9d6e249c7e8be04990739e9d, dateTime=2020-09-07T04:33:26Z, displayVersion=alpha, engineVersion=3.3.0-SNAPSHOT]
14:51:48.629 [main] INFO  o.terasology.engine.TerasologyEngine - Home path: C:\Users\jorda\Saved Games\Terasology
14:51:48.630 [main] INFO  o.terasology.engine.TerasologyEngine - Install path: C:\Users\jorda\Desktop\TerasologyLauncher-windows64-4.1.1\games\DistroOmega\1099
14:51:48.630 [main] INFO  o.terasology.engine.TerasologyEngine - Java: 11.0.7 in C:\Users\jorda\Desktop\TerasologyLauncher-windows64-4.1.1\jre
14:51:48.630 [main] INFO  o.terasology.engine.TerasologyEngine - Java VM: OpenJDK 64-Bit Server VM, version: 11.0.7+10-LTS
14:51:48.630 [main] INFO  o.terasology.engine.TerasologyEngine - OS: Windows 10, arch: amd64, version: 10.0
14:51:48.630 [main] INFO  o.terasology.engine.TerasologyEngine - Max. Memory: 3572 MiB
14:51:48.631 [main] INFO  o.terasology.engine.TerasologyEngine - Processors: 4
```

### PR DESCRIPTION
**Pull request by DarkWeird**
### Contains

Updating JNA
Removing embeded jna from jopenvr.jar
Fixes #4151
Fixes #4146

### How to test

1. ~~Check what VR works~~ :D (Seems, It is not works many time...)
2.  Check Terasology that works on Liberica 11 on Clean Windows (default libraries only)

### Outstanding before merging

### CODE REVIEW

**Review by keturn — APPROVED** [review]
At this point, we'd just as soon remove `jopenvr.jar` entirely, but there are a number of places where there are references to it and I guess that's a bit more work than this PR.

JNA 4.x to 5.x is a major version change. Terasology, outside of jopenvr, uses so little of the API than I don't expect that will be a problem for us.

I'm giving :+1: to this code review but do note I have **not** tested it under Windows as the test plan requires, so I won't be merging it straight away.

**Comment by DarkWeird** [comment]
Jopenvr have jna 3.5 :p (i see it in sourcecodes)
I don't think major versions too harmful

**Comment by keturn** [comment]
For Windows testing, we want a confirmation that this fixes #4151. So you need a Windows system that reproduces the "can't find dependent libraries" error seen there.

I'm not sure what the best way to get that environment is; any Windows installation that's been around for a while may have had MSVC redistributables installed by any number of things.

Maybe it would be easiest to use a VM for that? Performance in a VM may not be great but we don't need to actually _play_ the game to validate this. Getting to the main menu is probably enough. Maybe make a default Simple game and make sure you can see the world for a second if you're feeling thorough.

Would these VMs work for that? https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/
if so, testers wouldn't even need to be running Windows themselves, just have bandwidth and disk space.

**Comment by DarkWeird** [comment]
Yeah, virtual machine is great.

Another way. Check dependencies for extracted dlls.

**Comment by pollend** [comment]
we can use one of these windows VM. their setup for dev environment and are valid for like a month: https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/ you can just download a new one if it goes bad.

**Review by Cervator — APPROVED** [review]
I grabbed this locally for testing to at least make sure it would work normally on Windows, but this is a seasoned instance so I doubt that validates the actual issue - but as long as this works regularly I think we can merge and see if anybody resurfaces with the original issue :-)

**Pull request merged**
