### PR TITLE
Integrate symbol font into regular font

### PR DESCRIPTION
**Pull request by msteiger**
This should make it a lot easier to work with special characters.
Unfortunately `Enclosed Alphanumeric Supplements` had to be removed, because they were combined (more than one char) symbols.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/286/
Hooray Jenkins reported success with all tests good!

**Comment by msteiger** [comment]
It can also be combied with the font color characters:
image

**Comment by Cervator** [comment]
Nice! Will merge momentarily. Able to put it to use somewhere so we have a nice example?

(Btw: Tasks still use the GenericObject, able to upgrade that sometime? I merged the PR without realizing, probably pushed and didn't notice it was checked)

**Comment by msteiger** [comment]
Tasks should be fixed already. Maybe I forgot to push the changes from last night. 

Maybe an entry in the Wiki on fonts/text could be useful?

**Pull request merged**
