### PR TITLE
feat(JOML): migrate SkeletonRenderer

### PR DESCRIPTION
**Pull request by pollend**
This is a migration of just the skeleton renderer. hopefully we can get to migrating the other code for GLTF. The two key modules to test this would be: 

- Light And Shadow
- Wild Animals
- Gooey Quest
- Metal Renegades

make sure the animations work correctly and scaling is correct.

### CODE REVIEW

**Comment by jdrueckert** [comment]
Are there module PRs required for this or did omega compile fine?

**Comment by pollend** [comment]
its all internal code so no affect to module land.

**Review by jdrueckert — APPROVED** [review]
Models seem fine except for the sheep being unexpectedly big, but I don't think this is related to this PR as it's the only one. LaS fool, deer, MR robots, etc. looked as expected.

**Comment by jdrueckert** [comment]
`ci/cloudbees/error` didn't update but re-run succeeded

**Pull request merged**
