### PR TITLE
User player name & color settings even when a known player joins.

### PR DESCRIPTION
**Pull request by flo**
Unique player names are still enforced. If the user picks a name
that is used, he will get the wish name + a small number.

Reasoning for letting all players rename as they want:
They can create new profiles anyway. Cleanup up old profiles
isn't fun, so the goal should be to encourage players to keep
their profiles.

### CODE REVIEW

**Comment by Cervator** [comment]
I'm getting an NPE trying to clean run headless locally from source, then connecting a player to the server (also from source - server is running with -homedir) :-(

```
22:04:23.629 [New I/O worker #1] INFO  o.t.n.i.ServerHandshakeHandler - Sending Server Hello
22:04:24.040 [New I/O worker #1] INFO  o.t.n.i.ServerHandshakeHandler - Received new identity request
22:04:24.852 [New I/O worker #1] INFO  o.t.n.i.ServerConnectionHandler - Received Start Join
22:04:24.885 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.NullPointerException: null
	at org.terasology.network.internal.AbstractClient.addOrSetColorComponent(AbstractClient.java:90) ~[classes/:na]
	at org.terasology.network.internal.AbstractClient.createEntity(AbstractClient.java:72) ~[classes/:na]
	at org.terasology.network.internal.NetClient.connected(NetClient.java:332) ~[classes/:na]
	at org.terasology.network.internal.NetworkSystemImpl.processNewClient(NetworkSystemImpl.java:767) ~[classes/:na]
	at org.terasology.network.internal.NetworkSystemImpl.processPendingConnections(NetworkSystemImpl.java:327) ~[classes/:na]
	at org.terasology.network.internal.NetworkSystemImpl.update(NetworkSystemImpl.java:292) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:435) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:371) ~[classes/:na]
	at org.terasology.engine.Terasology.main(Terasology.java:137) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_31]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_31]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134) [idea_rt.jar:na]
22:04:24.885 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
22:04:24.896 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Creating game snapshot
22:04:24.897 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Snapshot created: Writing phase starts
22:04:24.946 [Saving-0] INFO  o.t.p.internal.SaveTransaction - Save game finished
22:04:24.968 [main] INFO  o.t.n.internal.NetworkSystemImpl - Client disconnected: Unknown Player
22:04:24.992 [main] INFO  o.t.n.internal.NetworkSystemImpl - Network shutdown
22:04:25.024 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
java.lang.NullPointerException
	at org.terasology.network.internal.AbstractClient.addOrSetColorComponent(AbstractClient.java:90)
	at org.terasology.network.internal.AbstractClient.createEntity(AbstractClient.java:72)
	at org.terasology.network.internal.NetClient.connected(NetClient.java:332)
	at org.terasology.network.internal.NetworkSystemImpl.processNewClient(NetworkSystemImpl.java:767)
	at org.terasology.network.internal.NetworkSystemImpl.processPendingConnections(NetworkSystemImpl.java:327)
	at org.terasology.network.internal.NetworkSystemImpl.update(NetworkSystemImpl.java:292)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:435)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:371)
	at org.terasology.engine.Terasology.main(Terasology.java:137)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
For more details, see the log files in C:\Dev\Terasology\Git\integrate\Terasology\terasology-server\logs
```

**Comment by flo** [comment]
Thanks for the quick test!

Oops, forgot to test it with a new game and had some if statements inverted.

I fixed it, please retest :)

**Comment by Cervator** [comment]
Alright, looks good now. If I am understanding it right I can change name on a local client, but rejoin where I was under the old name. And that seems to work. Cool!

Btw, if it is just a simple fix like this don't worry about rebasing to squash a single commit. It might be educational to see where a bug was introduced and how it was fixed :-)

(At first my workspace appeared to have been dirty again, but wasn't sure how I could easily confirm I had the right code)

**Comment by flo** [comment]
I used "git gui" for making the commit correction, and didn't do any rebasing or squashing. The tool allows you to adjust your last committed patch. It is as easy as making a commit if not easier.

**Pull request merged**
