### PR TITLE
Online player list

### PR DESCRIPTION
**Pull request by flo**
This pull request makes it possible to display a list of all online players by holding [TAB].

@immortius  this pull request makes client entities be synchronized to all players. Is anything speaking against that?

### CODE REVIEW

**Comment by Cervator** [comment]
@immortius - bump :-)

**Comment by Cervator** [comment]
Test this please

Yay pre-testing! Also: re-ping @immortius :-)

I'll just merge this within a day or two if no word

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/3/
Jenkins Success Message

**Comment by flo** [comment]
I rebased and resolved conflicts so that it can be merged again.

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/5/
Jenkins Success Message

**Comment by Cervator** [comment]
Thanks :-)

I should be able to catch up tonight now that I figured out what was wrong with the module builds in Jenkins

**Comment by Cervator** [comment]
Looks good - not to mention useful!

Jenkins is *almost* all set but still not quite. But I'm trying to mix in some PRs as part of the testing/fixing

**Pull request merged**
