### PR TITLE
'groovyw * list' output condensed format

### PR DESCRIPTION
**Pull request by mwesolowski**
### Contains

Addresses condensed output format for long lists mentioned in #3279

### How to test

Run: **groovyw module list**
Long lists are presented like below. Currently output format depends only on list size (threshold is hardcoded to 50). I think it would be a good idea to allow user override it and explicte specify which format he wants to use.

> --A: AdditionalFruits, AdditionalItemPipes, AdditionalRails, AdditionalVegetables, AdditionalWorlds, AdvancedBehaviors, Adventure, AdventureAssets, Alchemy, AlchemyPlantGenerator, AlterationEffects, Anatomy, AnotherWorld, AnotherWorldPlants
> --B: BasicCrafting, Behaviors, BlockDetector, BlockFamilyTutorial, BlockNetwork, BlockPicker, Books, BoomSticks, BoundlessWorlds, Breathing
> --C: CakeLie, Caves, ChangingBlocks, CheatsForAll, ChiselBlocks, ChrisVolume1OST, ChrisVolume2OST, Cities, ClimateConditions, Climbables, Combat, CombatSystem, CommonWorld, Compass, ComputerMonitors, Cooking, CopperAndBronze, Crafting, Crops, CustomOreGen
> --D: DamagingBlocks, DangerMod, Dialogs, Drills, Durability, DynamicBlocks, DynamicCities
> --E: Economy, EdibleFlora, EdibleSubstance, Equipment, EquipmentSmithing, EventualSkills
> --F: Fences, FlightModeToggleButton, Fluid, FluidComputerIntegration, FunnyBlocks
> --G: GelCubes, Genome, GooeysQuests, GrammarSystem, GrowingFlora, Guards
> --H: HUDToggleButtons, HealingBlocks, Herbalism, HjerlHede, Holdings, HumanoidCharacters, Hunger
> --I: IRLCorp, InGameHelp, InGameHelpAPI, Indicators, Inferno, ItemPipes, ItemRendering
> --J: JoshariasSurvival, Journal
> --K: KotlinLib
> --L: Lakes, LandOfTerra, LegacyMusic, LightAndShadow, LightAndShadowResources, LootPools, Lost
> --M: Machines, MagicalStats, Malicious, ManualLabor, ManualLaborEventualSkills, MarcinScIncubator, MarkovChains, MasterOfOreon, MedievalCities, MetalliFabrica, Minerals, Mineshafts, Minesweeper, Miniion, Minimap, MobileBlocks, ModularComputers, ModuleTestingEnvironment, MoreLights, MultiBlock, MusicDirector
> --N: NameGenerator, NeoTTA, NetworkTransport
> --O: OreGeneration, Oreons
> --P: Pathfinding, PhysicalStats, PlantPack, PolyWorld, Portals, PotentialEnergyDevices, Potions, Projectile, ProtoSignals
> --Q: QuestExamples
> --R: Rails, RomanCities, RpgSystem
> --S: Sample, ScalaLib, Scenario, Seasons, SegmentedPaths, Sensors, ServerMOTD, ShatteredPlanes, Signalling, SimpleFarming, SimpleLiquids, Smithing, SnakeTournament, Soils, Spawning, StaticCities, StoneCrafting, StructuralResources, StructureTemplates, SubstanceMatters, SurfaceFacets
> --T: Tasks, TheBetweenlands, Thirst, ThroughoutTheAges, TutorialAssetSystem, TutorialBehaviors, TutorialDynamicCities, TutorialGraphicTweaks, TutorialI18n, TutorialNui, TutorialParticleSystem, TutorialSectors, TutorialTelemetry, TutorialWorldGeneration
> --U: Underworld
> --V: Valentines
> --W: WeatherManager, WildAnimals, WildAnimalsGenome, WoodAndStone, WoodAndStoneCraftingJournal, WoodCrafting, Workstation, WorkstationCrafting, WorkstationInGameHelp, WorldPortals, WorldlyTooltip, WorldlyTooltipAPI

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by digitalripperynr** [comment]
Nice ! 
The non-condensed view could be forced using flags. I think that would be noce to have

**Comment by mwesolowski** [comment]
Hi @digitalripperynr, I've added the flags and described them in the usage section.

**Comment by digitalripperynr** [comment]
Awesome ! I'll test them after my exams are over :)

**Comment by digitalripperynr** [comment]
Thanks again for working on the Groovyw Utility !

The new format is working nicely and I've got 2 suggestions :
1. 
In the condensed view, the groups should be separated by spaces to make them look more clean.

2. 
I think the -default-list-format flag is not really required and could be removed.

Apart from these two things the changes work nicely and the flags are working properly.

**Comment by Cervator** [comment]
Thank you so much for the work @mwesolowski ! And the review @digitalripperynr :-)

I tweaked the usage text while merging to shrink it a bit and take out the default option, but leaving it in as an undocumented feature in case it should ever prove useful for some reason.

The spaces turns out after a quick chat to be a display issue on mobile so that's good as-is

Merging and adding to credits, thanks again!

**Pull request merged**
