### PR TITLE
[Work in Progress] Visually distinct UI elements for enabled/disabled

### LINKED ISSUE #2277: Visually distinct UI elements for enabled/disabled (and support for more disabled types)
*Edit: Started as a plain follow-up to #2274, after #2280 I'm hijacking it for a bit more detail, see new todo list below*

We can disable checkboxes now, huzzah! Yet they look the same. We should make that (and similar) situation appear more unique / grayed out :-)

A few more details in #2274 and maybe related to #2275 as well.

While in the main menu you can still access the game console and `showScreen migTestScreen` will show a screen with a bunch of test elements on it (close with `ESC`) - good place to test all the elements both for functionality, disable/enable, and visual distinction.

- [x] `UIButton` - done!
- [ ] `UISlider` - no disable support (so naturally no look either)
- [ ] `UIDoubleSlider` - no disable support (so naturally no look either)
- [ ] `UIText` - can be disabled, but doesn't have a unique look yet
- [ ] `UIDropdown` - can be disabled, but doesn't have a unique look yet
- [ ] `UIDropdownScrollable` - can be disabled, but doesn't have a unique look yet
- [x] `UICheckbox` - kinda done - very faint difference in appearance? Could be more distinct?
- [ ] `UIList` - no disable support, buttons have visual distinction so may just need the support
- [ ] `UIBox` - N/A ? Not sure why we would disable one of these or have it show differently. Maybe if you're grouping elements and want to show the entire group as disabled (like a part of a tech tree you haven't gotten to yet) ?
- [ ] `UIScrollbar` - can be disabled, but not sure if it shows well enough on the test screen to see a difference in appearance?
- [x] `UISpace` - included for completeness, but pretty sure this one is N/A
- [ ] `UILabel` - *MISSING* from the test screen, but otherwise supported and distinct (#2280) - just need to add it to the test screen for completeness

Any other elements? Please comment if so, we might as well catch em all!

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/32649715-visually-distinct-ui-elements-for-enabled-disabled-and-support-for-more-disabled-types?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by tdgunes**
### Contains

It's going to fix #2277.

### How to test

All the partial fixes can be/will be visible in `showScreen migTestScreen`.

#### Previously:
- [x] UIButton - done!
- [x] UICheckbox - "kinda done - very faint difference in appearance? Could be more distinct?" (going to find a fix for that.)
- [x]  UISpace - included for completeness, but pretty sure this one is N/A

#### PR currently includes:
 - [x]  UILabel - MISSING from the test screen, but otherwise supported and distinct (#2280) - just need to add it to the test screen for completeness
 - [x] UISlider - no disable support (so naturally no look either)
 - [x] UIDoubleSlider - no disable support (so naturally no look either)
 - [x] UIText - can be disabled, but doesn't have a unique look yet
    - Capability of supplying initial text 
    - A new dark texture
    - Has two different modes `enabled` and `readOnly`.
    - Disable cursor movement
 - [x] UIDropdown - can be disabled, but doesn't have a unique look yet
 - [x] UIDropdownScrollable - can be disabled, but doesn't have a unique look yet
 - [x] UIList - no disable support, buttons have visual distinction so may just need the support
 - [x] UIBox - N/A ? Not sure why we would disable one of these or have it show differently. Maybe if you're grouping elements and want to show the entire group as disabled (like a part of a tech tree you haven't gotten to yet) ?

@msteiger:
 - [x] UIScrollbar - can be disabled, but not sure if it shows well enough on the test screen to see a difference in appearance?
 - [x] Ability to enable/disable a widget to UIElement
 - [x] Achieve an elegant and reliable way to enable/disable interaciton in a general manner
 - [x] Run the checkstyle checks or integrate the plugin in your IDE so you can resolve the style issues
screen shot 2016-04-21 at 03 22 17

### CODE REVIEW

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/583/
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/589/
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/590/
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/591/
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/608/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Uh oh - @tdgunes it looks like you've got some merges caught up in this PR sneaking in already-merged commits. While that usually isn't critical it clouds up the history and can make it a bit harder to review :-)

That usually happens if you use merges to keep a fork up to date with unique commits both in your fork and the upstream repo (the order of commits ends up differing). Using rebase can help avoid that (since you just put your changes in front of the latest `head` from upstream - no merges involved)

Depending on your comfort with Git there are easy, hard, or brute force ways to fix that. Let me know your preference sometime :-)

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/609/
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/610/
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/611/
Uh oh, something went wrong with the build. Need to check on that

**Comment by tdgunes** [comment]
@Cervator, sorry about that mess again.

What do think about this one?

>  - [ ] UIScrollbar - can be disabled, but not sure if it shows well enough on the test screen to see a difference in appearance?

Personally, I am not sure either. :) Apart from that, I think it's ready for review.

**Comment by Cervator** [comment]
Yay clean Git!

Maybe make the slider go gray if it is disabled? That would be visible including on the test screen even though you can't see the scroll bar itself much. Or maybe there's a way to force a fake larger body to attach the scrollbar to on the test page so you actually can scroll it? Maybe just add a bunch of "lorem ipsum" junk text somehow.

But yeah this is probably ready, just need time to test :-)

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/612/
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/613/
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/614/
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/615/
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/616/
Hooray Jenkins reported success with all tests good!

**Comment by msteiger** [comment]
Apologies for being late to the party. A few assorted notes:

* I'd rather add the ability to enable/disable a widget to `UIElement`. The conditional cast to `AbstractWidget` isn't ideal imho.
* There should be an easier way to disable interaction than checking every listener method. Afaik, you need to call `Canvas.addInteractionRegion()` to support interaction. Maybe you can wrap around that to achieve an elegant and reliable way to enable/disable interaciton in a general manner?
* Please run the checkstyle checks or integrate the plugin in your IDE so you can resolve the style issues.

Everything else looks good to me.

**Comment by Cervator** [comment]
Noticed another potential element to add while checking PR #2315 - `UIImage` - again maybe somewhat unorthodox for the lineup on the test screen, but should it be included just in case? Maybe we could have a little "misc" section for UI elements that aren't subject to disabling or resizing. Although I suppose UI images *could* actually be scaled?

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Huzzah, progress! :-)

As a reminder: Make sure you hook up and run Checkstyle. I see a few missing braces and a * import in there. Minor but good to keep consistent with the code conventions.

(if you haven't already that is - unsure if the pending work you mentioned on Slack went into that new commit or is still not submitted yet)

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Ran a round of testing on this, keeping #2329 in mind.

Merged it with latest develop first since the PR branch is a little behind. No conflicts or anything, just missing some stuff.

So long as I didn't use auto-completion (see #2329) everything looked good. I think the UIScrollBar is the only piece not covered from #2277.

I see 4 minor Checkstyle issues with star imports and a single missing bracket, so that's pretty close to done :-)

Should we still wait for the tweaking of widgets or what not? Referencing the checklist + @msteiger's comments. May be worth merging this and submitting a follow-up issue for later? Don't want it to get too dusty just sitting around :-)

Let me know @tdgunes! But only if you aren't in the middle of being swamped with more academics :D

**Comment by tdgunes** [comment]
> @msteiger: I'd rather add the ability to enable/disable a widget to UIElement. The conditional cast to AbstractWidget isn't ideal imho.

Thanks for fixing this @msteiger, I had a small local commit to resolve casting that you mentioned before by adding `isEnabled()` and `setEnabled()` abstract methods to UIWidget to remove casting completely.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Merged all the things closing both PRs and the issue. Huzzah! Thanks both :-)

**Pull request merged**
