### PR TITLE
Additional TypeHandlers

### PR DESCRIPTION
**Pull request by eviltak**
This PR adds a number of additional TypeHandlers and TypeHandlerFactories to the engine for added functionality.

`TypeHandler`/`TypeHandlerFactory` | Description
--- | ---
`ObjectFieldMapTypeHandler` (and Factory) | Serializes objects as a fieldName -> fieldValue map. Used as the last resort. Replaces `MappedContainerTypeHandler` and makes `@MappedContainer` redundant.
`AssetTypeHandlerFactory` | Generates an `AssetTypeHandler` for each `T extends Asset` so that they do not need to be manually registered.
`RuntimeDelegatingTypeHandler` | Delegates serialization of a value to its runtime type if needed. Used in cases where a subclass instance is referred to as a supertype. Meant for internal use only, and is used in `Collection`, `Map`, and object as a field map serialization.

Minor changes:
- Add `ReflectionUtil.resolveType`
- Resolve types in `ReflectionUtil.getTypeParameterForSuper`
- Use `ReflectionUtil.getTypeParameterForSuper` in `Collection` and `StringMap` type handlers.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by eviltak** [comment]
Rebased onto `develop`. Please re-fetch.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Note: merged into a parking branch for merging at some point via #3490 (this didn't auto-close as merged, so closing manually - all changes have gone into the `newSerialization` branch)

**Pull request closed without merging**
