### PR TITLE
fix(facade): fix broken --load-last-game

### PR DESCRIPTION
**Pull request by keturn**
It wasn't calling engine.run()

### How to test

Run Terasology with the `--load-last-game` option.

If running from gradle, that's
```sh
gradlew game --args="--homedir=. --load-last-game"
```

Check `--create-last-game` too.

### CODE REVIEW

**Comment by jdrueckert** [comment]
Hm, when testing this, I get a "Missing required module or dependency error" :thinking: 
`21:32:21.081 [main] WARN  o.t.e.c.m.loadProcesses.RegisterMods - Missing at least one required module (or dependency) from the following list: [BiomesAPI, Thirst, StructureTemplates, Furnishings, CoreRendering, AnotherWorld, Health, CoreSampleGameplay, Inventory, Explosives, CoreWorlds, CoreAdvancedAssets, Drops, StructuralResources, AnotherWorldPlants, engine, ClimateConditions, AlterationEffects, Fluid, CoreAssets, PlantPack, GrowingFlora]`

Which is interesting as the last game I played before had the following modules enabled:
```
21:31:22.360 [main] INFO  o.t.gestalt.module.ModulePathScanner - Discovered module: CoreAdvancedAssets-1.3.0-SNAPSHOT
21:31:22.363 [main] INFO  o.t.gestalt.module.ModulePathScanner - Discovered module: Explosives-1.1.1-SNAPSHOT
21:31:22.366 [main] INFO  o.t.gestalt.module.ModulePathScanner - Discovered module: CoreSampleGameplay-4.1.1-SNAPSHOT
21:31:22.369 [main] INFO  o.t.gestalt.module.ModulePathScanner - Discovered module: WorldlyTooltipAPI-1.1.0-SNAPSHOT
21:31:22.381 [main] INFO  o.t.gestalt.module.ModulePathScanner - Discovered module: CoreWorlds-2.1.0-SNAPSHOT
21:31:22.384 [main] INFO  o.t.gestalt.module.ModulePathScanner - Discovered module: Drops-1.2.0-SNAPSHOT
21:31:22.391 [main] INFO  o.t.gestalt.module.ModulePathScanner - Discovered module: FlexiblePathfinding-1.1.0-SNAPSHOT
21:31:22.394 [main] INFO  o.t.gestalt.module.ModulePathScanner - Discovered module: BiomesAPI-4.1.1-SNAPSHOT
21:31:22.406 [main] INFO  o.t.gestalt.module.ModulePathScanner - Discovered module: Inventory-1.5.0-SNAPSHOT
21:31:22.411 [main] INFO  o.t.gestalt.module.ModulePathScanner - Discovered module: WildAnimals-1.1.0-SNAPSHOT
21:31:22.417 [main] INFO  o.t.gestalt.module.ModulePathScanner - Discovered module: ModuleTestingEnvironment-0.3.3-SNAPSHOT
21:31:22.423 [main] INFO  o.t.gestalt.module.ModulePathScanner - Discovered module: Health-2.0.0-SNAPSHOT
21:31:22.428 [main] INFO  o.t.gestalt.module.ModulePathScanner - Discovered module: CoreAssets-2.3.0-SNAPSHOT
21:31:22.436 [main] INFO  o.t.gestalt.module.ModulePathScanner - Discovered module: Behaviors-1.1.1-SNAPSHOT
21:31:22.445 [main] INFO  o.t.gestalt.module.ModulePathScanner - Discovered module: CoreRendering-1.1.2-SNAPSHOT
21:31:22.453 [main] INFO  o.t.gestalt.module.ModulePathScanner - Discovered module: NameGenerator-1.1.0-SNAPSHOT
21:31:22.455 [main] INFO  o.t.gestalt.module.ModulePathScanner - Discovered module: Furnishings-1.1.1-SNAPSHOT
21:31:22.458 [main] INFO  o.t.gestalt.module.ModulePathScanner - Discovered module: MarkovChains-1.6.1-SNAPSHOT
```

Not sure, where the game gets the information, that other modules such as `Fluid` should be present as well...

**Comment by keturn** [comment]
It looks like it's determining "latest" by sorting on the last-modified-time of the manifest file: https://github.com/MovingBlocks/Terasology/blob/142c44a2557942392bdc6ecd4cc8356a50705b7d/engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/savedGames/GameProvider.java#L68

Do we not have a `logger.info` somewhere telling us which game it's selected? Maybe that was only for headless mode.

Do you get the same "missing required module" error on both this branch and develop?

Is it the same with `--create-last-game`?

**Comment by jdrueckert** [comment]
> Do we not have a `logger.info` somewhere telling us which game it's selected? Maybe that was only for headless mode.

"Game" in the sense of gameplay or save game?
 
> Do you get the same "missing required module" error on both this branch and develop?
> Is it the same with `--create-last-game`?

Yes and yes.

**Comment by keturn** [comment]
hmm, `--create-last-game` was working for me on develop. Sounds like there's some _other_ issue going on in your case.

**Comment by keturn** [comment]
I stumbled across a source of the "missing required module" error:

`gradlew game --args=--load-last-game` overrides `game`'s default args list so it no longer sets the homedir, and then it was trying to load saves from my user directory instead of the development directory.

So invocation by gradle needs to be more like `gradlew game --args="--homedir=. --load-last-game"`

**Review by jdrueckert — APPROVED** [review]
Now it works like a charm

**Pull request merged**
