### PR TITLE
Suppress all warnings in auto-generated source code

### PR DESCRIPTION
**Pull request by msteiger**
This reduces the total amount of compiler warnings by ~300, but will be overwritten when the protobuf code changes.

In the long run we should consider generating a compiled JAR file instead. This would also significantly simplify the CheckStyle config setup.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/384/
Hooray Jenkins reported success with all tests good!

**Comment by MaloJaffre** [comment]
I send you a PR : [Add @Generated to protobuf package file](https://github.com/msteiger/Terasology/pull/25).
I didn't know how to send you this commit in an other way.

**Comment by msteiger** [comment]
Thanks! You can just type the (first 7 digits of the) commit SHA: f13f9db169 - github will recognize it.
Or copy&paste the entire link: https://github.com/MaloJaffre/Terasology/commit/f13f9db169d561664e4d47a420d54966f45b0036

It will look similar.

**Comment by MaloJaffre** [comment]
Ok, Thanks you, I didn't know you can reference a commit not in the same repository.

**Comment by Cervator** [comment]
So does that other PR with `@Generated` help Checkstyle avoid these warnings differently than just fixing them? Should we merge both?

**Comment by MaloJaffre** [comment]
I think we can cherry-pick my commit into this PR and merge with the two commits, because ````@Generated``` is mainly for documentation.

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/385/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Merging this with a few author tags removed as well and one puzzling question: Where did `Chunks.proto` go? `ChunksProtobuf.java` was generated from it but I don't see the proto file in the source tree?

**Pull request merged**
