### PR TITLE
Bumped -Xmx from 1024m to 1536m in launch configs

### PR DESCRIPTION
**Pull request by segfault802**
### Contains

This *mostly* addresses #2424.  The Windows launchers still need to be updated but I don't have a Windows machine to develop on.

### How to test

Run any of the launch configs in IntelliJ, I had to re-run 'gradlew idea' for it to show the updated parameters in the configuration window.

### Outstanding before merging

The IntelliJ, OSX, Linux and TeraEd launchers were updated.  The Windows
binaries were not. Re-run 'gradlew idea' to have the updated configs applied in
IntelliJ.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
@GooeyHub: ok to test

@segfault802: thanks! Will check on this soon :-)

Are you coming in from Hacktoberfest? Have we seen you on IRC or in our forum yet?

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by segfault802** [comment]
@Cervator Yes Hacktoberfest brought me here.  I haven't been on the forums or IRC.

**Comment by Cervator** [comment]
Tested and merged, thanks! :-)

Will be sending you an org invite to our contributors team here and you've also been added to the game credits! Feel free to post an intro in the forum sometime to get a Contributor badge.

Let me/us know if you have any questions or would like some guidance on picking more stuff to do :-)

**Pull request merged**
