### PR TITLE
Fixed warnings (part 4)

### PR DESCRIPTION
**Pull request by NoUserAgent**
This is the last part of my attempt to clean the code with respect to compiler warnings and code style.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by msteiger** [comment]
ok to test

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/316/
Hooray Jenkins reported success with all tests good!

**Comment by msteiger** [comment]
image

**Comment by Cervator** [comment]
That's a nice dive! Me likey :-)

**Pull request merged**
