### PR TITLE
Add auto complete for "showScreen" command

### PR DESCRIPTION
**Pull request by tdgunes**
### Contains

As title says, adds suggester for showScreen command. I couldn't resist to add this one. :)

### How to test

Open console, write showScreen and hit TAB, it should be able show available assets for selection. 

### Demonstration
screen shot 2016-04-09 at 17 14 44

### CODE REVIEW

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/581/
Hooray Jenkins reported success with all tests good!

**Comment by msteiger** [comment]
Nice! Code looks good to me. Haven't tested it (yet). Does this work with qualified names as well?

**Comment by tdgunes** [comment]
Thanks @msteiger, sorry but what do you actually mean by "qualified names"?

**Comment by msteiger** [comment]
I meant to ask whether it (still) works, if you add the module name in front.
Example: `engine:migTestScreen`.

I just spotted that you're using `UIWidget`, which probably results in large amounts of false positives. Maybe you can narrow it down by using `ScreenLayer` or sth. similar?

**Comment by tdgunes** [comment]
@msteiger it works, but auto completion only works with resource name. 
For narrowing down the results to UIScreenLayer, I didn't notice that definitely find a fix for it. 

@msteiger do you think auto completion should make suggestions with module name or without module name or both (with module name and resource name)?

The problem with both is that, there are lot's of duplicates:

screen shot 2016-04-10 at 00 45 19

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/586/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Tested it out real quick and I can confirm that it works, although now *only* with fully qualified command names :-)

For me the most intuitive would be without module/engine name unless there's an ambiguous screen name. But is that where the dupes come in?

**Comment by tdgunes** [comment]
For instance, if there is `engine:migTestScreen`  and `newModule:migTestScreen`, both should be visible or else only `migTestScreen`, is that what you are trying say? In this way, there will be no duplicates, I guess.

**Comment by Cervator** [comment]
@tdgunes exactly :-)

If you were to hit tab with `showScreen mig` present it would be nice if the logic was smart enough to pick either the engine or newModule option (starting at random or whatever) but leave both entries in the list so you can tab through them.

**Comment by tdgunes** [comment]
@Cervator that would be great to have! :)

For testing, how can I create `newModule:migTestScreen`?

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/588/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
> For testing, how can I create a newModule:migTestScreen?

Not really my expertise but I'm hoping you could just make a copy of engine/src/main/resources/assets/ui/migTestScreen.ui and drop it straight into a similar path of a test module then run the game and see if it shows up? The file has `engine:migTestScreen` in it so just change that part to `someModule:migTestScreen`

Maybe that's naive of me to suggest or perhaps the engine really is that easy to use, unsure which :D

**Comment by tdgunes** [comment]
Oh ok, :). I didn't think it would be that easy. By the way, is there a mechanism to state that "Terasology, please load this module in start"?

In theory, my latest commit generates suggestions just like I mentioned above. But I wanted to be sure whether it works or not.

**Comment by Cervator** [comment]
> Oh ok, :). I didn't think it would be that easy. By the way, is there a mechanism to state that "Terasology, please load this module in start"?

As in, loading a module in the main menu so you can see things from the console there? I don't think so at present. We'll need that eventually for modules that reskin or otherwise change the menus.

**Comment by Cervator** [comment]
I went ahead and tested this again just to be sure and all looks well :-)

Can confirm `migTestScreen` shows up unqualified if there is only one, and qualified if there are two (simply copied the `.ui` to Core) with the game running. Both work and open the UI.

With two options you can't auto-complete with `mig<tab>` since at that point it starts with either `engine` or `Core` - did you intend to find a way to make that work, @tdgunes? I'm happy merging this as-is since it is a nice addition and probably a rare use case to have identically named UIs in several places :-)

**Comment by tdgunes** [comment]
Nice to hear that it works! :-)

I think making it work like that way, requires some changes in suggestion system. It seems that suggestion system only start auto completion from beginning. I will definitely look into that in future, when I have some free time. 

This PR will be extremely helpful for me while testing #2288 (hate typing same thing over and over again :-) ), it would be great if you can merge it.

**Comment by Cervator** [comment]
Works for me! Thanks :-)

**Pull request merged**
