### PR TITLE
Add new run configuration for Java FlightRecorder

### PR DESCRIPTION
**Pull request by theobisproject**
### Contains

Follow up of PR #3469 
Provides a new run configuration with enabled Java FlightRecorder. The provided configuration will only work until Java 9 (didn't worked on Java 10+ for me).
 
### How to test

Run Terasology with the new configuration. After closing the program a new file called `terasology.jfr` should be in the project root directory.

### Outstanding before merging

Maybe the wiki entry @Cervator mentioned in the original PR. But I think the run configuration should be enough to start with. An entry for the analysis of the recording is IMHO out of scope.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Steampunkery** [comment]
Note: You must close Idea, run `./gradlew clean cleanIdea idea` then re-open idea after pulling from this branch.

**Comment by Steampunkery** [comment]
Tested on Ubuntu with Java 1.8.0_161 (Java 8). Works perfectly, but it took me a while to realize that Java Mission Control, the program that is used to open the *.jfr files only comes with the oracle JDK. The way I managed to launch Java Mission Control was:

1. Open a terminal and run `cd $JAVA_HOME/bin` (Assuming Oracle JVM is $JAVA_HOME)
2. run `./jmc` (Java Mission Control)
3. Profit.

**Comment by theobisproject** [comment]
@Steampunkery Thanks for noting the rebuilding of the IntelliJ files. Should have that included in the description from the start.
Java Mission Control will be part of the OpenJDK when OpenJDK 11 is released. But then recording will no longer work with the current configuration 😄

**Comment by Cervator** [comment]
Tested out the run config and merged it along with something else. All good 👍

**Pull request merged**
