### PR TITLE
feature(JMH): Migrate benchmarks to JMH

### PR DESCRIPTION
**Pull request by DarkWeird**
### Contains

Benchmark migration to JMH.
pros:
1. Easy to write
2. microbenchmarking standart.
3. integrate with gradle(custom)
cons:
1. not own solution :)

### How to test

1. just run `gradlew jmh`

<details>
<summary>Details</summary>

```
Benchmark                                                                 Mode Cnt    Score   Error Units
entitySystem.EntityCreateBenchmark.createEntity                           avgt   5 2190.730±568.068 ns/op
entitySystem.IterateComponentsBenchmark.iterateMultipleComponent          avgt   5  455.723± 97.854 ns/op
entitySystem.IterateComponentsBenchmark.iterateSingleComponent            avgt   5  481.269±135.628 ns/op
reflectFactory.ReflectionFactoryBenchmark.byteCodeConstructor             avgt   5   30.081±3.518 ns/op
reflectFactory.ReflectionFactoryBenchmark.byteCodeFieldAccessGet          avgt   5    6.028±0.054 ns/op
reflectFactory.ReflectionFactoryBenchmark.byteCodeFieldAccessSet          avgt   5    5.874±1.046 ns/op
reflectFactory.ReflectionFactoryBenchmark.byteCodeGetterSetterAccessGet   avgt   5    6.552±0.384 ns/op
reflectFactory.ReflectionFactoryBenchmark.byteCodeGetterSetterAccessSet   avgt   5    3.122±0.062 ns/op
reflectFactory.ReflectionFactoryBenchmark.directConstructor               avgt   5   29.112±0.993 ns/op
reflectFactory.ReflectionFactoryBenchmark.directFieldGet                  avgt   5    4.978±0.014 ns/op
reflectFactory.ReflectionFactoryBenchmark.directFieldSet                  avgt   5    4.013±0.364 ns/op
reflectFactory.ReflectionFactoryBenchmark.directGetterSetterGet           avgt   5    5.457±0.516 ns/op
reflectFactory.ReflectionFactoryBenchmark.directGetterSetterSet           avgt   5    0.969±0.070 ns/op
reflectFactory.ReflectionFactoryBenchmark.reflectionConstructor           avgt   5   35.013±3.501 ns/op
reflectFactory.ReflectionFactoryBenchmark.reflectionFieldAccessGet        avgt   5    9.162±0.500 ns/op
reflectFactory.ReflectionFactoryBenchmark.reflectionFieldAccessSet        avgt   5   10.715±4.790 ns/op
reflectFactory.ReflectionFactoryBenchmark.reflectionGetterSetterAccessGet avgt   5   10.218±1.422 ns/op
reflectFactory.ReflectionFactoryBenchmark.reflectionGetterSetterAccessSet avgt   5   10.337±1.157 ns/op
```

```
Benchmark                     (arrayType)  Mode  Cnt       Score      Error  Units
TeraArrayBenchmark1.fullRead   DENCE_4BIT  avgt    5  126226.249 ± 9869.381  ns/op
TeraArrayBenchmark1.fullRead   DENCE_8BIT  avgt    5   39574.907 ± 1794.974  ns/op
TeraArrayBenchmark1.fullRead  DENCE_16BIT  avgt    5   39785.658 ± 2435.308  ns/op
TeraArrayBenchmark1.fullRead  SPARCE_4BIT  avgt    5  139019.977 ± 6201.020  ns/op
TeraArrayBenchmark1.fullRead  SPARCE_8BIT  avgt    5   39475.244 ± 2886.460  ns/op
```

</details>

### Outstanding before merging

- [x] Migrate all other benchmarks on JMH.
- [x] Choose right parameters for benchmarking.

### CODE REVIEW

**Comment by skaldarnar** [comment]
Does this PR just migrate a part of the benchmarks, while keeping the old stuff still in place, or is it breaking things?

I could just run the benchmarks locally via `gradlew jmh` without problem, and I'm in favor of using standard tooling instead of building and maintaining our own stuff...

**Comment by DarkWeird** [comment]
@skaldarnar 

This is draft.
Early access :D
Other benchmarks will migrated too. I just want that you review idea on early stage.
Also i needs help with right parameters for benchmarks - warmups and measure states

**Comment by skaldarnar** [comment]
Do we have results of the old benchmarks to compare?

**Comment by DarkWeird** [comment]
> Do we have results of the old benchmarks to compare?

Maybe in old PRs :D or you can gather this result without PR

And old benchmarks gives only one value - execution time.

New benchmarks gives more values, can measure smaller invocation place and do it in more science/math way(persentiles, average, warmups, error(±))

(Also you can turn more options for jvm,compileretc. and have many features for manipulate turn on/off optimizations )

But i don't know how bake it in best way :D

**Comment by pollend** [comment]
We haven't been tracking any benchmarks so the previous benchmarks setup seems a bit irrelevant.

**Review by skaldarnar — APPROVED** [review]

**Pull request merged**
