### PR TITLE
Fix InputSystem#inputEntities sync with localPlayer's entities.

### LINKED ISSUE #3768: Error Dialog cannot be closed
# What you were trying to do
Close the error dialog coming up on starting a game whilst having dependency issues underneath.

### What actually happened
The "Ok" button is not clickable. It's also not greyed out or anything, but if I click on it, simply nothing happens.

### How to reproduce
* Create and save a game and exit Terasology (e.g. LaS)
* Enforce a dependency issue for some module used in the game (e.g. adapt dependency version of LaS dependency)
* Try to load the game (should result in an error dialog popping up)
* Try to click the "Ok" button

### PR DESCRIPTION
**Pull request by DarkWeird**
### Contains

Fixes #3768

### How to test

* Create and save a game and exit Terasology (e.g. LaS)
* Enforce a dependency issue for some module used in the game (e.g. adapt dependency version of LaS dependency)
* Try to load the game (should result in an error dialog popping up)
* Try to click the "Ok" button

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
Nice! Many thanks :-) Triggering bot test

@GooeyHub: add to whitelist

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by casals** [comment]
Tested as instructed - changed the required Behaviors version for WildAnimals. Works as expected, approving it.

**Comment by Cervator** [comment]
Merging! Thanks @DarkWeird & @casals (feel free to merge yourself if it checks out and seems safe!)

**Pull request merged**
