### PR TITLE
Keybinding modal window

### PR DESCRIPTION
**Pull request by Sk0ut**
Implementation of feature #1568 
Allows for new binding preview, remove binding and set it to default.
The layout needs to be worked a bit but its functional.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
Gooey: Test this please

ok to test

Thanks for this @Sk0ut ! Will test as soon as able :-)

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/344/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Reviewed, tested, and merged! Nice work and some handy lambdas as well :-)

I noted a few minor issues or related quirks and submitted #2064 for further work. Feel free to take a look and tweak some more if you're up for it!

**Pull request merged**
