### PR TITLE
Added Class Documentation to EventSerializer and EntitySerializer

### PR DESCRIPTION
**Pull request by nschnitzer**
### Contains

Adds Documentation to EntitySerializer and EventSerializer

### How to test

Ensure all descriptions are accurate and there are no grammatical  or styling errors

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
This pull request **introduces 1 alert** when merging fe8e7bbd758fb7464ff17f25e3b27e8ca6ea5718 into 61b49bff53a364967386aeb36c2a83fc250adec2 - [view on LGTM.com](https://lgtm.com/projects/g/MovingBlocks/Terasology/rev/pr-63f0a6d7f6218bd160a96de8b9eaa0a225dbf547)

**new alerts:**

* 1 for Spurious Javadoc @param tags

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by nschnitzer** [comment]
I never saw Cervator's initial feedback. I will finish the documentation when I get a chance. Sorry for the inconvenience.

**Comment by jellysnake** [comment]
That's perfectly fine, it's why I checked up on the PR. Look forward to it being finished :)

**Comment by skaldarnar** [comment]
@nschnitzer @eviltak Any news on this? What's the state? Unfortunately, I see a lot of merge conflicts have popped up…

**Comment by eviltak** [comment]
@skaldarnar the ping may have flown under the radar, apologies. Looks like the latest commits to the `newSerialization` combined with a force-push are causing the conflicts. Commits 9faf2b4 and 
fe8e7bb are the only ones that are relevant now and can be cherry-picked into `newSerialization` once the suggested changes are made.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Pull request closed without merging**
