### PR TITLE
Auto-include build.gradle from Core module

### PR DESCRIPTION
**Pull request by oniatus**
### Contains

Auto includes the build.gradle from the core module if a module has no such file.
Makes working with own forks a bit less complicated :)

### How to test

Clone a module via git or delete the build.gradle, then run ./gradlew eclipse or idea. The module should be included in the build process and also have the build.gradle included.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Good idea! Thanks for this :-)

I have a Gradle change pending locally that makes sure all modules are compiled more reliably, plus there are another Gradle PR or two waiting. Will get to them all together ASAP!

**Comment by flo** [comment]
@Cervator I guess this is a PR you have to look at again.

**Comment by Cervator** [comment]
Update - I grabbed this PR some time back, but after looking around a bit ended up finding a way to do away with `build.gradle` files in modules *entirely* - and was able to bake in compile support for Scala and Kotlin while I was at it via new `language` field in module.txt (although such modules would also still have to declare a dependency on ScalaLib or KotlinLib for runtime support)

Also came with an upgrade to Gradle 3.3 and some other stuff, and I still have a ways to go .. but it does technically build on this PR so it'll auto-close when my stuff is ready and gets merged ... :D

For anybody curious my first big commit is https://github.com/Nanoware/Terasology/commit/9ce582c0a7c7090959ab48ff73c7e818b1c0b4f9 with more coming.

**Comment by oniatus** [comment]
@Cervator I guess we can close this one without merging for now?

**Comment by jellysnake** [comment]
@Cervator pinging to see if we can close this one as it is covered by the pull you reference

**Comment by Cervator** [comment]
Will go ahead and close "early" - while I do have this merged I don't know if it'll disappear from rebasing or redoing things. Just a couple commits so I guess losing the contribution stats isn't the end of the world. Will credit in the eventual big PR :-)

**Pull request closed without merging**
