### PR TITLE
Fixed @Updates annotation to actually create the borders when requested

### LINKED ISSUE #2260: Borders in FacetProvider `@Updates` have no effect
Currently, `WorldBuilder` does only compute the borders for updated facets when the updating facet is required somewhere else. I was wondering if this behavior is intended or not. 

To get a border for updated facets am I required to write a (dummy) provider that requires the updated facet?

@CptCrispyCrunchy encountered problems when trying to update the SurfaceHeightFacet with several filtering passes which require borders.  See https://github.com/Terasology/ShatteredPlanes/blob/master/src/main/java/org/terasology/CanyonWorld/GaussFilter.java#L40
The implementation for computing borders was last touched by @MarcinSc: https://github.com/MovingBlocks/Terasology/blame/develop/engine/src/main/java/org/terasology/world/generation/WorldBuilder.java#L113

Pinging @Josharias and @immortius for additional feedback...

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/32290030-borders-in-facetprovider-updates-have-no-effect?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by CptCrispyCrunchy**
### Contains

Fixes #2260

### How to test

Filters in https://github.com/Terasology/ShatteredPlanes finally working now!

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
@GooeyHub: add to whitelist

@CptCrispyCrunchy: huzzah! :-)

Git rebase just came up in another PR, that may be something worth looking at here with three identically named commits :D

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/549/
Hooray Jenkins reported success with all tests good!

**Comment by CptCrispyCrunchy** [comment]
@Cervator  Ah strange, seems my  intelliJ PR really worked somehow. I have my ups and downs with this IDE (using it for the first time) :D. 
Sorry about that.

**Comment by CptCrispyCrunchy** [comment]
Oh I just noticed that adding @Requires to @Updates makes my code to be ignored, also I'll need to add support for produced facet border adjustment. Similar to the if(!requires) block.
So there'll be a second PR soon.

**Comment by skaldarnar** [comment]
Well, you can update this one easily :wink: Every new commit you push to the same branch will end up in this PR.

**Comment by CptCrispyCrunchy** [comment]
Got it now! Border area gets now safely and more efficiently determined :),
May needs some testing with different combinations of @Require but seems to work smoothly so far with my worldgen

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/551/
Hooray Jenkins reported success with all tests good!

**Comment by msteiger** [comment]
Great! This one requires careful review since it affect almost every module. Will have a look over the weekend.

**Comment by msteiger** [comment]
Didn't have time for this over the weekend, sorry. It reminded me that we have a few unit tests around this bit of code. Could you please write another one that tests your changes? I'll still review your changes asap.

**Comment by CptCrispyCrunchy** [comment]
No problem! I assume you mean the tests in engine-test repo, namely WorldBuilderTest right?
Shouldn't be a problem to write some additional tests, could take me a while however as I have an exam on saturday. 
One thing I noticed after playing around with biomes is that i had deprecated trees when they crossed the border at y=64 (height). I didn't encounter something similar for the sides though. They were just cut off. I also had some strange behavior at y=0 with my smoothing function sometimes. However, there is so many code involved that is hard to determine if this fix has something to do with it. I'll analyze this further soon after unit testing was successful.
Ah and it would make sense to take a test with the other worldgens beforehand. I tried the perlin with this fix and worked fine so far, however have to take a closer look at y=64 now.

**Comment by CptCrispyCrunchy** [comment]
Ok sooo, some good news and some bad news:
The above described deprecation of trees and other stuff at y=64 and y=0 is not related to this fix (tried it with unmodified worldbuilder class and it still happens.
The good news is that my fix didn't break anything as it seems. I'll write some test cases now soon.

However, the deprecation stuff is pretty strange. It completely baffles me at the moment. I'll take a look on other worldgens to see whether they encounter the same problems.

**Comment by Cervator** [comment]
You mean "decapitated" or maybe "truncated" rather than "deprecation" ? :-)

I know some trees in some cases get sheared off at trunk edges, it is most noticeable in Throughout the Ages which hasn't had its trees adjusted after the border concept and/or tree gen was tweaked to handle chunk borders better. I *thought* trees in Perlin were adjusted and always OK but I haven't looked thoroughly. I don't know if it matters how the world generator is engaged.

**Comment by msteiger** [comment]
Same for me. I thought I fixed the trees for the Core world generators. TtA is different, because it has its own generators.

The reason for truncated trees at chunk borders is that the border around chunk is too small (or incorrectly computed). As a result, it doesn't realize that a tree that is further away still reaches into the chunk.

**Comment by msteiger** [comment]
Any news on this one, @CptCrispyCrunchy?

**Comment by Cervator** [comment]
Ran another test on this and a bunch of worlds after the comments in https://github.com/Terasology/ShatteredPlanes/pull/2. All looks well as far as I can tell :-)

Tried ShatteredPlanes, Cities, PolyWorld, TTA

**Comment by msteiger** [comment]
So trees are no longer truncated at chunk borders?

**Comment by CptCrispyCrunchy** [comment]
The trees are still truncated at y=64. Didn't saw it at the sides yet. However I looked at the tree generation code and didn't see any relation to this problem, as there is no annotation which modifies the border area of the treefacet and therefore should be unaffected by the changed lines from this fix.

I looked at Perlin World Gen and couldn't find the same truncation of trees yet. 

Also keep in mind that some mountains are also truncated. 
To assure this, I ran it with the old version of WorldBuilder and got the same problems.
I guess it is some setup within the ShatteredPlanes Gen with which the engine has some problems, although I don't have a real clue what it might be yet.

So I would suggest to open a new issue for this.

**Comment by Cervator** [comment]
I tested what I could, favoring different altitudes in different world gens, but just saw the usual truncation in TTA. Wanted to get some stuff merged so we can start fresh :-)

@CptCrispyCrunchy mind submitting a nice new clean issue describing the issue, if you don't readily find a fix first? And any related unit tests are of course always welcome :D

**Comment by msteiger** [comment]
Thanks for checking, @Cervator !

**Comment by CptCrispyCrunchy** [comment]
I gathered some ideas and created a new issue in the ShatteredPlanes module repo 
->[here](https://github.com/Terasology/ShatteredPlanes/issues/3)

**Pull request merged**
