### PR TITLE
doc: move wiki content to docsify page

### PR DESCRIPTION
**Pull request by skaldarnar**
### Contains

Merges the content of the Terasology wiki (from commit `e4d4b10424f24eed6583ea0e998da8aa32a27a3f`) into the `docs/` folder and set up a [docsify](https://docsify.js.org/#/) page for it.

### How to test

The page can be previewed locally by starting a simple HTTP server from the `docs/` folder, for instance by running

```sh
python -m http.server 3000
```

### Outstanding before merging

I think this is mostly functional by now. The wiki content itself is far from perfect, and I already removed a couple of dead links.
However, I think this is a task for follow-up PRs.

- [x] Review to confirm this is in a somewhat usable state
- [ ] before or after merging: configure Github to serve Github pages for the engine repo

The following tasks should be performed after merging this:

- [ ] (after merge) delete/disable the wiki
- [ ] (after merge) check for links to the wiki and correct them
- [ ] (optional) merge the content from `docs-pre-merge/` into `docs`, but probably works better in a follow-up PR
- [ ] convert or delete `.mediawiki` pages

### CODE REVIEW

**Review by jdrueckert — COMMENTED** [review]
Generally looks good, except for
- images and links in included README.md are broken (might be due to the move of `docs/images`?)
- page titles are not shown except if they're explicitly included in the page content (probably due to wiki magic taking care of that before)

**Comment by BenjaminAmos** [comment]
I'm getting an error trying to clone this with git (on Windows):
`error: invalid path 'docs/Teracon-2017:-Slides-about-multiplayer.md'`

If we keep files with `:` in their names in the repository, then Windows users will always fail to clone it.

**Comment by skaldarnar** [comment]
> page titles are not shown except if they're explicitly included in the page content (probably due to wiki magic taking care of that before)

@jdrueckert This should be addressed by [2a7cb52](https://github.com/MovingBlocks/Terasology/pull/5155/commits/2a7cb5253e201d0272c54ff3114f2c7027771566)

> […] files with `:` in their names in the repository […]

@BenjaminAmos Addressed in [2789867](https://github.com/MovingBlocks/Terasology/pull/5155/commits/27898674b7ae4b10547da5b741bc95911fa23a9b)

**Comment by skaldarnar** [comment]
> images and links in included README.md are broken (might be due to the move of docs/images?)

@jdrueckert Without touching the main README in this PR, I instead made the **Home** page of the wiki the landing page in [fae7b47](https://github.com/MovingBlocks/Terasology/pull/5155/commits/fae7b47c4e86220ef5ae7d126278829a7fcd8d75), so at least no broken images/links.

**Review by jdrueckert — APPROVED** [review]
I think this is good enough for the initial migration :+1:

**Pull request merged**
