### PR TITLE
Add GenericObject for delayed conversion

### PR DESCRIPTION
**Pull request by msteiger**
Simple and straightforward.

Completes #1945 together with #1947.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/277/
Hooray Jenkins reported success with all tests good!

**Comment by immortius** [comment]
This seems a rather lazy way to avoid making TypeHandler definition available to modules.

**Comment by Cervator** [comment]
Is that a good thing or a bad thing? Should that be done instead or is it a problem to expose that?

(thanks for taking a look in any case!)

**Comment by immortius** [comment]
I guess I was envisioning modules being able to declare type handlers. I'm not sure how well GenericObject would work on components, particularly in the future - components are going to either be continuously copied for thread safety, or serialized into some sort of in-memory datastore, so there isn't really scope partially deserialized components unless you don't mind systems working with GenericObject directly.

Maybe I'm missing how GenericObject would be used though?

**Comment by msteiger** [comment]
The "lazy" part is very true actually. I've briefly sketched a concept for custom type adapters, but deferred it as it is not trivial. For now, the `GenericObject` approach fits well enough:

The `QuestSystem` has a hard-coded list of `TaskFactory` instances. Each one of them gets a `PersistedDataMap` and creates a certain type of `Task` from it. See [Tasks/QuestSystem](https://github.com/Terasology/Tasks/blob/develop/src/main/java/org/terasology/tasks/systems/QuestSystem.java#L159) for details.

This limits the definition of new task types to the QuestSystem class though - a generic approach based on custom type adapters would certainly help.

**Pull request merged**
